### ISSUE TITLE
Respect TRACKER_SCRIPT_NAME while generating tracking code

### ISSUE THREAD

**Issue by quickstar** [umami-software/umami#1038]
I love the ability to override the tracker script name via the environment variable `TRACKER_SCRIPT_NAME`. It works as expected if we manually just replace umami.js with the new name. Wouldn't' it make more sense if we click the button `Get tracking code` that the generated link respects to the environment variable?

If so, the API should probably also be extended to include the respective tracker script name

**Comment by HowWof** [comment]
I also think it's a good idea, currently I don't know if I gave the name of the script correctly

**Comment by mikecao** [comment]
The problem the app UI does not have access to environment variables. It's only available at build time or through the server functions. I think we can make an API call to get the tracker name if it's really an issue.

@HowWof just run the app and load your tracker by the new name, http://www.yourserver.com/tracker_name.js. If it loads then it works.

**Comment by quickstar** [comment]
> The problem the app UI does not have access to environment variables. It's only available at build time or through the server functions.

Is the tracker link generated in the front end? If so, maybe one can introduce kind of a settings api endpoint to receive `global`settings? Or maybe just store this setting in the database instead of an environment variable? The latter approach would also have the benefit that we might be able to change the script name for each website individually.

What do you think?

**Comment by mikecao** [comment]
Fixed in v1.37.0.
