### ISSUE TITLE
Page Visit time not correct

### ISSUE THREAD

**Issue by chatRG** [umami-software/umami#1047]
Expected that using navigator beacon API will fix the page visit time. When visiting a page and navigating to some other tab is not triggering the collect API endpoint for tracking time. It tracks time only after a page refresh which is not right as it adds a page view count unnecessarily.

How is the page visit time actually calculated? Was expecting the feature to be [something like this](https://jasonzissman.github.io/time-me-demo/).

**Comment by Sammy-T** [comment]
As I understand it, only event tracking has been migrated to use the beacon api so far while page views still use xhr. This is currently being tracked in #570.

**Comment by mikecao** [comment]
That's right, next release will tackle page visit time. It's tricky because I need to decide whether to make a database schema change or find another way around it.

**Comment by chatRG** [comment]
Is there any plan to prioritize this? As for proper analytics, the page visit time is pretty important.

Maybe it is possible to use the library I mentioned in the first comment.

**Comment by Sammy-T** [comment]
I've explored tracking the visit time to see if I could contribute on this. And it isn't particularly difficult to determine the duration on the client-side. 
But, similar to what @mikecao had mentioned, the database is where I hit a wall. I couldn't figure out how to non-destructively update the database schema and additionally keep the multiple database support.

**Comment by joeyscarim** [comment]
I have a similar use case: users come to our site -> go to stream page -> sit on page for x minutes/hours -> exit

This makes our realtime stats, current stats, and session times all off

Would calling track event from via JS client side on an interval (say, 3 minutes) keep this data up-to-date? Or would that possibly work for the realtime and current stats, but not session time?

**Comment by danielunited** [comment]
Hi. Is the metric still flawed? The visit duration looks suspiciously low for me.

**Comment by LushawnDev** [comment]
Yep, experienced the same thing. I thought my website visit time was awful until I checked using another analytics software for a few weeks and saw a massive difference. 

Also when looking at certain stats you can see a load with visit duration of 0s.

**Comment by RubenSmn** [comment]
This is still a thing, https://github.com/umami-software/umami/issues/3001

**Comment by LushawnDev** [comment]
I think Umami has a lot of great features, but this is an obvious drawback. In the meantime I'm just using the free hosted plan and also using Plausible in conjunction to have a more reliable set up.
