### ISSUE TITLE
Referrer filter not always accurate

### ISSUE THREAD

**Issue by HolgerHuo** [umami-software/umami#1108]
Currently, umami provides 3 sets of referrers view: `domain only`, `combined`, and `raw`. The internal code filters referrer by \*referrer\*(wildcards) which apparently does not apply to the use case when users want to get referrer stats from, e.g. `https://example.com/foo/` as umami will return all stats from not only `https://example.com/foo/` but also all paths in it, e.g. `https://example.com/foo/bar`.

Maybe we should split referrer to `source` and `referrer`, the first one represents a single domain and the second stands for the complete `URL` of the referrer. 
(It's not quite easy to do the parsing as the frontend show urls without protocols in combined view, while with protocols in raw view, and there may be protocols other than http(s), e.g. `android-app://com.slack/` in umami's demo page.)

Also, splitting referrer to source and referrer will also help to prepare umami for utm support.

**Comment by mikecao** [comment]
There is only one request for referrer data. The UI then does the filtering and combining depending on which filter you select.

**Comment by HolgerHuo** [comment]
I see that. So maybe we should tweak the UI to further filter results?

**Comment by HolgerHuo** [comment]
technically, this data i was referring to is the one used when filtering. Not the initial dashboard data.

**Comment by franciscao633** [comment]
Just following up on this. For the next version we are doing away with the combined / raw filters for referrer, but the data being collected is being split into domain, path, query param. The domain filters will now be accurate and the UI will no longer need to run logic on the single column URL to try to filter correctly.
