### ISSUE TITLE
Add a slug property to site for a better URL

### ISSUE THREAD

**Issue by max-programming** [umami-software/umami#1122]
I've noticed that when a new site is added, the name of the site is added to the URL for it's analytics page. 
For instance: 

![image](https://user-images.githubusercontent.com/51731966/164956960-419958fb-ee2c-4329-8110-43ca287a57ba.png)

Here, the URL is made according to the `name` in the database. It would be better to make it more URL-friendly by using something like [url-slug](https://www.npmjs.com/package/url-slug).

P.S. I am ready to implement this feature 😄

**Comment by franciscao633** [comment]
in v2 the new format will be websites/{website-id} with no name, therefore this feature is no longer needed. Thanks for the recommendation.

**Comment by max-programming** [comment]
Thanks @franciscao633 ! That makes more sense
