### ISSUE TITLE
can you provider a tracking image?

### ISSUE THREAD

**Issue by pbzyy** [umami-software/umami#1128]
can you provider a tracking image?

<img src=\"http://***/umami.jpg?data-website-id=24e5a836-a23b-46d1-ab4d-8df3a804e15e\" />

**Comment by CanRau** [comment]
Is this planned for v2 and/or what's the approx. roadmap for this?

**Comment by briancao** [comment]
We have this planned for v2, Q1 next year.  I just created a discussion to show the road map.

https://github.com/umami-software/umami/discussions/1698

**Comment by erhankaradeniz** [comment]
how would this work? no analytics expert, could you track any "image" from any website for example with this ? (or is that not even possible) sorry if this is not a smart question, just trying to understand how this works.
