### ISSUE TITLE
Segmentation fault error

### ISSUE THREAD

**Issue by Androz2091** [umami-software/umami#1132]
Hello,
The login page is served properly but when I click the submit button to login here is the error:
```
androz@supervps:~/services/umami$ yarn start
yarn run v1.22.17
$ next start
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/androz/services/umami/.env
warn  - using beta Middleware (not covered by semver) - https://nextjs.org/docs/messages/beta-middleware
Segmentation fault
```
does someone know why?
thank you

**Comment by Androz2091** [comment]
Or only an idea about how to debug the issue?

**Comment by mikecao** [comment]
Need more info, OS, node version, etc

**Comment by Androz2091** [comment]
Hey, thank you so much for responding. here are some extra details:
![Capture d’écran 2022-05-03 à 22 49 50](https://user-images.githubusercontent.com/42497995/166563784-9a3b5884-7da0-4166-9f92-6fe520af607e.png)

**Comment by Androz2091** [comment]
I'm using a custom domain backed by Nginx (analytics.androz2091.fr - you can't access it now, as umami is not started)

**Comment by mikecao** [comment]
A couple things to try..
1. Delete `node_modules` and reinstall
2. Try running in dev mode, `yarn dev`

**Comment by Androz2091** [comment]
I'm getting the same error after doing this...
![Capture d’écran 2022-05-08 à 13 35 42](https://user-images.githubusercontent.com/42497995/167294334-0d9288a4-08a1-48a3-ae35-7929ec873f2c.png)

**Comment by Androz2091** [comment]
Upgrading to v1.13.0 doesn't help

**Comment by Androz2091** [comment]
Is there anything I can do to debug?

**Comment by Androz2091** [comment]
Just let me know, ready to debug whatever you want

**Comment by mikecao** [comment]
Segmentation fault is likely something with the OS environment. Possibly missing libraries. I would try in a different environment if possible. Like the latest Ubuntu 64-bit.

**Comment by windfallw** [comment]
I have the same problem when using nodejs V19.0.0 on debian11, I just [downgrade](https://stackoverflow.com/questions/47008159/how-to-downgrade-node-version) node to v14.20.1 and the problem solved.

**Comment by Androz2091** [comment]
I can't downgrade my Node version to v14... so old

**Comment by Androz2091** [comment]
Indeed. It works with v14. Thank you.

**Comment by windfallw** [comment]
> I can't downgrade my Node version to v14... so old

You can try V18 or below, maybe it also work
