### ISSUE TITLE
Play/click event/trigger on video/embed

### ISSUE THREAD

**Issue by oceanclr** [umami-software/umami#1143]
Can someone guide me on how I can (easily) implement an event to be triggered a video plays?

```
<video width="100%" controls class="umami--click--event">
<source src="https://url.mp4" type="video/mp4">
</video>
```

or using embed plugin:

`[plugin:embed](https://url.mp4?classes="umami-click-event")`

Neither works for me, thank you in advance.

**Comment by mikecao** [comment]
Try wrapping a div around the video and moving the class to the div.

**Comment by oceanclr** [comment]
I have tried the following:

```
<div class="umami--click--event">
<a href="https://url.jpg" target="_blank"><img src="https://url.jpg"></a>
</div>
```

I tried with an image in order to test "div class" functionality - no result.
Do I have to declare <style>? 
If so, can someone provide a working example?
I'm fairly new to coding so any help to the right direction would help.

**Comment by mikecao** [comment]
We've made some updates to the tracker code in v1.38.0 and this use case should now work correctly.
