### ISSUE TITLE
Funnel, goals & custom event payloads

### ISSUE THREAD

**Issue by rogeriotaques** [umami-software/umami#1157]
Umami looks amazing! 🤩 Wonderful job!

Checking out umami's UI and docs, I realized that there are only 3 things missing, IMHO, that would make it a true replacement for Google Analytics or other analytics solutions like Splitbee.io, which are:

1. Custom event payloads
2. Goals (ou conversion goals) and funnels

The first (custom event payloads) would help a lot tracking specific custom data for general events. The second (goals and funnels) would help people to understand the users journey in their apps and websites until a goal to be achieved.

How does it sound to get these implemented?

**Comment by rogeriotaques** [comment]
Relates to #520.

**Comment by mikecao** [comment]
Both of those are on the roadmap. We need to do a complete rehaul of events which would be a major breaking change. Still trying to work out the best way to do that.

**Comment by rogeriotaques** [comment]
Great! Thank you for the follow-up, @mikecao. 🙇‍♂️
Question: is the roadmap visible somewhere? I couldn't find any reference on umami.is.

**Comment by mikecao** [comment]
@rogeriotaques Event payloads are now in v1.37.0.

**Comment by MostafaaRamadan** [comment]
@mikecao I have two questions regarding this, 
1- is there any npm integration package for umami to use with react js
2- regarding sending payload with events. Are there any docs for it, I couldn't find how we can send a payload

**Comment by rogeriotaques** [comment]
Brilliant, great job! 🤩 I will let my team know and check it out. Thank you.

**Comment by rogeriotaques** [comment]
@mikecao 👋 , checking the Umami [demo page](https://app.umami.is/share/8rmHaheU/umami.is) but could not figure out where the custom payloads can be seen. 🤔 Perhaps, there is something I have missed, but can you show me where it can be seen?

**Comment by JLN13X** [comment]
> @mikecao wave , checking the Umami [demo page](https://app.umami.is/share/8rmHaheU/umami.is) but could not figure out where the custom payloads can be seen. thinking Perhaps, there is something I have missed, but can you show me where it can be seen?

Cant find the custom payload either

**Comment by rogeriotaques** [comment]
I assume it might be [here](https://app.umami.is/share/8rmHaheU/umami.is?view=event), but not really sure if that is what I was expecting with __custom payloads__! 🤔

**Comment by mikecao** [comment]
Event payloads are not in the UI yet. Working on the best way to surface them since they are attached to individual events.

**Comment by DamienDeloubes** [comment]
New user here! Wanted to say that I like everything about Umami, it made me cancel my Plausible subscription 🎉 Do we have an update on the custom payload integration? It's kind of the only thing that is really missing. Would love to help

**Comment by briancao** [comment]
Basic queries for event payloads was added in 1.39.

https://github.com/umami-software/umami/discussions/1581

We're currently working on v2 of Umami, with better querying/reporting of event data planned for Q2 of this year.
