### ISSUE TITLE
[Feature Request] New environnement variable: DEFAULT LANGUAGE

### ISSUE THREAD

**Issue by loan-talvat** [umami-software/umami#1158]
It would be great to be able to define in environment variable a default language in public

**Comment by mikecao** [comment]
I think that we can detect a user's locale from their language setting and choose a default from that. Will that work?

**Comment by MarcHagen** [comment]
2cents: Im all for changing the language to a browser prefered locale. 
But still give the option to change the language. This is sometimes removed or missing, which can be annoying.

**Comment by humbertleonardo** [comment]
Check the PR I sent and write a feedback to motivate the admin to accept the update.

https://github.com/umami-software/umami/pull/2151

**Comment by MarcHagen** [comment]
@mikecao seems that this can be closed as done.
