### ISSUE TITLE
Re-order site list

### ISSUE THREAD

**Issue by ebdmuir** [umami-software/umami#1169]
Hi there,

I had a little search but couldn't see any relevant issues so I'd thought I'd create one. It would be great to be able to re-order the list of sites. I added a subdomain before adding the root domain and it just feels wrong to me but I don't want to lose my existing data by deleting and re-adding them. I'm guessing there'll be a workaround manually modifying the DB right? I have yet to connect but any pointers would be great

If I can find some time, I might dig around the codebase and put in a PR for a proper UI if it's wanted.

**Comment by mikecao** [comment]
Are you talking about the list of sites on the dashboard page or the settings page?

**Comment by ebdmuir** [comment]
I assumed they were both linked but the dashboard was my main priority

**Comment by pqvst** [comment]
+1 on this. It would be nice if it was possible to choose how to order sites on the dashboard.

For example, I have several sites that receive very little traffic, so I'd like to have the most visited sites at the top, especially since some of my sites end up being truncated into "More"

**Comment by d19dotca** [comment]
Somewhat related... would love to the ability to sort not only manually but (and more likely used by myself at least) by number of visitors for example so that my less-popular sites are at the bottom of the list keeping my most-visited sites above the "load more" section on the first page.

**Comment by mikecao** [comment]
Fixed in v1.37.0.
