### ISSUE TITLE
Change dashboard website limit

### ISSUE THREAD

**Issue by pqvst** [umami-software/umami#1176]
It would be nice if there was a way to change the dashboard website limit (which is currently set to 10).

```
DEFAULT_WEBSITE_LIMIT = 10
```

This could either be handled as a user setting, a page dropdown to choose the max amount, or even as an environmental variable (I don't believe that is supported at the moment).

Some of my sites with the most traffic always end up under "More" due to the default alphabetical order. So, by being able to change the limit, or by being able to re-order (#1169) the site list would make this more convenient.

**Comment by d19dotca** [comment]
Yes this would be a very nice feature to have, I too have some of my sites under the -More- section because of the alphabetical nature, and adds a bit of friction there. I am only tracking about 20 sites, would be nice to just have them all on the same page honestly without the pagination.

**Comment by franciscao633** [comment]
Hopefully re-ordering of the dashboard (v1.37.0) resolves this.
