### ISSUE TITLE
Page filters aren't reflected in other tables.

### ISSUE THREAD

**Issue by bernd-wechner** [umami-software/umami#1184]
I'm using [v1.31.0](https://github.com/mikecao/umami/releases) and I see this for the last 7 days:

__________<img src='https://user-images.githubusercontent.com/7296506/172117308-09230e8d-d777-4b72-a943-9efe89377321.png' width='500'>

I click on the page that has 9 views and see this:

__________<img src='https://user-images.githubusercontent.com/7296506/172117416-4f58cc54-aec1-45ba-a40b-827c65371853.png' width='500'>

The Browsers, Operating Systems, Devices and Countries tables don't reflect the 9 views, they have not changed, and reflect all the pages. Seems to be broken or if not broken to defeat the purpose of page filtering. I would like to see for a given posted news item the breakdown of visitors for example. Seems a fairly ordinary use case.

**Comment by mikecao** [comment]
It's because browsers, operating systems, etc are based on sessions while pages/referrers are based on page views. It should be possible cross filter the data but likely at a performance cost. Will need to think it over.

**Comment by mikecao** [comment]
Fixed in v2.0.0.
