### ISSUE TITLE
No referrer/Direct visits

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#1223]
Currently, we can't filter the direct visits (without referrer), nor view the amount of them.

Plausible has a Direct / None source
[https://plausible.io/plausible.io?source=Direct+%2F+None](https://plausible.io/plausible.io?source=Direct+%2F+None)

Could it be considered in Umami ?

**Comment by mikecao** [comment]
Marked as an enhancement 👍

**Comment by Maxime-J** [comment]
Perfect, thanks for all your work 👍

**Comment by mikecao** [comment]
Available in v1.34.0.
