### ISSUE TITLE
Referred from instagram and chrome webview is counted several times

### ISSUE THREAD

**Issue by MiladHossein** [umami-software/umami#1224]
I have 2 type of sites . one of them is wordpress and the other one is a next.js based web site .
when a visitor open link of these website in instaram using webview , his visit count several times
this image is for wp site
![Screenshot 2022-06-26 at 10-04-16 umami](https://user-images.githubusercontent.com/9536102/175801462-986937a0-d172-4d28-8387-d51c13ba3104.png)

this images is for next.js 

![Screenshot 2022-06-26 at 09-42-09 umami](https://user-images.githubusercontent.com/9536102/175801477-33eccbf5-a222-4384-a7a1-807e3c9a4d4f.png)
![Screenshot 2022-06-26 at 09-42-09 umami](https://user-images.githubusercontent.com/9536102/175801574-a1c0fe21-6a28-4fe0-88f6-56ec0d81d53c.png)
![Screenshot 2022-06-26 at 09-38-47 umami](https://user-images.githubusercontent.com/9536102/175801571-2b03cbda-cffe-458c-b3e2-fc9682a3b376.png)

I use v1.32.0 on docker and mysql

**Comment by mikecao** [comment]
Fixed in v1.34.0.
