### ISSUE TITLE
[enhancement] API endpoint for dropdown date options

### ISSUE THREAD

**Issue by ldpr** [umami-software/umami#1225]
Currently, it appears date/time is done via epoch seconds (when viewing network requests while logged in). This is a little confusing because [the docs](https://umami.is/docs/api) use a different date/time formatting.

Would it be possible to have API endpoints like so:

```
/api/website/1/stats/today
/api/website/1/stats/last24
/api/website/1/stats/thisweek
/api/website/1/stats/thismonth
etc
```

It would make scripting and pulling stats much cleaner, thanks!

**Comment by mikecao** [comment]
I think that can be useful.

**Comment by ldpr** [comment]
> I think that can be useful.

Awesome! My apologies too, I submitted this issue a bit early and spent time fixing it and have just now realised I never elaborated on the second part.

To me, it seems the API (or at least the documentation) uses two different time formats, is that intentional or am I mis-reading?
If that's right, would it be best to change to one constant or?

Thanks for your time Mike, appreciated - happy you see some value in this also!
