### ISSUE TITLE
Bug: No fallback if click event failed (need double click)

### ISSUE THREAD

**Issue by surjithctly** [umami-software/umami#1246]
Due to some database error, umami throwed an error (expected). But when I click on a link with event tracking enabled, I cannot continue with action. I have to click on each link twice for that action to work. Eg:  navigating to other page.

Umami script should fallback to default event incase umami failed. There should be an exception handler. 

See image. 

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/1884712/176691438-e1e0ed50-8fb2-4989-beda-812de344150c.png">

**Comment by mikecao** [comment]
Fixed in v1.37.0.
