### ISSUE TITLE
Pages links

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#1247]
It can be useful to have links next to pages, as there are for referrers.

Stumble into that for a website with a lot of pages,
I wanted to see the content of top pages, but couldn't easily.

Can it be added to the enhancements list?
Thank you !🙂

**Comment by Maxime-J** [comment]
I can submit a PR if wanted. I'm not so satisfied however.

By doing it, we have to choose a protocol for the link, so there's the easy way, link with https:// (what is done in Plausible)
Or a better way IMO would be a https checkbox in website settings, but it seems a bit overkill only for that extra feature.

What's your take on that?

**Comment by mikecao** [comment]
I believe if you send the user to just the url the browser will figure out if it's https or not.

**Comment by Maxime-J** [comment]
`href="domain.com"` is treated as a relative path => UMAMI_URL/domain.com
`href="//domain.com"` uses the protocol of the location where the link is: umami accessed via https => `https://domain.com`, otherwise `http://domain.com`

`href="http://domain.com"` is probably the safest, but it would need the website to handle correctly the redirections if it's preferable to use https.
`href="https://domain.com"` assumes that the website is accessible through https, and it appears like a safe bet nowadays.

**Comment by Maxime-J** [comment]
Same as #800.
