### ISSUE TITLE
Doesn't work with Next.js (Next.js's problem)

### ISSUE THREAD

**Issue by max-programming** [umami-software/umami#1248]
I really like this tool and it really helps me a lot! However, it doesn't seem to be working right now with my Next.js app.

It might be completely my problem though. But it doesn't even show the script tag when deployed to production. Can someone help me with this please?

This is the site: https://memoriez.cc
I added the script tag in the `Head` component, then I used the `Script` component and finally I used the `_document` file but it doesn't show up in production in all these ways

**Comment by max-programming** [comment]
I tried adding the script [this way](https://github.com/max-programming/memoriez/blob/33a921979c8c8538df56b89f627c2326ab978858/pages/_app.tsx#L27) now but it still doesn't even request the script

**Comment by njfdev** [comment]
Make sure the Script tag isn't inside of the Head tag as this won't work. Add the Script tag somewhere else.

If that doesn't work, I'd recommend just using a normal script tag.

**Comment by max-programming** [comment]
> Make sure the Script tag isn't inside of the Head tag as this won't work. Add the Script tag somewhere else.
> 
> If that doesn't work, I'd recommend just using a normal script tag.

Even tried the normal script tag, even tried it outside `Head` but nothing seems to work

**Comment by njfdev** [comment]
Try using this code in a `_document.js` file:
`
import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html>
      <Head>
        {<-- Put umami script here directly copied from your umami instance -->}
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
`

**Comment by max-programming** [comment]
Nope. Still doesn't work

Just FYI I am using Linode and not Vercel. Can that be the problem?

**Comment by njfdev** [comment]
I think this issue is unrelated to umami, so I'll create a separate issue in your repository.
