### ISSUE TITLE
Dashboard graphs not loading in v1.33.1

### ISSUE THREAD

**Issue by premento** [umami-software/umami#1251]
I installed v1.33.1 today morning and I started getting the data. But dashboard graphs show 'Something went wrong'. Real-time graphs are working fine. Any clue?

Browser console says
/api/website/6/active is 401 Unauthorized!

**Comment by premento** [comment]
TypeError: Do not know how to serialize a BigIntat JSON.stringify (<anonymous>)             at sendData (/var/www/html/umami/node_modules/next/dist/server/api-utils/node.js:280:47)        at apiRes.send (/var/www/html/umami/node_modules/next/dist/server/api-utils/node.js:160:31)     at sendJson (/var/www/html/umami/node_modules/next/dist/server/api-utils/node.js:307:9)         at apiRes.json (/var/www/html/umami/node_modules/next/dist/server/api-utils/node.js:162:31)     at json (/var/www/html/umami/.next/server/chunks/9718.js:1100:28)                               at ok (/var/www/html/umami/.next/server/chunks/9718.js:1097:12)                                 at __WEBPACK_DEFAULT_EXPORT__ (/var/www/html/umami/.next/server/pages/api/website/[id]/pageviews.js:163:64)     at async Object.apiResolver (/var/www/html/umami/node_modules/next/dist/server/api-utils/node.js:182:9)         at async NextNodeServer.runApi `(/var/www/html/umami/node_modules/next/dist/server/next-server.js:386:9)```

**Comment by mikecao** [comment]
This looks like problem with Next.js since it's happening here `next/dist/server/api-utils/node.js`. Try upgrading to see if that helps.

```
yarn upgrade next@latest
```

**Comment by premento** [comment]
@mikecao I upgraded to next@12.2.0
had to rename _middleware.js to middleware.js and moved to the folder just above the 'pages' folder as per the migration guide. The build was crashing because of that.

BUT the issue is not solved yet.

**Comment by premento** [comment]
@mikecao Issue seems to be solved for me.

**Comment by mikecao** [comment]
Fixed in v1.34.0.
