### ISSUE TITLE
MySQL: utf8mb4?

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#1264]
Concerning MySQL, tables on a fresh install are now created with `utf8mb4_unicode_ci` collation (and utf8mb4 charset)

I wonder if that's intended?
Because you stated not so much time ago about that https://github.com/umami-software/umami/issues/786
and there's no conversion/migration for the already created `utf8_general_ci` tables.

I don't know much about the consequences it might have on umami, but switching to utf8mb4 also implies some lengths concerns.
For reference, here is an interesting link
https://mathiasbynens.be/notes/mysql-utf8mb4
(with a side note that the 767 bytes length limit for index has since been increased in newer MySQL versions)

**Comment by mikecao** [comment]
Related to #1261. We need to update the migration file. Will track there.
