### ISSUE TITLE
Can't retrieve events with referrer filter

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#1268]
When referrer filter is set (eg in the demo https://app.umami.is/share/8rmHaheU/umami.is?referrer=google.com)
the request to get corresponding events fails with a 500 error
(metrics api: `/api/website/1/metrics?type=event[...]&referrer=google.com`)

Here is the error reported server side
```
Invalid `prisma.$queryRaw()` invocation:
Raw query failed. Code: `1054`. Message: `Unknown column 'pageview.referrer' in 'where clause'`
```

And the according incomplete query from `getPageviewMetrics` function
```
select concat(event_type, '	', event_value) x, count(*) y
from event
  
where event.website_id=?
and event.created_at between ? and ?
and pageview.referrer like ?


group by 1
order by 2 desc
```

**Comment by mikecao** [comment]
Events don't have referrers.

**Comment by Maxime-J** [comment]
I get it, but I don't make the request myself => It comes from the front-end app when a referrer is clicked.
Saw these 500 errors on the server, that's why I pinpointed that.

And it's reflected front end with "Something went wrong" messages in the events sections ('more' view and event listing if any).

**Comment by mikecao** [comment]
Ahh I see, will investigate.

**Comment by rohandebsarkar** [comment]
Hey, we still can't filter data using referrers. When clicked on a referrer, nothing happens.

**Comment by mikecao** [comment]
Seems to work on the demo site, https://app.umami.is/share/8rmHaheU/umami.is?view=referrer&referrer=github.com

**Comment by rohandebsarkar** [comment]
Sorry, this is working, it was a problem with one of my extension clearing out the filters.

**Comment by rohandebsarkar** [comment]
Another issue, when filtering using referrers, the (None) referrer seems always to be included.
