### ISSUE TITLE
Improper Unique Visitor Count?

### ISSUE THREAD

**Issue by premento** [umami-software/umami#1276]
![Screenshot 2022-07-08 at 9 04 52 AM](https://user-images.githubusercontent.com/15952736/177911924-6a3defda-defa-4bc0-addd-15bb8c963714.png)
![Screenshot 2022-07-08 at 9 04 45 AM](https://user-images.githubusercontent.com/15952736/177911931-0016f114-4989-4215-b061-e0027758708a.png)

If I compare the real-time as well as historical data, the unique visitor count seems to be improper. This is from dev's latest code.

**Comment by mikecao** [comment]
Are you still having this issue? Not sure how the data can end up like that.

**Comment by premento** [comment]
@mikecao The previous issue was solved. This is new. I am attaching the screenshots of the pageviews api;
<img width="830" alt="Screenshot 2022-07-09 at 4 46 47 AM" src="https://user-images.githubusercontent.com/15952736/178081112-1e14e38e-c6c6-45de-98fa-8b8e21b9ccc9.png">
<img width="853" alt="Screenshot 2022-07-09 at 4 46 54 AM" src="https://user-images.githubusercontent.com/15952736/178081130-e603f327-65ac-4264-b45f-face684e09f1.png">

**Comment by premento** [comment]
@mikecao This issue is still there in 1.34.0

**Comment by mikecao** [comment]
Fixed in v1.37.0.
