### ISSUE TITLE
Configure Data Retention period

### ISSUE THREAD

**Issue by svprdga** [umami-software/umami#1277]
I am currently evaluating Umami for use in my applications. The first thing I want to say is that it is a fantastic project, so congratulations and thanks to the creator and the contributors.

However, one of the weak issues that I see is regarding data retention.

It would be great to be able to configure a data retention period and automatically delete data prior to that period.

The retention period can have high value especially under European jurisdiction. The way I imagine it is maybe at the configuration level for each site, you could select the number of days you want to retain the data, and then the server automatically deletes every day all the data before the period.

I have searched and have not seen anything similar in Umami, I have also looked at the API and there is no endpoint to remove. If there was, I could create a script that would do it.

**Comment by Maxime-J** [comment]
I have the same concern, having the possibility to delete old data, automatically or not, would be nice.
That said, I ending up thinking I will do it directly on the database:
deleting entries in `session` table with `created_at` older than what is wanted is enough to clean all the data.

**Comment by mikecao** [comment]
Umami itself is just a web app. It's not a long running process where you could issue commands like that. This is more of a task for a cron job. That said, we can probably add a delete script that your cron job could call if that's what you need.

**Comment by rohandebsarkar** [comment]
> Umami itself is just a web app. It's not a long running process where you could issue commands like that. This is more of a task for a cron job. That said, we can probably add a delete script that your cron job could call if that's what you need.

This would be a good way to go.

**Comment by svprdga** [comment]
> Umami itself is just a web app. It's not a long running process where you could issue commands like that. This is more of a task for a cron job. That said, we can probably add a delete script that your cron job could call if that's what you need.

That would be awesome. A script would be good, or maybe a new API endpoint to delete data to give more flexibility. Then one could create a script that runs in a cron job and triggers this endpoint in the desired moments.

**Comment by fredrikj31** [comment]
I was thinking a bit about this, and I think there are two types of solutions to solve this problem, which both includes a cron job. If you have PHPmyadmin installed alongside your MySQL database instance, you can create cron jobs inside PHPmyadmin, which would delete data if they are too old, which you specify.

The other way is for you to have a cron job running. I don't think it's possible to run it directly from the website, but you can setup a serverless function to run every time, you again specify. Both Netlify and Vercel supports this, and it could be done by having an API endpoint which would delete it. But you could also set the cron job on your own server.

**Comment by fredrikj31** [comment]
Yeah okay. I havn't read the API documentation so much. But it does seem like it's a very simple task to do. Maybe the only thing that's needed for it to work with a bash script is a new API-endpoint, which deletes the data from the database. The endpoint could have some time/date for which data should be deleted

**Comment by espio999** [comment]
Hello

Automatic data retention support would also work better for hosting on free resources as Heroku.

I have an idea to support it.  On "Settings > Websites > Edit" on Umami, have new parts as 

-new textbox as "retention period"
-new button1
-new button2

As well as "Get tracking code", button1 output auto delete script based on "retention period" textbox.  And use implement it as own automatic retention maintenance.  This is for professional user.

Button 2 is for manual retention maintenance.  Pushing this button, Umami deletes records out of retention period.  This is for hobby user as using Heroku.

At least, Umami doesn't need to care execution timing of data deletion in both cases.

**Comment by sebiweise** [comment]
What about something like https://www.easycron.com/ it would be possible to just add a API endpoint that can be called with a POST Request and some kind of Webhook-Secret. Whenever the webhook endpoint is called you can check if some websites need to delete data.
The retention would be by default unlimited but can be define per website in days or via dropdown for example 1day; 1 month; 1year; and so on
