### ISSUE TITLE
Ability to Track Purchases

### ISSUE THREAD

**Issue by njfdev** [umami-software/umami#1280]
I think Umami should have the ability to track purchases. This would allow you to see revenue for certain days and a time period. I think this could reuse the event tracking but have a dedicated chart for purchases.

**Comment by mikecao** [comment]
This is what events are for. However you need to send the event data yourself. We will be making some changes so that you can store a larger payload for event data soon. This data could be purchase data or whatever else you need.

**Comment by njfdev** [comment]
Is there a way to show the value of events (ex: $491.45), instead of the number of events (ex: 1.2k events). Sorry if I am misunderstanding, but I would like a way to track a value alongside an event (`event: subscription_purchase, value: 4.99`).

**Comment by fredrikj31** [comment]
@njfdev How many types of store products have you listen on your website. Is it like 3 different subscription levels, or is it like 100 different types of products?

**Comment by njfdev** [comment]
This would work, but I think it would be nice to have a numerical value with the event. Then you could see the amount of money earned instead of the amount of subscriptions.

**Comment by njfdev** [comment]
I think a total count for events should work fine. But I think there should be a different kind of event that supports numerical values.

**Comment by njfdev** [comment]
Maybe it could be a feature to implement in the future

**Comment by mikecao** [comment]
New event system is now available in v1.37.0.
