### ISSUE TITLE
Data disappears while refreshing when OS filter selected

### ISSUE THREAD

**Issue by rohandebsarkar** [umami-software/umami#1286]
To reproduce:

1. Got to website detailed page (for example: https://app.umami.is/share/8rmHaheU/umami.is)
2. Select any operating system to filter the data.
3. Refresh the data using the refresh button at the top left.
4. All the data disappears.

Also, when going directly to a filtered link (for example: https://app.umami.is/share/8rmHaheU/umami.is?os=Windows+10), no data is visible.

**Comment by rohandebsarkar** [comment]
After checking the logs, it seems that this is only happening to the filters which contain a whitespace character.

**Comment by mikecao** [comment]
This might be fixed in the latest version:
![image](https://user-images.githubusercontent.com/477975/180630960-193931d2-f8b0-4781-b3d7-f9ad419e1730.png)

Can you verify?

**Comment by rohandebsarkar** [comment]
Now, it is behaving strange. Sometimes it works as expected, but most of the time either the data is not visible or the graph, and sometimes both the data and the graph is not visible.

I am attaching some screenshots.

![Screenshot 2022-07-24 at 09-16-23 umami](https://user-images.githubusercontent.com/50144004/180631272-bf313db7-6b12-40b4-b480-ed40a10bc0c3.png)
![Screenshot 2022-07-24 at 09-20-43 umami](https://user-images.githubusercontent.com/50144004/180631397-38c892f0-3864-4c19-bee5-15b5b99d7c6a.png)

**Comment by rohandebsarkar** [comment]
Sorry, this is working, it was a problem with one of my extension clearing out the filters. Apologies, for trouble caused.
