### ISSUE TITLE
Change default listening address. Docker compose

### ISSUE THREAD

**Issue by 4l1fe** [umami-software/umami#1287]
Now the address is `0.0.0.0` as it's not specified which is insecure, for example, in the case of working in public networks.

[master docker-compose.yml](https://github.com/umami-software/umami/blob/master/docker-compose.yml#L7)
```
    ports:
      - "3000:3000"
```

 What do you think if edit it as follows?
 ```
     ports:
      - "127.0.0.1:3000:3000"
 ```

**Comment by mikecao** [comment]
I think if people want to run on localhost they can do that, but it shouldn't be the default. Many people run containers on different machines.
