### ISSUE TITLE
 time zone issue

### ISSUE THREAD

**Issue by aniwn88480857** [umami-software/umami#1291]
How to change the time zone of the source code, which module is it under, the other time of my data is correct, but in the Realtime logs of the Realtime page, the time is wrong

**Comment by mikecao** [comment]
You just change the timezone under settings. Are you saying it doesn't work correctly on the realtime page? Then we can look into it.

**Comment by tholyong** [comment]
Yes, I have this issue. If I change to a different timezone (12 hours different) than my current timezone, the realtime page x-axis time range does not change, it still gives me the same period according to my current timezone. So I see no data on the chart. It only happens on realtime page.

**Comment by yandujun363** [comment]
The timezone on the summary page is incorrect. The timezone setting is Asia/Shanghai, but it is actually 8 hours behind, showing UTC time instead of UTC+8. However, the real-time page shows it correctly.
