### ISSUE TITLE
Time range selector

### ISSUE THREAD

**Issue by christopherpickering** [umami-software/umami#1293]
Thanks for the tool!

On the time range selector can a url parameter be used to set the initial value?

Something like:

https://analytics.example.com/share/EUf5qmgL/example?time=last_7_days

To choose the Last 7 Days.

![image](https://user-images.githubusercontent.com/17788706/178578314-1b4ac7fe-4560-4348-acdd-c94dd1184e1b.png)

I'm not sure how that can be handled in the framework though.

**Comment by mikecao** [comment]
Yea I think we can support query parameters.
