### ISSUE TITLE
Internal Server Error after update v1.34.0

### ISSUE THREAD

**Issue by mrkomarov** [umami-software/umami#1321]
After deployed, the main page returns the message `Internal Server Error`.
Deployed on Heroku and using PostgreSQL since August 2021. First time this happens.

I was using stack `heroku-20`. Also tried to deploy with `heroku-22`, same error.

**Comment by mikecao** [comment]
It's is probably because of Next.js. We've upgraded to the latest version in the latest release. You are free to continue using previous versions that work until Heroku fixes their side of things.

**Comment by arye321** [comment]
For the sake of future newbies please mention this on your website

https://umami.is/docs/running-on-heroku

**Comment by giuliomagnifico** [comment]
> For the sake of future newbies please mention this on your website
> 
> https://umami.is/docs/running-on-heroku

This is not a newbie issue but a Heroku issue because it is still using an old release of Next.js.

Now I don’t have this issue because I just migrated from Heroku to DigitalOcean (I wrote a post here http://giuliomagnifico.blog/misc/2022/08/01/switched-from-heroku-to-digitalocean.html) but Heroku is getting worse.

**Comment by arye321** [comment]
> > For the sake of future newbies please mention this on your website
> > https://umami.is/docs/running-on-heroku
> 
> This is not a newbie issue but a Heroku issue because it is still using an old release of Next.js.
> 
> Now I don’t have this issue because I just migrated from Heroku to DigitalOcean (I wrote a post here http://giuliomagnifico.blog/misc/2022/08/01/switched-from-heroku-to-digitalocean.html) but Heroku is getting worse.

I understand, but its not written anywhere, and it took me a couple of hours to figure out by finding this thread. 

anywas works great on vercel

**Comment by H0rn0chse** [comment]
The `Internal Server Error` should be resolved by https://github.com/umami-software/umami/pull/1380

**Comment by mikecao** [comment]
Fixed in v1.37.0.
