### ISSUE TITLE
The version number of the latest version is wrong

### ISSUE THREAD

**Issue by roywangdev** [umami-software/umami#1326]
After I update to the latest version of v1.35.0, I am still prompted to update the latest version of v1.35.0 after logging in umami. The version number in the lower right corner is v1.34.0

**Comment by roywangdev** [comment]
@mikecao

**Comment by njfdev** [comment]
Are you sure you have updated to the latest version and refreshed your browser. Works fine for me with the latest commit.

**Comment by roywangdev** [comment]
> 您确定您已更新到最新版本并刷新了浏览器吗？使用最新的提交对我来说很好。

Of course, it solves the histogram problem in 1.34.0

**Comment by mskian** [comment]
try this

```sh
git stash
git pull
```
