### ISSUE TITLE
Re-order websites in Settings or Dashboard

### ISSUE THREAD

**Issue by joaoramos** [umami-software/umami#1327]
Congratulations on such an amazing product 👋  Though I'm only somewhat tech savvy, I managed to install umami on Railway with a custom domain in less than 7 minutes. It tool only a few more minutes to migrate all my websites from Google Analytics to umami 🎉 

The only thing I'm missing is the ability to re-order websites in the Dashboard, either on that screen directly or from the Settings screen. In particular when having many websites set up, it may be hard to scan for the ones that really matter.

**Comment by njfdev** [comment]
I only have 2 websites setup, but it seems to be in order of the website ID in the database. To prevent a database schema change, we could just change the order of the ID's.

I think this would work on Postgres, not sure about MySQL.

**Comment by joaoramos** [comment]
> it seems to be in order of the website ID in the database

The order of my websites on the Dashboard doesn't seem to represent the IDs on the database, but rather the alphabetical order of the website name, from A to Z.

**Comment by njfdev** [comment]
Ahh, I see. This would take a bit of work to redo the UI so we can reorder the websites and to setup the logic (possible a new database column).

I think this should be an enhancement for the future as just looking in alphabetical order should work for now.

**Comment by mikecao** [comment]
Fixed in v1.37.0.
