### ISSUE TITLE
UTM issue with MySQL

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#1341]
About the added UTM feature (@cywio 👍)
URLs are not filtered correctly with MySQL, and all end up in umami UTM views.

`substring_index` in MySQL doesn't have the same behaviour as PostgreSQL `split_part`
- last arg of `split_part` is the part position to return, with an empty string returned if it's greater than number of parts after splitting
- whereas it's an occurrence count of the delimiter in `substring_index`, the returned value corresponding to the substring before that count. So the all string is returned if delimiter isn't there.

**Comment by Maxime-J** [comment]
Thought it could be filtered with a `where like` clause (with the utm param),
and the extraction handled with eventual various db specific functions.

It would probably be easier to have multiple db support.

What do you think?

**Comment by mikecao** [comment]
We should move all this logic to the UI and use table filters. The database query should simply do a search for `LIKE "%?"` which will pick up all urls with query strings, then we can filter them down on the frontend.

**Comment by mikecao** [comment]
Fixed in v1.37.0.
