### ISSUE TITLE
Referrer including site domain?

### ISSUE THREAD

**Issue by d19dotca** [umami-software/umami#1347]
I am somewhat new to Umami so I apologize if this was something I just never noticed before / overlooked, but is it normal for the referrer list to include the site domain that the analytics script is running on? I noticed only recently when reviewing data (and I swear I didn't see this before) that the Referrers list includes the site domain itself... is that being incorrectly recognized perhaps?

I'm currently running version (1.36).

FYI - you can see an example of what I'm talking about at this report URL: https://analytics2.d19.ca/share/PaeYiSoF/

**Comment by mikecao** [comment]
No, that shouldn't be happening. The domain that you set in the website settings should be used to filter out those results from referrers. But the demo site doesn't show this behavior, https://app.umami.is/share/8rmHaheU/umami.is?view=referrer

Is it possible you have a typo in your domain under settings?

**Comment by d19dotca** [comment]
I don't think it's a typo, as I see this behaviour in all my sites now and I've got around 15-18 of them configured. I don't think I saw it before either and haven't changed any settings since I basically set them up in early May so I'm sort of thinking this was somehow an issue presented in one of the version updates that I hadn't noticed before. 

I just noticed your demo is running 1.36.1 which looks like it was just released a few hours ago... maybe it's fixed in that one even inadvertently?

**Comment by Maxime-J** [comment]
Get this too with the newer versions,
website registered in umami without www (domain.tld) has the domain listed in referrers if referrer is `www.domain.tld`

Doesn't happen in 1.33.1, don't know if it's an intended change.
If you edit website domain in umami settings and include www, I guess you wouldn't see that.

**Comment by d19dotca** [comment]
I can confirm that upgrading to 1.36.1 didn't fix the problem. Definitely seems like an issue such as @Maxime-J mentioned where it isn't calculating things properly when it's www vs non-www. I will try changing one of mine and see if it resolves it later today.

**Comment by d19dotca** [comment]
Didn't realize it was such a quick process actually, thank you for allowing us to easily switch domain values on existing entries. :-) 

I can confirm in my environment that if I add "www." to the front of the domain I had before that it then disappears in the referral link for the same domain name, so I think this is a defect or something that was changed in Umami where it's not properly excluding referrals when from the same domain.

Thinking about it now though I guess I should have it set to www.example.com instead of just example.com in my case, but it wasn't a problem before so I didn't realize that mattered (plus the documentation and verbiage just state "domain" (not sub-domains)). 

It seems like a change that surfaced somewhere between 1.33.1 (judging by @Maxime-J's comment) and the 1.36.

**Comment by mikecao** [comment]
We made a lots of changes to the referrer logic recently and this is probably a side effect. This logic used to be in the UI but now it is handled in the database. But basically, www.example.com and example.com are considered different domains because technically you could have completely different content on both. In general people don't do that, they just forward one to the other.

So the options are:
1. Keep the current logic, www.example.com and example.com are different domains.
2. If you enter example.com, if will filter out all subdomains as well. If you want to track a subdomain specifically, you'll have to create another website entry.

**Comment by Maxime-J** [comment]
> I guess I should have it set to `www.example.com` instead of just `example.com` in my case, but it wasn't a problem before so I didn't realize that mattered (plus the documentation and verbiage just state "domain" (not sub-domains)).

Exactly the same for me. I asked my self on setup if I should include `www`, but how it's presented led me to put `example.com`
