### ISSUE TITLE
UTM parameter views not being recorded correctly

### ISSUE THREAD

**Issue by KevinVR** [umami-software/umami#1348]
Going to pages with the UTM tags for testing, using different IPs / clients (VPN):
![image](https://user-images.githubusercontent.com/2247829/180727811-a27ca578-cebe-4387-8b8b-ce97b1eedb26.png)

The stats still only show 1 view for those UTM tags:
![image](https://user-images.githubusercontent.com/2247829/180727896-82a9ab95-950e-44a2-b33e-86be045623f2.png)

I noticed people coming in through the UTM tag in real-time for my websites, but the UTM stats are not being updated (still 1 or 2)

**Comment by nominaltechnopv** [comment]
And, would be great if UTM tags could be selected for filters (like other parameters) 

p.s. and yes, utm tags don't working https://i.imgur.com/OiQWMrq.png

**Comment by mikecao** [comment]
Fixed in v1.37.0.
