### ISSUE TITLE
Custom API Endpoint issue

### ISSUE THREAD

**Issue by AliMickey** [umami-software/umami#1354]
Since discussions don't really get replies, here is an issue in an attempt to get an explanation.

What is the reason for requiring the new custom API endpoint environment variable to be a build time env.

I can confirm that the custom route resolves fine with a GET (not a 404, but an invalid request) similar to `/api/collect`. 

Where else, besides the script, is the endpoint change necessary that it requires change during build?

**Comment by rohandebsarkar** [comment]
The custom API variable is used in two places, once in the middleware and another for generating the script.

The custom API endpoint will be needed to be replaced in the script. And if I am not wrong, since the script is build only during the build time, it needs to be a build time variable.

**Comment by AliMickey** [comment]
If the script is the only place where a build time requirement is needed, it sounds like a bit of work can be done to remedy this. 

Unfortunately I don’t have experience with this framework, however I will try and research further.

**Comment by mikecao** [comment]
You can’t get around build time variables. A lot of them are enforced by Next.js because they in-line the data when building the app.

**Comment by AliMickey** [comment]
So I downloaded the script from Umami, edited the `api/collect` to `api/mickit` (my custom one specified via env).

And it works, I am able to verify that UBlock does NOT block the POST request as well as a record showing up under real-time in Umami.

So this is an easily fixable problem. The only thing that needs to be changed is the endpoint in the script, this can even be changed later (with regex as a worst case) if it HAS to be generated during build time.

**Comment by mikecao** [comment]
That is literally what the environment variable does, rewrites the endpoint at build time. But the middleware (runtime) still needs to know to forward `api/custom` to `api/collect`, so you still need to define an environment variable.

**Comment by AliMickey** [comment]
Yes, but my point is that I was able to get the custom endpoint working by only changing the endpoint string in the script. 

In order to support custom api endpoints, without building from source/docker build with source, is to change the script endpoint during runtime. 

Like I said, this can be done with simple regex, grab the env variable, find and replace `/api/collect` with the variable. That's it.

**Comment by mikecao** [comment]
I see what you mean. I think we would have to modify the start script specifically for docker to run some extra steps.

**Comment by AliMickey** [comment]
Yep exactly. Perhaps an extra script for the Dockerfile to run with simple bash regex. 

I'll take a look tomorrow, but I'm pretty sure it's a simple solution.

**Comment by mikecao** [comment]
Actually, there is probably an easier solution, simply include `build-tracker` in the start script. But we may just have to do an entire build because there are other build time variables that are affected. See #1369.

**Comment by AliMickey** [comment]
Sounds good, I trust that you will be able to come up with a desirable solution.

**Comment by mikecao** [comment]
Fixed in v1.37.0.
