### ISSUE TITLE
Docker registry seems to be down

### ISSUE THREAD

**Issue by JokerQyou** [umami-software/umami#1374]
According to README installation guide:

```bash
docker pull docker.umami.is/umami-software/umami:postgresql-latest
```

But results in error now:

```
Error response from daemon: received unexpected HTTP status: 502 Bad Gateway
```

By directly visiting https://docker.umami.is using a browser I can confirm the docker registry seems to be down.

**Comment by mikecao** [comment]
Can you try again? Should be working now

**Comment by JokerQyou** [comment]
It's working now.
