### ISSUE TITLE
Unable to analyze website referrer

### ISSUE THREAD

**Issue by xhemj** [umami-software/umami#1382]
Version is v1.36.1 with postgresql docker image.
When accessing the site via google, the referrer is not displayed in the control panel.
Manual query of  `document.referrer`  shows up correctly, but umami passes in the wrong value when requesting the api.
[Example website](https://baike.xmsyyxx.com/item/%E5%8E%A6%E9%97%A8%E5%B8%82%E9%9F%B3%E4%B9%90%E5%AD%A6%E6%A0%A1)

**Comment by franciscao633** [comment]
We redid the tracking script / api in v2. If you see any issues please feel free to report a new issue.
