### ISSUE TITLE
Add docker hub image 

### ISSUE THREAD

**Issue by DaiYuANg** [umami-software/umami#1383]
Because I am in China, and access GitHub/docker.umami.is/ghrc is very slowly. I did not find a mirror for that, there is docker hub mirror only.
For pull docker image, it takes me a one afternoon and one night.
Until now, the image did not pull finish
<img width="1121" alt="截屏2022-08-04 22 48 09" src="https://user-images.githubusercontent.com/106723472/182877152-17525257-4b9e-4d36-b3fb-b199836723c0.png">

Thanks!

**Comment by MarcHagen** [comment]
Try `docker.umami.is/umami-software/umami`, its a hosted server, but still in Europe.

**Comment by mikecao** [comment]
Try `docker.umami.dev` and see if it helps. This one is hosted on Cloudflare.

**Comment by DaiYuANg** [comment]
<img width="1090" alt="截屏2022-08-13 13 25 56" src="https://user-images.githubusercontent.com/106723472/184470023-428628b9-c88a-4c40-b3fa-06a180b91a3a.png">
`docker.umami.dev` is a bit faster than docker.umami.is but still slower than docker hub and when I pull image first, it shows TLS handshake timeout.
Especially 323ee911912e layer(103.5 MB), it's never pull success.

**Comment by sparanoid** [comment]
@DaiYuANg Try https://github.com/sparanoid/docker-umami and /ping @mikecao https://github.com/umami-software/umami/discussions/915#discussioncomment-3373644

**Comment by mikecao** [comment]
Sorry for the delay, finally got around to it, now on docker hub as `umamisoftware/umami`.

**Comment by DaiYuANg** [comment]
Thanks for your work
