### ISSUE TITLE
Setting the admin password from ENV variables

### ISSUE THREAD

**Issue by thetillhoff** [umami-software/umami#1384]
In order to fully support Infrastructure-as-Code settings, changing the admin password without manual intervention would also introduce additional security.

In case someone is actively searching for a new umami instance on a URL, that person could be faster than the administrator of said instance and gain unprivileged access.

Having the option to set the admin password via an environment variable would solve this issue. (And allows to reset the admin password with a simple restart of the instance.)

**Comment by stianlagstad** [comment]
To further support infrastructure-as-code settings, it would be great if one could start umami with a simple configuration file stating which websites should exist. Something like this:

websites.conf
```
some-website-name,predetermined-token
other-website-name,other-token
```

**Comment by stianlagstad** [comment]
In case it's helpful to others, here's a way to accomplish both when deploying umami on kubernetes: https://stianlagstad.no/2022/08/deploy-umami-analytics-with-kubernetes/.

**Comment by thetillhoff** [comment]
@mikecao seeing this issue going stale, are there any plans for improving the umami-initial setup without touching the database directly as @stianlagstad described?

If there are no plans, should we close this?

**Comment by mryechkin** [comment]
Any updates on this issue?

I'm currently facing a situation where I need to reset the `admin` password, and so far haven't been able to find how to do that. Having something like this would certainly make that easier.

**Comment by mryechkin** [comment]
I would still like to see this feature added :(
