### ISSUE TITLE
Copy Script Button does not respect TRACKER_SCRIPT_NAME env variable

### ISSUE THREAD

**Issue by timkley** [umami-software/umami#1386]
When setting the env variable `TRACKER_SCRIPT_NAME` the button `Get tracking code` on `BASE_PATH/settings` always returns `BASE_PATH/umami.js` instead of `BASE_PATH/TRACKER_SCRIPT_NAME.js`.

Currently, [the path is not dynamic](https://github.com/umami-software/umami/blob/master/components/forms/TrackingCodeForm.js#L27).

Would be glad to tackle this if you could point me in the right direction how you currently handle exposing environment variables to React. Are you using the [env settings in next.config.js](https://github.com/umami-software/umami/blob/master/next.config.js#L5-L10)?

**Comment by rohandebsarkar** [comment]
In my instance, this is working fine.

**Comment by mikecao** [comment]
Fixed in v1.37.0.

**Comment by timkley** [comment]
Wow thanks @mikecao for this lightning fast fix 🥰
