### ISSUE TITLE
When I try to deploy using the Next.js framework in cloudflare pages the build fails with the following error

### ISSUE THREAD

**Issue by essesoul** [umami-software/umami#1388]
When I try to deploy using the Next.js framework in cloudflare pages the build fails with the following error

10:15:21.009 | yarn install v1.22.4
10:15:21.100 | [1/4] Resolving packages...
10:15:21.349 | [2/4] Fetching packages...
10:15:45.740 | error @prisma/client@4.1.1: The engine "node" is incompatible with this module. Expected version ">=14.17". Got "12.18.0"
10:15:45.748 | error Found incompatible module.
10:15:45.748 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
10:15:45.776 | Error during Yarn install
10:15:45.779 | Failed: build command exited with code: 1
10:15:46.626 | Failed: an internal error occurred

**Comment by mikecao** [comment]
This is the error: Expected version ">=14.17". Got "12.18.0"
So the Node version on there is too old.

**Comment by essesoul** [comment]
By increasing the environment variable NODE_VERSION 14.17 I managed to resolve the above error and let the build continue, but then I got a series of errors before finishing.

![image](https://user-images.githubusercontent.com/58624474/183934598-f06824b1-70c6-426a-9107-15bebb0b80dc.png)

<html>
<body>


22:47:40.829 | Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
22:47:40.829 | Error: Error for page /login: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export
22:47:40.829 | at /opt/buildhome/repo/node_modules/next/dist/export/worker.js:209:27
22:47:40.829 | at async Span.traceAsyncFn (/opt/buildhome/repo/node_modules/next/dist/trace/trace.js:79:20)
22:47:40.849 |  
22:47:40.850 | Error occurred prerendering page "/console/[[...id]]". Read more: https://nextjs.org/docs/messages/prerender-error
22:47:40.850 | Error: Error for page /console/[[...id]]: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export
22:47:40.850 | at /opt/buildhome/repo/node_modules/next/dist/export/worker.js:209:27
22:47:40.850 | at async Span.traceAsyncFn (/opt/buildhome/repo/node_modules/next/dist/trace/trace.js:79:20)
22:47:40.850 | info  - Exporting (13/13)
22:47:40.853 | Error: Export encountered errors on following paths:
22:47:40.853 | /console/[[...id]]
22:47:40.853 | /login
22:47:40.853 | at /opt/buildhome/repo/node_modules/next/dist/export/index.js:395:19
22:47:40.853 | at processTicksAndRejections (internal/process/task_queues.js:95:5)
22:47:40.853 | at async Span.traceAsyncFn (/opt/buildhome/repo/node_modules/next/dist/trace/trace.js:79:20)
22:47:40.869 | Failed: build command exited with code: 1
22:47:41.708 | Failed: an internal error occurred


</body>
</html>

**Comment by mikecao** [comment]
I don't know if cloudflare pages supports Next.js.  You'll have to research.
