### ISSUE TITLE
There are some highlighted warnings when I try to deploy with vercel

### ISSUE THREAD

**Issue by essesoul** [umami-software/umami#1390]
There are some highlighted warnings when I try to deploy with vercel, although it can be successfully deployed and used.

![image](https://user-images.githubusercontent.com/58624474/183796226-90b67afd-e2ee-42e3-9925-113c96646dd5.png)

**Comment by essesoul** [comment]
<html>
<body>


warning "react-spring > @react-spring/konva@9.5.0" has unmet peer dependency "konva@>=2.6".
--
10:04:51.832 | warning "react-spring > @react-spring/konva@9.5.0" has unmet peer dependency "react-konva@^16.8.0  \|\| ^17.0.0".
10:04:51.832 | warning "react-spring > @react-spring/native@9.5.0" has unmet peer dependency "react-native@>=0.58".
10:04:51.832 | warning "react-spring > @react-spring/three@9.5.0" has unmet peer dependency "@react-three/fiber@>=6.0".
10:04:51.833 | warning "react-spring > @react-spring/three@9.5.0" has unmet peer dependency "three@>=0.126".
10:04:51.833 | warning "react-spring > @react-spring/zdog@9.5.0" has unmet peer dependency "react-zdog@>=1.0".
10:04:51.833 | warning "react-spring > @react-spring/zdog@9.5.0" has unmet peer dependency "zdog@>=1.0".
10:04:51.845 | warning "eslint-config-next > @typescript-eslint/parser > @typescript-eslint/typescript-estree > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 \|\| >= 3.2.0-dev \|\| >= 3.3.0-dev \|\| >= 3.4.0-dev \|\| >= 3.5.0-dev \|\| >= 3.6.0-dev \|\| >= 3.6.0-beta \|\| >= 3.7.0-dev \|\| >= 3.7.0-beta".
10:05:04.856 | [4/4] Building fresh packages...
10:05:12.071 | $ prisma generate \|\| true
10:05:14.085 | prisma:warn The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.


</body>
</html>

**Comment by mikecao** [comment]
Yes, they are common warnings. They don't affect the app.
