### ISSUE TITLE
Current visitor is missing in realtime view

### ISSUE THREAD

**Issue by Olakeen** [umami-software/umami#1396]
Sometimes, current visitor data is not displayed in realtime view :

![Capture d’écran 2022-08-10 111540](https://user-images.githubusercontent.com/26546237/183864764-9725c2b1-b4ff-47a7-b675-6b73cc29120b.png)

![Capture d’écran 2022-08-10 111556](https://user-images.githubusercontent.com/26546237/183864818-13d2ac41-1a81-4a46-be2c-418ce4fa3f0f.png)

![Capture d’écran 2022-08-10 111603](https://user-images.githubusercontent.com/26546237/183864833-0060d447-75e7-46a1-9992-f5705f227083.png)

I suspect it's because it's a returning visitor. Can this information be always displayed?

**Comment by mikecao** [comment]
Realtime and current visitor use different counts. On the dashboard, it's unique users in 5 minutes. On realtime it's what appears in the chart, which shows 0 new visitors, just views.
