### ISSUE TITLE
When multiple script names are defined, both names are shown in the tracking code

### ISSUE THREAD

**Issue by MagicLike** [umami-software/umami#1400]
Instead of specifying both names in the file name of the script, several codes could be generated to make copying easier.
Another possibility would be to choose only the first name for the tracking code.
![grafik](https://user-images.githubusercontent.com/82117109/183896958-8f4e604f-4c0d-486c-9b91-87ce8ad3ade6.png)

**Comment by MagicLike** [comment]
Any updates on this? - This bug does still occur.

**Comment by mikecao** [comment]
Fixed in v2.
