### ISSUE TITLE
Arm64 Image

### ISSUE THREAD

**Issue by DrMxrcy** [umami-software/umami#1404]
Is there a plan to provide an arm64 image? A lot of people run their services on things like raspberry Pis now, and it would be a good addition 

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by Mmx233** [comment]
Build multi platform image via Github Action is supported. I need arm version image too

**Comment by mikecao** [comment]
No plans at the moment. Would welcome a PR.
