### ISSUE TITLE
[feature] Share website with users, more advanced user/group/permission system

### ISSUE THREAD

**Issue by MarcHagen** [umami-software/umami#1407]
Hi,

We can create individual users, but cannot share 1 website amongst these users.
My use case is owner of website is me, adding 1 or 2 users with read permissions to a specific website. 

Could be a "simple" coupling/relationship table:
```mysql
CREATE TABLE account_website (
  id serial,
  user_id INT NOT NULL,
  website_id INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE (user_id, website_id),
  FOREIGN KEY (website_id) REFERENCES website.website_id ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES account.user_id ON DELETE CASCADE ON UPDATE CASCADE
)

```
`website.user_id` Would then still be the read/write account.
`account_website` coupling/relationship could be just read access accounts

Edit:
I cannot search properly apperently there is also a discussion https://github.com/umami-software/umami/discussions/826

**Comment by mikecao** [comment]
We have advanced roles and permissions in the pipeline. But for now you can use the share feature.

**Comment by mikecao** [comment]
Added ability to reassign owners for websites in v1.38.0. Other features still in the pipeline.
