### ISSUE TITLE
new ghcr.io/umami-software/umami:mysql-v1.37.0 image migrate db failed

### ISSUE THREAD

**Issue by bboysoulcn** [umami-software/umami#1419]
```
umami    | yarn run v1.22.19
umami    | $ npm-run-all check-db update-tracker start-server
umami    | $ node scripts/check-db.js
umami    | ✓ DATABASE_URL is defined.
umami    | ✓ Database connection successful.
umami    | ✓ Database tables found.
umami    | Prisma schema loaded from prisma/schema.prisma
umami    | Datasource "db": MySQL database "umami" at "10.0.0.194:3306"
umami    | 
umami    | 2 migrations found in prisma/migrations
umami    | 
umami    | Your local migration history and the migrations table from your database are different:
umami    | 
umami    | The last common migration is: 01_init
umami    | 
umami    | The migration have not yet been applied:
umami    | 02_add_event_data
umami    | 
umami    | The migration from the database are not found locally in prisma/migrations:
umami    | 20220627184654_init
umami    | 
umami    | Running update...
umami    | Error: P3018
umami    | 
umami    | A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
umami    | 
umami    | Migration name: 02_add_event_data
umami    | 
umami    | Database error code: 1064
umami    | 
umami    | Database error:
umami    | You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX  `username` TO `account_username_key`' at line 1
umami    | 
umami    | Please check the query number 16 from the migration file.
umami    | 
umami    | 
umami    | ✗ Command failed: prisma migrate deploy
umami    | Error: P3018
umami    | 
umami    | A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
umami    | 
umami    | Migration name: 02_add_event_data
umami    | 
umami    | Database error code: 1064
umami    | 
umami    | Database error:
umami    | You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INDEX  `username` TO `account_username_key`' at line 1
umami    | 
umami    | Please check the query number 16 from the migration file.
umami    | 
umami    | 
umami    | 
umami    | error Command failed with exit code 1.
umami    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami    | ERROR: "check-db" exited with 1.
umami    | error Command failed with exit code 1.
umami    | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by razinj** [comment]
Some work has been done recently, maybe you can try the tag `latest` and check this [issue](https://github.com/umami-software/umami/issues/1418#issuecomment-1212475931) for more context.

**Comment by wheeleran** [comment]
please @briancao can we have a fix for this for dummies like me on postgres docker-compose ubuntu.

**Comment by briancao** [comment]
1.37.0 has had it's migration script updated.  You will need to pull the latest version, then run the following commands to resolve the 02_migration failure.

```
yarn prisma migrate resolve --rolled-back "02_add_event_data"
yarn prisma migrate deploy
yarn check-db
```

**Comment by wheeleran** [comment]
> 1.37.0 has had it's migration script updated. You will need to pull the latest version, then run the following commands to resolve the 02_migration failure.
> 
> ```
> yarn prisma migrate resolve --rolled-back "02_add_event_data"
> yarn prisma migrate deploy
> yarn check-db
> ```

I'm very sorry for being an idiot in this,  but I run the docker-compose Postgres install. How exactly do I run this yarn script when yarn isn't recognized?

**Comment by miroslavpejic85** [comment]
> > 1.37.0 has had it's migration script updated. You will need to pull the latest version, then run the following commands to resolve the 02_migration failure.
> > ```
> > yarn prisma migrate resolve --rolled-back "02_add_event_data"
> > yarn prisma migrate deploy
> > yarn check-db
> > ```
> 
> I'm very sorry for being an idiot in this, but I run the docker-compose Postgres install. How exactly do I run this yarn script when yarn isn't recognized?

```bash
# Get running containers
docker ps

# Output something like this
CONTAINER ID   IMAGE                                                     COMMAND                  CREATED          STATUS          PORTS                                       NAMES
ce6dbbd35ee8   docker.umami.dev/umami-software/umami:postgresql-latest   "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   umami_umami_1
dd5b6df1e588   postgres:12-alpine                                        "docker-entrypoint.s…"   18 minutes ago   Up 18 minutes   5432/tcp                                    umami_db_1

# NAMES => umami_umami_1 (in my case)
docker exec -it umami_umami_1 yarn prisma migrate resolve --rolled-back "02_add_event_data"
docker exec -it umami_umami_1 yarn prisma migrate deploy
docker exec -it umami_umami_1 npm run check-db
```

**Comment by wheeleran** [comment]
hi @miroslavpejic85, and thanks; this _sort of_ worked. get running containers was 'sudo docker container ls' on my Synology NAS docker, and all script commands required sudo, but i've got the Realtime tab back, and no "something went wrong" error message in the Events tab.

But i've got no events, specifically the click-events that i've had running for weeks on one or two of my sites; no historical data, nothing that suggests there's anything there at all. can you help me with that?

**Comment by miroslavpejic85** [comment]
> hi @miroslavpejic85, and thanks; this _sort of_ worked. get running containers was 'sudo docker container ls' on my Synology NAS docker, and all script commands required sudo, but i've got the Realtime tab back, and no "something went wrong" error message in the Events tab.
> 
> But i've got no events, specifically the click-events that i've had running for weeks on one or two of my sites; no historical data, nothing that suggests there's anything there at all. can you help me with that? i've been probably dumb and changed my tracker script name today (something to do, twiddling my thumbs), updated it on all sites too of course, but could that possibly have anything to do with it?

I'm sorry, but I don't use events for now, I just collect simple statistics on my web app.
