### ISSUE TITLE
Migrate events data (1.37.0)

### ISSUE THREAD

**Issue by kunago** [umami-software/umami#1421]
I would kindly like to ask for support. I use events a lot, I have thousands of records. As is mentioned with the 1.37.0 release of Umami:

> When you start the app for the first time, the database changes will be automatically applied. Your data however will not be automatically migrated because we can't determine what event_name you will want to use. Your old event table has been renamed to _event_old, which you can use to manually move data to the new table. If you've never used events, feel free to delete the _event_old table.

If I knew how, I would migrate the data from one to another table but data table migrations may be quite tricky. Has anyone done the migration yet please?

**Comment by gouku** [comment]
You may got some issues when upgrade to 1.37.0 from an old instance for now. See https://github.com/umami-software/umami/issues/1406

**Comment by briancao** [comment]
Assuming you stored only string values in your event_value table, you can run the following script to run migrations of your `_event_old` data into your new `event` table.  The most important thing is for your time-series data to stay intact (created_at). 

```
INSERT INTO "event" (website_id, session_id, created_at, url, event_name)
SELECT website_id, session_id, created_at, url, event_value
FROM "_event_old"
```

We didn't include this in the migration because some users were not using the former type/value structure as intended (ex: storing json in event_value, etc).

**Comment by miguelcss** [comment]
Thanks

This script should be more clearly highlighted in the migration instructions, many default users run into an issue that has easy resolution. Maybe the db migrator could prompt users to migrate with this default behavior or skip).

Cheers

**Comment by NoLooseEnds** [comment]
@briancao 
I suggest that you add `;` to the SQL commands after `FROM _event_old` – ie `FROM _event_old;`. Or highlight that you need to close out the SQL commands with `;`.

I did not know (not that experienced in mysql), but then I saw [@ajfriesen comment](https://github.com/umami-software/umami/issues/1406#issuecomment-1217019768) and it worked. I got all my events back.

**Comment by kunago** [comment]
Maybe I am missing something but as I understand the 2 new tables, I should also populate event_data table, right?

`INSERT INTO event_data (event_id, event_data) SELECT (event_id, event_type) FROM _event_old ;`

Don't use this query on production data, I have not tested it.

**Comment by miguelcss** [comment]
After this migration, is it still possible to track events using css tags? 

- Documentation seems to point that yes: https://umami.is/docs/track-events
- In practice we lost css events tracking.

**Comment by briancao** [comment]
@kunago "event_type" has been dropped all-together and the event_data table does not need to be populated.  "event_data" can be seen as more of an additional feature going forward.  There is currently no way to even access that data in the UI at this time.  Unless you were one of the custom users that held JSON in their old event_type/event_value that is.

**Comment by kunago** [comment]
Okay, cool,, thank you for the explanation. So this is the solution:

> Assuming you stored only string values in your event_value table, you can run the following script to run migrations of your `_event_old` data into your new `event` table. The most important thing is for your time-series data to stay intact (created_at).
> 
> ```
> INSERT INTO event (website_id, session_id, created_at, url, event_name)
> SELECT website_id, session_id, created_at, url, event_value
> FROM _event_old;
> ```
> 
> We didn't include this in the migration because some users were not using the former type/value structure as intended (ex: storing json in event_value, etc).
> 
> (Edit: added semi-colon to end of script per suggestion)
