### ISSUE TITLE
Bounce rate is always 0% 

### ISSUE THREAD

**Issue by MostafaaRamadan** [umami-software/umami#1427]
After v1.37.0 the bounce rate is always zero percentage
<img width="685" alt="image" src="https://user-images.githubusercontent.com/97154768/184534557-1aa335b3-75f4-4aef-99c7-ba304cde16d1.png">

**Comment by njfdev** [comment]
In this picture, it shows there has only been 1 visit but there are many page views. A bounce rate of 0% is correct because a bounce is when a user visits just one page on your website.

**Comment by MostafaaRamadan** [comment]
Aha, got your point, thanks

**Comment by ThomasOrlita** [comment]
> bounce is when a user visits just one page on your website

Is it how it is calculated in umami? Since if you don't have more than one page (let's say the whole website is a landing page), then that wouldn't make much sense.
