### ISSUE TITLE
Umami.js as a <script> tag

### ISSUE THREAD

**Issue by 4l1fe** [umami-software/umami#1430]
I'd like to add **umami.js** code to a `<srcript>` tag. I can request it from the umami server and copy the code, but tried to find it out in the repo and didn't find it.

Tell me pls, can i copy the file from somewhere and how often is it changing?

**Comment by aidanm1999** [comment]
Hi @4l1fe,

The `<script />` tag that you find in umami is generated from the website ID and your current environment. If you are running the site locally your environment is `localhost` and therefore your `src` attribute will be `localhost/umami.js`. The website id only gets created once as it is an entry in the database, so it isn't hardcoded in the repo, it's just generated on the fly. It never changes; once the umami website is hosted and you have created a website from the admin panel, that script tag will stay the same as it is always fetching the same website id and domain name (unless you delete the website in umami or change your domain name).

<img width="732" alt="tracking code copy" src="https://user-images.githubusercontent.com/36016925/184634700-ca6900ea-5e12-4257-a475-ea1f53f55302.png">

**Comment by 4l1fe** [comment]
I forgot about `website-id`.
So workflowin my case should be:
1. Run umami locally
2. Do to the admin page
3. Create a domain record
4. Open the `/umami.js`, copy and paste content into an index page `script` tag
5. Copy `website-id` and paste it where?

My purpose is to remove a network request for `/umami.js` as it has big net.latency.

**Comment by aidanm1999** [comment]
What is your intended goal? The `umami.js` script is tiny (under 2KB) so the latency should be minimal. Besides, it uses `async` and `defer` by default so it doesn't impact your first contextual load. You need to host umami somewhere to be able to serve the script, and the script is just an interface to simplify sending API requests to the server. 

Have you set up the website and its domain correctly where you can access the umami dashboard?

**Comment by 4l1fe** [comment]
> What is your intended goal? The `umami.js` script is tiny (under 2KB) so the latency should be minimal. Besides, it uses `async` and `defer` by default so it doesn't impact your first contextual load. You need to host umami somewhere to be able to serve the script, and the script is just an interface to simplify sending API requests to the server.

I wrote my goal, probably you are used to all the static files are close to a client...

> 
> Have you set up the website and its domain correctly where you can access the umami dashboard?

Man you better help me with the workaround and explain how i have to pair my manually added `<script>` tag and js code in there up with `website-id`. If you know of course, thx.

**Comment by aidanm1999** [comment]
So, just to double check, you have:
- Forked/pulled the umami repo
- Deployed it to an accessible domain
- Deployed the database that is accessible

If you haven't done the above, it doesn't matter if you want to copy the code and add the `website-id` because there would be nowhere to send your requests to and nowhere that you can see your data. Umami is an analytics tool like Google Analytics. Google Analytics give you a script to add to your client site, which then communicates with Google servers and is displayed on the Google Analytics Dashboard. That's the same with umami. Umami has a dashboard that gives you the tracking code, you copy it and paste it into your site, it pulls the `umami.js` file which is the tracking script that communicates with the server and then you can log in and see your data visualised. 

The reason you can't find the `umami.js` file in the repo is that it is compiled at build time.

**Comment by 4l1fe** [comment]
Listen, you think in a very standard way, i understand it. I have a particular case and am not going to explain you everything, that's too long and unnecessary.

My question above is specific, if you can't help with it that's alright no problem.

**Comment by mikecao** [comment]
The script gets parameters from the `script` tag. If you want it to work a different way you have to rewrite the tracker and rebuild it yourself. The code is here

https://github.com/umami-software/umami/blob/master/tracker/index.js

Then run `yarn build-tracker` to compile it.

**Comment by 4l1fe** [comment]
I unminified `umami.js` to read and tried to paste it's content into the script tag. It doesn't work yet locally. I got an error but after parsing the `website-id` parameter...

The steps are gonna be working

> I forgot about `website-id`. So workaround in my case should be:
> 
> 1. Run umami locally
> 2. Go to the admin page
> 3. Create a domain record
> 4. Open the `/umami.js`, copy and paste content into an index page `script` tag
> 5. Copy `website-id` and paste it where?

**Comment by unindented** [comment]
> Listen, you think in a very standard way, i understand it. I have a particular case and am not going to explain you everything, that's too long and unnecessary.
> 
> My question above is specific, if you can't help with it that's alright no problem.

@4l1fe dude, be more respectful. The maintainers don't owe you shit.

**Comment by 4l1fe** [comment]
@unindented 

Dude, you take it too serious , take a look at this.
> if you can't help with it that's alright no problem.z

Umami is pretty good. I compared it to the competitors.
