### ISSUE TITLE
Events in website's MetricsBar

### ISSUE THREAD

**Issue by guigrpa** [umami-software/umami#1431]
Currently the MetricsBar component shows views, visitors, bounce rate and average visit time.

<img width="943" alt="Screenshot 2022-08-15 at 12 24 21" src="https://user-images.githubusercontent.com/2129481/184619290-1eb5b689-26b9-4539-81b0-66915417eaa8.png">
 
Would it be possible to add Events as well? This is key for websites to measure engagement, and is currently only available in the real-time view. If it is interesting, I can try to submit a PR.

**Comment by mikecao** [comment]
The total number of events is not very valuable without the context of what the event is. That's why you need to open up the details page.

**Comment by guigrpa** [comment]
Yes, I meant adding the Events counter to the details page. Would it be interesting that I submit a PR?

**Comment by mikecao** [comment]
I still think events should remain separate from the other stats. We will add enhanced events functionality in the future.
