### ISSUE TITLE
Migration Issue: Invariant violation: called markMigrationRolledBack on a database without migrations table.

### ISSUE THREAD

**Issue by briancao** [umami-software/umami#1435]
> 1.37.0 has had it's migration script updated. Users will need to pull the latest version, then run the following commands to resolve the 02_migration failure.
> 
> ```
> yarn prisma migrate resolve --rolled-back "02_add_event_data"
> yarn prisma migrate deploy
> yarn check-db
> ```

If I run the first line, I get this error: 
```
Error: Could not find a schema.prisma file that is required for this command.
You can either provide it with --schema, set it as `prisma.schema` in your package.json or put it into the default location ./prisma/schema.prisma https://pris.ly/d/prisma-schema-location
```

then I add the schema:
` yarn prisma migrate resolve --rolled-back "02_add_event_data" --schema=./db/postgresql/schema.prisma`

then I get this error:

```
Prisma schema loaded from db/postgresql/schema.prisma
Datasource "db": PostgreSQL database "postgres", schema "public" at "db.smkoohqmotkuxozodbpt.supabase.co:5432"
Error: Invariant violation: called markMigrationRolledBack on a database without migrations table.
   0: migration_core::state::MarkMigrationRolledBack
           with migration_name="02_add_event_data"
             at migration-engine/core/src/state.rs:328
```

error Command failed with exit code 1.

Can you help me please?

_Originally posted by @marc-on-github in https://github.com/umami-software/umami/issues/1393#issuecomment-1214698165_

**Comment by briancao** [comment]
Can I ask what version of Umami you're upgrading from?  It looks like it might pre-date our prisma migration files as the error message is stating you have no migration history.

We tested this scenario and in your case, it might be as simple as running 1 commands.

```
yarn build-db
yarn check-db
```

**Comment by marc-on-github** [comment]
thanks, now it works!
