### ISSUE TITLE
Deployment to Railway

### ISSUE THREAD

**Issue by sayzlim** [umami-software/umami#1437]
It seems that the setup on Railway is unable to detect the database I'm using. It was running fine in 1.36.1. Did I miss anything when I pulled the latest update?

![Railway Build Error](https://user-images.githubusercontent.com/791279/184942928-0bcf7d83-958f-4461-a86e-dfc8138abedf.png)

**Comment by mikecao** [comment]
Do you have `DATABASE_URL` defined?

**Comment by sayzlim** [comment]
It's defined on Railway, but when I run `railway up` the `DATABASE_URL` is undefined.

![Railway Variables](https://user-images.githubusercontent.com/791279/185015397-a7868bd8-f646-442c-ad31-c620dcf0369e.png)

I'm going to check with Railway to see if they can help with it.

**Comment by tony-atlas** [comment]
I have the same issue with the Railway update from 1.36.1 to 1.37.0.
I solved the problem add an environment variable "DATABASE_TYPE=postgresql"
@sayzlim you may try it to see if the problem is solved.

**Comment by sayzlim** [comment]
@tony-atlas thanks! It works for me. I didn't realize that it didn't pick up the `DATABASE_TYPE`.
