### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by azat-io** [umami-software/umami#1438]
Unable to deploy to Heroku. I am getting the following error:

"We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy"

![Screen Recording 2022-08-16 at 11 02 48 PM](https://user-images.githubusercontent.com/5698350/184974510-f904db1f-df06-45d1-a4f5-ba331cb02d74.gif)

**Comment by mikecao** [comment]
That's a Heroku problem. You'll have to submit a ticket with them.

**Comment by azat-io** [comment]
@mikecao Heroku response:

"As the error states, it appears that the source code of the app you attempted to deploy violates the [Salesforce Acceptable Use and External-Facing Services Policy](https://www.heroku.com/policy/aup). I'm afraid we cannot provide you any insight on this and the decision is final.

Regards,
Becky"

**Comment by mikecao** [comment]
There is nothing we can do about it. It is completely on Heroku side. And since they won't tell you the reason for the violation, it is impossible to fix.
