### ISSUE TITLE
delete event data

### ISSUE THREAD

**Issue by wheeleran** [umami-software/umami#1439]
hi. finally successfully migrated all event data to 1.37.0, but can someone help me with an SQL query to delete specific events from the postgres db? i've got two specific issues: a. a now-deleted tracked click event that seems to be stuck in the list of events in the umami UI, which i want **gone**, and b. even stranger, the name of a tracked event that's been entered letter by letter as seperate events. ie "this-event" is in as "t" and "th" and "thi" and this" and "this-" and "this-e" and "this-ev" and so on.... !

**Comment by briancao** [comment]
Are these new events as of 1.37.0? Or only events that were migrated from _event_old that have this odd behavior?

**Comment by wheeleran** [comment]
@briancao brand new events.

**Comment by mikecao** [comment]
Make sure the tracker is not cached (load the tracker and do a hard refresh) or clear your cache. It's possible you're picking up the old code.

**Comment by wheeleran** [comment]
Just incredible that it seemed to register each keystroke. I hadn't even saved the page yet. I've deleted site and CDN cache numerous times, and hard refreshed the page and browser. Same issue in incognito mode too, so I asked if there was any way to delete these entries from the dB, because I'm fresh out of ideas.

**Comment by briancao** [comment]
We should fix the root of the problem first as even with a DB fix, new entries are going to be written.  What CSS event are you using to capture data?

**Comment by wheeleran** [comment]
Simple click events on buttons or links, so 'umami--click--<event-name>'.

**Comment by wheeleran** [comment]
> Make sure the tracker is not cached (load the tracker and do a hard refresh) or clear your cache. It's possible you're picking up the old code.

it's not old code or cache, i've checked; it's not in page source so it's just in umami. can you help me with this? it's beyond annoying.

**Comment by wheeleran** [comment]
@briancao any assistance would be appreciated. If there's a bug with RESET I can't do that either, so I'm stuck. If you could help me with an SQL query to clear these entries out of the dB, I'd be grateful.

**Comment by briancao** [comment]
I think we've figured out how this happened.  I'm guessing all those unwanted events occured during a period when your DB was out of sync with the application, and the tracker was mis-aligned and parsing the event_value into a JSON object, resulting in multiple entries.  Now that your DB and app are aligned, no new 'bad data' should be getting inserted.

Performing the deletes is going to be a tedious process.  If you want to delete all the bad data out, you're going to have to run a version of the following script to review all the data you're about to delete.  Listed in the "IN CLAUSE" is all the events you want to keep.

`select * from analytics.event
where event_name not in ('your-event-name', 'another-event-name', 'everything-to-not-delete');`

If you're happy with the results, you can then delete the data querried by modifying the query into a delete.

`delete from analytics.event
where event_name not in ('your-event-name', 'another-event-name', 'everything-to-not-delete');`

**Comment by azat-io** [comment]
After clean install

<img width="1169" alt="image" src="https://user-images.githubusercontent.com/5698350/186146246-daee1a53-3bcb-4a14-a458-1749025f3eba.png">

**Comment by wheeleran** [comment]
> If you're happy with the results, you can then delete the data querried by modifying the query into a delete.
> 
> `delete from analytics.event where event_name not in ('your-event-name', 'another-event-name', 'everything-to-not-delete');`

hi brian, thanks for this. i was very hopeful but i get an immediate error: 'relation "analytics.event" does not exist'
can you have another look it this please, and is there a way to search for IN rather than 'NOT in'? having to print ALL my existing track even names is a bit of a pain (though you did say it would be tedious!). thanks in advance!

**Comment by briancao** [comment]
My mistake.  You'll have to remove the schema, as that 'analytics' schema name is specific to the data I'm working with.  

You can perform the following query to see all the unique events.
`select distinct event_name from event;`

Then perform either of the fixed queries to delete.
DELETE NOT IN
`delete from event where event_name not in ('your-event-name', 'another-event-name', 'everything-to-not-delete');`
DELETE IN
`delete from event where event_name in ('your-event-name', 'another-event-name', 'everything-to-delete');`

I did come up with a query to maybe help you identify some of your problematic data if your data-set is massive.  It slightly runs the risk of being too aggressive, so I would definitely review the data.
```
select distinct e2.event_name
from (select distinct event_name from event) e
    join (select distinct event_name from event) e2
        on e.event_name like (e2.event_name || '%')
        and e.event_name <>  e2.event_name
        and char_length(e2.event_name) > 1;
```

**Comment by wheeleran** [comment]
@briancao yes this worked! specifically the DELETE IN query; thank you so very much, and best of luck fixing all the bugs in this very problematic 1.37 update!
