### ISSUE TITLE
Compatibility with web worker offloads (i.e. Partytown?)

### ISSUE THREAD

**Issue by franciskafieh** [umami-software/umami#1442]
Hello there! I have been using umami from within a Partytown script. This has improved many of my Lighthouse performance metrics. To set the script up as a partytown script, you do: `<script src="/umami.js" ... type="text/partytown">`. This works until I try to query the value of a svelte store, combined with a checkbox (see reprod. code snippets below.) This throws a bunch of errors in the browser console: "TypeError: NodeCstr is not a constructor" coming from the `partytown-ww-sw.js` script. I can confirm this is an issue between partytown and umami, because if I change the src of the script to something else (e.g. cloudflare's jquery), the error goes away. If I remove the type="text/partytown" from the script, the error also goes away.

Is there something I am doing wrong? Thank you so much!

Code reprod: https://github.com/franciskafieh/franciskafieh.com/tree/staging

specifically...
1. My script in my page layout, located at https://github.com/franciskafieh/franciskafieh.com/blob/1c840719055ef609a067b8c54c9b047c8c636716/src/layouts/Page.astro#L37-L38 
2. My svelte store, located at https://github.com/franciskafieh/franciskafieh.com/blob/1c840719055ef609a067b8c54c9b047c8c636716/src/lib/stores.ts
3. My theme toggle component, located at https://github.com/franciskafieh/franciskafieh.com/blob/1c840719055ef609a067b8c54c9b047c8c636716/src/components/ThemeToggle.svelte

**Comment by franciskafieh** [comment]
Nevermind, this is an error specifically with astro's integration of Partytown. Closing....

**Comment by AkashRajpurohit** [comment]
Hey @franciskafieh can you share how you resolved it with asrto's integraton of Partytown?

**Comment by franciskafieh** [comment]
> Hey @franciskafieh can you share how you resolved it with asrto's integraton of Partytown?

I don't think I ever really did.... quote from my message in Astro's discord:
> now i'm using a store and reading it differently, and the error only produces on file save (dev mode) and then it goes away 

If you want to give the thread a read for some ideas, here you go: https://discord.com/channels/830184174198718474/1009703006033412126/1009703009397243915

But to be honest, it's been so long that I don't remember...
