### ISSUE TITLE
Cant reset website if custom event data exists

### ISSUE THREAD

**Issue by JLN13X** [umami-software/umami#1448]
I tracked some custom events and wanted to reset my whole website now but I always got 500. 
Had to empty the `event_data` Table manually in order for it to work. Probably some relation problems

**Comment by briancao** [comment]
This is the bug tracked in https://github.com/umami-software/umami/issues/1416.  A fix is currently in progress on this.

**Comment by briancao** [comment]
PR https://github.com/umami-software/umami/pull/1449. Will be solved in 1.38.0.
