### ISSUE TITLE
TRACKER_SCRIPT_NAME not working

### ISSUE THREAD

**Issue by modernphilosophy** [umami-software/umami#1452]
I set the environment variables TRACKER_SCRIPT_NAME: 'l.js' and COLLECT_API_ENDPOINT: '/api/c' in railway, but the script is still only available at '/umami.js'. I even tried redeploying after chaning the environment variables.

**Comment by farrej10** [comment]
`COLLECT_API_ENDPOINT = /api/endpoint
TRACKER_SCRIPT_NAME = l
`
like this the quotes are not working in my testing
