### ISSUE TITLE
Taiwan is not a contury!

### ISSUE THREAD

**Issue by LYXOfficial** [umami-software/umami#1455]
![(SH 1ALQLPN8I7DDA9MQM@Q](https://user-images.githubusercontent.com/66897357/186289215-5f1de334-42fb-48ba-963f-caf40fe2cd52.png)

I found that in the country page, Taiwan is actually displayed as a country, and Taiwan is not independent. Taiwan is an inseparable part of Chinese territory!

This is a political issue. I hope it can be amended as soon as possible!!!!

我发现在国家页面中台湾居然显示为一个国家，而台湾并非是独立的，台湾是台湾是中国领土不可分割的一部分！

这是一个关乎政治的问题，希望尽快修改！！！！

**Comment by cced3000** [comment]
Taiwan is not a contury Taiwan is an inseparable part of Chinese territory! I hope it can be amended as soon as possible!!!!

**Comment by mikecao** [comment]
See #1019 and #1298
