### ISSUE TITLE
Password length issue(guess), and needs reset

### ISSUE THREAD

**Issue by thepra** [umami-software/umami#1460]
Given no shown password rules I guess I locked myself out without knowing how to login back again.
It does seem that the 80 unicode chars long password provided from the password manager didn't got through as-is and now I'm locked out.
Is there a way to reset the admin password of a docker running image of umami?

**Comment by mikecao** [comment]
You need to update the database to reset the password back to the original.

```sql
UPDATE account SET password='$2b$10$BUli0c.muyCW1ErNJc3jL.vFRFtFJWrT8/GcR4A.sUdCznaXiqFXa' WHERE username='admin';
```
