### ISSUE TITLE
Error 403 Forbidden on collect API

### ISSUE THREAD

**Issue by valtlfelipe** [umami-software/umami#1461]
Hi! I'm having some trouble with the tracking script, where I'm getting `403 Forbidden` on the collect endpoint.

See a postman example to demonstrate:
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/3065339/186788865-f9326a71-1678-41b1-9065-1cdb5140c4da.png">

No logs are shown in the console, using the latest postgresql umami 1.37.0.

**Comment by mikecao** [comment]
Are you running a server in front of the app? This is usually a case of not having the correct CORS headers on the webserver.

**Comment by lucasjose501** [comment]
I noticed that error 403 is the response when you add your IP to IGNORE_IP environment. OP, is your IP in the ignore list?

**Comment by valtlfelipe** [comment]
> I noticed that error 403 is the response when you add your IP to IGNORE_IP environment. OP, is your IP in the ignore list?

Yeah, that's it. Sorry, my mistake 😅
