### ISSUE TITLE
[FEATURE] Implement autoclean data

### ISSUE THREAD

**Issue by qlaffont** [umami-software/umami#1469]
Hello 👋,

I'm wondering if it's planned or wanted to implement auto clean stats after a couple of times ? For example, 1 year compare to today.

To do this, I think we can work with an environment variable and use https://github.com/vercel/ms to make easier configuration.

(Maybe use this lib too to check every day https://tryslater.com/docs)

What do you think ? ^^
Regards 
Quentin

**Comment by mikecao** [comment]
There is nothing planned. I think most people just want to keep their data.
