### ISSUE TITLE
Database migration fails if the database password contains the `#` symbol

### ISSUE THREAD

**Issue by stianlagstad** [umami-software/umami#1480]
I discovered that if my `DATABASE_URL` has specific characters, such as the `#` character in a password, then `yarn check-db` fails:

```bash
yarn run v1.22.19
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✗ Unable to connect to the database.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here, `DATABASE_URL` was `postgresql://myuser:my#pass@myhost:5432/mydb`. I'm using `docker.umami.is/umami-software/umami:postgresql-v1.36.1`.

**Comment by stianlagstad** [comment]
Useful reads:
- https://www.prisma.io/docs/reference/database-reference/connection-urls#special-characters
- https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding

I solved it on my end by escaping the `#` into `%23`.

**Comment by franciscao633** [comment]
Closing this out. Thanks for providing a solution.
