### ISSUE TITLE
Documentation about docker images unclear

### ISSUE THREAD

**Issue by roldengarm** [umami-software/umami#1482]
I would like to run the MySQL Docker image, but I'm getting the following error when running the image:
```
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✗ DATABASE_URL is not defined.
```
I can't find anywhere in the documentation what I should specify for the DATABASE_URL for MySQL? It's running inside the container, so should be a localhost URL.

For Postgres, I can figure it out by checking the docker-compose.yml.

[The documentation](https://umami.is/docs/getting-started) is not clear about this.

**Comment by briancao** [comment]
An example of a mysql connection string can be found on the installation page, https://umami.is/docs/install.

**Comment by roldengarm** [comment]
Thanks @briancao . I got confused a little bit as I was assuming the docker image had MySQL built in... My bad!

It took me some time, but I now have it running on Azure using a PostgresDB Single Server. Loving it! 
If you want, I can share the bicep code to deploy this.
