### ISSUE TITLE
Inaccurate statistics after using cdn

### ISSUE THREAD

**Issue by SeTube** [umami-software/umami#1483]
Country/Region Displays only the node region of the cdn
![umami.webp](https://dd-static.jd.com/ddimg/jfs/t1/212560/11/21251/128098/63133622Ed823f96a/bc1733667b3e6e4c.webp)

**Comment by mikecao** [comment]
You need to see what headers are being passed to your servers. Then you can use `CLIENT_IP_HEADER` to track the correct IP address. See https://umami.is/docs/environment-variables
