### ISSUE TITLE
Same color for all visitor in realtime view

### ISSUE THREAD

**Issue by andlil** [umami-software/umami#1496]
Just upgraded to 1.38 and noticed that all visitors have the same color dot in front of every log entry making it impossible to distinguish them from each other.
![Skärmavbild 2022-09-06 kl  11 10 33](https://user-images.githubusercontent.com/10003475/188596234-ddd396e1-578a-427e-899d-892825cd2ff2.png)

**Comment by Jonnyan404** [comment]
我也是一样的情况
