### ISSUE TITLE
Not clear if migrations are run automatically

### ISSUE THREAD

**Issue by thomascenni** [umami-software/umami#1497]
Hi,
I just upgraded my server to latest v1.38.0, using official Umami Docker image on production.
I got this messages:

```
Sep 6 08:38:25 AM  Following migration have not yet been applied:
Sep 6 08:38:25 AM  03_remove_casade_delete
Sep 6 08:38:25 AM  
Sep 6 08:38:25 AM  To apply migrations in development run yarn prisma migrate dev.
Sep 6 08:38:25 AM  To apply migrations in production run yarn prisma migrate deploy.
```

The question is: do I need to run the migrations ? Shouldn't be done automatically ?
Thanks in advance.

**Comment by baubie** [comment]
Same here - the release notes say that they are run automatically but that isn't working - the same migration is not applied on our side.

**Comment by briancao** [comment]
@thomascenni Your entire log should look something like the following.  If this is what you have, consider yourself up to date.

```
umami-umami-1  | yarn run v1.22.19
umami-umami-1  | $ npm-run-all check-db update-tracker start-server
umami-umami-1  | $ node scripts/check-db.js
umami-umami-1  | ✓ DATABASE_URL is defined.
umami-umami-1  | ✓ Database connection successful.
umami-umami-1  | ✓ Database tables found.
postgres       | 2022-09-06 17:31:29.630 UTC [30] LOG:  could not receive data from client: Connection reset by peer
umami-umami-1  | Prisma schema loaded from prisma/schema.prisma
umami-umami-1  | Datasource "db": PostgreSQL database "umami", schema "analytics" at "postgres:5432"
umami-umami-1  | 
umami-umami-1  | 3 migrations found in prisma/migrations
umami-umami-1  | 
umami-umami-1  | Following migration have not yet been applied:
umami-umami-1  | 03_remove_casade_delete
umami-umami-1  | 
umami-umami-1  | To apply migrations in development run yarn prisma migrate dev.
umami-umami-1  | To apply migrations in production run yarn prisma migrate deploy.
umami-umami-1  | 
umami-umami-1  | Running update...
umami-umami-1  | Prisma schema loaded from prisma/schema.prisma
umami-umami-1  | Datasource "db": PostgreSQL database "umami", schema "analytics" at "postgres:5432"
umami-umami-1  | 
umami-umami-1  | 3 migrations found in prisma/migrations
umami-umami-1  | 
umami-umami-1  | Applying migration `03_remove_casade_delete`
umami-umami-1  | 
umami-umami-1  | The following migration have been applied:
umami-umami-1  | 
umami-umami-1  | migrations/
umami-umami-1  |   └─ 03_remove_casade_delete/
umami-umami-1  |     └─ migration.sql
umami-umami-1  | 
umami-umami-1  | All migrations have been successfully applied.
umami-umami-1  | 
umami-umami-1  | ✓ Database is up to date.
umami-umami-1  | $ node scripts/update-tracker.js
umami-umami-1  | $ node server.js
umami-umami-1  | Listening on port 3000
```

**Comment by thomascenni** [comment]
> @thomascenni Your entire log should look something like the following. If this is what you have, consider yourself up to date.
> 
> ```
> umami-umami-1  | yarn run v1.22.19
> umami-umami-1  | $ npm-run-all check-db update-tracker start-server
> umami-umami-1  | $ node scripts/check-db.js
> umami-umami-1  | ✓ DATABASE_URL is defined.
> umami-umami-1  | ✓ Database connection successful.
> umami-umami-1  | ✓ Database tables found.
> postgres       | 2022-09-06 17:31:29.630 UTC [30] LOG:  could not receive data from client: Connection reset by peer
> umami-umami-1  | Prisma schema loaded from prisma/schema.prisma
> umami-umami-1  | Datasource "db": PostgreSQL database "umami", schema "analytics" at "postgres:5432"
> umami-umami-1  | 
> umami-umami-1  | 3 migrations found in prisma/migrations
> umami-umami-1  | 
> umami-umami-1  | Following migration have not yet been applied:
> umami-umami-1  | 03_remove_casade_delete
> umami-umami-1  | 
> umami-umami-1  | To apply migrations in development run yarn prisma migrate dev.
> umami-umami-1  | To apply migrations in production run yarn prisma migrate deploy.
> umami-umami-1  | 
> umami-umami-1  | Running update...
> umami-umami-1  | Prisma schema loaded from prisma/schema.prisma
> umami-umami-1  | Datasource "db": PostgreSQL database "umami", schema "analytics" at "postgres:5432"
> umami-umami-1  | 
> umami-umami-1  | 3 migrations found in prisma/migrations
> umami-umami-1  | 
> umami-umami-1  | Applying migration `03_remove_casade_delete`
> umami-umami-1  | 
> umami-umami-1  | The following migration have been applied:
> umami-umami-1  | 
> umami-umami-1  | migrations/
> umami-umami-1  |   └─ 03_remove_casade_delete/
> umami-umami-1  |     └─ migration.sql
> umami-umami-1  | 
> umami-umami-1  | All migrations have been successfully applied.
> umami-umami-1  | 
> umami-umami-1  | ✓ Database is up to date.
> umami-umami-1  | $ node scripts/update-tracker.js
> umami-umami-1  | $ node server.js
> umami-umami-1  | Listening on port 3000
> ```

Hi,
And thanks for looking into this.
This is the complete log:

```
Sep 6 08:37:13 AM  yarn run v1.22.19
Sep 6 08:37:14 AM  $ npm-run-all check-db update-tracker start-server
Sep 6 08:37:18 AM  $ node scripts/check-db.js
Sep 6 08:37:20 AM  ✓ DATABASE_URL is defined.
Sep 6 08:37:20 AM  ✓ Database connection successful.
Sep 6 08:37:21 AM  ✓ Database tables found.
Sep 6 08:38:25 AM  Prisma schema loaded from prisma/schema.prisma
Sep 6 08:38:25 AM  Datasource "db": PostgreSQL database "umami", schema "public" at "xxxx:5432"
Sep 6 08:38:25 AM  
Sep 6 08:38:25 AM  3 migrations found in prisma/migrations
Sep 6 08:38:25 AM  
Sep 6 08:38:25 AM  Following migration have not yet been applied:
Sep 6 08:38:25 AM  03_remove_casade_delete
Sep 6 08:38:25 AM  
Sep 6 08:38:25 AM  To apply migrations in development run yarn prisma migrate dev.
Sep 6 08:38:25 AM  To apply migrations in production run yarn prisma migrate deploy.
Sep 6 08:38:25 AM  
Sep 6 08:38:25 AM  Running update...
Sep 6 08:39:17 AM  {
Sep 6 08:39:17 AM    table: 'pageview',
Sep 6 08:39:17 AM    column: null,
Sep 6 08:39:17 AM    filters: {
Sep 6 08:39:17 AM      url: undefined,
Sep 6 08:39:17 AM      referrer: undefined,
Sep 6 08:39:17 AM      os: undefined,
Sep 6 08:39:17 AM      browser: undefined,
Sep 6 08:39:17 AM      device: undefined,
Sep 6 08:39:17 AM      country: undefined
Sep 6 08:39:17 AM    },
Sep 6 08:39:17 AM    params: [ 2, 2022-09-05T12:00:00.000Z, 2022-09-06T11:59:59.999Z ]
Sep 6 08:39:17 AM  }
Sep 6 08:39:17 AM  {
Sep 6 08:39:17 AM    table: 'pageview',
Sep 6 08:39:17 AM    column: null,
Sep 6 08:39:17 AM    filters: {
Sep 6 08:39:17 AM      url: undefined,
Sep 6 08:39:17 AM      referrer: undefined,
Sep 6 08:39:17 AM      os: undefined,
Sep 6 08:39:17 AM      browser: undefined,
Sep 6 08:39:17 AM      device: undefined,
Sep 6 08:39:17 AM      country: undefined
Sep 6 08:39:17 AM    },
Sep 6 08:39:17 AM    params: [ 2, 2022-09-04T12:00:00.001Z, 2022-09-05T12:00:00.000Z ]
Sep 6 08:39:17 AM  }
Sep 6 08:39:17 AM  {
Sep 6 08:39:17 AM    table: 'pageview',
Sep 6 08:39:17 AM    column: null,
Sep 6 08:39:17 AM    filters: {
Sep 6 08:39:17 AM      url: undefined,
Sep 6 08:39:17 AM      referrer: undefined,
Sep 6 08:39:17 AM      os: undefined,
Sep 6 08:39:17 AM      browser: undefined,
Sep 6 08:39:17 AM      device: undefined,
Sep 6 08:39:17 AM      country: undefined
Sep 6 08:39:17 AM    },
Sep 6 08:39:17 AM    params: [ 2, 2022-09-05T12:00:00.000Z, 2022-09-06T11:59:59.999Z ]
Sep 6 08:39:17 AM  }
Sep 6 08:39:17 AM  {
Sep 6 08:39:17 AM    table: 'pageview',
Sep 6 08:39:17 AM    column: null,
Sep 6 08:39:17 AM    filters: {
Sep 6 08:39:17 AM      url: undefined,
Sep 6 08:39:17 AM      os: undefined,
Sep 6 08:39:17 AM      browser: undefined,
Sep 6 08:39:17 AM      device: undefined,
Sep 6 08:39:17 AM      country: undefined
Sep 6 08:39:17 AM    },
Sep 6 08:39:17 AM    params: [ 2, 2022-09-05T12:00:00.000Z, 2022-09-06T11:59:59.999Z ]
Sep 6 08:39:17 AM  }
Sep 6 08:39:19 AM  {
Sep 6 08:39:19 AM    table: 'pageview',
Sep 6 08:39:19 AM    column: null,
Sep 6 08:39:19 AM    filters: {
Sep 6 08:39:19 AM      url: undefined,
Sep 6 08:39:19 AM      referrer: undefined,
Sep 6 08:39:19 AM      os: undefined,
Sep 6 08:39:19 AM      browser: undefined,
Sep 6 08:39:19 AM      device: undefined,
Sep 6 08:39:19 AM      country: undefined
Sep 6 08:39:19 AM    },
Sep 6 08:39:19 AM    params: [ 1, 2022-09-05T12:00:00.000Z, 2022-09-06T11:59:59.999Z ]
Sep 6 08:39:19 AM  }
Sep 6 08:39:19 AM  {
Sep 6 08:39:19 AM    table: 'pageview',
Sep 6 08:39:19 AM    column: null,
Sep 6 08:39:19 AM    filters: {
Sep 6 08:39:19 AM      url: undefined,
Sep 6 08:39:19 AM      os: undefined,
Sep 6 08:39:19 AM      browser: undefined,
Sep 6 08:39:19 AM      device: undefined,
Sep 6 08:39:19 AM      country: undefined
Sep 6 08:39:19 AM    },
Sep 6 08:39:19 AM    params: [ 1, 2022-09-05T12:00:00.000Z, 2022-09-06T11:59:59.999Z ]
Sep 6 08:39:19 AM  }
Sep 6 08:39:19 AM  {
Sep 6 08:39:19 AM    table: 'pageview',
Sep 6 08:39:19 AM    column: null,
Sep 6 08:39:19 AM    filters: {
Sep 6 08:39:19 AM      url: undefined,
Sep 6 08:39:19 AM      referrer: undefined,
Sep 6 08:39:19 AM      os: undefined,
Sep 6 08:39:19 AM      browser: undefined,
Sep 6 08:39:19 AM      device: undefined,
Sep 6 08:39:19 AM      country: undefined
Sep 6 08:39:19 AM    },
Sep 6 08:39:19 AM    params: [ 1, 2022-09-05T12:00:00.000Z, 2022-09-06T11:59:59.999Z ]
Sep 6 08:39:19 AM  }
Sep 6 08:39:20 AM  {
Sep 6 08:39:20 AM    table: 'pageview',
Sep 6 08:39:20 AM    column: null,
Sep 6 08:39:20 AM    filters: {
Sep 6 08:39:20 AM      url: undefined,
Sep 6 08:39:20 AM      referrer: undefined,
Sep 6 08:39:20 AM      os: undefined,
Sep 6 08:39:20 AM      browser: undefined,
Sep 6 08:39:20 AM      device: undefined,
Sep 6 08:39:20 AM      country: undefined
Sep 6 08:39:20 AM    },
Sep 6 08:39:26 AM  Prisma schema loaded from prisma/schema.prisma
Sep 6 08:39:26 AM  Datasource "db": PostgreSQL database "umami", schema "public" at "xxxx:5432"
Sep 6 08:39:26 AM  
Sep 6 08:39:26 AM  3 migrations found in prisma/migrations
Sep 6 08:39:26 AM  
Sep 6 08:39:26 AM  
Sep 6 08:39:26 AM  No pending migrations to apply.
Sep 6 08:39:26 AM  
Sep 6 08:39:26 AM  ✓ Database is up to date.
Sep 6 08:39:28 AM  $ node scripts/update-tracker.js
Sep 6 08:39:31 AM  $ node server.js
Sep 6 08:39:33 AM  Listening on port 10000
```
It seems different from yours where you have the sentence "The following migration have been applied":

```
> umami-umami-1  | The following migration have been applied:
> umami-umami-1  | 
> umami-umami-1  | migrations/
> umami-umami-1  |   └─ 03_remove_casade_delete/
> umami-umami-1  |     └─ migration.sql
```
Thanks

**Comment by briancao** [comment]
@thomascenni Weird, it looks like you have some pageviews hitting your app while the migration was being ran. Can you run the following query against your postgresDB and give me the result?  That should tell the entire picture of what was run or not.

`select * from public._prisma_migrations`

**Comment by thomascenni** [comment]
Sure:

![image](https://user-images.githubusercontent.com/33039107/188721839-17660270-9b89-41c1-acf4-cab807e64216.png)

[Query_Results.csv](https://github.com/umami-software/umami/files/9500143/Query_Results.csv)

**Comment by briancao** [comment]
Looks like it ran, and your system should be in a good place right now.  I'm guessing the API hits ruined the log from fully printing out, I'm not sure.

**Comment by fireinrain** [comment]
I meet the same error.
env： docker umami mysql image latest,db is mysql 8.0.31
here is the full log:

$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database tables found.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "umami" at "umami-db:3306"
4 migrations found in prisma/migrations
Following migrations have not yet been applied:
03_remove_cascade_delete
04_add_uuid
To apply migrations in development run yarn prisma migrate dev.
To apply migrations in production run yarn prisma migrate deploy.
Running update...

Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `02_add_event_data` migration started at 2023-02-02 05:26:12.505 UTC failed
✗ Command failed: prisma migrate deploy

Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `02_add_event_data` migration started at 2023-02-02 05:26:12.505 UTC failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "check-db" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19


I dont know why this error happend
