### ISSUE TITLE
issues updating from 1.37 to 1.38

### ISSUE THREAD

**Issue by wheeleran** [umami-software/umami#1503]
hi. running umami in docker, docker-compose. after the horrors of updating to 1.37, now this: all migrations successfully applied, but then "ERROR:  duplicate key value violates unique constraint "session_session_uuid_key"" followed by a "validation error `Mutation.createOnepageview.data.pageviewCreateInput.website`"

any advice appreciated.

**Comment by briancao** [comment]
It looks like it's trying to insert the same session_uuid into the session table.  This can happen if a user is generating traffic on your sites too fast, causing race conditions during session data creation.  

If your site continues to be operational and is gathering data as expected, this error can be ignored.

**Comment by wheeleran** [comment]
I'll monitor it over the next day or two, thank you.
