### ISSUE TITLE
Abort fetching component for route: "/"

### ISSUE THREAD

**Issue by SeTube** [umami-software/umami#1504]
![](https://camo.githubusercontent.com/f17ec7f1d8e61e4f21a3da78bef9ebc9b9cf650e9469aeaef1fe009189ad16ed/68747470733a2f2f64642d7374617469632e6a642e636f6d2f6464696d672f6a66732f74312f33363130332f382f31373730312f33303330312f36333161303633374563376662613837312f306230326238313662343131656437632e706e67)

**Comment by briancao** [comment]
Need more details on this.  How are you running the application to generate this error, etc.
