### ISSUE TITLE
1.37 to 1.38 database migration fails on older versions of MySQL

### ISSUE THREAD

**Issue by tbkblues** [umami-software/umami#1506]
The problem is that a temporary sproc called CreateProcedureRenameIndex uses an index rename command only supported by later versions of MySQL. I had to manually edit db/mysql/migrations/02_add_event_data/migration.sql and add these statements:
drop index username on account;
drop index session_uuid on session;
drop index share_id on website;
drop index website_uuid on website;
create index `account_username_key` on `account` (username);
create index `session_session_uuid_key` on `session` (session_uuid);
create index `website_share_id_key` on `website` (share_id);
create index `website_website_uuid_key` on `website` (website_uuid);

I had to re-run it several times while fixing up the database with each run/test. This migration took me several hours to finish. 
Please get rid of the INDEX RENAME statement.

**Comment by briancao** [comment]
What version of MySql are you on?  The index rename should work on MySql 5.7 onwards, and is critical to lining up our database/releases with the community. Older versions are out of LTS, 

I'll discuss adding version support to our documentation with the team.

**Comment by briancao** [comment]
Another user reported, it only works on 10.5.2 or higher. 

Related issue: https://github.com/umami-software/umami/issues/1426

We'll have to add version requirements for both MySql and Maria.
