### ISSUE TITLE
How to track events wordpress buttons

### ISSUE THREAD

**Issue by edwinosky** [umami-software/umami#1512]
I want to record every time they press the download button on my wordpress website

I have umami software running, where I keep track of my traffic, I would like to add events every time someone presses the download button

In order for that event to be registered, I need to add the class "umami--click--download-button" to each button.

I have already tried in many ways but nothing seems to work the last thing I did was add the following script but it doesn't work either

I have more than 500 posts on my page, so I need to add the class globally
I was trying to use JQuery but it doesn't add the class to the button as expected

I have tried the following script
`<script>
    (function ($) {
        $('div.wp-block-button .wp-block-button__link').each(function () {
            const classToAdd = 'umami--click--download-button';
            const button = $(this);
            if (!button.hasClass(classToAdd)) {
                button.addClass(classToAdd);
            }
        });
    })(jQuery);
</script>`

My wordpress site shows the button as follows

`<div class="wp-block-button has-custom-font-size has-large-font-size">
<a class="wp-block-button__link has-white-color 
has-vivid-cyan-blue-to-vivid-purple-gradient-background 
has-text-color has-background wp-element-button" href="https://earnlink.click/" 
style="border-radius:10px" target="_blank"
rel="noreferrer noopener">DOWNLOAD</a></div>`

**Comment by edwinosky** [comment]
> h

your solution works correctly in my test environment, but on my website, which is where I am interested, I get an error, I will try to investigate it on my own since it must be a problem with the website, I thank you very much for your response, below I leave a sample of the error in case you have any idea

![image](https://user-images.githubusercontent.com/26192834/189744317-8af7ceb3-525f-4c2d-ab90-dfb4332e9221.png)

![image](https://user-images.githubusercontent.com/26192834/189744700-ce5396a4-682d-4e15-ac03-6ade517073b5.png)

**Comment by khromov** [comment]
@edwinosky When `querySelector` returns `null` it means [there were no matches](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector#return_value). Considering you are using WP + Gutenberg there are probably some content differences between your dev and prod site. Either copy the content from dev to prod or try to find an appropriate selector on your production site.

**Comment by edwinosky** [comment]
@khromov  my development site uses wordpress + grutember
instead my production site uses wordpres +elementor, maybe that's the problem

**Comment by edwinosky** [comment]
ok then i will close the problem because it no longer depends on umami but on my wordpress configuration, although i managed to register the clicks of the download button using jquery and then calling that file from functions.php
I really appreciate your help and your valuable time.
![image](https://user-images.githubusercontent.com/26192834/190002602-0376e791-9e6e-41ee-a2e3-991b86dc83d9.png)
