### ISSUE TITLE
Measure site performance with PerformanceNavigationTiming

### ISSUE THREAD

**Issue by khromov** [umami-software/umami#1513]
👋 It would be amazing if we could use the [PerformanceNavigationTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming) to get a chart of the sites performance. For example we can capture the time it takes for the DOM to become interactive and for the load event to fire, giving users a great view of their sites performance. PerformanceNavigationTiming is supported across all browsers.

**Comment by mikecao** [comment]
Yes, we are planning to implement performance metrics in the future.

**Comment by khromov** [comment]
@mikecao Thank you for the response. Is there a roadmap or other way of tracking this?
