### ISSUE TITLE
Unable to identify country/region

### ISSUE THREAD

**Issue by Lovelumine** [umami-software/umami#1520]
<img width="852" alt="image" src="https://user-images.githubusercontent.com/105962147/190065309-76afffdb-a6ab-4544-8118-cb65c859b219.png">

**Comment by briancao** [comment]
I assume that says 'Unknown'.  This might be of some help.

https://github.com/umami-software/umami/issues/1483#issuecomment-1236410918

**Comment by Lovelumine** [comment]
`CLIENT_IP_HEADER = <header name>`
Is this it? What should I fill in for<header name>

**Comment by Lovelumine** [comment]
Is it because my website has a port number at the back?

**Comment by mikecao** [comment]
The port should not matter. The country is determined by the IP address. But if you are behind a CDN or something that hides the IP, we can't figure out the country.

**Comment by Stargate-project** [comment]
why does it not show the state? only shows the country
