### ISSUE TITLE
How to restructure events?

### ISSUE THREAD

**Issue by jfbeats** [umami-software/umami#1521]
Examples don't seem to make sense. The one provided with the breaking changes is:
```js
umami.trackEvent('button-click', { userId: 123, buttonName: 'Newsletter signup' });
```
Doing it this way on the current version only let you know the number of 'button-click' events, and not that it's about the newsletter. 

I have no idea if/when/how the new `event_data` implementation will even work or be displayed in the interface, which doesn't help, but do I really have to go in blind and wait until an old feature is re-implemented? 😕

**Comment by mikecao** [comment]
That example is probably too generic, you're right. You wouldn't group all `button-click`'s together like that, but instead use different names, `login-button-click` or `signup-button-click`.

**Comment by danestves** [comment]
I just wanted to know this too because I don't know if `event_data` is even showed or something

**Comment by mikecao** [comment]
@danestves not currently, but will be in the next release

**Comment by jfbeats** [comment]
I would truly appreciate if you could confirm the following scenarios so that I don't have to rework it again in the future:

Example 1, collecting events from users going through affiliate links. I'd like to see the total number of outbound traffic for all affiliates but I'm mostly interested in being able to see which ones are the most popular. The affiliate name or link would be added to the `event_data`?

Example 2, collecting events from user interactions with an unlimited number of uniquely identified elements. I'd like to see the total number of those specific interactions, but also which IDs are the most interacted with. The ID here would be included in `event_data`?

Thank you 🙏

**Comment by mikecao** [comment]
@jfbeats The `event_data` is whatever you make of it. You collect the information that is important to you. So if a user clicks the **Add to Cart** button, you can record the product ID as `{ product_id: 153464 }`. Then you should be able to query to get a breakdown like:

| product_id | count |
|--|--|
|153464 | 20 |
| 128760 | 12 |
| 546354 | 8 |
