### ISSUE TITLE
location data not accurate enough

### ISSUE THREAD

**Issue by Stargate-project** [umami-software/umami#1522]
please use more accurate geo ip location /city/state/country

https://dev.maxmind.com/geoip/geolite2-free-geolocation-data?lang=en

**Comment by mikecao** [comment]
We plan to support it. Need to test a few things first.

**Comment by TdhPerso14** [comment]
Hello,

Have you been able to make progress on localization since September?
Thanks

**Comment by mikecao** [comment]
It is on the roadmap, but no time estimate at this time.

**Comment by TdhPerso14** [comment]
> It is on the roadmap, but no time estimate at this time.

Hello MikeCao
Thank you very much for your answer, I have other suggestions but the one concerning the localization is really very important. It's annoying not to have more visibility on the posting of this feature.
Thank you in advance for your work and we look forward to this development. Do you know if it seems possible to have it soon?

**Comment by viharm** [comment]
I noticed that this appears to be in the code https://github.com/umami-software/umami/blob/c7275ef85b124ed88126877487ff1c9fddaf068e/scripts/build-geo.js#L19
Is it released?
