### ISSUE TITLE
Failed Netlify + Supabase

### ISSUE THREAD

**Issue by azat-io** [umami-software/umami#1525]
Steps to reproduce:

1. Open Supabase
2. Create database
3. Open `Settings` / `Database` / `Connection Pooling`
4. Copy `Connection string`, replace `[YOUR-PASSWORD]` with password, add `?pgbouncer=true` to string
5. Open `SQL editor`, paste code from [here](https://github.com/umami-software/umami/blob/master/sql/schema.postgresql.sql) and click RUN

7. Open Netlify
8. Connect forked repo with project
9. Open `Site settings` / `Build & deploy` / `Enviorenment`
10. Add variables `HASH_SALT` with random string and `DATABASE_URL` with our updated connection string
11. Open `Deploys`, click `Trigger deploy`

After these steps I get the following error:

```
9:12:48 PM: Error: P3018
9:12:48 PM: 
9:12:48 PM: A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
9:12:48 PM: 
9:12:48 PM: Migration name: 02_add_event_data
9:12:48 PM: 
9:12:48 PM: Database error code: 42501
9:12:48 PM: 
9:12:48 PM: Database error:
9:12:48 PM: ERROR: must be owner of table event
9:12:48 PM: 
9:12:48 PM: DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42501), message: "must be owner of table event", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("aclchk.c"), line: Some(3583), routine: Some("aclcheck_error") }
9:12:48 PM: 
9:12:48 PM: ✗ Command failed: prisma migrate deploy
9:12:48 PM: Error: P3018
9:12:48 PM: 
9:12:48 PM: A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
9:12:48 PM: 
9:12:48 PM: Migration name: 02_add_event_data
9:12:48 PM: 
9:12:48 PM: Database error code: 42501
9:12:48 PM: 
9:12:48 PM: Database error:
9:12:48 PM: ERROR: must be owner of table event
9:12:48 PM: 
9:12:48 PM: DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42501), message: "must be owner of table event", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("aclchk.c"), line: Some(3583), routine: Some("aclcheck_error") }
9:12:48 PM: 
9:12:48 PM: 
9:12:48 PM: 
9:12:48 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
9:12:48 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
9:12:48 PM: ERROR: "check-db" exited with 1.
9:12:48 PM: error Command failed with exit code 1. (https://ntl.fyi/exit-code-1)
9:12:48 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by duboiss** [comment]
Seems to be on your database configuration side.
I use Netlify with a postgresql database on heroku, I have no errors (just deployed few minutes ago with the latest version of unami).

Ok you got this error. But what did you try to do to fix it?

**Comment by azat-io** [comment]
It seems that I do everything according to the documentation

**Comment by duboiss** [comment]
Don't understand why you follow Supabase documentation if you want to use Netlify ?
I just follow netlify documentation (without useless HASH_SALT environment variable) using the postgres connection string (without `pgbouncer=true` option) and it works well.

**Comment by azat-io** [comment]
@duboiss Looks like everything works without `pgbouncer=true`. Thanks! But sometimes on various requests I get an "Internal server error"

**Comment by duboiss** [comment]
By various requests you mean when you navigate on the website one deployed on Netlify you have some errors ? Which page in particular ?

**Comment by azat-io** [comment]
<img width="561" alt="Screenshot 2022-09-17 at 4 22 52 PM" src="https://user-images.githubusercontent.com/5698350/190859203-1d164705-25d4-4233-9d00-0c2384bb3bb8.png">

@duboiss On all pages there are different requests break. It's just that everything is unstable. After refreshing the page, they may start working, or others may break.

**Comment by briancao** [comment]
It looks like anytime the event table is hit, you're getting errors which makes me believe your 01 migration ran ok, but your 02 did not.  Did you run any special commands to re-run your migrations after getting errors?

**Comment by azat-io** [comment]
@briancao 
> Did you run any special commands to re-run your migrations after getting errors?

No

**Comment by briancao** [comment]
It looks like there's an issue w/ supabase not assigning table edit permissions to the login.

https://github.com/supabase/supabase/discussions/4825

You'll have to run some kind of permission update, where postgres is the user login.

```GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;```

**Comment by azat-io** [comment]
@briancao I used the [script](https://supabase.com/docs/guides/integrations/prisma#troubleshooting) but nothing changed. The problem persists. If I use `pgbouncer=true` I get the same error in deployment. If I use clean url for DB I get 500 error

**Comment by briancao** [comment]
Can you re-post the error you're getting?  Migrations shouldn't run alters if the previous migration failed w/o --rollbacks or --applied.

**Comment by ijkml** [comment]
Just tried deploying and I'm getting the same error. :)

**Comment by rohandebsarkar** [comment]
Try following https://github.com/umami-software/umami/discussions/1486#discussioncomment-3567397.

**Comment by azat-io** [comment]
@rohandebsarkar It works! Thank you!
