### ISSUE TITLE
Logseq SPA can't work in umami

### ISSUE THREAD

**Issue by rebron1900** [umami-software/umami#1528]
my logseq link : https://garden.1900.live/
Page views can not be counted，see the attach.↓

![image](https://user-images.githubusercontent.com/7929884/190948753-288f28fa-c987-456f-8009-2dbebd912c7e.png)

**Comment by briancao** [comment]
I'm seeing 22 views, with 1 unique visitor.  What is the issue here?

**Comment by rebron1900** [comment]
It can't record Page Path

**Comment by mikecao** [comment]
What does your URL look like?

**Comment by rebron1900** [comment]
> What does your URL look like?

like this `https://garden.1900.live/#/page/%E5%B7%A5%E5%85%B7%E7%9B%B8%E5%85%B3`

**Comment by rebron1900** [comment]
But when I visited umami site on my phone, I could see it, and this is what it looked like:

![8214e21a27b95dab2cabf5786cff8ac1](https://user-images.githubusercontent.com/7929884/192125076-6f83bc10-06e6-46f3-a309-8b62c2101c47.jpg)

**Comment by rebron1900** [comment]
我因为在页面嵌入了评论系统，为了保证评论系统能和它同步，我写了下面这段代码，会是这个的问题吗？

---

Because I embedded the comment system on the page, in order to ensure that the comment system can be synchronized with it, I wrote the following code, is this the problem?

---

```html
<script>
    history.pushState = (f => function pushState() {
        var ret = f.apply(this, arguments);
        window.dispatchEvent(new Event('pushstate'));
        window.dispatchEvent(new Event('locationchange'));
        return ret;
    })(history.pushState);
    history.replaceState = (f => function replaceState() {
        var ret = f.apply(this, arguments);
        window.dispatchEvent(new Event('replacestate'));
        window.dispatchEvent(new Event('locationchange'));
        return ret;
    })(history.replaceState);
    window.addEventListener('popstate', () => {
        window.dispatchEvent(new Event('locationchange'))
    });
    window.addEventListener('locationchange', function() {
        const iframe = document.querySelector('iframe.giscus-frame');
        const title = decodeURIComponent(location.hash.split('/').slice(-1)[0]);
        console.debug("location change to:", title, iframe);
        if (!iframe || !title) return;
        iframe.contentWindow.postMessage({
            giscus: {
                setConfig: {
                    term: title
                }
            }
        }, 'https://giscus.app');
        console.debug("try refresh giscus:", title);
    }, false);
</script>
```

**Comment by rebron1900** [comment]
>mike — 今天11:40
It is probably because anything with # is not a real URL. You can disable automatic collection and send the URL yourself. https://umami.is/docs/tracker-functions

thks @mike ,He reminded me on discord ，`#` the link that begins with the symbol will not be logged.
So I disabled automatic logging and manually removed the `#` symbol on `location.hash` and created the record
Now that umami is working well, I think the problem is over
