### ISSUE TITLE
yarn build - out of mermory

### ISSUE THREAD

**Issue by foxytocin** [umami-software/umami#1539]
Since version 1.38.0 i'am unable to build an optimized productions build on the shares hoster https://uberspace.de/. Each user has a limit of 1.5 GB of RAM. Versions before 1.38.0 could be build by using and running the command multiple times:

- NODE_OPTIONS=--max_old_space_size=512 npm run build --debug
or
- NODE_OPTIONS=--max_old_space_size=512 npm run build-app --debug

Now i'am unable to generate a build. Using next dev is working as aspected.
Is there a way, to reduce the memory consumption to make umami available again to such kind of hosters?

**Comment by mikecao** [comment]
The build is out of our control since it is done by Next.js. If you are simply running the frontend, why not go with a free service like Vercel or Netlify?

**Comment by foxytocin** [comment]
Because of the DSGVO (GDPR) here in Germany. It's mandatory to host the service on a Server in Germany having a data processing agreement with the provider.

**Comment by mikecao** [comment]
The data is still in your database, I'm assuming hosted in Germany. These services only host the frontend.

**Comment by rohandebsarkar** [comment]
In Vercel, you can also choose where to host your Serverless Functions (API endpoints): https://vercel.com/docs/concepts/functions/serverless-functions/regions#configuring-the-region. If you select it to be Germany (Frankfurt), and assuming your database is already in Germany, you can host Umami as a whole including the database all within Germany.

**Comment by foxytocin** [comment]
Unfortunately, it is not only important where the data is located, but also whether it is transmitted to a third country or can be accessed. Vercel itself states that it collects indirect data. If German IP addresses are recorded during access (which can be assumed) because otherwise no communication with servers is possible, this is already a violation of the GDPR. In Germany, for example, there is already a ruling that prohibits the dynamic integration of google fonts into websites, since the ip is then transmitted to google. In Germany, the IP address is one of the personality traits.

Since versions before 1.38.0 worked, something seems to have changed in the build process or new dependencies are used. All I found out is that webpack has tweak options to control the build process. Unfortunately, my attempts have not led to success. Unfortunately, building on the pc and transferring to the server does not work either, since CORS errors then occur.

It would be really great if building with little RAM was taken into account in further development.

**Comment by aidanm1999** [comment]
Hi @foxytocin, could give [Digital Ocean](https://digitalocean.com/) a go? They have servers in Frankfurt.

**Comment by pxlfrk** [comment]
Hi all,
run in the same error as mentioned above (also on Uberspace shared hosting). Also tried different `max_old_space_size=512` settings but nothing worked yet.

Any tips/tricks for this?

**Comment by amxmln** [comment]
@pxlfrk I was able to circumvent this issue by building the frontend on my local machine and then copying the `/.next` directory to the server (all the other build steps work fine on the server). Unfortunately this no longer works as of v1.39.4 due to the following error:

```
Error: Invariant: invalid matchers for middleware {"env":["COLLECT_API_ENDPOINT","TRACKER_SCRIPT_NAME"],"files":["server/edge-runtime-webpack.js","server/middleware.js"],"name":"middleware","page":"/","regexp":"^(?:\\/(_next\\/data\\/[^/]{1,}))?(?:\\/((?:[^\\/#\\?]+?)(?:\\/(?:[^\\/#\\?]+?))*))?(.json)?[\\/#\\?]?$","wasm":[],"assets":[]}
```

Don’t know why that happens. :shrug:

**Comment by pxlfrk** [comment]
@amxmln thanks for the hint! With your tip, i was able to build the frontend local and skip this step on the vm succesfully.
just used `yarn build-app` local and on the server `/node_module/.bin/npm-run-all build-db check-db build-tracker build-geo`.

But still, the question is why the umami build process - especially for the frontend - keeps using that much ram in the newer versions.

**Comment by spackmat** [comment]
Thanks @amxmln that worked for me!

> But still, the question is why the umami build process - especially for the frontend - keeps using that much ram in the newer versions.

As a slightly too aged dev (not from the JS-ecosystem) I would say: Because nearly no one in the JS world cares about their code wasting resources as long as people just throw in more resources to solve their problems. The answers on this issue are no exception: 🤷 get another hosting.

**Comment by boehs** [comment]
![image](https://user-images.githubusercontent.com/51836263/219379724-168a524a-aeb4-4318-bcb7-30cf4894c576.png)

with enough pain, it does build on uberspace 😁

**Comment by spackmat** [comment]
1. Choose Umami to have a feature-small analytics tool on hand with a small resource-footprint.
2. Find out that it is the first ever web-app where the 1.5G server-side RAM on uberspace (or any other small virtual server package) isn't enough.
3. Hassle around a while, give up and finally build on your local machine.
4. Find out that it is a really really feature-small analytics tool, where the site profiles can only be viewed by their owning user account and there is only one admin account and even that cannot see the analytics of other accounts.
5. Throw it all away and install Matomo again.

Btw. if anyone is wondering why so many uberspace users end up here: They have a very comfy way to host non-PHP web-apps on their shared hosting with dead simple and well documented reverse proxy and daemon stuff. In fact hosting non-PHP stuff ist nearly as simple as hosting PHP stuff.

**Comment by mikecao** [comment]
@spackmat The admin can see all analytics in the system. Go to settings -> accounts and open their dashboard. In the next version there will be a teams feature where you can share access to websites.

**Comment by amxmln** [comment]
FYI to anyone who might still be running into this, as mentioned in the [thread](https://github.com/Uberspace/lab/issues/1882) in the Uberspace Lab docs, I’ve had success building with the following options added to next.config.js:

```js
{
  experimental: {
    cpus: 1,
    workerThreads: false,
  }
}
```
