### ISSUE TITLE
Error 500 when trying to log in

### ISSUE THREAD

**Issue by alv** [umami-software/umami#1545]
I am getting an error 500 on DevTools Console when trying to log in to Umami, which I hosted on Netlify. Database is on Supabase and right now the admin credentials are the default ones:

[https://stats.alvaro.design/login](https://stats.alvaro.design/login)

`POST https://stats.alvaro.design/api/auth/login 500`

It's working fine on localhost: I can log in, create new users, change passwords, add new sites... but somehow not on the deployed site.

Happy to provide any more info! The tool looks amazing and I feel I am very close to getting it installed correctly but I don't know what else to try :(

Thanks!

**Comment by phanendraguptha** [comment]
I am facing the same issue @alv, what was the workaround?

**Comment by alv** [comment]
@phanendraguptha I edited this file /pages/api/collect.js

I replaced "unauthorized" with "ok" (appears in two places). After that it was working fine.

Can't seem to find the GitHub issue I got that fix from. Hope it helps :)

**Comment by phanendraguptha** [comment]
@alv I don't see any "unauthorized" in the path you've mentioned

https://github.com/phanendraguptha/umami/blob/master/pages/api/collect.js

**Comment by alv** [comment]
@phanendraguptha your collect.js is exactly like mine now, so it's not that then. 

You have umami 1.39.5, I have 1.39.4, in case a downgrade would help.

Netlify environment variables:

1) DATABASE_URL

Starts with postgres://postgres:, taken from Supabase

2) HASH_SALT

A word I made up

3) IGNORE_IP

This was optional, was trying to force umami to ignore my IP

Hope you find a solution, let me know if I can provide any more info that would help.

**Comment by phanendraguptha** [comment]
@alv I have added the `DATABASE_URL` and `HASH_SALT` as well.
I just forked the repository, can you please tell me how to downgrade a version?

**Comment by alv** [comment]
@phanendraguptha you could download the code for that previous version:

https://github.com/umami-software/umami/releases/tag/v1.39.4

And replace the files in your repo with those.

However, do so at your own risk, I am no expert in this and don't know if that would break things more.
