### ISSUE TITLE
Cannot do npm run build with PlanetScale

### ISSUE THREAD

**Issue by leonhfr** [umami-software/umami#1549]
Hi!

I'm following the [guide](https://umami.is/docs/running-on-planetscale) to deploy to `PlanetScale`. In `schema.mysql.sql` I deleted the 6 alter table commands with the foreign keys. The tables created successfully on PlanetScale, but when running `npm run build` I get an error:

```
✗ Command failed: prisma migrate deploy
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 02_add_event_data

Database error code: 1091

Database error:
target: umami-db.-.primary: vttablet: rpc error: code = FailedPrecondition desc = Can't DROP 'event_ibfk_1'; check that column/key exists (errno 1091) (sqlstate 42000) (CallerID: planetscale-admin): Sql: "alter table `event` drop foreign key event_ibfk_1", BindVars: {}

Please check the query number 1 from the migration file.



ERROR: "check-db" exited with 1.
```

Not sure how to fix it or if the guide is up to date?

**Comment by briancao** [comment]
You'll have to alter/remove foreign key references to in the migration scripts as well.

I'll be preparing a  planet-scale specific script by early next week if you'd like to wait for that.

**Comment by leonhfr** [comment]
Hi, thanks for your answer.

I retried with a freshly created database and remove all references to foreign keys in the migration scripts, and have a similar error:

```
Migration name: 02_add_event_data

Database error code: 1105

Database error:
syntax error at position 47 near 'PROCEDURE'

Please check the query number 10 from the migration file.
```

I think I might wait for your script :)
