### ISSUE TITLE
401 (Unauthorized) error during lighthouse report

### ISSUE THREAD

**Issue by switowski** [umami-software/umami#1555]
Hi,

I have successfully set up an umami instance (thanks for creating this awesome tool!) and everything works fine, but when I try to run the Lighthouse report on my website, umami records an error to the console:

Source | Description
-- | --
/api/collect:1:0(switowski-umami.netlify.app) | Failed to load resource: the server responded with a status of 401 (Unauthorized)

See screenshot:
![Lighthouse_Report_Viewer](https://user-images.githubusercontent.com/4835412/194722774-2e569b38-39be-4ad9-9855-eb04c452e745.jpg)

I did a bit of digging in the code and I see that initially there was a feature added to check for bots (commit: [943c2c73d](https://github.com/umami-software/umami/commit/943c2c73d476eeac475135e931540b79d2ee3ee4)) that was returning status OK, but later it was changed to unauthorized in commit [bb507537046e](https://github.com/umami-software/umami/commit/bb507537046e49b60d63b8975c39064e75187b92). There is no explanation on why it was turned into unauthorized.

Any recommendations how to deal with this problem? If the return code can't be reverted back to OK, maybe this error can be somehow caught inside the tracker code snippet, so it doesn't leak out to the console (sorry, I'm not experienced enough with JS to fix that myself)?

I tried to find other users of umami that were facing the same lighthouse problem, but to no avail (which surprises me - really no one cares?) It's not a big deal, but it's the only problem that's preventing me from reaching the 4x100 lighthouse score, which bothers me a bit. So I'm trying to find the easiest solution.

**Comment by t3brightside** [comment]
Having the same issue.

**Comment by kwiat1990** [comment]
Same for me.

**Comment by mikecao** [comment]
We can change it back to 200.

**Comment by Visoar** [comment]
Same issue here.

**Comment by alv** [comment]
Same here

**Comment by liberatingsayan** [comment]
Same issue for me.

**Comment by sn0n** [comment]
also having this issue. unsure if a cloudflare issue or not though. i did change a few things around the same time.
