### ISSUE TITLE
json file lost when deploy with standalone mode

### ISSUE THREAD

**Issue by SeesawLiu** [umami-software/umami#1556]
if build umami with nextjs standalone mode,all json file will return 404,include realtime.json,settings.json.and worldmap json file

**Comment by briancao** [comment]
Can you show your build-logs for this?

**Comment by SeesawLiu** [comment]
info  - Collecting page data  
info  - Generating static pages (12/12)
info  - Finalizing page optimization

Route (pages)                              Size     First Load JS
┌ ○ /                                      296 B           255 kB
├   /_app                                  0 B             254 kB
├ ○ /404                                   369 B           308 kB
├   └ css/ce16c43b6179ab29.css             1.98 kB
├ λ /api/account                           0 B             254 kB
├ λ /api/account/[id]                      0 B             254 kB
├ λ /api/account/password                  0 B             254 kB
├ λ /api/accounts                          0 B             254 kB
├ λ /api/auth/login                        0 B             254 kB
├ λ /api/auth/verify                       0 B             254 kB
├ λ /api/cache/reset                       0 B             254 kB
├ λ /api/collect                           0 B             254 kB
├ λ /api/config                            0 B             254 kB
├ λ /api/heartbeat                         0 B             254 kB
├ λ /api/realtime/init                     0 B             254 kB
├ λ /api/realtime/update                   0 B             254 kB
├ λ /api/scripts/telemetry                 0 B             254 kB
├ λ /api/share/[id]                        0 B             254 kB
├ λ /api/website                           0 B             254 kB
├ λ /api/website/[id]                      0 B             254 kB
├ λ /api/website/[id]/active               0 B             254 kB
├ λ /api/website/[id]/events               0 B             254 kB
├ λ /api/website/[id]/metrics              0 B             254 kB
├ λ /api/website/[id]/pageviews            0 B             254 kB
├ λ /api/website/[id]/pattern              0 B             254 kB
├ λ /api/website/[id]/reset                0 B             254 kB
├ λ /api/website/[id]/stats                0 B             254 kB
├ λ /api/websites                          0 B             254 kB
├ λ /console/[[...id]]                     4.25 kB         445 kB
├   └ css/16ab3d8868c91834.css             4.42 kB
├ ○ /dashboard/[[...id]]                   36.8 kB         478 kB
├   └ css/be94dab138cf6385.css             4.62 kB
├ λ /login                                 1.55 kB         320 kB
├   └ css/e549ee379a621660.css             2.39 kB
├ ○ /logout                                336 B           255 kB
├ ○ /realtime                              7.22 kB         471 kB
├   └ css/63071d6b18fa70b9.css             3.66 kB
├ ○ /settings                              225 B           425 kB
├ ○ /settings/accounts                     265 B           425 kB
├ ○ /settings/cache                        263 B           425 kB
├ ○ /settings/profile                      264 B           425 kB
├ ○ /share/[...id]                         650 B           495 kB
└ ○ /website/[...id]                       756 B           495 kB
+ First Load JS shared by all              264 kB
  ├ chunks/framework-5f4595e5518b5600.js   42 kB
  ├ chunks/main-bbe58558011449f9.js        34.7 kB
  ├ chunks/pages/_app-3d791f500327ceb2.js  177 kB
  ├ chunks/webpack-0596ac5c5444ecae.js     891 B
  └ css/a08252ae0c9a1095.css               9.4 kB

ƒ Middleware                               20 kB

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)

**Comment by SeesawLiu** [comment]
now all website.json request response html 😭
