### ISSUE TITLE
click events redirecting to /null

### ISSUE THREAD

**Issue by christopherpickering** [umami-software/umami#1569]
Hi!

I have a click event on a shopping cart button like
```html
<button class="button h-100 is-white navbar-item snipcart-checkout umami--click--nav-cart" type="button">
            <span class="icon cart px-5">
                <i class="fas fa-cart-shopping fa-lg has-text-grey-dark"></i>
                <span class="snipcart-items-count tag is-info is-rounded">0</span>
            </span>
      </button>
```
The button is just used for a javascript event to open the shopping cart modal. I have also changed the button to a <div> and have the same result.

Somehow whenever I click the button/div, the website is redirecting to `/null` url.

I'm thinking it is from this line (146) -

![image](https://user-images.githubusercontent.com/17788706/195780306-627c53cb-e4fb-4296-b995-3cb766e9cc3b.png)

Maybe it can be changed so that if there is no href on the element being clicked, the window.location is not set?

**Comment by mikecao** [comment]
Yes, we can guard around that. But in general anchor elements should have an href. If you want something clickable you can just use a div.

**Comment by christopherpickering** [comment]
Cool thanks! I supposed it would be more common on buttons than a div :)

**Comment by christopherpickering** [comment]
Thanks @mikecao !
