### ISSUE TITLE
Please update the image on Docker Hub

### ISSUE THREAD

**Issue by aaro-n** [umami-software/umami#1578]
The image on[ Docker Hub](https://hub.docker.com/r/umamisoftware/umami) is using version 1.37, please update.
Why?
I want to deploy umami to fly.io, only Docker Hub image can be deployed, `docker.umami.is/umami-software/umami:mysql-latest`cannot be deployed

**Comment by s-thom** [comment]
`docker.umami.is` is really just GitHub's container registry, and I don't know why this project has decided to have their own domain. My guess would be tracking image pulls, but that seems odd given that GitHub also has stats for image pulls.

```sh
$ curl -v https://docker.umami.is
[...]
< Location: https://ghcr.io/
[...]
```

I've been using the [ghcr.io image names](https://github.com/umami-software/umami/pkgs/container/umami) on Fly with no issues so far. If this works for you as well, then I suspect the CNAME is causing issues for Fly. In your case that would be `ghcr.io/umami-software/umami:mysql-latest`

**Comment by aaro-n** [comment]
This problem can be closed. I used GitHub Actions to automatically deploy before. At that time, I found that there would be a problem with `ghcr.io/umami-software/umami:postgresql-latest` image deployment. You must use the image on Docker Hub or use the command `fly deploy --local -only deploy`.
Just tried it, `ghcr.io/umami-software/umami:postgresql-latest` can be deployed automatically.
