### ISSUE TITLE
A new umami project not work to the 1.39.1

### ISSUE THREAD

**Issue by humorwang** [umami-software/umami#1588]
in **docker.umami.is/umami-software/umami:mysql-latest**   test case.

docker-compose logs -f  not error, the logs 

wy@my-oio ~\Desktop\umami\app ❯❯❯ docker-compose logs -f
app-umami-1  | yarn run v1.22.19
app-umami-1  | $ npm-run-all check-db update-tracker start-server
app-umami-1  | $ node scripts/check-db.js
app-umami-1  | ✓ DATABASE_URL is defined.
app-umami-1  | ✓ Database connection successful.
app-umami-1  | ✓ Database tables found.
app-umami-1  | Prisma schema loaded from prisma/schema.prisma
app-umami-1  | Datasource "db": MySQL database "uuuuu" at "xx.xxx.xx.xxx:3306"
app-umami-1  |
app-umami-1  | 4 migrations found in prisma/migrations
app-umami-1  |
app-umami-1  |
app-umami-1  | Database schema is up to date!
app-umami-1  |
app-umami-1  | ✓ Database is up to date.
app-umami-1  | $ node scripts/update-tracker.js
app-umami-1  | $ node server.js
app-umami-1  | Listening on port 3000

every one page   “api/collect” API is 404 

this login error page

![login](https://user-images.githubusercontent.com/19926102/197716476-c0c22c61-a2d5-4b46-994a-a9739a289431.png)

**Comment by humorwang** [comment]
my docker-compose.yml 

`
version: '3'
services:
  umami:
    image: docker.umami.is/umami-software/umami:mysql-latest
    ports:
      - "3001:3000"
    environment:
      DATABASE_URL: mysql://root:ziyuzile@xx.xxx.xx.xxx:3306/uuuuu
      DATABASE_TYPE: mysql
      HASH_SALT: xxxx
      TRACKER_SCRIPT_NAME: a
      COLLECT_API_ENDPOINT: /api/c

`

**Comment by humorwang** [comment]
i found TRACKER_SCRIPT_NAME can't set a .i change TRACKER_SCRIPT_NAME  to  **abc**，everything is ok

**Comment by briancao** [comment]
Assuming this is self-resolved, closing.

We resolved some login errors in 1.39.2.
