### ISSUE TITLE
Accessing others users dashboards doesn't work after upgrade

### ISSUE THREAD

**Issue by nemunaire** [umami-software/umami#1590]
Hi!

I just update from 1.37.0 to 1.39.1.

When I go to the `/settings/accounts` page, all the links to dashboards point to `undefined` instead of the user id.
Eg. : `/dashboard/undefined/admin`.

Here is what I get from `/api/accounts`:

```
[
  {"id":1,"username":"admin","isAdmin":true,"createdAt":"2021-06-09T23:28:04.245Z","updatedAt":"2021-06-09T23:28:04.245Z"},
  {"id":3,"username":"xxxxx","isAdmin":false,"createdAt":"2021-10-19T01:06:03.873Z","updatedAt":"2021-10-19T01:06:03.873Z"}
]
```

Both links contains `undefined` instead of the user ID. Links looked like `/dashboard/1/admin` or `/dashboard/3/xxxxx` before the upgrade.

**Comment by sebiweise** [comment]
Same on my side. Also it isn´t possible to just put in the userid like it was before, the impersonate dashboard isn´t working completely.
