### ISSUE TITLE
Rearranging Dashboard not working on 1.39.1

### ISSUE THREAD

**Issue by GamerKingFaiz** [umami-software/umami#1597]
From the `/dashboard` view, click the cog in the top right corner, and click edit dashboard.

Here in 1.38 you were able to rearrange the order, but now it doesn't seem to work.
![chrome_rC2KOkvObm](https://user-images.githubusercontent.com/9065136/197858206-be7f6833-2c90-498d-b5c1-0605378bffa1.gif)

**Comment by danestves** [comment]
![CleanShot 2022-10-25 at 15 13 22](https://user-images.githubusercontent.com/31737273/197861623-d583c662-cd8c-4520-bdab-7b8162785ffa.png)

This is because the items has the same id, change that will fix the error @mikecao

**Comment by briancao** [comment]
Have this fixed. Will be releasing 1.39.2 tonight.

**Comment by mikecao** [comment]
Fixed in v1.39.2.
