### ISSUE TITLE
No analytics after updating

### ISSUE THREAD

**Issue by candideu** [umami-software/umami#1598]
![image](https://user-images.githubusercontent.com/55474996/197882547-f18e926e-fd53-4c40-aa41-f8129d3b3ab8.png)

I've recently upgraded to [v1.39.1](https://github.com/umami-software/umami/releases/tag/v1.39.1), and my stats no longer appear for any of my websites.

I'm using Supabase for my database, and Vercel to host the app.

**Comment by Lennart01** [comment]
Can confirm this issue. Also exists on the default install with docker-compose.

**Comment by Lennart01** [comment]
@candideu can you also post your error log?
mine is here:
`db_1     | 2022-10-25 21:57:17.810 UTC [33] ERROR:  column event.event_uuid does not exist at character 185
db_1     | 2022-10-25 21:57:17.810 UTC [33] HINT:  Perhaps you meant to reference the column "event.event_id".
db_1     | 2022-10-25 21:57:17.810 UTC [33] STATEMENT:  SELECT "public"."event"."event_id", "public"."event"."website_id", "public"."event"."session_id", "public"."event"."created_at", "public"."event"."url", "public"."event"."event_name", "public"."event"."event_uuid" FROM "public"."event" WHERE (("public"."event"."event_id") IN (SELECT "t0"."event_id" FROM "public"."event" AS "t0" INNER JOIN "public"."website" AS "j0" ON ("j0"."website_id") = ("t0"."website_id") WHERE ("j0"."website_uuid" IN ($1) AND "t0"."event_id" IS NOT NULL)) AND "public"."event"."created_at" >= $2) OFFSET $3
umami_1  | PrismaClientKnownRequestError: 
umami_1  | Invalid `prisma.event.findMany()` invocation:
umami_1  | 
umami_1  | 
umami_1  | The column `event.event_uuid` does not exist in the current database.
umami_1  |     at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/index.js:30873:13)
umami_1  |     at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:30856:12)
umami_1  |     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.js:31836:16)
umami_1  |     at async Promise.all (index 2)
umami_1  |     at async getRealtimeData (/app/.next/server/chunks/769.js:1787:43)
umami_1  |     at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/realtime/init.js:158:22)
umami_1  |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
umami_1  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
umami_1  |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
umami_1  |     at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36) {
umami_1  |   code: 'P2022',
umami_1  |   clientVersion: '4.5.0',
umami_1  |   meta: { column: 'event.event_uuid' }
umami_1  | }
umami_1  | TypeError: Cannot destructure property 'websiteId' of 'undefined' as it is undefined.
umami_1  |     at relationalQuery (/app/.next/server/chunks/769.js:1427:34)
umami_1  |     at Object.prisma (/app/.next/server/chunks/769.js:1423:69)
umami_1  |     at runQuery (/app/.next/server/chunks/2050.js:83:31)
umami_1  |     at savePageView (/app/.next/server/chunks/769.js:1422:70)
umami_1  |     at __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/collect.js:218:78)
umami_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
umami_1  |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
umami_1  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
umami_1  |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
umami_1  |     at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)`

**Comment by candideu** [comment]
@Lennart01 Sorry, I'm not the most tech-savvy. Where can I find my error log?

**Comment by Lennart01** [comment]
@candideu I don't know where vercel stores logs. Have you checked here?
https://vercel.com/guides/where-are-vercel-logs
But I guess it is probably the same issue

**Comment by mikecao** [comment]
Try logging out and back in. We made some auth changes so your old cookie may be out of date.

**Comment by Lennart01** [comment]
Results in me not being able to login anymore.
db_1     | 2022-10-26 05:43:35.287 UTC [33] ERROR:  column account.account_uuid does not exist
at character 197
db_1     | 2022-10-26 05:43:35.287 UTC [33] STATEMENT:  SELECT "public"."account"."user_id", "p
ublic"."account"."username", "public"."account"."password", "public"."account"."is_admin", "pub
lic"."account"."created_at", "public"."account"."updated_at", "public"."account"."account_uuid"
 FROM "public"."account" WHERE ("public"."account"."username" = $1 AND 1=1) LIMIT $2 OFFSET $3
umami_1  | PrismaClientKnownRequestError:
umami_1  | Invalid `prisma.account.findUnique()` invocation:
umami_1  |
umami_1  |
umami_1  | The column `account.account_uuid` does not exist in the current database.
umami_1  |     at RequestHandler.handleRequestError (/app/node_modules/@prisma/client/runtime/i
ndex.js:30873:13)
umami_1  |     at RequestHandler.request (/app/node_modules/@prisma/client/runtime/index.js:308
56:12)
umami_1  |     at async PrismaClient._request (/app/node_modules/@prisma/client/runtime/index.j
s:31836:16)
umami_1  |     at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/auth/login.js:7
9:21)
umami_1  |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.j
s:366:9)
umami_1  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.j
s:481:9)
umami_1  |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:735:37)
umami_1  |     at async Router.execute (/app/node_modules/next/dist/server/router.js:247:36)
umami_1  |     at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:3
47:29)
umami_1  |     at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-s
erver.js:285:20) {
umami_1  |   code: 'P2022',
umami_1  |   clientVersion: '4.5.0',
umami_1  |   meta: { column: 'account.account_uuid' }
umami_1  | }

**Comment by giuliomagnifico** [comment]
I updated from 1.38 to 1.39.1 yesterday -but it was mess- so I went back to .38 and now to .39.2 and I had the same "blank page" issue, logout and login again fixed it, also I noticed the url changed of my bookmarked websites.

**Comment by dlford** [comment]
I also can't log in on anything newer that 1.38, rolled back to that version and everything works.

**Comment by briancao** [comment]
> umami_1 | The column account.account_uuid does not exist in the current database.

@Lennart01 If the account_uuid is being asked for, then the 04_migration didn't run.

Try removing the failed attempt by running...

`delete from _prisma_migrations where migration_name = '04_add_uuid';`

Then rebuild umami to redeploy the 04 migration.

**Comment by jonahgoldwastaken** [comment]
> I also can't log in on anything newer that 1.38, rolled back to that version and everything works.

I had this problem as well, and I think I narrowed it down to a change in how passwords are hashed in version 1.39.x

If you run `node scripts/change-password.js` after installing the `prompts` package, you can set the password of your account to the one you already use and be able to log in again in the UI.

Hope this solves it for you as well!

**Comment by dlford** [comment]
That doesn't seem to work either for me:

```
/app/scripts/change-password.js:86
    if (error.meta.cause.includes('Record to update not found')) {
                         ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at /app/scripts/change-password.js:86:26
```

**Comment by dlford** [comment]
Ok, I got it working now with postgres v15, here are the steps I took:

1. Backup the database

    ```
    docker exec -t umami_db pg_dump --no-owner -U umami umami > umami_db.sql

    docker stop umami_app umami_db
    docker rm umami_db
    docker volume rm umami_data
    ```

2. Change postgres version in docker compose to `postgres:15-alpine`, comment out the umami app so it doesn't get created and initialize the new database, and run `docker compose up -d`

3. Restore database

    ```
    cat umami_db.sql | docker exec -i umami_db psql -U umami -d umami
    ```

4. Delete migration record

    ```
    docker exec -it umami_db psql -U umami
    > delete from _prisma_migrations where migration_name = '04_add_uuid';
    > exit
    ```

5. Uncomment the umami app from docker compose and re-run `docker compose up -d`

6. Change password (if needed, I didn't need to at this point).

    ```
    docker exec -it umami_app sh
    yarn add prompts
    npm run change-password
    # Follow the prompts
    ```

**Comment by wheeleran** [comment]
> Try logging out and back in. We made some auth changes so your old cookie may be out of date.

this is what worked for me on 1.39.3

**Comment by dlford** [comment]
@wheeleran I had to do that too, but if you're using postgres v12 like the example docker-compose file you'll have to upgrade postgres first as detailed above.

**Comment by wheeleran** [comment]
@dlford great, thanks, will do, though everything is up and running normally.

**Comment by geekgonecrazy** [comment]
Upgrading from v1.32.0 to v1.39.5 I ran into this.  Looks like also need to upgrade username and password due to change in password encryption between the two

https://www.crunchydata.com/blog/how-to-upgrade-postgresql-passwords-to-scram
