### ISSUE TITLE
[Feature Request] Team Dashboard/User sharing

### ISSUE THREAD

**Issue by sebiweise** [umami-software/umami#1607]
Thank you for umami, it is fantastic!

I would like to see the ability to create teams to be able to share websites across multiple users that dont have the admin role (therefor they cannot use the "impersonate" feature).

Also it would be great to be able to manage website based permissions to share analytics data directly to (non) admin users.

**Comment by mikecao** [comment]
Teams is coming in v2.

You can already share stats publicly using the share URL feature.

**Comment by sebiweise** [comment]
Yes publicly but when I want to have some websites from another college on my own dashboard I cannot do this at the moment :)
