### ISSUE TITLE
[Feature Request] Auth0/SAML/SSO Login

### ISSUE THREAD

**Issue by sebiweise** [umami-software/umami#1608]
Thank you for umami, it is fantastic!

I would like to see the ability to somehow connect my Auth0 company SSO tenent to umami to be able to implement our SSO to login to umami. Also it would be great to connect Auth0 so that our clients - we have already on-boarded into Auth0 - can login with the same credentials in all our services.
Maybe next-auth support or something like that.

**Comment by mikecao** [comment]
This might be a possible solution, https://github.com/auth0/nextjs-auth0

**Comment by sebiweise** [comment]
Or maybe some next-auth integration to let the users decide what login-provider they want to use: https://next-auth.js.org/providers/

**Comment by zapplebee** [comment]
Even if SSO is not built into the solution, even a custom auth hook would be useful.
