### ISSUE TITLE
Feature to add city and region in geolocation

### ISSUE THREAD

**Issue by AugustinHavas** [umami-software/umami#1610]
Hi,
Do you plan to add cities and regions in the location ?
If so, can you estimate a release date ?

Best regards

**Comment by mikecao** [comment]
This is planned, but we have no estimate.

**Comment by m90khan** [comment]
@mikecao : Thanks for the amazing tool.

https://umami.is/docs/tracker-functions

Which file handles saving tracker functions to the database. would like to save an extra city field based on the IP?
