### ISSUE TITLE
Graph for today/last 24 h disappear and dates missing in datepicker

### ISSUE THREAD

**Issue by mk3media** [umami-software/umami#1618]
Since today in Umami 1.38 and 1.39.3 the graph for today / last 24 h will shortly show up an then disappear immediately (with scaling effect) – but all data like Page and Referrers is ok. For all other dates ranges, yesterday and real time it works like intended.

After further investigations I found that the 30th and 31st of October are missing:

![Screenshot 2022-10-30 at 12 47 39](https://user-images.githubusercontent.com/77986974/198876839-64bb0dc9-2cc9-480a-b7d6-75362e747945.png)

When you change to date range and select 1st November, the 30th and 31st are shown in the right side date picker and the graph will show up like intended:

![Screenshot 2022-10-30 at 12 48 02](https://user-images.githubusercontent.com/77986974/198876841-18694818-dbfc-473d-abe4-6ce66c5d4b7d.png)

Might there be correlation with  last night's time change?  Daylight Saving ended last night here in Europe.

**Comment by mauricerenck** [comment]
Same problem here (Europe/Germany)

**Comment by andlil** [comment]
It has to do with DST ending, same thing has been reported previously #333 #833

**Comment by mk3media** [comment]
Thx! Today everything is back to normal. So, yes, DST is still a problem…

**Comment by mikecao** [comment]
Yes, unfortunately this happens every year. One day we'll get it fixed.
