### ISSUE TITLE
countries and regions Incorrect display

### ISSUE THREAD

**Issue by xiuyuanjun** [umami-software/umami#1620]
Taiwan is not a country,Taiwan belongs to China。    version:v1.33.1
<img width="757" alt="1667178167811" src="https://user-images.githubusercontent.com/24690740/198911712-716e98f9-153f-44e0-bc42-32abddecadc5.png">

**Comment by mikecao** [comment]
See https://github.com/umami-software/umami/issues/1019 and https://github.com/umami-software/umami/issues/1298
