### ISSUE TITLE
Unable to delete, reset, or view analytics (Vercel + Supabase)

### ISSUE THREAD

**Issue by candidexmedia** [umami-software/umami#1631]
I recently switched from Railway to Vercel + Supabase, but have been having issues with getting any analytics to go through:

![image](https://user-images.githubusercontent.com/95003834/199286187-01dc6bf6-dfc5-416b-8889-6e67c9d71b2c.png)

I have other trackers installed, so I know that I had some traffic in October. Supabase hasn't stored any new data either.

I've attempted to delete my sites to start over, but I'm unable to do so:

![image](https://user-images.githubusercontent.com/95003834/199285828-f3045726-f1bc-4a46-9433-f48c8e2071d9.png)

Same thing with reset:

![image](https://user-images.githubusercontent.com/95003834/199287143-83ebb594-865a-4d86-aee9-b82ef7fea371.png)

**Comment by sebiweise** [comment]
This could be a postgresql connection problem, did you follow the instructions to setup the supabase connection pooling?
https://umami.is/docs/running-on-supabase
Maybe you can find some errors in the supabase logs or your vercel logs?!

**Comment by DrMxrcy** [comment]
Getting this issue with Vercel + Render.

**Comment by Ckang2021** [comment]
Getting this issue with Vercel + Local MySQL.

**Comment by sebiweise** [comment]
Could you try to get the Logs for this error? Maybe we will see the problem when you try to reproduce the error and also have the function-logging open in Vercel.

**Comment by Ckang2021** [comment]
> Could you try to get the Logs for this error? Maybe we will see the problem when you try to reproduce the error and also have the function-logging open in Vercel.

Of course, the following are the error reports for deletion and reset respectively.

![image](https://user-images.githubusercontent.com/101509191/199937368-ee9f27ae-aeba-4010-bb79-dc703bb4cb4a.png)
![image](https://user-images.githubusercontent.com/101509191/199937470-27438761-c344-4052-8a6c-fef0771224e4.png)

**Comment by briancao** [comment]
If the event_data table does not exists, it means migrations didn't run correctly.  You can query your migrations using  `select * from _prisma_migrations`

**Comment by DrMxrcy** [comment]
> If the event_data table does not exists, it means migrations didn't run correctly. You can query your migrations using `select * from _prisma_migrations`

I tried to see if the migrations failed but I get

```✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database tables found.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

Datasource "db": PostgreSQL database ]

4 migrations found in prisma/migrations


Database schema is up to date!

✓ Database is up to date.```

Can't add,view or do anything at all.

**Comment by candidexmedia** [comment]
> This could be a postgresql connection problem, did you follow the instructions to setup the supabase connection pooling? https://umami.is/docs/running-on-supabase

Yes, I did. I even reset my Supabase password and updated the env variables in Vercel. Now, I don't see any of my stats at all.

> Maybe you can find some errors in the supabase logs or your vercel logs?!

Vercel log error when I clicked on Realtime stats:

```
[GET] /api/realtime/init
11:18:30:41
Function Status:None
Edge Status:500
Duration:729.71 ms
Init Duration: N/A
Memory Used:205 MB
ID:...
User Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0

2022-11-07T16:18:31.154Z	8cfe91d4-ae14-46a9-ba15-64817d44c156	ERROR	PrismaClientKnownRequestError: Invalid `prisma.event.findMany()` invocation:The column `event.event_name` does not exist in the current database.    at RequestHandler.handleRequestError (/var/task/node_modules/@prisma/client/runtime/index.js:30873:13)    at RequestHandler.request (/var/task/node_modules/@prisma/client/runtime/index.js:30856:12)    at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:31836:16)    at async Promise.all (index 2)    at async getRealtimeData (/var/task/.next/server/chunks/9447.js:2036:43)    at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/realtime/init.js:160:22)    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:366:9)    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:481:9)    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:735:37)    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:247:36) {  code: 'P2022',  clientVersion: '4.5.0',  meta: { column: 'event.event_name' }}2022-11-07T16:18:31.155Z	8cfe91d4-ae14-46a9-ba15-64817d44c156	ERROR	PrismaClientKnownRequestError: Invalid `prisma.event.findMany()` invocation:The column `event.event_name` does not exist in the current database.    at RequestHandler.handleRequestError (/var/task/node_modules/@prisma/client/runtime/index.js:30873:13)    at RequestHandler.request (/var/task/node_modules/@prisma/client/runtime/index.js:30856:12)    at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:31836:16)    at async Promise.all (index 2)    at async getRealtimeData (/var/task/.next/server/chunks/9447.js:2036:43)    at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/realtime/init.js:160:22)    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:366:9)    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:481:9)    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:735:37)    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:247:36) {  code: 'P2022',  clientVersion: '4.5.0',  meta: { column: 'event.event_name' }}RequestId: 8cfe91d4-ae14-46a9-ba15-64817d44c156 Error: Runtime exited with error: exit status 1Runtime.ExitError
```

No errors when I tried to reset or delete.


Supabase log:

I got this error:
`column event.event_name does not exist`

I also kept getting this warning:
`PgBouncer auth request: postgres`

**Comment by candidexmedia** [comment]
> select * from _prisma_migrations

I did this, and got this result:

![image](https://user-images.githubusercontent.com/95003834/200362795-8ba42f7f-dd87-4bc8-af98-dc1d7e1c8375.png)

```
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 02_add_event_data

Database error code: 42501

Database error:
ERROR: must be owner of table event

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42501), message: "must be owner of table event", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("aclchk.c"), line: Some(3583), routine: Some("aclcheck_error") }

   0: sql_migration_connector::apply_migration::apply_script
           with migration_name="02_add_event_data"
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:105
   1: migration_core::commands::apply_migrations::Applying migration
           with migration_name="02_add_event_data"
             at migration-engine/core/src/commands/apply_migrations.rs:91
   2: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:185"
```

**Comment by sebiweise** [comment]
Try to look at your notifications on Supabase. There was some change that was forced until 5th of November I think, something related to the supabase/admin permissions maybe this will help you.

**Comment by DrMxrcy** [comment]
For some reason for me, I had to just delete the project on vercel, and redeploy. And just use my existing DB

**Comment by yuangezhizao** [comment]
> > select * from _prisma_migrations
> 
> I did this, and got this result:
> 
> ![image](https://user-images.githubusercontent.com/95003834/200362795-8ba42f7f-dd87-4bc8-af98-dc1d7e1c8375.png)
> 
> ```
> A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
> 
> Migration name: 02_add_event_data
> 
> Database error code: 42501
> 
> Database error:
> ERROR: must be owner of table event
> 
> DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42501), message: "must be owner of table event", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("aclchk.c"), line: Some(3583), routine: Some("aclcheck_error") }
> 
>    0: sql_migration_connector::apply_migration::apply_script
>            with migration_name="02_add_event_data"
>              at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:105
>    1: migration_core::commands::apply_migrations::Applying migration
>            with migration_name="02_add_event_data"
>              at migration-engine/core/src/commands/apply_migrations.rs:91
>    2: migration_core::state::ApplyMigrations
>              at migration-engine/core/src/state.rs:185"
> ```

Try following https://github.com/umami-software/umami/discussions/1486#discussioncomment-3567397.

**Comment by candidexmedia** [comment]
Thanks for the tips everyone! I've tried everything, but nothing has been working. It's starting to feel like there's no hope...


> Try following https://github.com/umami-software/umami/discussions/1486#discussioncomment-3567397.

I followed that previously, when I was first setting up Supabase + Vercel. I even did the yarn stuff, but it didn't help.

> Try to look at your notifications on Supabase (the bell icon in the up right corner). There was some change that was forced until 5th of November I think, something related to the supabase/admin permissions maybe this will help you.

Hmmm, I tried that, but didn't notice a difference.

> For some reason for me, I had to just delete the project on vercel, and redeploy. And just use my existing DB

Just tried this, but unfortunately, no difference... :(

**Comment by sebiweise** [comment]
Can you try to delete the supabase project and start a fresh migration or are there some data already in your database?
Otherwise you can manuale check the permissions in the supabase admin panel, the last error is telling you something about the permissions on table event :/
