### ISSUE TITLE
Questions about new features

### ISSUE THREAD

**Issue by AugustinHavas** [umami-software/umami#1633]
Hi,
I have a list a new features that could be added :
- Clicks tracking (on every DOM element)
- Exit page
- Add filters like remove an IP address
- Download CSV report file with differents categories
- Track new visitors (per day or selected date/time)

For each feature mentioned above, can you tell me if you plan to integrate them and if so, do you have an estimated date of release ?

Best regards

**Comment by franciscao633** [comment]
Hello, our plan is to have a public roadmap in the near future, which will include features we will be working on. I will label this as enhancement, so we can review this list as we add more features. 

Thanks,

**Comment by CanRau** [comment]
Here's the Roadmap [discussion](https://github.com/umami-software/umami/discussions/1698)
