### ISSUE TITLE
Docker server down?

### ISSUE THREAD

**Issue by tombrereton** [umami-software/umami#1634]
Hi Team Umami,

Loving what you've built here, I'm currently using it for my website and hosting it on Azure Container Apps 😄 

However when I try to get the latest build from your docker server I'm getting a 502 bad gateway.

Does the server need a restart?

Command:
```sh
docker pull docker.umami.is/umami-software/umami:mysql-latest
```

Response
```sh
Error response from daemon: received unexpected HTTP status: 502 Bad Gateway
```

When I try to pull another image it works:
```sh
docker pull hello-world

Using default tag: latest
latest: Pulling from library/hello-world
7050e35b49f5: Pull complete
Digest: sha256:e18f0a777aefabe047a671ab3ec3eed05414477c951ab1a6f352a06974245fe7
Status: Downloaded newer image for hello-world:latest
docker.io/library/hello-world:latest
```

My system info is:
```sh
System:
  OS: macOS 13.0
  CPU: (10) arm64 Apple M1 Pro
  Shell: 5.8.1 - /bin/zsh
```

**Comment by meepmeep** [comment]
Yes, https://docker.umami.is is sending back a 502 error.

**Comment by mikecao** [comment]
Sorry, we keep having issues with our docker server. Alternatively you can use `docker.umami.dev`.

**Comment by tombrereton** [comment]
No problem @mikecao. I'm happy to chip in so let me know if you need a hand with anything.

**Comment by meepmeep** [comment]
https://docker.umami.is/ is down again. Throwing 502 error code again.
