### ISSUE TITLE
Uncaught (in promise) Error: Cannot animate between AnimatedValue and AnimatedString, as the "to" prop suggests

### ISSUE THREAD

**Issue by m90khan** [umami-software/umami#1638]
When trying to filter event data inside EventDataForm.js, it is giving following error.
![image](https://user-images.githubusercontent.com/6104751/199965849-d2d80dc5-4c26-4bfa-b1d3-f194dc94f554.png)

The error is happening inside
components\metrics\DataTable.js

**Comment by briancao** [comment]
I saw your message on discord.  Is this only happening on EventData's implementation of DataTable?

**Comment by m90khan** [comment]
@briancao : Yes
