### ISSUE TITLE
Improved location of Internet users

### ISSUE THREAD

**Issue by TdhPerso14** [umami-software/umami#1641]
Hello,

Congratulations on this program to track consultation statistics
Do you think it is possible to improve the stats on the location of Internet users? Currently we only have countries but not regions, departments or cities.
Thanks in advance
Cordially

**Comment by placko** [comment]
I agree with @TdhPerso14.
The ability to refine user location results (at least by city) would be a real asset for local marketers and data analysts.
Best regards ;)

**Comment by TdhPerso14** [comment]
Congratulations again for these developments. No news on our request for precision concerning the location of the consultations?
This will be really interesting because it is essential data for monitoring visits.

**Comment by glamothe9** [comment]
It won't happen. Because umami is GPDR compliant, it does not store the entire IP address of the visitors thus cutting off the possibility of having more precise information

**Comment by TdhPerso14** [comment]
Hi glamothe9, Thank you for your answer
This is surprising because Matomo (https://fr.matomo.org/gdpr/?menu) for example seems to list the locations (regions-cities) while being GDPR compliant thanks to the anonymization of the IPs.
This is also what you do but only for countries

**Comment by placko** [comment]
Hi, do you have any news about refine user location results (at least by city) ?
Best regards ;)

**Comment by briancao** [comment]
It's currently on the roadmap, scheduled for Q1 next year.

https://github.com/umami-software/umami/discussions/1698
