### ISSUE TITLE
Error when deploying with Dokku

### ISSUE THREAD

**Issue by IgnisDa** [umami-software/umami#1655]
I tried to get Umami running with Dokku but was unsucessful in securing it with `https`. `dokku letsencrypt:enable umami` failed with this error:

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/60938164/202208280-1837edd3-4670-4707-9cf0-3d1f904241cb.png">

Here are the steps to get to where I was

```bash
APPNAME="umami"
dokku apps:create "$APPNAME"
dokku postgres:create "$APPNAME"
dokku postgres:link "$APPNAME" "$APPNAME"
IMAGE_NAME="docker.umami.dev/umami-software/umami:postgresql-latest"
docker pull $IMAGE_NAME
image_sha="$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE_NAME)"
dokku git:from-image "$APPNAME" "$image_sha"
```

**Comment by briancao** [comment]
This looks like a Dokku specific error, related to their cert generation process.

I recommending using one of the hosting platforms we have documentation for.  We do not have plans to write Dokku specific documentation at this time.

https://umami.is/docs/hosting
