### ISSUE TITLE
Analytics shows me as Windows 10 but am on Windows 11

### ISSUE THREAD

**Issue by Ravavyr** [umami-software/umami#1656]
I just installed cloud beta and tried it on my site. 

It shows me as being on windows 10:
https://gyazo.com/6480e2ed3152fcdd910638904c00475b

Here's my actual system info - Windows 11:
https://gyazo.com/0f8cae7d9cdd180f2af671f424b7635d

Here's my user agent in chrome while i'm on my website:
https://gyazo.com/2145a118d525831b01fa688c1253b130

Good luck :)

**Comment by Ravavyr** [comment]
Googled some myself, found this:
https://learn.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11

Looks like you need to check for certain headers [doesn't that just defeat the purpose of the user agent?]
https://gyazo.com/4d34c6121aecbab24fe1ba11a2f2c3ad

**Comment by wangyang0210** [comment]
https://caniuse.com/?search=userAgentData

some browsers may not support `userAgentData` 🙁
