### ISSUE TITLE
Cannot log in after updated to the v1.39.5

### ISSUE THREAD

**Issue by ArmandoArias** [umami-software/umami#1658]
pm2 log
<img width="545" alt="putty_DTZPZruCZX" src="https://user-images.githubusercontent.com/4276549/202258154-25c563f0-24b9-4b07-9cda-6ad7e242b7f4.png">

**Comment by franciscao633** [comment]
It looks like migration 04 did not run successfully, since you are still missing UUID columns. Have you tried the steps in #1604 ?

**Comment by ArmandoArias** [comment]
> It looks like migration 04 did not run successfully, since you are still missing UUID columns. Have you tried the steps in #1604 ?

if it was the first thing i did

**Comment by franciscao633** [comment]
Cool. Were you able to confirm there is no account_uuid column in your account table, but the migrations say there were applied? I'm just trying to recreate this scenario.

**Comment by ArmandoArias** [comment]
> Cool. Were you able to confirm there is no account_uuid column in your account table, but the migrations say there were applied? I'm just trying to recreate this scenario.
I solved it by executing the sql script in the console
