### ISSUE TITLE
calendar widget only shows 29 days

### ISSUE THREAD

**Issue by brunoamaral** [umami-software/umami#1667]
When setting a custom date range, the calendar doesn't show the full month.

<img width="830" alt="image" src="https://user-images.githubusercontent.com/543344/202818998-e52e0555-ceab-47f5-b044-3676208ad00b.png">

**Comment by briancao** [comment]
Confirmed bug.  Will get this triaged.  Thanks!

**Comment by briancao** [comment]
Have this fixed in DEV.  We'll be deploying in the next few days.

**Comment by franciscao633** [comment]
Fixed in v1.40.0
