### ISSUE TITLE
Event data window popup too large for my screen

### ISSUE THREAD

**Issue by uPesy** [umami-software/umami#1669]
On v1.39.5, the window to search event data is too large for my screen (1366x768): i can't click on the bottom buttons : 
![image](https://user-images.githubusercontent.com/61392244/202917424-7e4a0d67-00aa-4f53-91c9-decb9685a68c.png)
It should be resize base on the viewport

**Comment by franciscao633** [comment]
Thanks for reporting, however this is currently removed and we're redoing the entire event data modal.
