### ISSUE TITLE
Hash routes doesn't count as  pages

### ISSUE THREAD

**Issue by NeoN0x** [umami-software/umami#1670]
Hello,

I'm building an app and I'm facing the issue described here :

### Discussed in https://github.com/umami-software/umami/discussions/1142

The issue is that the route URL is correctly tracked (no matter if it starts with `#` or not), but it does not count as page, as you can see on the screenshot below

![image](https://user-images.githubusercontent.com/1714902/203083225-8b8ef313-0191-4d48-afc4-a581ce9db8d8.png)

I can see two solutions that could enable these kind of use case and make Umami more usable.

1) Disable the automatic way of sending of page views (maybe by using data-mode="manual")

I'll then be able to manage the route using `unami.trackView()` (by splitting # or substring 1..) on my own.

2) Adding a per-site option

- It would either be an "url prefix" that would be removed on the server side. By default "/{url}", "/#{url}", or "/somepath/{url}"
- Or an option "Route based navigation" / "hash based navigation"

Thanks

**Comment by NeoN0x** [comment]
Hi,

Sorry, I haven't noticed the `data-auto-track=false` in [tracker configuration documentation](https://umami.is/docs/tracker-configuration).

Doing this do the trick : 

```js
    // Trigger this on each page change
    umami.trackView(window.location.href.split('#')[1], document.referrer, "mywebsiteid")
```

Works as expected, event if it does not looks clean.

Note FYI:  I'm using a subfolder (mywebsite.com/somefolder/#/myroute/etc and plausible does not work in this case, even with plausible.hash.js - no issue when using root, but when using subfolder, it does not track anything)


So, feel free to close if this use case is too specific for deserving an option, as it can be easily workarounded (maybe a paragraph in the doc "hash based navigation" would help here

Thanks

**Comment by john-dev** [comment]
Im running into the same issue. Any chance this can be addressed?

My path also looks like this:
https://m.domain/account/#/apps/events

the recognized url is app2k and #/apps/events is not being recognized as part of the domain:
![grafik](https://user-images.githubusercontent.com/1394374/216732841-74b97075-f6c9-4351-949a-ae4b5069a72e.png)
