### ISSUE TITLE
[Cloud Beta] Visitors on mobile & number of views

### ISSUE THREAD

**Issue by TigersWay** [umami-software/umami#1676]
Hi,
A visitor from a browser on mobile may be changing app, browser to something else - back and forth.

while for the same visitor, it seems that each "visit" is counted, even after a few seconds!

Is that intended?
Thanks

**Comment by mikecao** [comment]
A visit is a single load of a page, doesn't matter what browser they use, every one will count. A visitor is a unique person identified by their IP address and browser. If they change browser, they are considered a different visitor.

**Comment by TigersWay** [comment]
I need to learn how to explain better 😄 

The unique visitor leaving his browser for a few seconds - to answer a message, get a call or anything - and then coming back to the same browser he started with will be counted as:
- one and only visitor = GREAT
- starting then a SECOND view...  Well less great in my sense.
