### ISSUE TITLE
GDPR Concerns / Load locally

### ISSUE THREAD

**Issue by danielslyman** [umami-software/umami#1677]
Hello,

First off, thanks so much for creating this. I love umami!

I wanted to ask, is there some way to proxy or embed the script locally and send the ID to the umami server differently somehow? Maybe someone here has an answer or an idea. I tried simply loading it from a local directory but obviously that didn't work.

Thanks,
Daniel

**Comment by mikecao** [comment]
You can host the tracker script anywhere, then use `data-host-url` to send the data somewhere else. See https://umami.is/docs/tracker-configuration

**Comment by danielslyman** [comment]
oh wow, thanks so much for this and sorry for overlooking this!
