### ISSUE TITLE
strict-origin-when-cross-origin Error

### ISSUE THREAD

**Issue by wchorski** [umami-software/umami#1679]
I'm using NextJS. both Umami & NextJS are self hosted.
- my website → https://dev-garden.williamusic.com/
- Umami app → https://analytics.williamusic.com/

 I tried putting the umami `<script>` into the `<Head>` and also used the `next/script` `<Script>` tag in the body of my markdown.

both times I got a `strict-origin-when-cross-origin` error. Is this something I can fix in the next.config.js?

Here is my `next.config.js`
```js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
  async rewrites() {
    return [
      {
        source: '/api/:path*',
        destination: 'https://analytics.williamusic.com/:path*'
      }
    ]
  },
  images: {
    remotePatterns:[
      {
        protocol: 'https',
        hostname: 'images.dog.ceo',
        port: '80',
        pathname: '/**',
      },
    ]
  },
  output: 'standalone',
}


module.exports = nextConfig
```

How do I clear this Cross Origin Policy?

**Comment by DMaxence** [comment]
Hi,
I found that while searching : 
https://github.com/umami-software/umami/issues/100
https://vercel.com/guides/how-to-enable-cors#enabling-cors-using-vercel.json

Can you try it ?

**Comment by DMaxence** [comment]
@wchorski Did you manage to fix your CORS issue ? 
I'm having the same issue and cannot find how to fix it.

**Comment by wchorski** [comment]
> @wchorski Did you manage to fix your CORS issue ? I'm having the same issue and cannot find how to fix it.

I believe this is an issue directly with **Microsoft Edge**. To simplify troubleshooting, I hosted a static html site with nginx. enable cors with  `add_header Access-Control-Allow-Origin *;` 

- Firefox → worked fine
- chrome → worked fine
- edge → blocked by `strict-origin-when-cross-origin`

I tried turning off edge's privacy restrictions, but I'm still having issues.

**Comment by DMaxence** [comment]
I'm having this issue with Chrome, didn't tried with other browsers.

For me it's when I try to access to the API through my website. Otherwise it's working when connecting to the dashboard directly, or from Postman.

**Comment by Loongphy** [comment]
Edge Inprivate mode works, but normal failed.

**Comment by myesn** [comment]
disable browser plugin: `uBlock Origin`
