### ISSUE TITLE
Button click events overcounting

### ISSUE THREAD

**Issue by pashashocky** [umami-software/umami#1686]
I've played around with events on localhost and they record 1 button click correctly. However, when deployed on the web, I'm getting a single button click counting for 4-8+ events.

![Fi0lNCTXwAEUn7J](https://user-images.githubusercontent.com/673857/205489333-0a34516e-95df-45ba-9f12-334a2c920099.png)

**Comment by mikecao** [comment]
Are you manually sending the events or using the css classes?
