### ISSUE TITLE
404 When Using api/website/3/stats

### ISSUE THREAD

**Issue by dhanny34** [umami-software/umami#1688]
Hi, I'm Using Docker with digital ocean tutorial. 

I got, 404 when using https://umami.domain.com/api/website/3/stats?start_at=1670259600000&end_at=1670345940000

but when using https://umami.domain.com/api/websites I get 200 result

Please guide me to solve this.

Thanks

**Comment by Mokkapps** [comment]
I have the same problem

**Comment by mikecao** [comment]
What version are you on? The website ids have changed in the latest version.

**Comment by dhanny34** [comment]
> What version are you on? The website ids have changed in the latest version.

v1.39.5 and when I try this api/websites/5/stats?start_at=1641536633000&end_at=1670394233000 it's shows error 500.

On my docker logs umami_db_1 shows something like this

2022-12-11 01:12:11.459 UTC [2111] ERROR:  invalid input syntax for type uuid: "5" at character 585
2022-12-11 01:12:11.459 UTC [2111] STATEMENT:  select sum(t.c) as "pageviews",
	        count(distinct t.session_id) as "uniques",
	        sum(case when t.c = 1 then 1 else 0 end) as "bounces",
	        sum(t.time) as "totaltime"
	      from (
	        select pageview.session_id,
	          to_char(date_trunc('hour', pageview.created_at), 'YYYY-MM-DD HH24:00:00'),
	          count(*) c,
	          floor(extract(epoch from max(pageview.created_at) - min(pageview.created_at))) as "time"
	        from pageview
	          join website 
	            on pageview.website_id = website.website_id
	          
	        where website.website_uuid='5'
	          and pageview.created_at between $1 and $2
	          
	          
	        group by 1, 2
	     ) t

**Comment by dhanny34** [comment]
Found it, https://github.com/umami-software/umami/issues/1632

Using uuid not id on newer version.

Previously I thought because of wrong configuration. after trying to recreate it from scratch and ignoring the old data it turns out that the id was replaced by uuid

**Comment by Mokkapps** [comment]
It also worked for me using the uuid instead of the id

Additionally, I still used an old endpoint `api/website/` instead of `api/websites`
