### ISSUE TITLE
Unable to connect to the database.

### ISSUE THREAD

**Issue by git-kings** [umami-software/umami#1689]
[root@izbp1finc6d22c39tcxmzuz umami]# npm -v
7.5.1
[root@izbp1finc6d22c39tcxmzuz umami]# node -v
v15.8.0
[root@izbp1finc6d22c39tcxmzuz umami]# yarn -v
1.22.19
[root@izbp1finc6d22c39tcxmzuz umami]# pwd
/root/umami/umami
[root@izbp1finc6d22c39tcxmzuz umami]# ls -a
![image](https://user-images.githubusercontent.com/66518019/206081918-f0908ffa-81bd-466c-9581-90da37389d0c.png)

operating steps
1.yarn install
2.create .env : DATABASE_URL=mysql://root:xxxx@xxxx:3306/umamidb
3.yarn build
![image](https://user-images.githubusercontent.com/66518019/206082398-18e7b5ea-9c45-490d-929a-fa4e874f6171.png)

**Comment by mikecao** [comment]
Make sure your username and password do not have any weird characters that can cause the connection to fail. Also verify that you can connect manually from somewhere else.

**Comment by git-kings** [comment]
Yes my database is normal and the password contains. And /, and can be used for normal remote connections

**Comment by mikecao** [comment]
The connection is a url, so you need to encode any special characters in your username/password. See https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding

**Comment by git-kings** [comment]
> 连接是一个 url，因此您需要对用户名/密码中的任何特殊字符进行编码。请参阅https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding
That's it. Thank you.

**Comment by git-kings** [comment]
> 连接是一个 url，因此您需要对用户名/密码中的任何特殊字符进行编码。请参阅https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding

I have a question. Does umami have to use nginx as the reverse proxy?

**Comment by mikecao** [comment]
No, you can have the app run on port 80 if you want.

**Comment by git-kings** [comment]
> No, you can have the app run on port 80 if you want.

Ok, do visitor pages not support embedding in https pages?

**Comment by mikecao** [comment]
If you want SSL, you need a reverse proxy.
