### ISSUE TITLE
Doesn't show data

### ISSUE THREAD

**Issue by nominaltechnopv** [umami-software/umami#1695]
if we're change period from today\yesterday to week\month - https://i.imgur.com/G4Pjs1t.png
 
We noticed that if data are big, very, very long wait loading. Or doesn't loading.  https://i.imgur.com/zSOWXep.png

And press button "refresh" don't help us. https://i.imgur.com/dkeacbB.png

**Comment by mikecao** [comment]
How big is big? How many records? What are your server specs?

**Comment by nominaltechnopv** [comment]
> How big is big? How many records? What are your server specs?

For example - https://i.imgur.com/GgXipW2.png. 23k uniq users and 502 error or now loading.

**Comment by nominaltechnopv** [comment]
and second example with little data for day https://i.imgur.com/knLvSgr.png - 3-7 seconds, and loading all data done
but if project with big data for day (20k+ per day) - problems is coming

**Comment by briancao** [comment]
> How big is big? How many records? **What are your server specs?**

What are your server specs?  Umami should be able to handle your volume.  For instance, our demo is hosted on a 4 core / 8 gb machine and performs reasonably well.  

We have optimizations planned in the future as we redo the calculation for visit length, maybe introduce materialized views, etc.  But it'll be an on-going fight as we're introduced to larger data sets.
