### ISSUE TITLE
Where to see event_data in dashboard?

### ISSUE THREAD

**Issue by CanRau** [umami-software/umami#1696]
Can't figure out where to see `event_data`, I'm looking everywhere, also `?view=event` in the pages details, I only find the `event_name`

I tried the following to track events
```
umami.trackEvent(`Button"`, { type: "signup", userId: 123 });
umami.trackEvent(`Button 2"`, "StriNg");
```

What am I missing?

Tried to open a Discussion instead but couldn't 🤔 the button is greyed out for me, haha 🤦🏼 just found the checkbox you need to click before you can start a discussion 😅

**Comment by mikecao** [comment]
https://github.com/umami-software/umami/releases/tag/v1.39.0

**Comment by CanRau** [comment]
Thanks, not exactly sure how to use that or I mean I can't see values for example from `userId: 123` right?
Maybe funnels or campaign in v2 would bring a way to see which logged-in user is doing what?
