### ISSUE TITLE
DISABLE_LOGIN still redirects to login page

### ISSUE THREAD

**Issue by tasiotas** [umami-software/umami#1699]
Hi,

I build docker image from your Dockerfile, by adding below

Dockerfile
```
...
ARG DISABLE_LOGIN
ENV DISABLE_LOGIN $DISABLE_LOGIN
...
```

build command
`docker build --build-arg DATABASE_TYPE=postgresql --build-arg BASE_PATH=/bRs47jH13fdsBFMQ93/umami --build-arg DISABLE_LOGIN=1`

Once I run the image and go to url, I still get redirected to login page. Login widget is not visible.
Expected behavior is not to be redirected to login, just straight to dashboard.

Thanks

**Comment by mikecao** [comment]
DISABLE_LOGIN does not skip the login process. It disables the login page so that people can't use it to try and log in.

**Comment by tasiotas** [comment]
Just to clarify, how admin can get to dashboard without login page?

**Comment by mikecao** [comment]
You only need to disable the login if you're using only the API. Otherwise just log in.
