### ISSUE TITLE
Error 500 when trying to log in

### ISSUE THREAD

**Issue by phanendraguptha** [umami-software/umami#1703]
I am getting an error 500 when trying to log in to Umami, which I hosted on Netlify and the database is on Supabase.

Please help me find the solution.
Thanks!

**Comment by briancao** [comment]
We'll need a lot more details.  Can you post a log of your actual error?

**Comment by phanendraguptha** [comment]
![image](https://user-images.githubusercontent.com/47347106/208586885-26c16fa7-5f33-49d4-a409-69f8290a08ed.png)

**Comment by briancao** [comment]
I'll need to see actual server log errors.

**Comment by phanendraguptha** [comment]
![image](https://user-images.githubusercontent.com/47347106/208612445-4f0e60f2-2af9-40e7-b359-61a45623ff1b.png)
This will work?

**Comment by phanendraguptha** [comment]
It seems the migrations did not complete. I ran the below command to add migrations to the db `npx prisma migrate deploy --schema="./db/postgresql/schema.prisma"` now it's working fine. I followed the documentation https://umami.is/docs/running-on-supabase seems this step is missing there.

**Comment by briancao** [comment]
Umami build process should have run the migrations.  We're actually in the process of re-writing how we perform migrations all-together in v2 of Umami, and will update our docs at that time.
