### ISSUE TITLE
API routes under api/websites/ returning 401.

### ISSUE THREAD

**Issue by yelinaung** [umami-software/umami#1706]
Hi! First of all, thanks for the wonderful umami software!

#### Setup

Umami v1.39.5 running inside docker-compose, behind Nginx, with Postgres

I'm facing some issues with the dashboard. It is just showing me a blank page.

![image](https://user-images.githubusercontent.com/275120/207591720-3b79ec19-5cf7-4698-a0ac-f6ef978b03d9.png)

I've inspected the Chrome console and found that the API routes under the `api/websites` are returning 401 Unauthorized. Anything that I am missing? 

![image](https://user-images.githubusercontent.com/275120/207592269-ac0bf042-b081-4473-baca-d2c1af4fd328.png)

The rest of the API routes are working fine. Real-Time is working fine as well.

There aren't any events. Just page views. Not a lot of data as well.

There are some errors when I do the `docker logs <container name>`. I've pasted them at https://pastebin.com/dxiSDGAb

Thanks!

**Comment by yelinaung** [comment]
Actually, it's now working again (and not sure why 🤔 ) But I am gonna close the issue!

**Comment by simonwiles** [comment]
I just experienced this too; in my case (at least) it was a result of refreshing an open page after upgrading the Umami version.  Logging out and in again solved it.
