### ISSUE TITLE
Un-enable Share URL

### ISSUE THREAD

**Issue by wheeleran** [umami-software/umami#1709]
hi. just updated to v1.39.5, docker. I can't UN-enable the 'share URL' on a site. i untick the Share box, click Save, refresh page. the Share URL tick box is still enabled, the 'Get Share URL' clipboard link is still present. Not sure what to do.

**Comment by wheeleran** [comment]
OK, thanks!

**Comment by pcnetwizard** [comment]
I've also found this bug, do you have an ETA for the next version release?  

thanks,

Andrew,

**Comment by briancao** [comment]
Have it fixed.  We have a release planned before end of week.

**Comment by wheeleran** [comment]
Much appreciated!

**Comment by franciscao633** [comment]
Fixed in v1.40.0
