### ISSUE TITLE
Getting 500 status while changing the initial password

### ISSUE THREAD

**Issue by phanendraguptha** [umami-software/umami#1712]
Here are the server logs. Please help me on this.
`Dec 23, 05:13:57 PM: 284f20f1 ERROR  PrismaClientUnknownRequestError:Dec 23, 05:13:57 PM: 284f20f1 ERROR  Invalid `prisma.account.findUnique()` invocation:Dec 23, 05:13:57 PM: 284f20f1 ERROR  Error occurred during query execution:Dec 23, 05:13:57 PM: 284f20f1 ERROR  ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P05), message: "prepared statement \"s0\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("prepare.c"), line: Some(446), routine: Some("StorePreparedStatement") }) }) })Dec 23, 05:13:57 PM: 284f20f1 ERROR      at RequestHandler.handleRequestError (/var/task/node_modules/@prisma/client/runtime/index.js:30877:13)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at RequestHandler.request (/var/task/node_modules/@prisma/client/runtime/index.js:30856:12)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at async PrismaClient._request (/var/task/node_modules/@prisma/client/runtime/index.js:31836:16)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at async __WEBPACK_DEFAULT_EXPORT__ (/var/task/.next/server/pages/api/accounts/[id]/password.js:156:25)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:366:9)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:481:9)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:735:37)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at async Router.execute (/var/task/node_modules/next/dist/server/router.js:247:36)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:347:29)Dec 23, 05:13:57 PM: 284f20f1 ERROR      at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:285:20) {Dec 23, 05:13:57 PM: 284f20f1 ERROR    clientVersion: '4.5.0'Dec 23, 05:13:57 PM: 284f20f1 ERROR  }Dec 23, 05:13:57 PM: 284f20f1 INFO   [POST] /api/accounts/8c310804-0788-4a7d-97f6-b3cfaa124132/password (API)`

**Comment by franciscao633** [comment]
Sorry for the late reply. Are you using Supabase by any chance?

**Comment by phanendraguptha** [comment]
Yes I am using Supabase only.

**Comment by franciscao633** [comment]
Just to confirm, you already added `?pgbouncer=true` to your DATABASE_URL?

**Comment by phanendraguptha** [comment]
adding `?pgbouncer=true` solves the problem thanks!
