### ISSUE TITLE
add loading indicator when move to another page

### ISSUE THREAD

**Issue by fiqryq** [umami-software/umami#1717]
Please add a loading indicator/shimmer when moving to another page. I think it's weird if we try to go to another page and the page is left blank like this :

![Screenshot 2022-12-28 at 20 26 04 (2)](https://user-images.githubusercontent.com/25787603/209819332-f052088a-5ba8-4654-a417-9f9faa97075f.png)

**Comment by mikecao** [comment]
Feature added.
