### ISSUE TITLE
share URL can view data for all sites

### ISSUE THREAD

**Issue by incitere** [umami-software/umami#1720]
I open the sharing URL through the InPrivate window. When the window is reduced to the size of the mobile phone, I can open the Realtime menu to see all the statistical information of the whole site, and even enter the background to change the Settings! Fortunately, "Something went wrong."

**Comment by briancao** [comment]
We've completely changed the way we're showing settings, along with adding roles and permissions in v2.  This isn't a problem there.

Confirming the bug in v1.  We'll get it prioritized.
