### ISSUE TITLE
Running into local issue when running `yarn build`

### ISSUE THREAD

**Issue by markcellus** [umami-software/umami#1721]
Hey, love this package! I'm running the project locally on my server and everything works flawlessly until I ran `yarn build`. Here is output

<details>
<summary><code>yarn build</code> Output</summary>

```
$ yarn build
yarn run v1.22.19
$ npm-run-all build-db check-db build-tracker build-geo build-app
$ npm-run-all copy-db-files build-db-client
$ node scripts/copy-db-files.js
Database type detected: postgresql
Copied /home/openrss/umami/db/postgresql to /home/openrss/umami/prisma
$ prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.5.0 | library) to ./node_modules/@prisma/client in 193ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
<code>
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
</code>
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database tables found.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "umami", schema "public" at "localhost:5432"

4 migrations found in prisma/migrations


Database schema is up to date!

✓ Database is up to date.
$ rollup -c rollup.tracker.config.js
/bin/sh: 1: rollup: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-tracker" exited with 127.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

</details>

Any thoughts?

```bash
$ node -v
v18.12.1
$ yarn -v
1.22.19
```

**Comment by markcellus** [comment]
@briancao sorry to @ message you, but should this issue be labeled a bug? It doesn't seem to let me classify it. It's preventing me from using the software. Thanks for any information.

**Comment by briancao** [comment]
Not a problem. I'm using node v16.14 to dev locally, and our test site is on v18.9.0, so it shouldn't be a problem.

I'll have to take a deeper look.

**Comment by markcellus** [comment]
@briancao it appears that the reason I'm running into errors like `/bin/sh: 1: rollup: not found` error is because I have `NODE_ENV` env var is set to `production` on my server, so none of the [packages in `devDependencies`](https://github.com/umami-software/umami/blob/9ee6fb994cc51e48b228fe3e52d36f463412efc4/package.json#L107-L138) are being installed when running `yarn install`.

I must have `NODE_ENV` set to `production` on my server for other unrelated node processes, so I can't remove it, unfortunately.  Would you be willing to accept a PR that moves these `devDependencies` to `dependencies`? After all, they probably should be `dependencies` anyway, because they're required to run the project on production level servers.

**Comment by briancao** [comment]
Glad you were able to solve the problem.  I had no luck on my end trying to reproduce the issue, but I'll create a ticket on our end to look into issues with NODE_ENV further.

No PR is necessary at this time.

**Comment by markcellus** [comment]
I think you're misunderstanding. i didnt solve the problem. I just now know why the issue exists. 

You can easily reproduce the issue by cloning the repo of this project. setting NODE_ENV to production and attempting to run `yarn install` and then `yarn build` per the instructions.

Not sure why this issue was closed.

**Comment by briancao** [comment]
My mistake. Re-opening.

**Comment by mikecao** [comment]
According to https://github.com/yarnpkg/yarn/issues/1830 it looks like you can simply run
```
$ NODE_ENV=development yarn install
```

**Comment by markcellus** [comment]
I'll use that but that sets the NODE_ENV to a value that is not applicable to the environment and will cause negative side effects. https://github.com/yarnpkg/yarn/issues/1830#issuecomment-260520242 from a yarn contributor says in that same thread:

> If you need your dev packages in production promote them to the dependencies group.

Why are packages that are needed in the production server declared as `devDependencies`? Moving them to `dependencies` is the less risky approach here. I also offered to open a PR to do this if you're not able.

**Comment by markcellus** [comment]
Actually, I think I'll just hold off on using this project and just use plausible instead. Setting `NODE_ENV` to development in a production environment could have unintended side effects. Suggesting it as a solution makes me think there's a possible misunderstanding of how the Node ecosystem works and makes me a little nervous about the viability of the package. Anyway, thanks for your help!
