### ISSUE TITLE
Migration error using Supabase and render.com

### ISSUE THREAD

**Issue by OB-UNISA** [umami-software/umami#1724]
I followed the [official guide for Supabase](https://github.com/umami-software/website/blob/370c69e625a41c8465284c5959219e2da42e2ddb/content/running-on-supabase.mdx) but the migration always fail. I checked the table *_prisma_migration* and it has the following error: 

```
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 02_add_event_data

Database error code: 42501

Database error:
ERROR: must be owner of table event

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42501), message: "must be owner of table event", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("aclchk.c"), line: Some(3788), routine: Some("aclcheck_error") }

   0: sql_migration_connector::apply_migration::apply_script
           with migration_name="02_add_event_data"
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:105
   1: migration_core::commands::apply_migrations::Applying migration
           with migration_name="02_add_event_data"
             at migration-engine/core/src/commands/apply_migrations.rs:91
   2: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:186
```

The only way to fix it was to manually apply the [migrations](https://github.com/umami-software/umami/tree/9ee6fb994cc51e48b228fe3e52d36f463412efc4/db/postgresql/migrations) and set the env variable `SKIP_DB_CHECK` to 1.

I am deploying umami on [render.com](https://render.com/) using a _Web Service_ and as runtime environment _Node_. I am using this repository on the master branch and from render.com I added a `.env` file for `DATABASE_URL` and `HASH_SALT`. As Build Command I use `npm run build` and as Start Command I use `npm start`.

**Comment by briancao** [comment]
Have you tried the solutions in this discussion?

https://github.com/umami-software/umami/discussions/1542

**Comment by OB-UNISA** [comment]
> Have you tried the solutions in this discussion?
> 
> #1542

Yes, but because I already applied the migrations manually it was still showing some errors like this one:
```
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 04_add_uuid

Database error code: 42701

Database error:
ERROR: column "account_uuid" of relation "account" already exists

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42701), message: "column \"account_uuid\" of relation \"account\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("tablecmds.c"), line: Some(7134), routine: Some("check_for_column_name_collision") }

   0: sql_migration_connector::apply_migration::apply_script
           with migration_name="04_add_uuid"
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:105
   1: migration_core::commands::apply_migrations::Applying migration
           with migration_name="04_add_uuid"
             at migration-engine/core/src/commands/apply_migrations.rs:91
   2: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:186
```

To fix it I used [this solution](https://github.com/umami-software/umami/discussions/1542#discussioncomment-3756936) to mark the migrations which were showing errors as done.

**Comment by briancao** [comment]
So it looks like your DB should be up to date now if you manually ran them, and marked as applied.  Can we close this issue?

**Comment by OB-UNISA** [comment]
> So it looks like your DB should be up to date now if you manually ran them, and marked as applied.  Can we close this issue?

Sure, I had no other issues and it works now.
