### ISSUE TITLE
Allow database connection information as environment variables

### ISSUE THREAD

**Issue by christianknell** [umami-software/umami#1727]
Currently, it is only possible to define the database connection using the `DATABASE_URL` environment variable.

It would be good if there were a way to define the single components of this URL (database type, hostname, username, password, etc.) as single environment variables, like DATABASE_HOST, DATABASE_USER, DATABASE_PASSWORD. This would enable the usage of Secrets for defining the environment variables when deploying Umami on Kubernetes.

I have created a [Helm Chart for Umami](https://github.com/christianknell/helm-charts/tree/main/charts/umami) ([ArtifactHub](https://artifacthub.io/packages/helm/christianknell/umami)) and would love to add this feature to make the Chart and therefore the usage of Umami more secure.

**Comment by khromov** [comment]
SQL connection strings are incredibly common, standardized and easier to work with than trying to split up the parameters in non-standard variable names. (`DB_PASSWORD`? `DATABASE_PW`? `DATABASE_PASSWORD`? etc)

I see you already solved the problem in the Helm chart by [stitching the values together](https://github.com/christianknell/helm-charts/blob/794ed332706044e1600fad5ea7472b56cffe84f3/charts/umami/templates/deployment.yaml#L39), so what is the problem? :-)

From a security perspective, putting the whole connection string in a secret makes sense.

**Comment by christianknell** [comment]
You are right that I can also use a Secret for the whole connection string. But that is relatively uncommon in the cloud-native area. You mostly see only the passwords inside the Secret. Another downside to this approach is, that changing any database attribute (hostname, port, ...) requires the generation of a new secret. Also in a practical scenario where a k8s-admin has limited the number of people being able to read content from Secrets it might cause more work to debug connection errors (are we using the right host, the correct port, ...?).

But for now it's okay on my side to create the whole connection string inside the Secret. I will refactor the Helm Chart in a next release.
