### ISSUE TITLE
utm_ tags are considered as unique pages

### ISSUE THREAD

**Issue by prasannamestha** [umami-software/umami#1730]
Hello,
Great job building Umami - I love it. I am using it on my personal blog [prasannamestha.com](https://www.prasannamestha.com) and I noticed that umami considers utm tags and other query params as unique pages. Wouldn't it be better if we not consider query params as unique pages or maybe add a configuration/filter to do the same?

Screenshot:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/24790143/210729523-8d334f89-8a12-4100-aff6-312acdc213d9.png">

Thank you

**Comment by saschwarz** [comment]
I have the same need - FB can assign many different `fbclid`s to an URL and for my reporting I'd like to treat all the URLs the same regardless of query parameters. This would be the opposite of this feature request: https://github.com/umami-software/umami/discussions/619 

One idea would be to add a config parameter to the tracking script to delete query parameters.

**Comment by d19dotca** [comment]
I'd like to see the same too. Having various utm_ tags from things like fbclid treated as their own page is quite annoying for the reports leading to inaccurate reporting IMO. 

Even Umami's own demo page shows many that IMO should be rolled up to the main root page ('/'):

<img width="857" alt="image" src="https://user-images.githubusercontent.com/8153796/214780531-a197d554-798e-45c9-aa9a-5666ff0cd581.png">

**Comment by razinj** [comment]
Same issue here, would be nice if they are grouped with the canonical URL.

<img width="741" alt="screenshot 2023-02-01 at 20 20 01" src="https://user-images.githubusercontent.com/37253974/216141715-dc9cc2ab-d6a1-477e-b98b-2f51f20b0602.png">

**Comment by franciscao633** [comment]
This will be fixed next release. #1790 different issue, but same problematic behavior. The default view will be combined URLs, filtering out the query params. The user can still see the query params in the raw view.

**Comment by mikecao** [comment]
Fixed in v2.0.0.
