### ISSUE TITLE
Unknown Country

### ISSUE THREAD

**Issue by mdestafadilah** [umami-software/umami#1744]
after update latest...

**Comment by EffakT** [comment]
As a quick fix, I had to edit the lib/request.js
`return result?.country?.iso_code;`
becomes
`return result?.registered_country?.iso_code;`

**Comment by mdestafadilah** [comment]
> 

have you done create PR ?

**Comment by EffakT** [comment]
> > 
> 
> have you done create PR ?

No, I haven't had time to create a PR yet, and likely wont until the weekend.

**Comment by mdestafadilah** [comment]
> > > 
> > 
> > 
> > have you done create PR ?
> 
> No, I haven't had time to create a PR yet, and likely wont until the weekend.

ok, waiting just PR from you.
