### ISSUE TITLE
Shareable Link Make Me Login to Dashboard

### ISSUE THREAD

**Issue by mdestafadilah** [umami-software/umami#1748]
![18-01-2023 15-03-25](https://user-images.githubusercontent.com/5575882/213116406-3216bca5-30d1-4a95-bd8d-eabbbccb53af.png)

**Comment by briancao** [comment]
Duplicate of https://github.com/umami-software/umami/issues/1720.  Have it fixed.  We'll be preparing a security release this week.

**Comment by briancao** [comment]
Closing as dupe.
