### ISSUE TITLE
umami container keeps restarting

### ISSUE THREAD

**Issue by AntouanK** [umami-software/umami#1750]
Trying to run umami in a new server, and the umami container keeps restarting with this output : 

![image](https://user-images.githubusercontent.com/4569111/213266401-d1b67cfa-4830-4454-9de3-8f2b1bf27c93.png)

any idea why?

**Comment by erhankaradeniz** [comment]
You could try running the yarn command with the option --cache-folder option as stated in the error.

It could also be an issue with your yarn install, did you install it with sudo? You could also try to sudo chown the folders to the current user, that might fix the error.

**Comment by khromov** [comment]
Which container are you using? Did you build it yourself? I am running the prebuilt `ghcr.io/umami-software/umami:postgresql-v1.39.5` container without any volume mounts and it works fine.
