### ISSUE TITLE
Getting statistics through the api is always 0

### ISSUE THREAD

**Issue by EtcFly** [umami-software/umami#1751]
This is my background data
![image](https://user-images.githubusercontent.com/28503485/213348678-667a3790-e443-4bb0-a17e-da926977d23d.png)

But the data kept returning 0 when accessed through the api(`/api/websites/{id}/stats`), 
```c
url:http://127.0.0.1:3000/api/websites/1/stats?start_at=1350679719687&end_at=1990039038644
header={
    "Access-Control-Allow-Origin": '*',
    "Accept": "application/json",
    "Authorization": "Bearer xxxx"
}
```
reuturn value
```sh
{"pageviews":{"value":0,"change":0},"uniques":{"value":0,"change":0},"bounces":{"value":0,"change":0},"totaltime":{"value":0,"change":0}}
```
please help !

**Comment by briancao** [comment]
Try using the website UUID instead of the PK.

We haven't updated the documentation to reflect those changes accordingly.  We plan on updating after  releasing v2.

**Comment by EtcFly** [comment]
> 尝试使用网站 UUID 而不是 PK。
> 
> 我们尚未更新文档以相应地反映这些更改。我们计划在发布 v2 后进行更新。
Thanks for your reply, but  What does pk mean, Can you give an example? In addition, when can the new document be released

**Comment by EtcFly** [comment]
> Try using the website UUID instead of the PK.
> 
> We haven't updated the documentation to reflect those changes accordingly. We plan on updating after releasing v2.

Thanks for your reply, but  What does pk mean, Can you give an example? In addition, when can the new document be released
