### ISSUE TITLE
Bug: Umani icon leads to blank screen instead of dashboard

### ISSUE THREAD

**Issue by aminahbl** [umami-software/umami#1756]
Clicking on the Umani link leads to https://analytics.umami.is/dashboard and renders a blank page:

![image](https://user-images.githubusercontent.com/74622040/213887304-871107ef-fd59-4eef-8e23-2aeef8bc0723.png)

The URL https://cloud.umami.is/websites does lead to the dashboard.

**Comment by mikecao** [comment]
Fixed in v2.0.0.
