### ISSUE TITLE
Incorrect link opens if same Umami event tracking is added to multiple <a> tags

### ISSUE THREAD

**Issue by Droidion** [umami-software/umami#1762]
- Have server-sided page which renders several html links in a loop.
- Have links like `<a href="https://foo.bar/code" class="umami--click--Foobar"><img ...></a>`, with different codes in link href, but the same class name.
- Observe how regular clicking on any link (in the same tab) will actually open url of the first link.
- Observe how opening link in the new tab works properly.
- Replicated in Safari desktop mobile, also desktop Chrome and Firefox, all latest versions.
- Disabling umami on a page, or disabling javascript, or disabling event tracking fixes the problem.

Expected behaviour:
- If several links have the same event tracked by Umami, link url is not changed.
- OR documentation warns that you cannot attach same event to different links.

**Comment by mikecao** [comment]
Fixed in v2.0.0.
