### ISSUE TITLE
api/websites always 401 

### ISSUE THREAD

**Issue by bboysoulcn** [umami-software/umami#1768]
version: ghcr.io/umami-software/umami:mysql-v1.40.0
db: mysql
reverse proxy: nginx reverse proxy

**Comment by franciscao633** [comment]
Were you able to successfully generate the bearer token and add it to your header?

**Comment by bboysoulcn** [comment]
> Were you able to successfully generate the bearer token and add it to your header?

no

**Comment by franciscao633** [comment]
just follow the steps in the [authentication](https://umami.is/docs/api) section before making calls and the 401 error will resolve.

**Comment by bboysoulcn** [comment]
> just follow the steps in the [authentication](https://umami.is/docs/api) section before making calls and the 401 error will resolve.

not api request

in web ui

**Comment by bboysoulcn** [comment]
> just follow the steps in the [authentication](https://umami.is/docs/api) section before making calls and the 401 error will resolve.

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-owcO/bHLEVFcY7NHxG63zHDgDORpYq7d7agJJhZitvY='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by cocowalla** [comment]
I'm getting the same on the latest version for Postgres. Notably, the Dashboard doesn't work in Firefox, but does work in Chrome.

**Comment by bboysoulcn** [comment]
I'm not sure why the value of my "user_id" field became empty, but it's fixed now after making some modifications.

**Comment by bboysoulcn** [comment]
It could have been caused during one of the updates.
