### ISSUE TITLE
TRACKER_SCRIPT_NAME broken on latest docker

### ISSUE THREAD

**Issue by Samir-Rashid** [umami-software/umami#1769]
tldr: `TRACKER_SCRIPT_NAME: a` breaks login while any other value works.
I tried a few other one letter and longer values which all worked correctly.

I am using the latest `docker-compose.yml` (v1.40.0) and setting the value of `TRACKER_SCRIPT_NAME: a` breaks the entire webpage. The tracker script shows up at website/a.js but you can no longer login. The login page does not submit and the network log shows a request to `/_next/static/chunks/api/collect` is 404ing and returning the 404 page. The container does not log anything abnormal.

**Comment by franciscao633** [comment]
Can't seem to figure this one out. Capitol `A` works, and the lowercase `a` works on the previous docker image version. I will mark as a bug, but please use another value for now. Thanks for reporting.

**Comment by franciscao633** [comment]
Probably won't dig into this any further. Users can just input any other value.
