### ISSUE TITLE
Default date range for a public dashboard.

### ISSUE THREAD

**Issue by 4l1fe** [umami-software/umami#1776]
Hey, i see that if i loggen in i can set the date range up for a session,but as i published a dashboard to let people see the statistics, i would like to demonstrate data within a longer range than 24 hours.

As i understand, at the moment it's not implemented for unlogged in users. Is there a workaround to achieve it?

**Comment by franciscao633** [comment]
When you publish a dashboard, are you referring to the share URL or a different method? Share URL should have a date range dropdown

**Comment by 4l1fe** [comment]
Sure, exactly this dropdown i would like to change a default option in. From `24 hours` to something longer.
