### ISSUE TITLE
migration error on fresh supabase install

### ISSUE THREAD

**Issue by korbal** [umami-software/umami#1782]
Tried to install umami on vercel (from the latest repo) and set up a supabase postgres database, but it just wouldn't work. here are the steps: 

1. forked Umami, cloned, removed Dockerfile, pushed it back to github. 
2. create new Supabase project with the schema copied [from here](https://github.com/umami-software/umami/blob/master/sql/schema.postgresql.sql)
3. set up new project on vercel from github
4. added env variables: postgres://postgres:xxxxxx@db.udndvzvwufaaoytosgbu.supabase.co:6543/postgres?pgbouncer=true and HASH_SALT as well. 
5. Hit deploy

then after some building: 

Error: P3018
16:22:10.245 | A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

not sure what to make of this, read the docs. I cannot roll anything back during deploy. 

then it runs and then throws this error: 

Migration name: 02_add_event_data
16:22:10.246 | Database error code: 42501
16:22:10.246 | Database error:
16:22:10.246 | ERROR: must be owner of table event
and on and on and on

I can see that it created a new table in supabase called _prisma_migrations and two rows  01_init and 02_add_event_data but that is about it. 

I tried to rebuild - no luck. 
I tried to delete the _prisma_migrations table and then rebuild - no luck. 

spent 2 hours on this and I'm not sure what am I doing wrong. Can anyone point me in the right direction? Thank you!

**Comment by franciscao633** [comment]
Hello, the build should automatically generate the db schema for you. I think if you skip the part from step #2 where you manually create the schema, it should work. I would start with a fresh db, add the new env variable to vercel, and deploy. Let me know if you have issues. Also I will update the Supabase docs right now.

**Comment by mvolpato** [comment]
I can confirm that without step 2, the installation continues without errors.

**Comment by baddate** [comment]
Is there any solution? I have the same error :(
btw, i deploy this with my vps(ubuntu20.04) and mariadb.

**Comment by korbal** [comment]
Thank you @franciscao633 and @mvolpato , I can confirm this works! @baddate it's probably the schema.
