### ISSUE TITLE
Feature Request: Last Month and Last Year time ranges

### ISSUE THREAD

**Issue by bernd-wechner** [umami-software/umami#1787]
On the dashboard we have Last 24 hours, and Last 7 Days (which could be Last Week) how about Last Month (~last 30 days actually on the nth day of month M, back to the nth day of Month M-1) and Last Year (~last 365 days, actually on the day day/month back that day last year).

I watch some very low traffic sites and am keen on long term trends and these are missing. We have This Month and This Year, but they are no useful at the start of a month or year ... alas, for seeing a trend over a month or over a year.

If I were to be hopeful I'd also love to see Last Quarter (3 months) and Last Semester (or Half-Year).

**Comment by mikecao** [comment]
These options are really just shortcuts. You can use the custom range option to get whatever date range you want. But I can see how Last Month may be useful to add.

**Comment by bernd-wechner** [comment]
While true, the custom range is a manual endeavour for spot needs and not available as a convenient default setting nor quick UX to select a commonly desired setting. I have mine currently default to this year, which sucks because it's February. The sites I watch are very low traffic, and I'm interested in the annual trend. The last month would be my first zoom in ;-).

**Comment by bernd-wechner** [comment]
Wow, I'd rather this was, implemented than closed. Hate these stale bots in the FOSS world where things simply more slowly because we're all busy on paid work, family and other matters as well as what we can give to FOSS.
