### ISSUE TITLE
Feature request: Comparison View, IP Address Exclusion(s)

### ISSUE THREAD

**Issue by anseltaft** [umami-software/umami#1788]
It would be nice if Umami had a toggle to compare the same time period against the previous year, whether it's 30 days, a full year, or a custom timeframe (as long as it's less than a year of course). I believe the view would need to switch from bars to differently-colored lines though, so it would be easier to delineate between two.

Edited to add: Is there a way to exclude IP addresses? I'm picking up my own traffic as I write articles on my site and it would great to filter out my own activity.

I just started with Umami and I'm digging it! A thank you to Mike and the rest of the contributors for breathing this into life!

**Comment by mikecao** [comment]
Yes, you can use `IGNORE_IP`, see https://umami.is/docs/environment-variables

**Comment by anseltaft** [comment]
Thank you for pointing me in the right direction. I dug further into the docs and spotted the parts about using events - another welcome feature.

For anyone else: the ENV file is used by Docker and if you have Portainer installed you can edit your container and add a new ENV entry then redeploy the Docker container.

**Comment by Pathsis** [comment]
> Thank you for pointing me in the right direction. I dug further into the docs and spotted the parts about using events - another welcome feature.
> 
> For anyone else: the ENV file is used by Docker and if you have Portainer installed you can edit your container and add a new ENV entry then redeploy the Docker container.

hi, @anseltaft 
You might also be able to block umami's js file with your own adblocker for that purpose.
