### ISSUE TITLE
Pages without trailing slash still showing in reports despite canonical URL set on page

### ISSUE THREAD

**Issue by d19dotca** [umami-software/umami#1794]
I have found a strange issuer where a few pages are showing up in the Pages results without a trailing slash (despite trailing slashes still enabled), even when the page in question has a canonical URL set on it. If loading it without the trailing slash in the browser it redirects to the one with the forward slash too. 

Any ideas how this could have happened and how this can be corrected?

<img width="543" alt="image" src="https://user-images.githubusercontent.com/8153796/220840776-0c47f86a-061e-48ae-a064-cbfcdf468f25.png">

**Comment by d19dotca** [comment]
I should add that this is _not_ happening in Matomo/Piwik despite both scripts running together on the site as I evaluate Umami, suggesting this is more of an issue in Umami.

**Comment by mikecao** [comment]
Umami will record whatever the current URL is. Even if your website redirects, the original will still be picked up if the page loads. You can use the variable `REMOVE_TRAILING_SLASH` if you want consistent URLs. See https://umami.is/docs/environment-variables

**Comment by mikecao** [comment]
We can probably add an enhancement to look at the `rel="canonical"` property if one is specified, I'm guessing that is what Matomo is doing.

**Comment by Maxime-J** [comment]
I wouldn't consider it as an enhancement,

**Comment by Maxime-J** [comment]
Sorry for my previous incomplete message.

To add to the discussion, I wouldn't like it by default/not configurable.
Indeed, Canonical URL indicates search engines the page they should consider, but technically these pages don't have the same URLs, and I expect an analytics solutions to log all of them.
Looking at Matomo discussions and testing on my side, that's also their approach.

Weird that you don't see that happening, these views are probably grouped in page titles view but urls should be counted separatly.

**Comment by d19dotca** [comment]
> Indeed, Canonical URL indicates search engines the page they should consider, but technically these pages don't have the same URLs, and I expect an analytics solution to log all of them.

The intention of Canonical URL is to tell robots to look only at that one URL instead, otherwise it leads to duplicates which is exactly what's happening here. 

In my case all the URLs which don't have the forward slash afterwards immediately redirects to the one with the forward slash (as it should). Technically if the analytics solution is logging both then it's duplicating data because it's showing someone hitting /contact and then immediately /contact/ again. It should **not** be logging that first one IMO. 

> Looking at Matomo discussions and testing on my side, that's also their approach.
> 
> Weird that you don't see that happening, these views are probably grouped in page titles view but urls should be counted separatly.

I don't see other solutions doing that, so that's strange. For example looking at the demos on other tools like Plausible or Fathom, I'm not seeing this same behaviour at all. In my Matomo instance I'm not either. If a user hits /contact and then immediately is redirected to /contact/ then Matomo is logging only the second one (as I'd expect it to).
