### ISSUE TITLE
Showing more pageviews but far less unique users than GA

### ISSUE THREAD

**Issue by Fawesum** [umami-software/umami#1798]
When we first installed Umami it was to get around the usual blockers who now defaults to blocking Google Analytics. The first year or so was very promising, showing around 30% more unique users and around 20% more pageviews over GA.

This has now changed. We're still seeing around 20% more pageviews being recorded with Umami, but GA is now showing 20-30% more unique visitors. It's the same when we look at live traffic - Umami is consistently showing 20-30% less than GA. This really does not make any sense to me, as GA should be blocked by a sizeable user group on our site.

Any ideas what could be causing this?

Edit: I have verified that the script is not blocked by most blockers. We're using both COLLECT_API_ENDPOINT and TRACKER_SCRIPT_NAME to bypass the blockers.

**Comment by Fawesum** [comment]
No one having the same issues? I feel like I can't trust the Umami numbers anymore since this started - Umami should be showing far more hits than GA.

**Comment by briancao** [comment]
I ended up answering your question in another thread.

https://github.com/umami-software/umami/discussions/1764#discussioncomment-5324899
