### ISSUE TITLE
Feature: Show events on main dashboard

### ISSUE THREAD

**Issue by korbal** [umami-software/umami#1801]
It would be nice to see the event count on the main dashboard for all  websites. It would give us an indication how things go. Something like this: 

![image](https://user-images.githubusercontent.com/8694537/222054418-a5e5a849-bb01-4ff4-a924-cf94e7c87398.png)

It would be similar to this: https://github.com/umami-software/umami/issues/520 but easier to implement. 

I assume that the event count is stored somewhere, so it is a question of displaying them.

I'd be happy to dig into it and create the feature if there is an interest for it (might do it for myself).

**Comment by franciscao633** [comment]
If there is enough interest and a big enough use-case we can add it. There are some schema changes in 2.0 which will change how you will aggregate events, so I would hold off for now if you wanted to add it for your own instance.
