### ISSUE TITLE
Migrate from source installation (MySQL DB) to docker compose with Postgres

### ISSUE THREAD

**Issue by mihha** [umami-software/umami#1805]
Hi,

I need a suggestion, how can I migrate my Umami installation

In the past, I have installed Umami using source code installation

Because of various reasons, I would like to migrate my existing Umami instance to the Docker compose type of installation, using Postgres DB

Can you please suggest, if possible, how can I migrate the data from my current MySQL DB to the Postgres DB in that case?

Thank you all for your help!

**Comment by franciscao633** [comment]
seems like pgloader is a common solution, however I have not tried it myself. You can docker compose up a postgres instance, then try to migrate the data over via pgloader.

**Comment by mihha** [comment]
Thank you 

I guess that I will have to investigate this. Since Umami supports different DB solutions, I was hoping (honestly) that some internal way of doing this would exist

Maybe some kind of export/import feature could be added to the solution
