### ISSUE TITLE
Dashboard fails to load if collection endpoint uses path element from any of the dashboard routes

### ISSUE THREAD

**Issue by christiannicola** [umami-software/umami#1806]
Hi!

I just stumbled upon this by accident. I installed umami via helm chart on my cluster and noticed that the dashboard was not loading correctly (getting 500 errors from the umami API). At first I tried to downgrade to different versions, but that did not seem to help.

It turned out to be a configuration issue. I set `COLLECT_API_ENDPOINT` to `/metrics`, and when I checked the network traces of the failed requests I noticed that all those requests went to `/api/websites/<website-id>/metrics`. 

After changing the `COLLECT_API_ENDPOINT` to `/trace` the requests went through fine without issues.

Thanks for your hard work! I hope this information is useful to you.

**Comment by franciscao633** [comment]
I think you can also get around the issue by setting it as /api/metrics. Thanks for the info, as it may help others in the future.
