### ISSUE TITLE
Display (or not) umami version in public dashboard

### ISSUE THREAD

**Issue by Lanxor** [umami-software/umami#1810]
Hello,

I've been using umami (v1.40.0) for a few months on my personal blog (a little bit of traffic, but it's still nice to follow the use of my blog). I would like to share a dashboard (which works very well) in public mode, but I observed that the version number of umami used was displayed at the bottom of the dashboard.
This may be a detail for some, but I think that this information could be not displayed.
For example, the Gitea application has a `SHOW_FOOTER_VERSION` variable that allows to hide the version of the application, which could be used by malicious people (https://docs.gitea.io/en-us/config-cheat-sheet/#other-other). Just like you can hide the version of the httpd web server for another example.

I think this could be a good feature to enable/disable as an environment variable.

What do you think about it?

I am not an expert in NodeJs (some knowledge), but if I have time, I can try to see what I can do and propose a PR.

**Comment by franciscao633** [comment]
We will probably keep displaying version without a environment var, but it should be easy enough to implement on your instance of Umami. If you feel its a security issue, you can remove the CURRENT_VERSION from footer.js

**Comment by Lanxor** [comment]
Ok thanks, no worries, I'll see what I can do with my own docker image then :/
