### ISSUE TITLE
[feature] create plugin for Angulartics2

### ISSUE THREAD

**Issue by eliaharm** [umami-software/umami#1814]
Is it possible to create a plugin so that we can use Angulartics2 with umami?
https://github.com/angulartics/angulartics2#supported-providers

I am not an expert, but based on the PRs for other providers in Angulartics2 it looks strait forward to add a new provider from their side if the js script for the analytics creates a compatible object.

**Comment by franciscao633** [comment]
I don't see why not. If this is something you want to take on, feel free to. First time seeing that repo, but it looks cool and we may try to add our plugin down the line.
