### ISSUE TITLE
Exclude query parameters from statistics

### ISSUE THREAD

**Issue by slawiko** [umami-software/umami#1826]
I see multiple query parameters with different values in my statistics (see `fbclid` on the screenshot below)
<img width="1055" alt="Screenshot 2023-03-09 at 09 27 53" src="https://user-images.githubusercontent.com/10272192/223964200-df00d722-9f12-4695-9d51-00835f9a2dd9.png">

Would be awesome to have ability to exclude some query parameters from statistics. This way view will be cleaner and more intuitive.

I'm ready to contribute, but it would be nice to have approval of this idea preliminary

**Comment by mikecao** [comment]
Fixed in v2.

**Comment by cocowalla** [comment]
@mikecao great that this was fixed, but would you mind pointing to the docs, or somewhere else we can find out how to use this please? 🙏

**Comment by EoinGriffin-AI** [comment]
+1 Would love to know how to do this.
Our application modifies the URL frequently to capture some state when the view changes, but umami is capturing an event every time this happens.

**Comment by psifertex** [comment]
Yet another ping asking for how to do this. I have a particular field I'd like to exclude from the statistics.

**Comment by psifertex** [comment]
If anyone found this issue, the answer is that you specify:

`data-exclude-search="true"` in the script tag that loads your umami.js.

However, if you just want to exclude a specific parameter and not turn them all off by default, here's an example you can use by specifying the `data-before-send` parameter and giving it the name of the function, `removeNameParam` in this case:

```js
<script>
    function removeNameParam(type, payload) {
      if (payload.url) {
        try {
          const url = new URL(payload.url, window.location.origin);
          url.searchParams.delete('name');
          payload.url = url.pathname + url.search + url.hash;
        } catch (e) {
          // If URL parsing fails, return payload as-is
        }
      }

      // Also clean referrer if it contains the serial parameter
      if (payload.referrer) {
        try {
          const refUrl = new URL(payload.referrer);
          refUrl.searchParams.delete('name');
          payload.referrer = refUrl.toString();
        } catch (e) {
          // If URL parsing fails, return payload as-is
        }
      }

      return payload;
    }
  </script>
```
