### ISSUE TITLE
Event data doesn't seem to be working with numeric data

### ISSUE THREAD

**Issue by lpalazzi** [umami-software/umami#1830]
I'm trying to use the Event Data in a test environment, and in most cases besides "count" I'm not getting what I'm expecting.

I'm only using one event data so this should be pretty clear what to expect. Here is the data in my `event_data` table:
```
event_data_id  | event_id |               event_data  
---------------+----------+---------------------------------------------------------------
             1 |        1 | {"distance": 12800, "preferPaved": 1, avoidMainRoads": 0}
```

1. Getting the average of a number field always shows 0, even though count shows there is 1 event with that field as expected

![image](https://user-images.githubusercontent.com/33534854/224149831-a503889f-06ea-4af9-969c-f523db4da18b.png)

![image](https://user-images.githubusercontent.com/33534854/224149758-aa52a7ef-0c98-4b72-af7e-252165cba6bc.png)

2. Getting the sum of a number field also doesn't seem to work for me, always showing 0:

![image](https://user-images.githubusercontent.com/33534854/224153766-cc1f676b-8146-41f3-a38a-4688a56e1550.png)

![image](https://user-images.githubusercontent.com/33534854/224153708-d881a873-0670-40f9-9884-b73c7080eeea.png)

Not sure if I'm missing something here, but would appreciate any help. Thanks!

**Comment by turbo2ltr** [comment]
I haven't been able to get anything but count = 0 out of that screen and there are no instructions on how it's supposed to work.

**Comment by franciscao633** [comment]
We are currently rewriting the event data functionality for the app. Storing all the data in a single json column with no restrictions and trying to query and aggregate that data has not been optimal.

**Comment by lpalazzi** [comment]
@franciscao633 That makes sense, thanks for the response. I'll keep my eyes open for when those updates are in.
