### ISSUE TITLE
Build for 3 website but only work for one, what should I do

### ISSUE THREAD

**Issue by rT-Troy** [umami-software/umami#1837]
I build umami for recored 3 website, but only the first getting setup one works, others just record 0. All services was built by docker in same server.

**Comment by franciscao633** [comment]
can you confirm the tracker script is being loaded on the 2 websites that aren't recording and collecting data? You can do this through the network tab by browsing to your websites.

**Comment by screenfluent** [comment]
Tried to add new user and switch, still not working. Added custom domain, nothing. Just first website I've added is working, other not.
