### ISSUE TITLE
Deployment Failed 1.37 to 1.40

### ISSUE THREAD

**Issue by theodorusclarence** [umami-software/umami#1842]
Hi! Thanks for creating umami. I need some help about upgrading from 1.37.0 to 1.40.0

![CleanShot 2023-03-23 at 19 17 05](https://user-images.githubusercontent.com/55318172/227201338-3a9de098-694d-4e01-9b0e-59d410c51cde.png)

I've tried following this https://github.com/umami-software/umami/issues/1393#issuecomment-1214698165, and I got this error from the CLI

```
➜ yarn prisma migrate deploy --schema=./db/postgresql/schema.prisma
4 migrations found in prisma/migrations

Applying migration `02_add_event_data`
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 02_add_event_data

Database error code: 42P07

Database error:
ERROR: relation "event_old_pkey" already exists

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42P07), message: "relation \"event_old_pkey\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("tablecmds.c"), line: Some(3521), routine: Some("RenameRelationInternal") }
```

Is there anything I miss?

Thanks!

**Comment by franciscao633** [comment]
Can you confirm you already have the `_event_old` and `event_data` table already in your schema? If so, we need to skip the 02 migration by marking it applied using the commands below.


yarn prisma migrate resolve --applied "02_add_event_data"
yarn prisma migrate deploy

**Comment by theodorusclarence** [comment]
Awesome, that works. Thank you so much @franciscao633!
