### ISSUE TITLE
JavaScript events not being added

### ISSUE THREAD

**Issue by ctrlbrk42** [umami-software/umami#1847]
v1.40

Automatic pageviews working fine, registering and counting Visitors + Pageviews.

However, this code block under that for registering an Event to track user properties does not work.  Total events registered = 0 per dashboard.

Yes, I am disgusing as download.php but that part works fine.  It's the second script block that isn't working.  The below is for a guest user, but logged in members also not working with just more properties.

![image](https://user-images.githubusercontent.com/1001097/227988365-de9d048b-5325-4d17-80b3-202ec0877cea.png)

```
<script async defer data-website-id="xxxx" data-cache="true" data-auto-track="true" src="https://login.xxxxx/download.php"></script>

  | <script>
  | umami.trackEvent(
  | 'User', {
  | Userid: 0,
  | Username: 'Unregistered',
  | Usergroup: 'Guest'
  | },
  | '/',
  | 'xxxxx');
  | </script>

```

**Comment by briancao** [comment]
Are you saying you're not receiving events at all?  Can you check your events tab to see if events are recording at all?

Similar to the umami.is demo site: https://app.umami.is/share/8rmHaheU/umami.is?view=event

**Comment by ctrlbrk42** [comment]
Thanks for the reply.  I do not have an Event section at all.  It all used to work fine before the 1.37 broke everything.  I changed my code but it just isn't working whether it's API or JS.

![image](https://user-images.githubusercontent.com/1001097/228121275-021dd27a-36e4-4764-a5f0-e3085ee483a8.png)

**Comment by briancao** [comment]
The UI is a bit misleading.  It'll show no events section if no events have been collected.  I imagine your `umami.trackEvent` is throwing a 500 error.  If you can show the server error, we can probably figure it out.

Otherwise, if you can live without events and wait for umami 2.0 (few weeks?), we have a much simpler implementation of how eventData works.  Might be worth just waiting for it.

**Comment by ctrlbrk42** [comment]
I can survive until 2.0 in that case.  Is there a thread somewhere with the planned enhancements of 2.0 for events (or in general)?

I hope to see a longer cutoff threshold for the name/description of the event.

**Comment by mikecao** [comment]
Resolved in v2.
