### ISSUE TITLE
No way to go to the actual link

### ISSUE THREAD

**Issue by psifertex** [umami-software/umami#1856]
From stats there's no easy way to go to the link in question.

It was implemented for referers but not for actual pages. This was requested in #800 (which included a suggested UI even) and the issue was mistakenly closed when it was implemented for refers but the actual issue is still not complete. It was requested to be re-opened but with no response for a week I'm instead filing a separate issue here to track it.  Feel free to close this in favor of re-opening the old issue, just want to make sure it's not missed.

**Comment by franciscao633** [comment]
Going to re-open the issue. and close this one. Makes sense to me.
