### ISSUE TITLE
Suggestion, allow more than one user access to the dashboards

### ISSUE THREAD

**Issue by brunoamaral** [umami-software/umami#1861]
I noticed that in the settings I can change the owner of the website, but didn’t find a way to assign two or more users. Not really important since we can enable share urls, just nice to have. 

(On mobile, in case that’s relevant.)

**Comment by franciscao633** [comment]
We are introducing teams in the next version, which will resolve your scenario. It's currently in our cloud beta if you want to peek at the functionality.
