### ISSUE TITLE
Command failed with signal "SIGSEGV".

### ISSUE THREAD

**Issue by BE-CH** [umami-software/umami#1865]
When running the code on ``arm64`` architecture, it runs for some time - but then it crashes and restarts. 

I get the error ``Command failed with signal "SIGSEGV".``.

Anyone have a direction of why this is happening? 

```
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database tables found.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"

4 migrations found in prisma/migrations


Database schema is up to date!

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
Listening on port 3000
error Command failed with signal "SIGSEGV".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start-server" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Maxime-J** [comment]
Maybe linked to https://github.com/prisma/prisma/issues/18510 ?

**Comment by BE-CH** [comment]
> Maybe linked to [prisma/prisma#18510](https://github.com/prisma/prisma/issues/18510) ?

Yes, definitely related to this!

**Comment by anthonyalayo** [comment]
It looks like the issue only exists after 4.9.0, and right now Umami is on the latest, 4.13.0. Would a downgrade be possible until the bug is closed? I'm also encountering it (after recently setting up the project).

**Comment by franciscao633** [comment]
@anthonyalayo Sorry for the late reply. Will see if we can rollback to 4.9 as this seems to be a persistent issue that hasn't been resolved on the prisma side.

**Comment by anthonyalayo** [comment]
Thanks @franciscao633 ! That would be great. I've been following the prisma chat and I don't think anyone from the prisma team has chimed in yet.

**Comment by anthonyalayo** [comment]
@franciscao633 @mikecao I made a PR, what do you think? It's been over a month and the crashes make ARM unusable at the moment.

**Comment by mikecao** [comment]
@anthonyalayo The latest version is now 4.14. Have your tried seeing if that fixes your issue?

**Comment by anthonyalayo** [comment]
@mikecao there's an active discussion on prisma with new reports of it today yet no responses from the dev team:
https://github.com/prisma/prisma/issues/18510

I think it's safe to say they didn't fix it yet.

**Comment by anthonyalayo** [comment]
Is this project still being maintained?

**Comment by mikecao** [comment]
We are reviewing whether reverting to 4.9 is an option for the next release. If 4.9 works for you, you can simply rebuild with that version for now.

**Comment by ryanccn** [comment]
`linux-musl-arm64` support seems to have only been added in Prisma 4.10?

**Comment by MattsBos** [comment]
I just figured to take a look at the open issue at the Prisma repo and someone just replied this is apparently only happening with this specific combination Node 18 and Prisma 4.10+. Using a different Node version seems to fix this.
Have not tried anything yet for myself, just figured this might be key to fix this issue and update here.

https://github.com/prisma/prisma/issues/18510#issuecomment-1602554403

**Comment by BE-CH** [comment]
@mikecao Maybe we should look at upgrading our Dockerfile to use Node19 or later?

**Comment by BE-CH** [comment]
### WORKAROUND / FIX

I figured out the problem lies in the version of Node the Dockerfile is using! @mikecao 

❌  The ``Dockerfile`` currently uses ``node:18-alpine`` which for some reason results in the SIGSEGV error. 

**✅  Upgrading the ``Dockerfile`` to use ``node:18-slim`` no longer gives any errors.** 

_This results in the image being a little larger (~ 100 MB) but fixes the problem._

**Comment by ShermanQ** [comment]
@BE-CH Thank you, man. By the way, for those who encounter similar problems, we need to create. env with your DATABASE_ URL and DATABASE_ TYPE.
This is my Dockerfile:

# Install dependencies only when needed
FROM node:18-slim AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apt-get update && apt-get install -y libc6-dev
WORKDIR /app
COPY package.json yarn.lock ./
# Add yarn timeout to handle slow CPU when Github Actions
RUN yarn config set network-timeout 300000
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:18-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY docker/middleware.js .
COPY . .

ARG DATABASE_TYPE
ARG BASE_PATH

ENV DATABASE_TYPE $DATABASE_TYPE
ENV BASE_PATH $BASE_PATH

ENV NEXT_TELEMETRY_DISABLED 1

RUN yarn build-docker

# Production image, copy all the files and run next
FROM node:18-slim AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

RUN yarn add npm-run-all dotenv prisma

# You only need to copy next.config.js if you are NOT using the default configuration
COPY --from=builder /app/next.config.js .
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/scripts ./scripts

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["yarn", "start-docker"]

**Comment by Azaeres** [comment]
Per [this comment](https://github.com/prisma/prisma/issues/18510#issuecomment-1660681429), Prisma suffers segmentation faults at Node versions after `18.15`. In my Dockerfile, I got it to run reliably on arm64 using a base image of `node:18.15-slim`.

**Comment by BE-CH** [comment]
Created PR to fix this.  #2182
