### ISSUE TITLE
Diffrent number of online users in dashboard and realtime page

### ISSUE THREAD

**Issue by MiladHossein** [umami-software/umami#1866]
Hi I use 1.40.0 on docker 
I see different number of online user in dash and realtime page for the same site
 
![Screenshot 2023-04-05 at 13-50-39 umami](https://user-images.githubusercontent.com/9536102/230073581-22c3ba3d-1423-4ca3-9725-cc72e4c19cdc.png)
![Screenshot 2023-04-05 at 13-50-11 umami](https://user-images.githubusercontent.com/9536102/230073591-65e6be32-1660-4a48-8a2e-59f343350cbc.png)

**Comment by franciscao633** [comment]
There's a difference in the time ranges when querying for distinct sessions between the two pages. We are actually removing that stat from realtime because its confusing, and this will no longer be an issue.
