### ISSUE TITLE
No way to get custom event data?

### ISSUE THREAD

**Issue by Dawesign** [umami-software/umami#1868]
I successfully tracked an event and added custom data to the payload as described here: https://umami.is/docs/tracker-functions

Now I  wish to retrieve this data via the API but the docs (https://umami.is/docs/api) only document one endpoint to get event data.

Why does `GET /api/websites/{websiteUuid}/events` not return this data?
Why is sending custom event data possible if there is no way to get the data via api nor via the dashboard? 
Am I missing something?

**Comment by franciscao633** [comment]
We use to have a event data modal, where you can aggregate custom event data, but we weren't happy with the implementation and removed it. We needed to completely refactor event data in v2, which will include documentation on how to retrieve via the API.

**Comment by konstantinosftw** [comment]
Hello @franciscao633, is there a guesstimation on when the custom event data will be available on the API? And if there is also a plan to show them to the Umami UI maybe?

I personally rely heavily on event data adding the extra into the event name can get quite chaotic.

**Comment by briancao** [comment]
At a minimum, we're at least 2 weeks away.   It's actively being worked on at this time, amongst other reports.

**Comment by konstantinosftw** [comment]
Great, thank you @briancao. Just to clarify, is this going to affect the API only, or is it being built in the UI also?

**Comment by briancao** [comment]
UI as well.

**Comment by AndreiSoroka** [comment]
@briancao 
> but we weren't happy with the implementation and removed it

Hi
Could you please describe it? what will be changed? And why need to remove the current implementation before the new implementation?
Thanks
