### ISSUE TITLE
add support to sqlite

### ISSUE THREAD

**Issue by alphaleadership** [umami-software/umami#1869]
to store date locally and no less data and data privacy

**Comment by franciscao633** [comment]
We will probably by only officially be supporting mysql / postgres in the near future. There is a bunch of overhead and continuous support in adding db support. Maybe as the team grows.

**Comment by jikkuatwork** [comment]
I too wish this was possible! Especially for small sites and to take this for a spin real quick, this would be much more easy to manage!

**Comment by andupotorac** [comment]
+1

**Comment by jpchavat** [comment]
+1
