### ISSUE TITLE
The project was wrong while building in yarn

### ISSUE THREAD

**Issue by xyhcode** [umami-software/umami#1881]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/64968400/231458537-98d1098b-a894-4380-9c36-ed788dfe48cf.png">
Multiple attempts to delete node_modules to no avail

**Comment by franciscao633** [comment]
Not much is happening in build-geo. Could be a network issue. Does your server have external access to download links? I believe its failing when trying to download the country db from github.

**Comment by xyhcode** [comment]
I'm debugging locally My computer is a Mac m1 pro chip

**Comment by xyhcode** [comment]
> build-geo 中没有发生太多事情。可能是网络问题。您的服务器是否具有下载链接的外部访问权限？我相信它在尝试从 github 下载国家数据库时失败了。

I also get the error in centos 7：
```
error /opt/umami/node_modules/@prisma/engines: Command failed.
Exit code: 1
Command: node scripts/postinstall.js
Arguments: 
Directory: /opt/umami/node_modules/@prisma/engines
Output:
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'read',
```

node:16.18.1
