### ISSUE TITLE
trackEvent ignoring website_id

### ISSUE THREAD

**Issue by ajboni** [umami-software/umami#1882]
Hello!
I'm in version 1.40.0 docker, I have a function with two lines of code

```js
umami.trackEvent(eventName, eventData, url, websiteId);
umami.trackEvent(eventName, eventData, url, website2Id);
```

When called, we get two events but always pointing to the same website, sometimes is the first and sometimes is the second.

On the contrary, doing a trackView works ok:

```js
umami.trackView(url, referrer, websiteId);
umami.trackView(url, referrer, website2Id);
```

If I just run it in the console I get the same behaviour, seems that the website_id is random or the last used (is not the  same as `data-website-id=` in the script tag)

**Comment by ajboni** [comment]
Thanks, it's not working as described for me, but I can  wait for v2!

**Comment by mikecao** [comment]
v2 is now released. Please see docs on how the new tracker functions work, https://umami.is/docs/tracker-functions
