### ISSUE TITLE
About the map

### ISSUE THREAD

**Issue by Mtoly** [umami-software/umami#1884]
Why is Taiwan distinguished from China, Taiwan is a province of China instead of a country
![image](https://user-images.githubusercontent.com/52591084/232195234-f958ee29-cba7-40f1-8595-bbb18716fc2f.png)

**Comment by xyhcode** [comment]
I wonder if anyone is still maintaining this project. centos7 cannot be installed, nor can it be installed locally☹️

**Comment by bluelinden** [comment]
respectfully, this is not the place to discuss that. umami uses an external mapping component and it is not the umami team's responsibility to stay on top of political controversies that are brought to attention by said map. if you'd like to tell someone about it, the library is [react-simple-maps](https://www.npmjs.com/package/react-simple-maps). however, i doubt that they would be interested in hearing complaints about their map unless it is an actual, objective factual inaccuracy. i hope you have a wonderful day.

[Political Status of Taiwan](https://en.wikipedia.org/wiki/Political_status_of_Taiwan)

- blue

**Comment by mikecao** [comment]
Thanks @bluelinden. We get many requests like this and it's always not up to us to decide.
