### ISSUE TITLE
Migrating to 2.0 when deployed using docker_compose?

### ISSUE THREAD

**Issue by saschwarz** [umami-software/umami#1887]
Would it be possible to update the v1 to v2 migration document to describe how to perform the migration if you are using the supplied `docker_compose` file?

**Comment by franciscao633** [comment]
Good idea. Will work on that now.

**Comment by Darmau** [comment]
same needs

**Comment by berti92** [comment]
This worked for me:

- Upgrade to the latest version before v2. Use the tag `mysql-v1.40` or `postgresql-v1.40`
- Go into your running docker container. `docker exec -ti -u 0 umami_umami_1 sh`. Please use your real container name. You can find the name by the output of `docker ps`
- Install git: `apk add git`
- Clone the migration repo: `git clone https://github.com/umami-software/migrate-v1-v2.git` 
- Go into the migration folder: `cd migrate-v1-v2/`
- Please make sure that the ENV variable `DATABASE_URL` is set. Normally this is already configured in the docker-compose.yml. If not, create a .env file just like the original migration guide says.
- Execute `yarn install`
- Execute `yarn build`
- Execute `yarn start`
- That's it. Now you can go out of the container with the command `exit` and follow the normal upgrade guide (`docker-compose down`, change in the docker-compose.yml to the right tag or pull the latest tagt, `docker-compose up -d`)

**Comment by jonaskuske** [comment]
Not directly applicable to Compose, but this is what I used for Docker Swarm (via CapRover), for anyone stumbling over this issue:

```sh
docker service create \
  --name copernicus_migrate_v1_v2 \
  --mode replicated-job \
  --replicas 1 \
  --network captain-overlay-network \
  --env DATABASE_TYPE=postgres \
  --env DATABASE_URL=postgresql://<redacted>/umami \
  --user root \
  --workdir /app \
  --entrypoint="/bin/sh" \
  ghcr.io/umami-software/umami:postgresql-v2.0.0 -c\ 
  "yarn add @umami/migrate-v1-v2 &&\
   cp -r /app/node_modules/@umami/migrate-v1-v2/db/postgresql /app/node_modules/@umami/migrate-v1-v2/prisma &&\
   npx @umami/migrate-v1-v2"
```

**Comment by ariakeumi** [comment]
> 这对我有用：
> 
> * 升级到v2之前的最新版本。使用标签`mysql-v1.40`或`postgresql-v1.40`
> * 进入正在运行的 docker 容器。`docker exec -ti -u 0 umami_umami_1 sh`. 请使用您的真实容器名称。您可以通过以下输出找到名称`docker ps`
> * 安装 git：`apk add git`
> * 克隆迁移仓库：`git clone https://github.com/umami-software/migrate-v1-v2.git`
> * 进入迁移文件夹：`cd migrate-v1-v2/`
> * 请确保`DATABASE_URL`已设置 ENV 变量。通常这已经在 docker-compose.yml 中配置。如果没有，请创建一个 .env 文件，就像原始迁移指南所说的那样。
> * 执行`yarn install`
> * 执行`yarn build`
> * 执行`yarn start`
> * 就是这样。现在你可以使用命令离开容器`exit`并按照正常的升级指南进行操作（`docker-compose down`，将 docker-compose.yml 更改为正确的标签或拉取最新的标签，`docker-compose up -d`）

it's right.

**Comment by ariakeumi** [comment]
> This worked for me:
> 
> * Upgrade to the latest version before v2. Use the tag `mysql-v1.40` or `postgresql-v1.40`
> * Go into your running docker container. `docker exec -ti -u 0 umami_umami_1 sh`. Please use your real container name. You can find the name by the output of `docker ps`
> * Install git: `apk add git`
> * Clone the migration repo: `git clone https://github.com/umami-software/migrate-v1-v2.git`
> * Go into the migration folder: `cd migrate-v1-v2/`
> * Please make sure that the ENV variable `DATABASE_URL` is set. Normally this is already configured in the docker-compose.yml. If not, create a .env file just like the original migration guide says.
> * Execute `yarn install`
> * Execute `yarn build`
> * Execute `yarn start`
> * That's it. Now you can go out of the container with the command `exit` and follow the normal upgrade guide (`docker-compose down`, change in the docker-compose.yml to the right tag or pull the latest tagt, `docker-compose up -d`)

it's right.

**Comment by viriatusX** [comment]
> This worked for me:
> 
> * Upgrade to the latest version before v2. Use the tag `mysql-v1.40` or `postgresql-v1.40`
> * Go into your running docker container. `docker exec -ti -u 0 umami_umami_1 sh`. Please use your real container name. You can find the name by the output of `docker ps`
> * Install git: `apk add git`
> * Clone the migration repo: `git clone https://github.com/umami-software/migrate-v1-v2.git`
> * Go into the migration folder: `cd migrate-v1-v2/`
> * Please make sure that the ENV variable `DATABASE_URL` is set. Normally this is already configured in the docker-compose.yml. If not, create a .env file just like the original migration guide says.
> * Execute `yarn install`
> * Execute `yarn build`
> * Execute `yarn start`
> * That's it. Now you can go out of the container with the command `exit` and follow the normal upgrade guide (`docker-compose down`, change in the docker-compose.yml to the right tag or pull the latest tagt, `docker-compose up -d`)

I got this error when following these steps. Nobody knows what happens.....

![image](https://user-images.githubusercontent.com/64467637/232895330-251cd8fa-6efc-49df-bd13-850ac17b5e70.png)

**Comment by jemus42** [comment]
In my case the migration script ran successfully under `umami:postgresql-v1.40`, but after pulling `umami:postgresql-latest` again I'm just getting a container in a bootloop and this log output:

```
umami-umami-1  | yarn run v1.22.19
umami-umami-1  | $ npm-run-all check-db update-tracker start-server
umami-umami-1  | $ node scripts/check-db.js
umami-umami-1  | ✓ DATABASE_URL is defined.
umami-umami-1  | ✓ Database connection successful.
umami-db-1     | 2023-04-18 22:54:21.211 UTC [45] ERROR:  syntax error at or near "version" at character 18
umami-db-1     | 2023-04-18 22:54:21.211 UTC [45] STATEMENT:  select version() version
umami-umami-1  | ✗
umami-umami-1  | Invalid `prisma.$queryRaw()` invocation:
umami-umami-1  |
umami-umami-1  |
umami-umami-1  | Raw query failed. Code: `42601`. Message: `db error: ERROR: syntax error at or near "version"`
umami-umami-1  | error Command failed with exit code 1.
umami-umami-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami-umami-1  | ERROR: "check-db" exited with 1.
umami-umami-1  | error Command failed with exit code 1.
umami-umami-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami-umami-1 exited with code 1
 ```

Am I missing something?

**Comment by franciscao633** [comment]
On you running on railway by any chance? For some reason it does not like the version check in check-db.js, `select version() as version`. Might need to add an env var to disable version check.

**Comment by mikecao** [comment]
@jemus42 can you try pulling the latest from master? That statement should say `select version() as version`.

**Comment by jibsaramnim** [comment]
Following the steps as described in [the documentation](https://umami.is/docs/migrate-v1-v2) I'm running into the following issue, and I'm not quite sure what to make of it. I did not try to run `prisma generate` as don't _think_ I am supposed to do that, but if I should, please let me know.

```logs
/app # npx @umami/migrate-v1-v2
/app/node_modules/@umami/migrate-v1-v2/node_modules/.prisma/client/index.js:3
    throw new Error(
          ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/app/node_modules/@umami/migrate-v1-v2/node_modules/.prisma/client/index.js:3:11)
    at /app/node_modules/@umami/migrate-v1-v2/index.js:295:12
    at Object.<anonymous> (/app/node_modules/@umami/migrate-v1-v2/index.js:320:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by yumusb** [comment]
```shell
cd umami-dir
git clone https://github.com/umami-software/migrate-v1-v2.git
cd migrate-v1-v2
chmod 777 .
cd ../

# add volumes  for umami service  in  docker-compose.yml 
    depends_on:
      - db
    restart: always
    volumes:
      - ./migrate-v1-v2:/tmp/migr
  db:

# then run migrate in  umami service 
docker-compose exec umami sh 
cd /tmp/migr && yarn install && yarn build && yarn start 
```

Migration of data is over, but there will still be errors. I think this release is not tested enough, others can wait for a while before upgrading to 2.0

**Comment by viriatusX** [comment]
> @viriatusX is your container still running v1.4 and targeting your existing v1 database? If confirmed, check your _prisma_migrations table and make sure the latest v1 migrations have ran. The script is looking for migration `04_add_uuid`

Hi!
Look at the content of the **_prisma_migrations** table.
There is **04_add_uuid** but it gives the following error:

Any solution please?

<img width="1392" alt="Captura de pantalla 2023-04-19 a las 17 04 13" src="https://user-images.githubusercontent.com/64467637/233118204-5c2bf179-7676-4be7-aac9-def81223f834.png">

`A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 04_add_uuid

Database error code: 42701

Database error:
**ERROR: column "account_uuid" of relation "account" already exists**

DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E42701), message: "column \"account_uuid\" of relation \"account\" already exists", detail: None, hint: None, position: None, where_: None, schema: None, table: None, column: None, datatype: None, constraint: None, file: Some("tablecmds.c"), line: Some(6298), routine: Some("check_for_column_name_collision") }

   0: sql_migration_connector::apply_migration::apply_script
           with migration_name="04_add_uuid"
             at migration-engine/connectors/sql-migration-connector/src/apply_migration.rs:105
   1: migration_core::commands::apply_migrations::Applying migration
           with migration_name="04_add_uuid"
             at migration-engine/core/src/commands/apply_migrations.rs:91
   2: migration_core::state::ApplyMigrations
             at migration-engine/core/src/state.rs:186`

**Comment by franciscao633** [comment]
@jibsaramnim can you try running the latest migration? We've made some changes that hopefully resolve the error

`npx @umami/migrate-v1-v2@latest`

**Comment by viriatusX** [comment]
> 2\. npx prisma migrate resolve --applied 04_add_uuid



> Hello @viriatusX,
> 
> Looks like you need to resolve your v1 migrations before trying to switch to v2. Can you confirm your account table already has an account_uuid column? If so try following the steps below.
> 
> 1. Go into your app docker container `docker exec -ti -u 0 <container name> sh`
> 2. Run `npx prisma migrate resolve --applied 04_add_uuid`
> 3. Run `npx @umami/migrate-v1-v2@latest`
> 4. Now you can go out of the container with the command `exit` and follow the normal upgrade guide (`docker-compose down`, change in the docker-compose.yml to the right tag or pull the latest tag, `docker-compose up -d`)

Thanks a lot for your reply..
It's strange.
1. I have account_uuid column. See the image:
<img width="1431" alt="Captura de pantalla 2023-04-19 a las 19 13 22" src="https://user-images.githubusercontent.com/64467637/233150231-6c898060-6891-4773-bf61-5ec3e48ce811.png">

And after executing npx prisma migrate resolve --applied 04_add_uuid **(with error ho you can see)** and the npx @umami/migrate-v1-v2@latest command:

The message changes from **Database v1 tables are not rady for migration** to **Database v1 tables have not been detected.**.....

<img width="630" alt="Captura de pantalla 2023-04-19 a las 19 13 54" src="https://user-images.githubusercontent.com/64467637/233150327-cd2dcde9-1b95-4afb-b1cd-0cf218268061.png">

**Comment by franciscao633** [comment]
try running the resolve command from the root app folder and not the migrate-v1-v2 repo. Let me know if you still get an error.

**Comment by viriatusX** [comment]
> try running the resolve command from the root app folder and not the migrate-v1-v2 repo. Let me know if you still get an error.

The same... :(
<img width="493" alt="Captura de pantalla 2023-04-19 a las 20 38 46" src="https://user-images.githubusercontent.com/64467637/233169393-9a8eccbf-2a03-4db6-a722-d9905a50abcc.png">

**Comment by viriatusX** [comment]
When I execute the npx @umami/migrate-v1-v2@latest command,
if I view the log of the PostgreSQL, it's show these errors:

<img width="892" alt="Captura de pantalla 2023-04-19 a las 20 54 24" src="https://user-images.githubusercontent.com/64467637/233172965-448a03c8-c888-4a1c-a3ea-420043c41eed.png">

**Comment by viriatusX** [comment]
Okay....
Now seems to be updated ok:

<img width="773" alt="Captura de pantalla 2023-04-19 a las 21 08 54" src="https://user-images.githubusercontent.com/64467637/233175999-392ec612-2

But in the PostgreSQL logs:

<img width="1165" alt="Captura de pantalla 2023-04-19 a las 21 10 21" src="https://user-images.githubusercontent.com/64467637/233176250-93680615-0525-492e-a9d7-10e62981f2d2.png">
ef2-428c-8a39-b1f208a65c6b.png">

And the Umami docker container not start with "latest" tag. It's show this error:


<img width="1312" alt="Captura de pantalla 2023-04-19 a las 21 09 49" src="https://user-images.githubusercontent.com/64467637/233176139-659b7fa4-476f-4ef3-8ffe-78e2fad381a8.png">

**Comment by franciscao633** [comment]
You're right there. Thanks for your patience. We made it fix for that, but not sure it's in the latest docker image. Try pulling latest from master. Alternatively, a new image will be made when we cut a release, which will be soon.

**Comment by viriatusX** [comment]
> You're right there. Thanks for your patience. We made it fix for that, but not sure it's in the latest docker image. Try pulling latest from master. Alternatively, a new image will be made when we cut a release, which will be soon.

It is not fixed in the "latest". I am waiting for the update. Hopefully it will be fast, as the Umami service is not working now because of this. Thank you very much 🙏

**Comment by viriatusX** [comment]
More bad news I seem...
I just updated to: docker.umami.dev/umami-software/umami:postgresql-v2.0.1
**(v.2.0.1)**

But the error now is this:
<img width="1312" alt="Captura de pantalla 2023-04-19 a las 23 13 13" src="https://user-images.githubusercontent.com/64467637/233201532-c71aa47f-8a14-428b-a8e6-74bbab1ef12b.png">

**Comment by franciscao633** [comment]
Weird, looks like there was an attempt to run v1 migrations on your v2 db. Go into your prisma_migrations table, delete the 02_event_data failed record and compose up again

**Comment by jibsaramnim** [comment]
> can you try running the latest migration? We've made some changes that hopefully resolve the error

That did the trick, thank you!

**Comment by aaro-n** [comment]
> 



> Hello @viriatusX,
> 
> Looks like you need to resolve your v1 migrations before trying to switch to v2. Can you confirm your account table already has an account_uuid column? If so try following the steps below.
> 
> 1. Go into your app docker container `docker exec -ti -u 0 <container name> sh`
> 2. Run `npx prisma migrate resolve --applied 04_add_uuid`
> 3. Run `npx @umami/migrate-v1-v2@latest`
> 4. Now you can go out of the container with the command `exit` and follow the normal upgrade guide (`docker-compose down`, change in the docker-compose.yml to the right tag or pull the latest tag, `docker-compose up -d`)

If you get an error while running the command, you can run the following command:
`docker-compose run --rm <container name>  npx prisma migrate resolve --applied 04_add_uuid`
`docker-compose run --rm <container name>  npx @umami/migrate-v1-v2@latest`

**Comment by viriatusX** [comment]
> Weird, looks like there was an attempt to run v1 migrations on your v2 db. Go into your prisma_migrations table, delete the 02_event_data failed record and compose up again

If I delete the row "02_event_data" the error is.....

<img width="1186" alt="Captura de pantalla 2023-04-20 a las 17 04 57" src="https://user-images.githubusercontent.com/64467637/233407954-bef4dd39-9054-4a5f-8050-dd0a7879275a.png">

**Comment by franciscao633** [comment]
@viriatusX contact me on the umami discord and I will help you troubleshoot.

**Comment by viriatusX** [comment]
> @viriatusX contact me on the umami discord and I will help you troubleshoot.

Solved!!!!!!!!! Finally!!!!!!!!!!!

With the command: docker-compose run --rm <container_name> yarn prisma migrate resolve --rolled-back "02_add_event_data".

THANKS!!!!!!

**Comment by ddeimeke** [comment]
After doing the migration steps and switching back to master I get the following error message:

```
$ docker-compose up
Creating network "umamigit_default" with the default driver
Creating umamigit_db_1 ... done
Creating umamigit_umami_1 ... done
Attaching to umamigit_db_1, umamigit_umami_1
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2023-04-21 05:30:52.856 UTC [1] FATAL:  database files are incompatible with server
db_1     | 2023-04-21 05:30:52.856 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.2.
umami_1  | yarn run v1.22.19
umamigit_db_1 exited with code 1
umami_1  | $ npm-run-all check-db update-tracker start-server
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2023-04-21 05:30:54.287 UTC [1] FATAL:  database files are incompatible with server
db_1     | 2023-04-21 05:30:54.287 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.2.
umami_1  | $ node scripts/check-db.js
umami_1  | ✓ DATABASE_URL is defined.
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2023-04-21 05:30:55.071 UTC [1] FATAL:  database files are incompatible with server
db_1     | 2023-04-21 05:30:55.071 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.2.
umamigit_db_1 exited with code 1
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2023-04-21 05:30:56.255 UTC [1] FATAL:  database files are incompatible with server
db_1     | 2023-04-21 05:30:56.255 UTC [1] DETAIL:  The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.2.
umamigit_db_1 exited with code 1
umami_1  | ✗ Unable to connect to the database.
umami_1  | error Command failed with exit code 1.
umami_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami_1  | ERROR: "check-db" exited with 1.
umami_1  | error Command failed with exit code 1.
umami_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Furthermore, I am not able to start the database with PostgreSQL 12.

Any ideas?

**Comment by franciscao633** [comment]
@ddeimeke  Can you post your postgresql container logs? Need to troubleshoot why the db doesnt start.

**Comment by ddeimeke** [comment]
@franciscao633 Unfortunately, I do not get more logs than those prefixed with db_1 above.

**Comment by ddeimeke** [comment]
Switched back to an older commit - 43499eb4fd0b1d617f6f052174f1da6f21653892 - and get the following error.

```
$ docker-compose logs --no-color db
Attaching to umamigit_db_1
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2023-04-23 09:15:06.319 UTC [1] LOG:  starting PostgreSQL 12.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
db_1     | 2023-04-23 09:15:06.319 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2023-04-23 09:15:06.319 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2023-04-23 09:15:06.324 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2023-04-23 09:15:06.372 UTC [22] LOG:  database system was shut down at 2023-04-21 05:29:00 UTC
db_1     | 2023-04-23 09:15:06.382 UTC [1] LOG:  database system is ready to accept connections
db_1     | 2023-04-23 09:15:08.418 UTC [31] ERROR:  relation "account" does not exist at character 15
db_1     | 2023-04-23 09:15:08.418 UTC [31] STATEMENT:  select * from account limit 1db_1     | 2023-04-23 09:15:09.198 UTC [32] LOG:  could not receive data from client: Connection reset by peer
db_1     | 2023-04-23 09:15:11.040 UTC [36] ERROR:  relation "account" does not exist at character 15
db_1     | 2023-04-23 09:15:11.040 UTC [36] STATEMENT:  select * from account limit 1
db_1     | 2023-04-23 09:15:11.859 UTC [37] LOG:  could not receive data from client: Connection reset by peer
db_1     | 2023-04-23 09:15:13.674 UTC [41] ERROR:  relation "account" does not exist at character 15db_1     | 2023-04-23 09:15:13.674 UTC [41] STATEMENT:  select * from account limit 1
db_1     | 2023-04-23 09:15:14.462 UTC [42] LOG:  could not receive data from client: Connection reset by peer
db_1     | 2023-04-23 09:15:16.638 UTC [46] ERROR:  relation "account" does not exist at character 15
```

**Comment by franciscao633** [comment]
Sorry my mistake, the errors were already in your previous post.

`The data directory was initialized by PostgreSQL version 12, which is not compatible with this version 15.2.`

Instead of using 15-alpine and you stick with PostgreSQL 12. Alternatively you can try upgrading to 15, but I have not gone through it myself [here](https://www.postgresql.org/docs/current/upgrading.html). If sticking with 12, make sure you switch back to latest umami.

**Comment by ddeimeke** [comment]
@franciscao633 

It seems, we are getting closer, there is still an error left.

Look: `db_1     | 2023-04-25 07:26:21.250 UTC [31] ERROR:  relation "account" does not exist at character 15`

Complete log:

```
$ docker-compose up
Creating network "umamigit_default" with the default driver
Creating umamigit_db_1 ... done
Creating umamigit_umami_1 ... done
Attaching to umamigit_db_1, umamigit_umami_1
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2023-04-25 07:26:18.894 UTC [1] LOG:  starting PostgreSQL 12.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
db_1     | 2023-04-25 07:26:18.894 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2023-04-25 07:26:18.894 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2023-04-25 07:26:18.895 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2023-04-25 07:26:18.922 UTC [22] LOG:  database system was shut down at 2023-04-24 19:05:16 UTC
db_1     | 2023-04-25 07:26:18.934 UTC [1] LOG:  database system is ready to accept connections
umami_1  | yarn run v1.22.19
umami_1  | $ npm-run-all check-db update-tracker start-server
umami_1  | $ node scripts/check-db.js
umami_1  | ✓ DATABASE_URL is defined.
umami_1  | ✓ Database connection successful.
umami_1  | ✓ Database version check successful.
db_1     | 2023-04-25 07:26:21.250 UTC [31] ERROR:  relation "account" does not exist at character 15
db_1     | 2023-04-25 07:26:21.250 UTC [31] STATEMENT:  select * from account limit 1
umami_1  | Error: P3009
umami_1  | 
umami_1  | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
umami_1  | The `02_add_event_data` migration started at 2023-04-21 05:28:49.366150 UTC failed
umami_1  | 
umami_1  | 
umami_1  | ✗ Command failed: prisma migrate deploy
umami_1  | Error: P3009
umami_1  | 
umami_1  | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
umami_1  | The `02_add_event_data` migration started at 2023-04-21 05:28:49.366150 UTC failed
umami_1  | 
umami_1  | 
umami_1  | 
umami_1  | error Command failed with exit code 1.
umami_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami_1  | ERROR: "check-db" exited with 1.
umami_1  | error Command failed with exit code 1.
umami_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by franciscao633** [comment]
Are you able to go into your db container and delete the `02_add_event_data` record(s) in the _prisma_migrations table?
Alternatively in your umami repo you can run the prisma steps below, while your db container is still running. The app container should be stopped due to the error already. 

1. create an `.env` file with DATABASE_URL pointing to your db container.
2. `yarn build-db`
3. `npx prisma migrate resolve --rolled-back 02_add_event_data`

Start your app container making sure its `latest`.

**Comment by ddeimeke** [comment]
Hi @franciscao633 

I am back from vacation and started a new container connecting to the database.

Thar worked well: 

```
/app/umami.git # yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
warning chart.js@4.2.1: The engine "pnpm" appears to be invalid.
[3/4] Linking dependencies...
warning " > next-basics@0.27.0" has incorrect peer dependency "next@^12.3.2".
warning "react-basics > react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "konva@>=2.6".
warning "react-basics > react-spring > @react-spring/konva@9.5.5" has unmet peer dependency "react-konva@^16.8.0 || ^17.0.0".
warning "react-basics > react-spring > @react-spring/native@9.5.5" has unmet peer dependency "react-native@>=0.58".
warning "react-basics > react-spring > @react-spring/three@9.5.5" has unmet peer dependency "@react-three/fiber@>=6.0".
warning "react-basics > react-spring > @react-spring/three@9.5.5" has unmet peer dependency "three@>=0.126".
warning "react-basics > react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "react-zdog@>=1.0".
warning "react-basics > react-spring > @react-spring/zdog@9.5.5" has unmet peer dependency "zdog@>=1.0".
warning " > react-simple-maps@2.3.0" has incorrect peer dependency "react@^16.8.0 || 17.x".
warning " > react-simple-maps@2.3.0" has incorrect peer dependency "react-dom@^16.8.0 || 17.x".
warning " > react-simple-maps@2.3.0" has unmet peer dependency "prop-types@^15.7.2".
warning "react-spring > @react-spring/konva@9.7.1" has unmet peer dependency "konva@>=2.6".
warning "react-spring > @react-spring/konva@9.7.1" has unmet peer dependency "react-konva@^16.8.0 || ^16.8.7-0 || ^16.9.0-0 || ^16.10.1-0 || ^16.12.0-0 || ^16.13.0-0 || ^17.0.0-0 || ^17.0.1-0 || ^17.0.2-0 || ^18.0.0-0".
warning "react-spring > @react-spring/native@9.7.1" has unmet peer dependency "react-native@>=0.58".
warning "react-spring > @react-spring/three@9.7.1" has unmet peer dependency "@react-three/fiber@>=6.0".
warning "react-spring > @react-spring/three@9.7.1" has unmet peer dependency "three@>=0.126".
warning "react-spring > @react-spring/zdog@9.7.1" has unmet peer dependency "react-zdog@>=1.0".
warning "react-spring > @react-spring/zdog@9.7.1" has unmet peer dependency "zdog@>=1.0".
warning " > rollup-plugin-dts@5.3.0" has incorrect peer dependency "rollup@^3.0.0".
warning " > ts-node@10.9.1" has unmet peer dependency "@types/node@*".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
Done in 49.10s.
/app/umami.git # yarn build-db
yarn run v1.22.19
$ npm-run-all copy-db-files build-db-client
$ node scripts/copy-db-files.js
Database type detected: postgresql
Copied /app/umami.git/db/postgresql to /app/umami.git/prisma
$ prisma generate
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.13.0 | library) to ./node_modules/@prisma/client in 254ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
Done in 2.63s.
/app/umami.git # npx prisma migrate resolve --rolled-back 02_add_event_data
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"
Error: P1001: Can't reach database server at `db`:`5432`

Please make sure your database server is running at `db`:`5432`.
npm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.6
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.6.6
npm notice Run npm install -g npm@9.6.6 to update!
npm notice 
```

After starting the original container again, I still get a (different) error:

```
Creating network "umamigit_default" with the default driver
Creating umamigit_db_1 ... done
Creating umamigit_umami_1 ... done
Attaching to umamigit_db_1, umamigit_umami_1
db_1     | 
db_1     | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1     | 
db_1     | 2023-05-07 15:20:19.054 UTC [1] LOG:  starting PostgreSQL 12.14 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
db_1     | 2023-05-07 15:20:19.054 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1     | 2023-05-07 15:20:19.054 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1     | 2023-05-07 15:20:19.072 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1     | 2023-05-07 15:20:19.093 UTC [22] LOG:  database system was shut down at 2023-05-07 15:20:13 UTC
db_1     | 2023-05-07 15:20:19.107 UTC [1] LOG:  database system is ready to accept connections
umami_1  | yarn run v1.22.19
umami_1  | $ npm-run-all check-db update-tracker start-server
umami_1  | $ node scripts/check-db.js
umami_1  | ✓ DATABASE_URL is defined.
umami_1  | ✓ Database connection successful.
umami_1  | ✓ Database version check successful.
db_1     | 2023-05-07 15:20:20.686 UTC [31] ERROR:  relation "account" does not exist at character 15
db_1     | 2023-05-07 15:20:20.686 UTC [31] STATEMENT:  select * from account limit 1
db_1     | 2023-05-07 15:20:21.509 UTC [32] LOG:  could not receive data from client: Connection reset by peer
umami_1  | Error: P3009
umami_1  | 
umami_1  | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
umami_1  | The `02_add_event_data` migration started at 2023-04-21 05:28:49.366150 UTC failed
umami_1  | 
umami_1  | 
umami_1  | ✗ Command failed: prisma migrate deploy
umami_1  | Error: P3009
umami_1  | 
umami_1  | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
umami_1  | The `02_add_event_data` migration started at 2023-04-21 05:28:49.366150 UTC failed
umami_1  | 
umami_1  | 
umami_1  | 
umami_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami_1  | error Command failed with exit code 1.
umami_1  | ERROR: "check-db" exited with 1.
umami_1  | error Command failed with exit code 1.
umami_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami_1  | yarn run v1.22.19
umami_1  | $ npm-run-all check-db update-tracker start-server
umami_1  | $ node scripts/check-db.js
umami_1  | ✓ DATABASE_URL is defined.
umami_1  | ✓ Database connection successful.
umami_1  | ✓ Database version check successful.
```

**Comment by kiprasmel** [comment]
@ddeimeke you're having the same issue i had, see https://github.com/umami-software/umami/issues/1999

**Comment by BartVrancken** [comment]
Hi, in addition to the above Q&A, perhaps this docker-compose could also be helpful to solve the error message migrating from v1 to v2. After setting up the container, I did not need to enter the container terminal. 

version: '3'
services:
  umami:
    container_name: umami
    image: ghcr.io/umami-software/umami:mysql-v1.40
    ports:
      - 3999:3111
    environment:
      DATABASE_URL: mysql://[name_of_mariadb]:[password_of_mariadb]@[IP_address_server]:[port_number_mariadb]/[name_of_mariadb]
      DATABASE_TYPE: mysql
      PORT: 3111
    restart: always


The log of the umami container reads:

```
yarn run v1.22.19

$ npm-run-all check-db update-tracker start-server

$ node scripts/check-db.js

✓ DATABASE_URL is defined.

✓ Database connection successful.

✓ Database tables found.

Prisma schema loaded from prisma/schema.prisma

Datasource "db": MySQL database "umami" at "192.168.1.2:6603"

4 migrations found in prisma/migrations

Database schema is up to date!

✓ Database is up to date.

$ node scripts/update-tracker.js

$ node server.js

Listening on port 3111
```
