### ISSUE TITLE
TRACKER_SCRIPT_NAME is ineffective in version 2.0

### ISSUE THREAD

**Issue by Jonnyan404** [umami-software/umami#1891]
Although I have set the TRACKER_SCRIPT_NAME variable in Docker, it did not take effect.

**Comment by franciscao633** [comment]
This is a bug we redid the middleware, and it got lost. Will add back.

**Comment by mikecao** [comment]
Fixed in v2.0.1.

**Comment by simonwiles** [comment]
Came here looking for this issue, having skipped `2.0.0` and gone straight to `2.0.1` -- `TRACKER_SCRIPT_NAME` still seems to be ignored and `script.js` used regardless?

**Comment by eallion** [comment]
me too

**Comment by Jonnyan404** [comment]
> Fixed in v2.0.1.

Upgrading to v2.0.1 did not take effect.

**Comment by mikecao** [comment]
If you go to `/{TRACKER_SCRIPT_NAME}.js` do you see anything? That's how you tell if it works.

If you're talking about the tracking code form, then yes we don't show the alternate name there.

**Comment by Jonnyan404** [comment]
> If you go to `/{TRACKER_SCRIPT_NAME}.js` do you see anything? That's how you tell if it works.
> 
> If you're talking about the tracking code form, then yes we don't show the alternate name there.

it show 404

**Comment by Jonnyan404** [comment]
> 



> If you go to `/{TRACKER_SCRIPT_NAME}.js` do you see anything? That's how you tell if it works.
> 
> If you're talking about the tracking code form, then yes we don't show the alternate name there.

![image](https://user-images.githubusercontent.com/20352705/233271992-0fcf0b17-b661-4135-881b-8235ec7224b4.png)

**Comment by choque88** [comment]
Not working for me either with 2.0.1. Getting a 404 when trying to access the script under the "alias" defined via TRACKER_SCRIPT_NAME

**Comment by mikecao** [comment]
Think I found the problem. The docker middleware is not appending `.js` to the name.

@Jonnyan404 If you try `/mrdoc` alone it should work.

**Comment by Jonnyan404** [comment]
> Think I found the problem. The docker middleware is not appending `.js` to the name.
> 
> @Jonnyan404 If you try `/mrdoc` alone it should work.

I have tried it, and it does work indeed.

**Comment by RichyHBM** [comment]
> Think I found the problem. The docker middleware is not appending `.js` to the name.
> 
> @Jonnyan404 If you try `/mrdoc` alone it should work.

Can we assume this will remain the case? Or is the plan to change it to add `.js` to the end again?
I have fixed my site by adding .js to the end of the TRACKER_SCRIPT_NAME env, but want to make sure this wont change back to the old behaviour again breaking the current way

**Comment by mikecao** [comment]
It will remain this way. This will give you the option of using either `name` or `name.js` or whatever else you want.

**Comment by shiruken** [comment]
Perhaps the docs should be updated to make it more clear that `TRACKER_SCRIPT_NAME` does not append '.js' to the provided name. The current text makes it seem like it should since that's what happens with script.js.

![image](https://user-images.githubusercontent.com/867617/233456616-0d448ae1-989a-4c73-a625-1807eea02049.png)
