### ISSUE TITLE
Umami Teams Error - Something went Wrong

### ISSUE THREAD

**Issue by mskian** [umami-software/umami#1892]
while opening Teams it end up with Something went Wrong error

![Screenshot from 2023-04-18 11-03-59](https://user-images.githubusercontent.com/10300271/232680774-8318712e-8110-46c0-add0-826482433a34.png)

```sh
http://umami.example.com/api/teams

401 Unauthorized

```

Version: v2.0.0
Database: MYSQL
OS: Ubuntu 
server: nginx as a reverse proxy
running via systemd

**Comment by bboysoulcn** [comment]
the same issues
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha=ZwA='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by bboysoulcn** [comment]
I am using Nginx as a reverse proxy.

**Comment by franciscao633** [comment]
This is fixed in dev, and we will release a hotfix soon. #1893

**Comment by mikecao** [comment]
Fixed in v2.0.1.

**Comment by bboysoulcn** [comment]
v2.0.1 doesn't seem to have fixed this issue.

![iFPjMA.png](https://i.328888.xyz/2023/04/20/iFPjMA.png)
