### ISSUE TITLE
FORCE_SSL doesn't work at runtime

### ISSUE THREAD

**Issue by jonaskuske** [umami-software/umami#1909]
It's documented as a runtime variable but has no effect with the pre-built docker image

**Comment by franciscao633** [comment]
Labelling as bug, we messed up on the env vars, will try to get a hotfix out asap.

**Comment by jonaskuske** [comment]
For anyone finding this, it is fixed by updating the documentation to note that the setting doesn't work at runtime. `FORCE_SSL` remains a build-time env variable. Closing as the fix is live already https://umami.is/docs/environment-variables#:~:text=FORCE_SSL
