### ISSUE TITLE
Charts x-axis labels not localized anymore

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#1913]
On charts, time data labels on x-axis used to be localized.
Previous x labels logic was removed on that change https://github.com/umami-software/umami/commit/c1d3e9ec6757d4f67265486968e4ef1fc0702df9, now those are printed without taking care of the current locale.

By the way, nice to see the v2 release👍🎉 and good luck for dealing with migration issues 💪

**Comment by franciscao633** [comment]
labelling as bug. Always appreciate your help @Maxime-J !
