### ISSUE TITLE
Unable to change password, role Unknown after logout (v2)

### ISSUE THREAD

**Issue by sandroshu** [umami-software/umami#1914]
I am unable to change other users password. No error reported on Save. Can not log in with new password.
After checking the database the update date column still shows the old date (no update).

After logging out then loggin in I loose my admin rights and I become role "Unknown".
Restarting the container solves this issue and I am administrator once again.

This is the container log after server start:
```
$ node server.js
Listening on port 3000 url: http://28344e9f25e6:3000
PrismaClientValidationError: 
Unknown field `teamUser` for include statement on model Team. Did you mean `teamUsers`?
    at ti.validate (/app/node_modules/@prisma/client/runtime/library.js:149:91)
    at Wr.createMessage (/app/node_modules/@prisma/client/runtime/library.js:164:13655)
    at /app/node_modules/@prisma/client/runtime/library.js:174:10933
    at runInChildSpan (/app/node_modules/@prisma/client/runtime/library.js:70:25817)
    at t._executeRequest (/app/node_modules/@prisma/client/runtime/library.js:174:10922) {
  clientVersion: '4.11.0'
```

I've ran the migration script according to instructions from here https://github.com/umami-software/umami/issues/1887 by berti92.

**Comment by franciscao633** [comment]
Theres an issue in the prisma schema file for MySQL causing the temaUser error, which I assume you are using #1893? I'm not sure it's related to the password issue, so I'm going to look into that now.
