### ISSUE TITLE
Error while migrating [Database]

### ISSUE THREAD

**Issue by dhwaj1902** [umami-software/umami#1918]
Got error while Running standalone, the command ``yarn install`` and ``yarn build`` works fine, but got the error in ``yarn start``

```
/home/ubuntu/migrate-v1-v2# yarn start
yarn run v1.22.19
$ node index.js
Running v0.15.0
✓ DATABASE_URL is defined.
✓ Database connection successful.
✗ Database v1 tables have not been detected.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by franciscao633** [comment]
hmmm, did you create an .env file pointing to your v1 database?

**Comment by dhwaj1902** [comment]
Yep!

**Comment by nkilm** [comment]
Hey! I am also facing the same error. Checkout this discussion - #1920

**Comment by franciscao633** [comment]
@dhwaj1902 Can you check your _prisma_migrations table and see if you have a success record for 04_add_uuid. We use this check to make sure the db is in sync before running migrations.
