### ISSUE TITLE
Wrong pageviews

### ISSUE THREAD

**Issue by yumusb** [umami-software/umami#1919]
In this endpoint:

https://domai.com/api/websites/{uuid}/stats?startAt=xxx&endAt=xxx

https://github.com/umami-software/umami/blob/3eabe9b95875e775463988cc2963ee44c92294ae/queries/analytics/stats/getWebsiteStats.ts#L7

You need to specify  `event_type = 1`  in the SQL query to get the correct number of pageviews, otherwise you will get the number of pageviews+events.

**Comment by franciscao633** [comment]
Thanks for reporting! This is fixed in dev and will be release with the hotfix release.

**Comment by mikecao** [comment]
Fixed in v2.0.1.
