### ISSUE TITLE
"Log in" localization

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#1922]
Localization of the login form submit button got lost in v2 update.

Login labels from 1.40 could be restored,
but you went from 'Login' to 'Log in', which changes the translations.

So two choices:
-Bringing back `label.login` translations from 1.40
-Just adding `label.login` and letting everyone do the according translation (to be sure that the translation reflects the original meaning).

I may be picky on that but I prefer to ask.
Can work on a PR if wanted.

**Comment by mikecao** [comment]
I think the first choice would be the right one. A PR would be appreciated.

**Comment by mikecao** [comment]
Fixed in v2.1.0.
