### ISSUE TITLE
Err 404 at /api/collect

### ISSUE THREAD

**Issue by thomasbnt** [umami-software/umami#1924]
Version of Umami : `2.0.1`.

When I load a website like https://mrrobot.app, you can see an error 404 from Umami. 
The CORS on Netlify for this website is setup.

```bash
Request URL: https://umami.thomasbnt.dev/api/collect
Request Method: OPTIONS
Status Code: 404 Not Found
Remote Address: :443
Referrer Policy: strict-origin-when-cross-origin
```

> Access to fetch at 'https://umami.thomasbnt.dev/api/collect' from origin 'https://mrrobot.app' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 
>
> POST https://umami.thomasbnt.dev/api/collect net::ERR_FAILED
>
> Uncaught (in promise) TypeError: Failed to fetch (at umami.js)

**Comment by mikecao** [comment]
The endpoint is no longer called `/api/collect` but instead `/api/send`.

**Comment by jonaskuske** [comment]
The endpoint is `/api/send` now, it's one of the breaking changes: https://umami.is/docs/migrate-v1-v2#:~:text=endpoint%20has%20been%20renamed

The site is probably still using the old tracking script that's configured for the old endpoint. Make sure the new script (now called `script.js` instead of `umami.js`) is loaded and if it is, try adding something like `?v=2` for cache busting

**Comment by thomasbnt** [comment]
Yeah but I didn't changed the endpoint 🤔

**Comment by thomasbnt** [comment]
> The endpoint is `/api/send` now, it's one of the breaking changes: [umami.is/docs/migrate-v1-v2#:~:text=endpoint%20has%20been%20renamed](https://umami.is/docs/migrate-v1-v2#:~:text=endpoint%20has%20been%20renamed)
> 
> The site might still be using the old tracking script that's configured for the old endpoint. Make sure the new script (now called `script.js` instead of `umami.js`) is loaded and if the name didn't change because you're using a custom one, try adding something like `?v=2` for cache busting

I try that

**Comment by thomasbnt** [comment]
With `?v=2` not working. Same error with CORS.

**Comment by thomasbnt** [comment]
Oooooooooh woaw, okay closed ticket 'cause wrong name of the file.
