### ISSUE TITLE
Event data isn't being saved

### ISSUE THREAD

**Issue by shiruken** [umami-software/umami#1928]
After upgrading to v2, event data does not appear to be saving in the `event_data` table. The events themselves are appearing properly in the `website_event` table.

**Comment by franciscao633** [comment]
A pageview is now considered a type of event, so both pageviews / events are stored in `website_event`. You can distinguish the two by the `event_type` column (1 = pageview, 2 = event).  The `event_data` table only stores any dynamic data sent with the event. You can read more on event data at https://umami.is/docs/tracker-functions.

**Comment by franciscao633** [comment]
Are you using the newest method to track events? The v1 method will no longer work.

- The tracker no longer uses CSS class names to trigger events. It now uses HTML data attributes. See [Track events](https://umami.is/docs/track-events) for more information.
- The methods on the global umami Javascript object have changed. There is now a single .track() method and a new way to send event data. See [Tracker functions](https://umami.is/docs/tracker-functions) for more information.

**Comment by shiruken** [comment]
Yes, I have updated my implementation to use both the new HTML data attributes and the .track() method and have confirmed they are appearing properly in the `website_event` table. However, none of the dynamic data associated with the event is being populated into the `event_data` table.

**Comment by MexHigh** [comment]
I also have this problem where event data is only sometimes being stored. Most of the time, not even the event fires. I'm using the `data-umami-event` method.

**Comment by franciscao633** [comment]
@shiruken are you using nested elements like in #1939? Can you give a snippet of a data-attribute in your code?

**Comment by shiruken** [comment]
Actually, I'm only trying to pass event data using the umami.track() method. None of my uses of the new HTML data attribute have additional event data.

**Comment by tmlmt** [comment]
Same stuff here, or more like wondering where the event data is supposed to be shown. In your [Demo dashboard](https://analytics.umami.is/share/LGazGOecbDtaIwDr/umami.is?view=event) I don't see the "Event Data" button which is referred to in the closing comment of #1696. As that been rolled back while you're developing v2 ?

More over, the [doc](https://umami.is/docs/track-events) in the `View Events` section doesn't explain how we're supposed to visualize event data. Thanks in advance for your clarification :)

**Comment by tmlmt** [comment]
Makes sense now. Thanks @franciscao633 for clarifying

**Comment by anthon** [comment]
>Event data visualization has been rolled back temporarily.

@franciscao633, thanks for clarifying. Any info regarding when this might be re-implemented? Is there a public roadmap somewhere?

Thanks for any hints!

**Comment by konstantinosftw** [comment]
Hey @anthon, the feature is a few weeks away according to [this answer](https://github.com/umami-software/umami/issues/1868#issuecomment-1553603640).
