### ISSUE TITLE
Users: Edit not working && button not showing correctly

### ISSUE THREAD

**Issue by sebiweise** [umami-software/umami#1929]
Hey guys,
after the v2 update the edit button in the users page is not showing correctly also the edit isn´t working, I cannot change users.
![image](https://user-images.githubusercontent.com/22999200/233270610-122ca9c9-7eb3-4517-957d-18991abb3438.png)
Every other edit button is displaying fine so far.

**Comment by franciscao633** [comment]
Confirmed and labelling as a bug. 

1. Need to fix the css for the UsersTable to account for all languages. 
2. Also need to fix the save for editing user password. It seems like changing the Username / Role works.

**Comment by sebiweise** [comment]
Yes I can confirm that changing the username and/or role is working fine. Also deleting a user is working fine.

**Comment by mikecao** [comment]
Fixed in v2.1.0.
