### ISSUE TITLE
Sending page views via API

### ISSUE THREAD

**Issue by cocowalla** [umami-software/umami#1933]
I'm on Umami v1.40.0, and looked at upgrading to v2.0.0. However, the v1.x API included `POST /api/collect`, which could be used to send both page views AND events. In v2.x this endpoint is now `POST /api/send`, but the docs say:

> type: (string) event is currently the only type available

I took a look at the code, and it looks like it's now not possible to send page view events using the API - have I misunderstood this, or is it planned to add back the ability to do this?

My use case is logging page views from the server-side.

**Comment by franciscao633** [comment]
So, a pageview is now a type of event, so what your seeing in the documentation is how to send a pageview. We have not fully documented sending an event, but if you add the `name` parameter to the payload, the record will change the `event_type` from pageview to event.

**Comment by cocowalla** [comment]
I'm relieved it's still an option 😅 

Is it still possible to send data with events too?

**Comment by franciscao633** [comment]
Yea you can send a payload with the `name` and `data` parameter like below.
![image](https://user-images.githubusercontent.com/31608805/233448939-1e96da51-e25d-4095-9617-d299fabe29bc.png)

**Comment by mikecao** [comment]
Docs have been updated for the latest release, https://umami.is/docs/tracker-functions

**Comment by tmlmt** [comment]
Hey guys, just for the sake of clarity, with the API and `type: 'event'`:
- omitting `name` in the payload will consider the payload as pageview
- setting a `name` will consider the payload as a event named `name`
Is that correct?

It'd be great to add a few more words in [this doc page](https://umami.is/docs/sending-stats) too.

**Comment by franciscao633** [comment]
That is all correct. We will update the docs to clarify.

**Comment by tmlmt** [comment]
Thanks @franciscao633 for confirming.
