### ISSUE TITLE
Event tracking: Clicks on a-Tags with multiple-nested elements sometimes fail

### ISSUE THREAD

**Issue by MexHigh** [umami-software/umami#1939]
When having HTML like below, the click listener ([registered here](https://github.com/umami-software/umami/blob/master/tracker/index.js#L146)) only tries to determine, if the clicked target itself or its parent element is an `<a>` element. In the example below, this is not sufficient, if the click target is the inner `<span>` or `<i>`element, for example.

```html
<a class="button is-outlined" 
    href="https://example.com"
    target="_blank" rel="noopener"
    data-umami-event="some event"
    data-umami-event-articleurl="some-article"
    data-umami-event-articlename="/some-article.html"
>
    <span class="icon-text">
        <span class="icon">
            <i class="fas fa-solid fa-envelope"></i>
        </span>
        <span>Send to example.com</span>
    </span>
</a>
```

In this case, the click event will not be recorded.

Might be related to: #1928

I'm going to open a MR soon, I'm already having a fix for this.

**Comment by mikecao** [comment]
Fixed in v2.1.0.
