### ISSUE TITLE
CORS issue since v2

### ISSUE THREAD

**Issue by marc-on-github** [umami-software/umami#1952]
Access to fetch at 'https://analytics.xx.com/api/send' from origin 'https://xx.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by mikecao** [comment]
Nothing has changed on the CORS end of things and we are running the same codebase in production. Is it possible you have something else sending different headers?

**Comment by mauricerenck** [comment]
I do have the same issue and was wondering because I didn't change anything. What I saw then, is that I get an error 503 which results in this CORS message (in firefox). Maybe have a look if that is happening with your setup, too. That cors message may be confusing. 

In general umami keeps crashing as soon as a request is sent from a website. 
```
error Command failed with signal "SIGKILL".
ERROR: "start-server" exited with 1.
error Command failed with exit code 1.
```

I run this on a koyeb instance. This keeps happening with new and old migrated mysql databases. Maybe have a look in your logs, to see if something similar is happening. Unfortunately I have to say, I am not able to get umami up and running with the v2 update - at least on koyeb.

**Comment by jazerix** [comment]
I am experiencing the same in my instance. It worked fine before migration. Service is running as it should, and Umami is reporting no errors in the cli.

**Comment by mauricerenck** [comment]
> I am experiencing the same in my instance. It worked fine before migration. Service is running as it should, and Umami is reporting no errors in the cli.

I had to upgrade the machine to micro, after that it's working fine. Running not from docker but directly from the repo showed a nextjs error saying it needs more RAM.

**Comment by marc-on-github** [comment]
Okay for me, the error was that I was still on Node version 14. After the Update to Node 16 everything works again.

**Comment by BradNut** [comment]
> Nothing has changed on the CORS end of things and we are running the same codebase in production. Is it possible you have something else sending different headers?

I had the same issue described in this bug and, like @marc-on-github, upsetting from Node version 14 to 16 allowed everything to work correctly without CORS issues. This is on Vercel for me.

Maybe the minimum Node version requirements differ on different platform deployed?

**Comment by RamaHerbin** [comment]
Hello everyone, 
I have a similar issue when I post login credential to the /api/auth/login endpoint.

I request from my front-end on localhost:3000 to umami on localhost:8080

The request works fine in Postman.
What am I doing wrong ?

```javascript
  fetch("http://localhost:8080/api/auth/login", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      'Accept': '*/*',
      "Access-Control-Allow-Headers": "*",
      "Access-Control-Allow-Methods": "*",
      "Access-Control-Allow-Origin": "*",
    },
    body: JSON.stringify(formState),
  })
```

![Screenshot 2023-04-28 at 13 59 16](https://user-images.githubusercontent.com/41597427/235141917-a433db80-3ed3-4f73-9377-385fc62276dd.jpg)

**Comment by mdestafadilah** [comment]
same here, i'm using v2 with node v18. now cors has issued.
