### ISSUE TITLE
User role unknown after login v2

### ISSUE THREAD

**Issue by t3brightside** [umami-software/umami#1954]
After logging in user role is "unknown". If reloading while logged in user role is set correct (Administrator / User)

**Comment by franciscao633** [comment]
Were you able to catch the error? I'm trying to recreate the scenario, but so far I am unsuccessful.

**Comment by t3brightside** [comment]
Ok, let's see...in Chrome and Opera there's nothing on the console really.
In Firefox I get on loading the login window or any pages after login:
"Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). [content.js:142:48]"

But issue is present in all browsers, user role turns from Unknown to Administrator as soon as I reload the whole thing after login.

Any ideas how to debug further?

**Comment by franciscao633** [comment]
Thanks for helping to debug! We will continue to look into it. For whatever reason the user role isn't getting passed on initial login.

**Comment by franciscao633** [comment]
fixed in v2.3.0
