### ISSUE TITLE
Database timeout after upgrading to version 2.x

### ISSUE THREAD

**Issue by weijarz** [umami-software/umami#1957]
After upgrading to version 2.x, the database often times out.
Once the timeout occurs, the umami node-js process will simply exit.
I installed it on a low disk performance HDD VPS, which may have caused this problem to become more pronounced.
In version 1.x this problem seems is not obvious.

```
Apr 21 23:46:49 s2 npm[3086140]: PrismaClientKnownRequestError:
Apr 21 23:46:49 s2 npm[3086140]: Invalid `prisma.user.findFirst()` invocation:
Apr 21 23:46:49 s2 npm[3086140]: Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/co>
Apr 21 23:46:49 s2 npm[3086140]:     at pn.handleRequestError (/root/umami/node_modules/@prisma/client/runtime/library.js:176>
Apr 21 23:46:49 s2 npm[3086140]:     at pn.handleAndLogRequestError (/root/umami/node_modules/@prisma/client/runtime/library.>
Apr 21 23:46:49 s2 npm[3086140]:     at pn.request (/root/umami/node_modules/@prisma/client/runtime/library.js:176:5786)
Apr 21 23:46:49 s2 npm[3086140]:     at async t._request (/root/umami/node_modules/@prisma/client/runtime/library.js:179:1048>
Apr 21 23:46:49 s2 npm[3086140]:     at async /root/umami/.next/server/chunks/3972.js:177:16 {
Apr 21 23:46:49 s2 npm[3086140]:   code: 'P2024',
Apr 21 23:46:49 s2 npm[3086140]:   clientVersion: '4.13.0',
Apr 21 23:46:49 s2 npm[3086140]:   meta: { connection_limit: 5, timeout: 10 }
Apr 21 23:46:49 s2 npm[3086140]: }
```

**Comment by mikecao** [comment]
Both Prisma and Next have been upgraded since v1, so it's possible they are more resource intensive. You can also try limiting the total database connections. See https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/connection-pool

**Comment by weijarz** [comment]
Thank you. 
Problem resolved after append '?connection_limit=10&pool_timeout=60' to my 'DATABASE_URL' environment variable

**Comment by JorisKok** [comment]
Thanks! This solved the issue for me as well. I was running it on AWS elastic beanstalk and kept getting random 502 error messages. I added the connection limit directly to my docker-compose.yml 
`DATABASE_URL: postgresql://umami:umami@db:5432/umami?connection_limit=10&pool_timeout=60`
