### ISSUE TITLE
Umami not collecting data

### ISSUE THREAD

**Issue by Sevenyine** [umami-software/umami#1959]
Umami is not collecting data after migration from v1 to v2.
Both realtime and dashboard are not showing new visitors.
Environment: Vercel deployment + MySQL
script is correctly downloaded and configured in HTML
![image](https://user-images.githubusercontent.com/65720409/233761385-d9dd2aae-9c70-4598-9062-d30ba9344eef.png)
![image](https://user-images.githubusercontent.com/65720409/233761404-d2ea6e24-9aae-4f24-9c16-dc7ef5900150.png)
![image](https://user-images.githubusercontent.com/65720409/233761945-20851b4d-b4c4-43c4-936e-e9e98b75f8aa.png)
![image](https://user-images.githubusercontent.com/65720409/233761905-51d81b10-ad5b-476e-92e9-4f4983819434.png)
![image](https://user-images.githubusercontent.com/65720409/233761326-a7f67009-de8f-4fdc-8e25-a0472826e3b8.png)

**Comment by mikecao** [comment]
What does the network tab under developer tools say? There should be an entry for /api/send.

**Comment by Sevenyine** [comment]
> What does the network tab under developer tools say? There should be an entry for /api/send.

![image](https://user-images.githubusercontent.com/65720409/233778922-ea360d47-de2b-4ab1-aa8c-2894338b26ef.png)

![image](https://user-images.githubusercontent.com/65720409/233779017-550cf52e-7623-4631-9509-5236942d874e.png)

**Comment by Sevenyine** [comment]
The latest version solved that problem. Thank you.
