### ISSUE TITLE
Use IPv6 to visit the website, umami can count the country where the visitor is located, but there is no specific city.

### ISSUE THREAD

**Issue by aaro-n** [umami-software/umami#1962]
# Operating 
environment introduction: Docker running, umami version v2.1.0, database: Supabase cloud
# Problem Description
According to umami statistics, there are 6 visitors, and these 6 visitors are all in the same country. When checking the specific visitors, only 1 visitor shows the specific city, and the other 5 visitors disappeared, and then passed the mobile network test (mobile phone The network has IPV6), when the visitor visits through IPV4, it can be counted to the specific city, and when it is accessed through IPV6, it can only be counted to the country where it is located.
# other problems
The visitor area is divided into countries, provinces, and specific cities. There are too many levels. I want to quickly see the area where the visitor is located.
Also, since the specific cities of visitors can be displayed, can the map show how many visitors there are in each province? Now it only shows the country in general.

**Comment by franciscao633** [comment]
We use MaxMind's GeoLite2-City.mmdb, which looks like it may not always have a city or region for IPV6. We recently added regions / cities data, so you can have a more granular level of where your visitors are coming from and to be able to filter on those as well. The map in v1 was only connected to countries and still is in v2.

**Comment by aaro-n** [comment]
Ok, I've now turned off IPv6 access.
