### ISSUE TITLE
Error creating UUID,

### ISSUE THREAD

**Issue by elit1234** [umami-software/umami#1964]
Hi there, when running the default docker-compose I get the following error inside the umami app:

> umami_1  | Prisma schema loaded from prisma/schema.prisma
> umami_1  | Datasource "db": PostgreSQL database "umami", schema "public" at "db:5432"
> umami_1  |
> umami_1  | 1 migration found in prisma/migrations
> umami_1  |
> umami_1  | Applying migration `01_init`
> umami_1  |
> umami_1  | The following migration have been applied:
> umami_1  |
> umami_1  | migrations/
> umami_1  |   └─ 01_init/
> umami_1  |     └─ migration.sql
> umami_1  |
> umami_1  | All migrations have been successfully applied.
> umami_1  |
> umami_1  | ✓ Database is up to date.
> umami_1  | $ node scripts/update-tracker.js
> umami_1  | $ node server.js
> umami_1  | Listening on port 3000 url: http://dddf4ef6cb75:3000
> umami_1  | PrismaClientKnownRequestError:
> umami_1  | Invalid `prisma.website.findUnique()` invocation:
> umami_1  |
> umami_1  |
> umami_1  | Inconsistent column data: Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `u` at 1
> umami_1  |     at pn.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:6477)
> umami_1  |     at pn.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:176:5907)
> umami_1  |     at pn.request (/app/node_modules/@prisma/client/runtime/library.js:176:5786)
> umami_1  |     at async t._request (/app/node_modules/@prisma/client/runtime/library.js:179:10484)
> umami_1  |     at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/websites/[id].js:154:25)
> umami_1  |     at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:372:9)
> umami_1  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:514:9)
> umami_1  |     at async Object.fn (/app/node_modules/next/dist/server/next-server.js:828:35)
> umami_1  |     at async Router.execute (/app/node_modules/next/dist/server/router.js:243:32)
> umami_1  |     at async NextNodeServer.runImpl (/app/node_modules/next/dist/server/base-server.js:432:29) {
> umami_1  |   code: 'P2023',
> umami_1  |   clientVersion: '4.13.0',
> umami_1  |   meta: {
> umami_1  |     message: 'Error creating UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-zA-Z], found `u` at 1'
> umami_1  |   }
> umami_1  | }

This is after setting up the project, and adding a site. After I start doing some things on the site that are trackable, it just fails?

I am using Remix.js, and it is loading the script.js file fine.

**Comment by franciscao633** [comment]
So you were able to create a website, insert the tracking code, but you get errors on collect? Can you check your session / website_event table and seeing if there's data? I'm wondering where its failing to create the UUID.
