### ISSUE TITLE
v2 track events with CSS classes

### ISSUE THREAD

**Issue by wheeleran** [umami-software/umami#1965]
Is there any particular reason why this simple and straightforward method of tracking events has been removed in v2? Is this temporary? Not only would i have to go back into many, many sites and redo all my event codes, but i'd have to write a bunch of js for sites that don't use data attributes. not looking forward to it.

**Comment by mikecao** [comment]
The reason we changed was because data attributes allow you set arbitrary values, whereas CSS classes had to follow CSS variable naming rules.

**Comment by IncalSchorsch** [comment]
I understand the reason for the change to data attributes, but I had the same problem as @wheeleran.
Further, my Wordpress theme does well support the custom css-classes everywhere, but does not support the adding of data attributes.

#### I came up with following solution, to migrate my umami css class event tracking from v1 to v2.

This script has been added to the footer! section of my pages:
```
<script> 
document.querySelectorAll("[class*='umami--click']").forEach((element, index) => {
	element.onclick = (event) => {
	umami.track('Click' + index + ': ' + event.target.innerText); 
//	console.log('Click' + index + ': ' + event.target.innerText);	// for debugging
	}
}) 
</script>
```

- The script watches all my existing `umami--click--xxxxxxxxx` classes
- At click, the script calls `umami.track()` to send the information I need. In my case I want to see the innerText and the index (if two elements on a page have same innerText).
- I used the console.log line only for debugging

**Comment by wheeleran** [comment]
Oh now THIS is cool!!
