### ISSUE TITLE
Cannot find module 'dns/promises'

### ISSUE THREAD

**Issue by slycat34** [umami-software/umami#1967]
Recent build, using node 14.21 & yarn 1.22. Cloned, installed, build just fine. Database built as expected using mariadb/mysql. Umami starts fine but when the script is queried from a website I get the following output from stdout
```
Error: Cannot find module 'dns/promises'
Require stack:
- /var/www/umami/.next/server/pages/api/send.js
- /var/www/umami/node_modules/next/dist/server/next-server.js
- /var/www/umami/node_modules/next/dist/server/next.js
- /var/www/umami/node_modules/next/dist/server/lib/start-server.js
- /var/www/umami/node_modules/next/dist/cli/next-start.js
- /var/www/umami/node_modules/next/dist/lib/commands.js
- /var/www/umami/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.mod._resolveFilename (/var/www/umami/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.6003 (/var/www/umami/.next/server/pages/api/send.js:137:18)
    at __webpack_require__ (/var/www/umami/.next/server/webpack-api-runtime.js:25:42)
    at /var/www/umami/.next/server/pages/api/send.js:165:70
    at Function.__webpack_require__.a (/var/www/umami/.next/server/webpack-api-runtime.js:89:13)
    at Object.4181 (/var/www/umami/.next/server/pages/api/send.js:151:21) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/www/umami/.next/server/pages/api/send.js',
    '/var/www/umami/node_modules/next/dist/server/next-server.js',
    '/var/www/umami/node_modules/next/dist/server/next.js',
    '/var/www/umami/node_modules/next/dist/server/lib/start-server.js',
    '/var/www/umami/node_modules/next/dist/cli/next-start.js',
    '/var/www/umami/node_modules/next/dist/lib/commands.js',
    '/var/www/umami/node_modules/next/dist/bin/next'
  ]
}
```

Checked yarn log, saw some unmet dependencies were there so I installed those then rebuilt. Same error.  yarn now only shows "incorrect dependencies" which I believe is a package.json error. Git was pulled today.

**Comment by Deerzen** [comment]
I have the exact same issue after updating today. As slycat34 pointed the problem lies at /var/www/umami/.next/server/pages/api/send.js:151:21 - more specifically dns_promises__WEBPACK_IMPORTED_MODULE_7__ . Repeating "yarn install" and "yarn build" did not solve the issue for me either.

**Comment by mikecao** [comment]
Try upgrading your Node to a higher version.

**Comment by slycat34** [comment]
Distro package manager is severely outdated, running on node 20.x resolves dns/promise issue

**Comment by gamedevsam** [comment]
@mikecao I also ran into this, it should be noted in the migration instructions (and in the README) that the minimum supported node version changed.

**Comment by mdestafadilah** [comment]
> Try upgrading your Node to a higher version.

it's not work. i have installed with node v18.16.0 (latest) Error: Cannot find module 'dns/promises'
