### ISSUE TITLE
Website is broken on Firefox

### ISSUE THREAD

**Issue by candideu** [umami-software/umami#1968]
Hi there! For the past week or so, the Umami website has been broken on Firefox, both on mobile and desktop.

![image](https://user-images.githubusercontent.com/55474996/233799231-0a50e48d-ede7-4b58-9c34-33f50e558875.png)

The site looks fine on Vivaldi:

![image](https://user-images.githubusercontent.com/55474996/233799262-cbdedca2-6041-42ca-a15b-c848d38e59a2.png)

**Comment by mikecao** [comment]
It looks like you have an ad blocker or something blocking the CSS file.

**Comment by candideu** [comment]
You're right, AdGuard is blocking umami's CSS. Weird, because this is the first website this has happened with...

![image](https://user-images.githubusercontent.com/55474996/234738989-1d880c1d-7582-4f80-b08d-dd5ece4cbbc5.png)
