### ISSUE TITLE
Error: Client Side Exception after setting data view to all time

### ISSUE THREAD

**Issue by m4xr1s** [umami-software/umami#1976]
I am getting this client-side exception since setting the default view to all time on the profile settings page.
The error occurs on the main page and on the profile page.
The cause can be seen in the browser console.

_running 2.1.0 in docker with postgres_

![image](https://user-images.githubusercontent.com/22116677/233845406-363efd74-b998-418a-9c23-04729b1b0eb6.png)

**Comment by franciscao633** [comment]
I was able to reproduce this bug. Only way to get past it was clearing my browser history.
