### ISSUE TITLE
Loading tracking script on website triggers "Uncaught TypeError".

### ISSUE THREAD

**Issue by KiaArmani** [umami-software/umami#1978]
Greetings,

I am currently experiencing an issue where one website, and only that one, is no longer tracking views since upgrading to V2.
I embed the script as followed:

`<script defer src="https://DOMAIN.TLD/CUSTOMNAME.js" data-website-id="GUID_HERE"></script>`

but the console shows this error when loading the page:

`Uncaught TypeError: MutationObserver.observe: Argument 1 is not an object.`

Please let me know if you require further information to resolve this bug.

Sincerely,
Kia

**Comment by mikecao** [comment]
It's probably because that website doesn't have a page title. There was a bug in the script that didn't handle that case, but it should be resolved in the latest version.

**Comment by KiaArmani** [comment]
I have deployed v2.1.0 and the issue still persists.
