### ISSUE TITLE
Missed the v1 to v2 announcement and now docker container constantly reboots so I can't migrate the DB

### ISSUE THREAD

**Issue by anseltaft** [umami-software/umami#1985]
The Umami dashboard alerted me to the fact that a new version was out so I followed the update instructions on [this page](https://umami.is/docs/updates). I might suggest a notice there, to alert people to perform a v1 to v2 migration so they don't find themselves in the same predicament as I do...

After the update I see in Portainer that my umami container is keeps restarting:

```
umami     | yarn run v1.22.19
umami     | $ npm-run-all check-db update-tracker start-server
umami     | $ node scripts/check-db.js
umami     | ✓ DATABASE_URL is defined.
umami     | ✓ Database connection successful.
umami     | ✓ Database version check successful.
umami     | ✗ Umami v1 tables detected. For how to upgrade from v1 to v2 go to https://umami.is/docs/migrate-v1-v2.
umami     | error Command failed with exit code 1.
umami     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami     | ERROR: "check-db" exited with 1.
umami     | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami     | error Command failed with exit code 1.
umami exited with code 1
```

I wonder what steps I should take to correct the situation? I can't keep the container running long enough for a migration, so is there a way to revert to the last v1 image? Sorry for my ignorance, I've only used Docker for about 2 months and still a little green.

Cheers

**Comment by franciscao633** [comment]
For docker upgrades, instead of using the `latest` image stay on `1.4`.  You can refer to [this post](https://github.com/umami-software/umami/issues/1887#issuecomment-1512915162) on how to upgrade from v1 to v2.
