### ISSUE TITLE
V2 migration broke my site!

### ISSUE THREAD

**Issue by ismetbalat** [umami-software/umami#1986]
Hi, I have migrated from v1 to v2. After migration, I couldn't login with current user and I run reset-password script on console. Now, I can login but umami is not working and console give 500 error. Because no website id in request url. How can I fix it?

![image](https://user-images.githubusercontent.com/12069482/234198361-901505ec-8166-4316-8d4e-6898aed64307.png)

Also I checked the user table. Why no any user_id column in user table? How it bind website with user?

![image](https://user-images.githubusercontent.com/12069482/234224980-24e7ee1d-e57b-441f-8cd3-18303e55032c.png)

my latest umami db tables are below:

![image](https://user-images.githubusercontent.com/12069482/234234505-157378b3-d2ee-4ff2-95f0-2398dbaf1ff8.png)

**Comment by franciscao633** [comment]
If you can login, your user table is correct. Try adding a schema to you user query like `select * from public.user`. If that doesnt work try wrapping `user` in quotes. `user` is treated as a function (without parentheses) and is synonymous to the current_user function.

For the actual issue, that websites API call does not look correct, do you have custom code?  We do not have a `enabled` parameter. You can refer to the docs [here](https://umami.is/docs/websites-api).
