### ISSUE TITLE
See all pages in Settings as an Administrator in v2?

### ISSUE THREAD

**Issue by t3brightside** [umami-software/umami#1987]
I think in v1 I saw all the pages in the system in "Settings/Websites" section if logged in as an Administrator. Those as well that belonged to other users.
Now in v2 I only see those registered by that certain Administrator user and none other.

Is this intentional? Or is something up with my v2 install?

**Comment by mikecao** [comment]
You should see this if you are admin:
![image](https://user-images.githubusercontent.com/477975/234478112-a569079b-822c-428b-b5c6-fa8c48f22d00.png)

**Comment by t3brightside** [comment]
Ah, ok, found it now, thanks!
