### ISSUE TITLE
Feature - Realtime link to dashboard and detail view?

### ISSUE THREAD

**Issue by t3brightside** [umami-software/umami#1988]
Feels a bit cumbersome right now to navigate to the Realtime view of a page. Select tab from header, and then certain page.
Header tab for Realtime would make more sense if there would be an overview of all my pages in real time...

Could me more natural to select Realtime view from dashboard and from detailed view itself?

Two buttons in dashboard maybe? One for details and one for real time? And then just set the state for selected view.
<img width="1072" alt="Screenshot 2023-04-25 at 11 57 43" src="https://user-images.githubusercontent.com/771791/234227011-eb38fd68-7fcd-4388-a81a-021e9d946e8d.png">

**Comment by mikecao** [comment]
This totally makes sense.

**Comment by mikecao** [comment]
Real-time button is now on the details page.
