### ISSUE TITLE
Settings link in Dashboard menu broken

### ISSUE THREAD

**Issue by wheeleran** [umami-software/umami#1990]
I'm getting a {} blank page error when clicking the link to Settings in the top menu bar in v2. Going through Profile top right works. docker-compose on Synology NAS. Any ideas?

**Comment by franciscao633** [comment]
First time seeing this. Any errors in the console or network tab to give us some more info?

**Comment by wheeleran** [comment]
Nothing. Elelemnts and Console are blank, nothing in Network, but i've just realised/noticed that if i think refresh the page, it loads. So, first load, blank/bblack screen with '{}' in the upper left corner, refresh browser tab, it loads. Bizarre.
