### ISSUE TITLE
Client-side Exception, "... null (reading 'toLowerCase')"

### ISSUE THREAD

**Issue by slycat34** [umami-software/umami#1991]
Umami v2 not dockerized, built w/ node 20.0, yarn 1.22. All pages running fine except `localhost:3000/websites/website-id` or the "View details ->" button from dashboard, and any share url link

Next.js throwing error page after partial load which says to review browser console (below)
![image](https://user-images.githubusercontent.com/131544144/234282348-c487f5e9-2a8e-4503-9afc-9beb1eab79f7.png)

Cleared browser history, attempted in incognito or private tab mode, umami running as root, nothing has changed

**Comment by franciscao633** [comment]
I'm wondering if your on the latest umami version with the flag images. Can you check your folder structure for this?
![image](https://user-images.githubusercontent.com/31608805/234380396-45548429-f506-4133-98d3-c6ff9b676fce.png)

**Comment by slycat34** [comment]
Yes, appears to contain 254 png files in umami/public/images/flags/ dir

**Comment by mikecao** [comment]
Will have a release today that may fix this.

**Comment by mikecao** [comment]
Should be fixed in v2.2.0.
