### ISSUE TITLE
Too much data for the pages in the realtime

### ISSUE THREAD

**Issue by JerrySukin** [umami-software/umami#1993]
It displays thousands of pages and affects browser performance.
I don't know if it's just me, but I've found this problem both in Edge and Chrome.

![um01](https://user-images.githubusercontent.com/45689550/234355162-28ccd6ca-bb3f-40b4-9d34-66530c6a2893.png)
![um](https://user-images.githubusercontent.com/45689550/234354838-3cfeb404-f15b-49ad-ab43-86a2044c2de6.png)

**Comment by franciscao633** [comment]
Definitely a bug.  We should've limited the dataset to a top n to remove the clutter. Will get a fix out.

**Comment by franciscao633** [comment]
fixed in v2.3.0
