### ISSUE TITLE
Deploy crashed after migrating v1 to v2 - Error: P3005 The database schema is not empty.

### ISSUE THREAD

**Issue by meirroth** [umami-software/umami#2005]
Hi @mikecao,

- I'm hosting on Railway.app.
- @umami/migrate-v1-v2 was successful.
- Pulled upstream to update from  v1.40.0 to v2.2.0.
- Build on railway was successful.

However, deployment crashed with the the following error log:

```
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Error: P3005
The database schema is not empty. Read more about how to baseline an existing production database: https://pris.ly/d/migrate-baseline
✗ Command failed: prisma migrate deploy
Error: P3005
The database schema is not empty. Read more about how to baseline an existing production database: https://pris.ly/d/migrate-baseline
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "check-db" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any ideas as to how I can fix this? If there's any more info you need let me know.
Thank you

**Comment by franciscao633** [comment]
Can you check the records in your _prisma_migrations table? Should have a record for 01_init from the @umami/migrate-v1-v2. Error usually occurs when the table is missing.

**Comment by meirroth** [comment]
@franciscao633 Thank you for your prompt response!
I don't see a _prisma_migrations table. I've got these tables:
```
_event_old
event_data
session
team
team_user
team_website
user
website
website_event
```

**Comment by franciscao633** [comment]
from the root of your umami repo try running these commands.

1. make sure you have env file for DATABASE_URL pointing to your railway db
2. `yarn build-db`
3. `npx prisma migrate resolve --applied 01_init`
4. redeploy

**Comment by meirroth** [comment]
@franciscao633 I'm not sure how I can do that on Railway. I don't think I've got SSH access.

**Comment by meirroth** [comment]
@franciscao633 Done, and issue resolved 😀 
Thank you so much for the support! BTW, v2 looks great!
