### ISSUE TITLE
[feature request] exposing prometheus metrics

### ISSUE THREAD

**Issue by ldpr** [umami-software/umami#2006]
I think it'd be super useful if we could export metrics via prometheus. It would allow people to scrape and display the metrics in tools like [grafana](https://grafana.com/) where it can be drilled down further and enable users to setup better monitoring. Right now, we can basically monitor every other part of a platform apart from analytics so being able to monitor it all from one place would be a great QOL improvement :)

Prometheus also display all exporters [here](https://prometheus.io/docs/instrumenting/exporters/).

Thanks for your time!

**Comment by franciscao633** [comment]
We use prometheus/grafana ourselves to help with monitoring our infra, so an export wouldn't be a bad idea. 👍

**Comment by FHU-yezi** [comment]
Any update about this?

**Comment by ldpr** [comment]
would be a really nice QOL feature if someone is interested in a PR :)

**Comment by mikecao** [comment]
No time wo work on this.

**Comment by ldpr** [comment]
@franciscao633 @mikecao is there any interest in revisiting this?
it's cool if not but figured it can't hurt to ask after the time that's passed.
