### ISSUE TITLE
The ui has been built successfully, but the page data is always empty

### ISSUE THREAD

**Issue by ly0511** [umami-software/umami#2008]
![image](https://user-images.githubusercontent.com/23255488/235081675-a3431632-87d9-430b-b640-b65368e8c6b4.png)

In my mysql database, the user and website tables have data, but other tables like website_event, session, event_data, etc. have no data

**Comment by franciscao633** [comment]
You verified that the script is loaded to the website and collecting data? You can verify through the network tab.
