### ISSUE TITLE
Vercel's one click deployment not working

### ISSUE THREAD

**Issue by screenfluent** [umami-software/umami#2011]
### Describe the Bug

I decided to not bother with migration and just start with new install for v2 but I can't follow guide as I did with 1.4 because I get error in Vercel.
![Screenshot 2023-04-29 at 09 53 21](https://user-images.githubusercontent.com/116732045/235291598-0790b31d-e326-4bd6-8c13-681dbc6563de.png)

### Database

PostgreSQL

**Comment by franciscao633** [comment]
Not sure if that's on Vercel's side, but I can't get a successful deploy myself, so we will look into it.

**Comment by screenfluent** [comment]
Thanks! Any updates? :)

**Comment by franciscao633** [comment]
Sorry, just got to this... The URL parameters were incorrect for the button. This has been resolved. Let me know if you have any issues, but I will close for now.
