### ISSUE TITLE
Docker Deployment fails on Google Cloud Run: "Application failed to start: exec format error"

### ISSUE THREAD

**Issue by dennishendricks** [umami-software/umami#2018]
### Describe the Bug

We deploy Umami via Google Cloud Run and use Cloud SQL with a PostgreSQL database. 
Unfortunately, when deploying v2.2.0 via Docker, we only get the error message: `terminated: Application failed to start: Failed to create init process: failed to load /usr/local/bin/docker-entrypoint.sh: exec format error`.

v1.4.0 ran error-free under the same setup, the database has been prepared via the migration script before the 2.2.0 deployment.

According to our tests, the bug is due to a platform-specific Docker deployment and the lack of ARM support under Cloud Run. Was the current Docker image created via an M1 Apple? If so, according to web reports, it would be possible to bypass the limitation when building the image with the following command: `docker buildx build --platform linux/amd64 -t {project-name} .`

### Database

PostgreSQL

### Relevant log output

```shell
Ready condition status changed to False for Revision {PROJECT}-00XXX-bid with message: The user-provided container failed to start and listen on the port defined provided by the PORT=3000 environment variable.

ERROR: terminated: Application failed to start: Failed to create init process: failed to load /usr/local/bin/docker-entrypoint.sh: exec format error
```

### How are you deploying your application? (if relevant)

Google Cloud Run, Cloud SQL (PostgreSQL 14)

**Comment by mikecao** [comment]
In v1.4.0 we didn't have any arm builds, but we do now in v2. All the images are built using GitHub actions after a version release. I believe they use Linux machines. But you are free to build your own image for your specific platform.
