### ISSUE TITLE
TRACKER_SCRIPT_NAME is not working as expected

### ISSUE THREAD

**Issue by JerrySukin** [umami-software/umami#2025]
### Describe the Bug

`TRACKER_SCRIPT_NAME=test.js`

I set the script to /test.js in .env, but actually the server serves the script at /test without .js extension.

I know the extension is not necessary now, but I still like to have it to better handle cache.

### Database

MySQL

**Comment by mikecao** [comment]
I just tested it and it works fine. What version are you on? How are you deploying?
