### ISSUE TITLE
Flags' .png files are in different path

### ISSUE THREAD

**Issue by konstantinosftw** [umami-software/umami#2031]
### Describe the Bug

Hello,

I just updated to v.2.2.0 and the flag `.png` file paths are not loading. It seems that my umami dashboard tries to fetch them with `<img src="/images/flags/gr.png" alt="GR">`, while the actual flag files are downloaded under the `/umami/images/flags` path.

Haven't seen it as an issue here, so I just thought to report it.

Great tool, keep it up!

### Database

PostgreSQL

### How are you deploying your application? (if relevant)

Angular 14

**Comment by mikecao** [comment]
Are you using the `BASE_PATH` variable? That's likely what is happening here.

**Comment by konstantinosftw** [comment]
Hello @mikecao and thank you for the response.
Yes, my `.env` file has `BASE_PATH=/umami` in it. Should I be using another one for my case?

<img src="https://github.com/umami-software/umami/assets/23435302/d60561bd-b407-4fcf-ba35-559d6b3b1cca" width=600>

**Comment by konstantinosftw** [comment]
Upgrading to the new 2.3.0 version made the flags load again.
