### ISSUE TITLE
Impossible to delete sites

### ISSUE THREAD

**Issue by AugustinHavas** [umami-software/umami#2033]
### Describe the Bug

Hi
When I want to delete a site (with data), the loader still turns and the app is very slowed and sometimes crashed.
After reloading the container, all seems good.

Any way to delete sites with datas ?

### Database

MySQL

### How are you deploying your application? (if relevant)

docker

**Comment by franciscao633** [comment]
Any errors comes up in the logs? I just tested a MySQL docker setup myself without issues. The only thing I can think of is if that website had millions of records.
