### ISSUE TITLE
role "Unkown" after renaming admin account

### ISSUE THREAD

**Issue by davideperozzi** [umami-software/umami#2037]
### Describe the Bug

I'm not quite sure if this is a bug or expected behavior, but semed like a bug to me. 
I wanted to rename the admin account, which has the role set to "administrator". 
After I renamed the accounts role had been set to `Unknown`. 

![image](https://github.com/umami-software/umami/assets/4140184/3ab7fb68-4a95-44d7-849b-20ba2022a68a)

Is it possible to reset this without loggin into the database?
Really appreciate the product! :) 

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker (Swarm)

**Comment by franciscao633** [comment]
Probably a duplicate of #1954 . If you go to settings then back to profile does it still show Unknown?  I notice when I change my username then go straight to profile, the old username is still displayed. Probably need to fetch the user on the profile page.

**Comment by davideperozzi** [comment]
@franciscao633 Yes can confirm. It works after reloading. I'ts a duplicate. Can be close! :)
