### ISSUE TITLE
Issue while migrating from v1.33.1 to v2.2.0

### ISSUE THREAD

**Issue by Toaaa** [umami-software/umami#2041]
### Describe the Bug

Hi, I followed all the instructions in the migration guide to migrate my Docker container from v1.33.1 to v2.2.0. However, I am getting the following error:
![grafik](https://i.toaaa.de/i/pby09.png)

I have all the tables created by Umami v1.33.1. Here is a picture of output of the `\dt+` command.
![grafik2](https://i.toaaa.de/i/34499.png)

### Database

PostgreSQL

### Relevant log output

```shell
root@NPM:$ docker exec -ti -u 0 analytics_umami_1 sh
/app $ npx @umami/migrate-v1-v2@latest
Need to install the following packages:
  @umami/migrate-v1-v2@latest
Ok to proceed? (y) y
Running v0.15.0
✓ DATABASE_URL is defined.
✓ Database connection successful.
✗ Database v1 tables have not been detected.
```

### How are you deploying your application?

Docker

**Comment by mikecao** [comment]
You have to migrate from the latest v1 branch, which is 1.40.

**Comment by Toaaa** [comment]
> You have to migrate from the latest v1 branch, which is 1.40.

So I have to upgrade to 1.40 first to be able to migrate to 2.2.0?

**Comment by mikecao** [comment]
Yes

**Comment by Toaaa** [comment]
Got it. Migration was successful.
