### ISSUE TITLE
Breaking change migrating from v1 to v2 not in docs

### ISSUE THREAD

**Issue by tairosonloa** [umami-software/umami#2046]
### Describe the Bug

Hi all!

I detected a breaking change not described in docs when migrating from v1 to v2.

I was using a custom script name for my tracker script, let's say `hello`. I was populating the env variable like.

```
TRACKER_SCRIPT_NAME=hello
```

In v1, umami automatically was adding the `.js` extension to my script, so I was loading `my-umami-deployment.com/hello.js`. However, after update, the extension is not being added automatically anymore, so I have to apply one of the two following actions:

Either update the env var to include the extension:
```
TRACKER_SCRIPT_NAME=hello
```

Or update the url for the script in my website:
```
my-umami-deployment.com/hello.js
```

In fact, the current [docs](https://umami.is/docs/environment-variables) continue saying you don't need the `.js` extension, so seems confusing.

### Question

Is this per design or an introduced bug with the v2 release? I'm happy with fixing it (if a bug) or updating the documentation accordingly (if per design feature) by myself if you guys @mikecao @franciscao633 point me in the right direction. I'll open a PR in the required repo when it's clear (it should be done the same or next day).

### Database

PostgreSQL

### Relevant log output

```shell
Not relevant
```

**Comment by FHU-yezi** [comment]
Just found this bug in my application, but it seems have no effect in the data collection, because we use script tag and whether the file has .js, it will be execute as a Javascript file.

**Comment by tairosonloa** [comment]
Yep, that's not the problem. The problem is accessing a script `hello.js` when the env variable value is `hello`. In v1.X this would serve a script, but now resolves to 404.

**Comment by mikecao** [comment]
The tracker script name can be whatever you choose, `hello`, `hello.js`, `hello.jpg`, `hello.php`. It no longer appends anything, it takes whatever is set.

**Comment by tairosonloa** [comment]
> The tracker script name can be whatever you choose, `hello`, `hello.js`, `hello.jpg`, `hello.php`. It no longer appends anything, it takes whatever is set.

I understand then this is now as it is by design, so I think we should update docs then. I'll create a PR for this shortly and close the bug issue here. Please, feel free to reopen this issue if you want.
