### ISSUE TITLE
usability, team websites hard to find

### ISSUE THREAD

**Issue by Quadrubo** [umami-software/umami#2050]
### Describe the Bug

When a user is member of a team but doesn't have any websites on their account themselves, the websites of the team are incredibly hard to find. 
The Dashboard & Realtime shows "You do not have any websites configured."
To find the Team websites you need to go to `Settings -> Teams -> View Team -> Websites -> View`. 
The Realtime view doesn't seem to work at all.

### Database

PostgreSQL

**Comment by mikecao** [comment]
Agreed, we have plans to expose team websites throughout the entire app soon.

**Comment by mikecao** [comment]
Fixed in v2.4.0. Teams websites now appear on the dashboard.
