### ISSUE TITLE
After setting `TRACKER_SCRIPT_NAME` , But access link not a javascript code (404)

### ISSUE THREAD

**Issue by Zhengqbbb** [umami-software/umami#2053]
### Describe the Bug

`TRACKER_SCRIPT_NAME` environment variables set but not working
<img width="488" alt="CleanShot 2023-05-20 at 15 03 29@2x" src="https://github.com/umami-software/umami/assets/40693636/10df9d90-c6c5-4d54-bb42-3d51b5d53a7c">

<img width="1920" alt="image" src="https://github.com/umami-software/umami/assets/40693636/56fac931-d14c-4321-86f3-47ff689019cc">

![CleanShot 2023-05-20 at 15 04 27@2x](https://github.com/umami-software/umami/assets/40693636/9f48a143-ba93-4d6f-8d5c-049c7ff647fd)

### Database

PostgreSQL

### Relevant log output

```shell
2:45:20 PM: $ rollup -c rollup.tracker.config.js
2:45:20 PM: 
2:45:20 PM: tracker/index.js → public/script.js...
2:45:21 PM: created public/script.js in 607ms
```

### How are you deploying your application? (if relevant)

netlify

**Comment by mikecao** [comment]
Have your tried it without the .js extension?

**Comment by Zhengqbbb** [comment]
> Have your tried it without the .js extension?

Yeah! I have tried. But the result is only `*/script.js` can be access.

**Comment by m4g3s** [comment]
> > Have your tried it without the .js extension?
> 
> Yeah! I have tried. But the result is only `*/script.js` can be access.

Same issue using Netlify. If you find a solution let me know please.

**Comment by pstation** [comment]
Also having an issue with this as well. my .env is set to "/something.js" and /something.js returns a 404 but /something works

**Comment by Zhengqbbb** [comment]
anything update ? 👀

**Comment by mikecao** [comment]
We have had a few releases since this issue. You can try updating. Another solution is to copy the default script.js and name it something else.

**Comment by Sammy-T** [comment]
I checked the latest release on my Netlify deployment and `script.js` is still the only one that works for me.

**Comment by ijkml** [comment]
Came across this issue on Netlify today, too. Can't access `newname` or `newname.js` only `script.js` :+1:

**Comment by Zhengqbbb** [comment]
no stale

**Comment by Sammy-T** [comment]
I'm guessing not many people host on Netlify.
