### ISSUE TITLE
deploy on platform.sh fails because database is only ready after build and deploy

### ISSUE THREAD

**Issue by jankohlbach** [umami-software/umami#2056]
### Describe the Bug

I am trying to deploy umami to platform.sh, so I can set up the frontend and database in one place.
The issue is, that first the frontend is build (via yarn install and yarn build) and only later the postgresql database is initialized, so the build fails, because it has no connection.
Their support advised me to ask for help from you, because maybe you could split up tasks for building the frontend and creating the database.
I can actually run the tasks separately by myself also, but then the issue is that the output after the build-step is read-only and prisma is doing database things I don't understand well enough and apparently needs write access to different places.
So I don't really know how to deploy this in that way.

### Database

PostgreSQL

### Relevant log output

```shell
I got following output:
Prisma schema loaded from prisma/schema.prisma
    W: Error: 
    W: EROFS: read-only file system, unlink '/app/node_modules/.pnpm/@prisma+client@4.13.0_prisma@4.13.0/node_modules/.prisma/client/index.js'
    W: 
    W: 
     ELIFECYCLE  Command failed with exit code 1.
    W: ERROR: "build-db-client" exited with 1.
     ELIFECYCLE  Command failed with exit code 1.


So I tried setting 'output   = "../src/generated/client"' in schema.prisma, but then I get other errors during the build step
    Prisma schema loaded from prisma/schema.prisma
    W: Error: 
    W: ENOENT: no such file or directory, mkdir '/app/src'
    W: 
    W: 
     ELIFECYCLE  Command failed with exit code 1.
    W: ERROR: "build-db-client" exited with 1.
     ELIFECYCLE  Command failed with exit code 1.
```

### How are you deploying your application? (if relevant)

via platform.sh by cloning the repository

**Comment by mikecao** [comment]
If you want to build the app without a database connection, you can set `DATABASE_TYPE` and `SKIP_DB_CHECK`. This is what we do for docker builds. See https://umami.is/docs/environment-variables

**Comment by jankohlbach** [comment]
hm, I think I tried that, but how do I establish the db connection then afterwards?

**Comment by jankohlbach** [comment]
alright, I found a solution, I have the two environment variables so the build is working yes, but what was missing was running 'yarn update-db' after everything is done on platform.sh
that was not documented anywhere, I just stumbled upon this because I read every deploy guide on the documentation
