### ISSUE TITLE
Visits / Visitors not recording for single page website

### ISSUE THREAD

**Issue by luigigorlero** [umami-software/umami#2069]
### Describe the Bug

Hello! I’m recording stats for two separate websites. One works great, the other – consinsting of a single page – cannot record page visits and visitor numbers. 

The curious fact is that Realtime stats, as well as events, are registered, they just won’t translate into Views/Visitors/Time

_Two images for reference, the highlithed sections refer to the country and events registered during the “Realtime” session_
![](https://github.com/umami-software/umami/assets/22613842/9d504da1-db85-4ada-8cca-e4d015121cc4)
![](https://github.com/umami-software/umami/assets/22613842/bd1db5cc-2d2b-4862-8b3c-7a390a9865f2)

Currently running Umami `v2`, only custom configuration `ignoreLocalhost: true`

### Database

PostgreSQL

**Comment by FHU-yezi** [comment]
Maybe you can add a handler to the route change event in your router library, and call `umami.track()` manualy.

The reason is that umami only capture 'true' page switch and record the event, but SPA only render new content and overwrite the current url, without trigger a page switch.
