### ISSUE TITLE
umami keeps crashing

### ISSUE THREAD

**Issue by nyancrimew** [umami-software/umami#2072]
### Describe the Bug

umami keeps crashing on my arm64 (ampere on oracle cloud) setup, seemingly for no reason, there does not appear to be anything relevant in the log. i am running it via pm2 and it appears to crash in a way where pm2 does not recover/restart it from the crash.

### Database

PostgreSQL

**Comment by joemaller** [comment]
Pretty sure this is a problem with the Prisma ORM running on ARM64. I burned days chasing the same thing on Apple Silicon. 

Ref [prisma#18510](https://github.com/prisma/prisma/issues/18510) linked from [umami#1865 (comment)](https://github.com/umami-software/umami/issues/1865#issuecomment-1497593656)

**Comment by zhucaidan** [comment]
same here, after few refresh the website will crush and appear 502 error

by the same time node process on ARM64 CPU will running high

**Comment by nyancrimew** [comment]
for now my workaround is to keep downgrading prisma to 4.9.0 as discussed in the other thread, it's really annoying that upstream keeps releasing new versions without addressing this whatsoever - not blaming umami here but wanted to at least provide a (hopefully) temporary workaround
