### ISSUE TITLE
Year not displayed properly in All time view

### ISSUE THREAD

**Issue by andlil** [umami-software/umami#2073]
### Describe the Bug

When viewing statistics for all time, year is not displayed properly in graph

### Database

PostgreSQL

![Skärmavbild 2023-06-06 kl  19 46 48](https://github.com/umami-software/umami/assets/10003475/5d067173-ace8-435a-b75b-474a6baf58ab)

**Comment by franciscao633** [comment]
Fixed in v2.3.0. Thanks for reporting!
