### ISSUE TITLE
Unreliable Events Tracking

### ISSUE THREAD

**Issue by sunflowerm** [umami-software/umami#2074]
### Describe the Bug

I'm currently tracking two types of events. The first one is working most of the time, the second one isnt responding.

1) `<a href="https://www.facebook.com/" target="_blank" id="social-facebook" data-umami-event="Social FB"><FaFacebookSquare size={28} className="cursor-pointer" /> </a>`
2) `<button onClick={showVideo} id="watch-demo" data-umami-event="Demo Video" className="relative"> <div className="flex"> Watch a Demo </div> </button>`

For the first href, it registers most of the time. However for the second one, it only registers sometimes in dev mode (when i deploy it locally) but doesn't register in production (after deploying on vercel). After deployment, Ive confirmed that the "id" and "data-umami-event" is correct in the web inspector.

I have yet to use javascript to track the events, as I'm slightly confused how to use umami.track(). Do i have to yarn add umami to my front end vercel site? Ideally, I'd like to use the data attributes method.

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Front End on Vercel (NextJS), Umami fully on Railway.

**Comment by mikecao** [comment]
For your second one, it looks like you have your own onClick handler. Are you intercepting the click event and not letting it pass through. Umami does attribute tracking by using a global click handler.

**Comment by sunflowerm** [comment]
Hi Mike, thanks for the quick reply and explanation. From there, I checked what it was logging when i clicked. And I realised the issue! 

```
useEffect(() => {
      document.addEventListener("click", function (evnt) {
         console.log(evnt.target)
      })
}, [])
```

For the second instance of the button, I noticed that it was registering the div inside rather than the button wrapping it, so I put the id and data-umami-event attribute on the button instead and it worked!

However, I then noticed that for the first situation of clicking on a react-icon, it was unreliable as sometimes it was tracking the svg, and sometimes it was tracking the path.

If it tracked correctly it would register this.
`<svg id="hi" data-umami-event="hi"><path></path></svg>`

Otherwise it would register this, which wouldnt send the event to umami as it doesnt have the attributes.
`<path></path>`

I suppose its no longer a bug, perhaps more on react-icon's side than umami. But does anyone have any work around for this? I'm not sure how i can cause it to track reliable for the svg.

**Comment by sunflowerm** [comment]
Ok, I solved the first scenario as well. Adding pointer events none to the svg and adding the umami attributes to the parent works! Hope this is useful to anyone who's facing the same issues. Not sure if its in the docs, but if it isnt, could use this to improve the docs for tracking events. Thanks!

```
<a href="https://www.facebook.com/" target="_blank" id="social-facebook" data-umami-event="Social FB">
    <FaFacebookSquare size={28} className="pointer-events-none " />
</a>
```
