### ISSUE TITLE
[v2.2.0] Cannot reset website statistics

### ISSUE THREAD

**Issue by gander** [umami-software/umami#2079]
### Describe the Bug

Settings -> Websites -> [id] -> Data -> Reset

"Reset statistics" modal appears, with disabled "reset" button. Into Confirm input provide "DELETE" text, but nothing happens, button still remain disabled. 

![image](https://github.com/umami-software/umami/assets/421597/b2d2069a-982c-40bb-91e9-62b8bc518fc7)

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by gander** [comment]
`RESET` is valid confirmation.

---

![image](https://github.com/umami-software/umami/assets/421597/337629ca-fb79-4867-86c5-01c6fa2427d0)
![image](https://github.com/umami-software/umami/assets/421597/4174988a-33e8-44ed-abe3-d71d95dca66b)

---

![image](https://github.com/umami-software/umami/assets/421597/2a652e39-6c62-4d87-b345-0bf8418db5e7)
![image](https://github.com/umami-software/umami/assets/421597/8abf67dc-a3cc-43fc-b461-20df47ba5c97)

**Comment by FHU-yezi** [comment]
Chinese translation also has this issue.

**Comment by gander** [comment]
I think most if not all (excluding US) have this problem.  I did a PR for the ones I knew how to correct (GB is US copy).

**Comment by JackGoldfinch** [comment]
Confirming that it affects German as well.

**Comment by franciscao633** [comment]
We will have to replace with the default message for all languages that are incorrect, until we get some proper translations. The English default message provides better direction then "Reset Statistics".

**Comment by franciscao633** [comment]
fixed in v.2.3.0. will probably need help again with translations.
