### ISSUE TITLE
user role "viewer"

### ISSUE THREAD

**Issue by jesperordrup** [umami-software/umami#2085]
### Describe the feature or enhancement

I've setup a server and I want to give access to users to their own websites. Im the server admin and I dont want them to be able to create new websites stats. I instead will create both user and a website and then they can view.

Possible?

I've been searching for a user role "viewer" of sorts or a "flag" on the user to disable creating websites. 
Aditionally make it possible for an admin to assign websites to users/teams.

**Comment by franciscao633** [comment]
This has been requested by several users and currently in our plans to implement.

**Comment by franciscao633** [comment]
This has been implemented in v.2.3.0, but we really need to expose team websites into the dashboard etc, and not a bunch of clicks into the teams menu. It will be high priority next release.
