### ISSUE TITLE
Umani没有数据

### ISSUE THREAD

**Issue by RobKing9** [umami-software/umami#2087]
### Describe the Bug

通过docker-compose搭建的，已经将代码贴到了halo博客的统计代码中，但是还是没有数据
![image](https://github.com/umami-software/umami/assets/78016475/2c1e4c3c-485c-4bc3-92e7-2301004e26f5)
![image](https://github.com/umami-software/umami/assets/78016475/0e516af6-83a4-4666-a272-0b45c6cf00d5)

### Database

PostgreSQL

**Comment by FHU-yezi** [comment]
Please open the DevTools and chexk whether the script is successful load in Network tab.

**Comment by RobKing9** [comment]
> Please open the DevTools and check whether the script is successful loaded in Network tab.

yes,  the script is successful loaded in Network tab.
![image](https://github.com/umami-software/umami/assets/78016475/c5f1e61d-995f-4b19-9863-b9243589c60f)

**Comment by RobKing9** [comment]
this is my blog.  robking.top. you can have a try.
the lab page has umami.

**Comment by RobKing9** [comment]
The AD blocker has been disabled

**Comment by gitnamenull** [comment]
我也是这个问题，解决了吗
