### ISSUE TITLE
Get raw referrer links?

### ISSUE THREAD

**Issue by gouku** [umami-software/umami#2088]
### Describe the feature or enhancement

Our website got many referrers from forum posts but I can only get the hostname. I'd like to know which exact posts referring to our site. So it's great to have the raw referrer links collected.

**Comment by mikecao** [comment]
It depends on the browser the user is using. If strict-origin-when-cross-origin is enabled, then only the domain will be passed. We have no control over it. See https://developer.chrome.com/blog/referrer-policy-new-chrome-default/
