### ISSUE TITLE
Refused to load the script CSP

### ISSUE THREAD

**Issue by iriath** [umami-software/umami#2097]
### Describe the Bug

Hello, since April that I installed Umami it has been working without problems. Version 2.2.0 is installed but for a few days it has stopped working.

Tests that I have done to try to fix it:

- Re-deploy the app in Vercel
- Try other DBs
- Use Umami Cloud 

None of these tests have worked and the following error continues to appear in the browser:

`Refused to load the script 'https://xxxxxx.vercel.app/script.js' because it violates the following Content Security Policy directive: "script-src http: https: 'nonce-XXXXX' 'strict-dynamic'". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

Has it happened to someone else?

### Database

MySQL

### Relevant log output

```shell
Refused to load the script 'https://xxxxxx.vercel.app/script.js' because it violates the following Content Security Policy directive: "script-src http: https: 'nonce-XXXXX' 'strict-dynamic'". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

Vercel

**Comment by mikecao** [comment]
You need to check the CSP, https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP, on your site where you are loading the tracker script.

**Comment by thomasbnt** [comment]
> You need to check the CSP, [developer.mozilla.org/en-US/docs/Web/HTTP/CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), on your site where you are loading the tracker script.

I just reloading the page after waiting some minutes, and works. I can login and see the dashboard 🤔😆
