### ISSUE TITLE
怎么没有显示统计的ip，

### ISSUE THREAD

**Issue by phpmac** [umami-software/umami#2104]
### Describe the feature or enhancement

怎么没有显示统计的ip，

**Comment by dianso** [comment]
木有

**Comment by phpmac** [comment]
加一个嘛，我喜欢

通过 [Proton Mail](https://proton.me/) 安全邮箱发送。

------- Original Message -------
2023年7月9日 星期日 2:48 下午，DIANSO ***@***.***> 来信：

**Comment by nailuoGG** [comment]
https://github.com/umami-software/umami/issues/1117
