### ISSUE TITLE
can't run on v2.3.0.  Err msg: migrate found failed migrations in the target database

### ISSUE THREAD

**Issue by appotry** [umami-software/umami#2118]
### Describe the Bug

image: docker.umami.dev/umami-software/umami:mysql-latest

SQL: mariaDB 10.3

### Database

MySQL

### Relevant log output

```shell
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `02_report_schema_session_data` migration started at 2023-07-13 04:00:33.871 UTC failed


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "check-db" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
✗ Command failed: prisma migrate deploy
Error: P3009

migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `02_report_schema_session_data` migration started at 2023-07-13 04:00:33.871 UTC failed



Error: P3009
```
```


### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

docker

**Comment by orilights** [comment]
I am using docker and MySQL 5.7

below is the migration log I found in `_prisma_migrations`

```
A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 02_report_schema_session_data

Database error code: 1064

Database error:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COLUMN `event_data_type` TO `data_type`;
ALTER TABLE `event_data` RENAME COLUMN ' at line 2

Please check the query number 1 from the migration file.

   0: sql_schema_connector::apply_migration::apply_script
           with migration_name="02_report_schema_session_data"
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:106
   1: schema_core::commands::apply_migrations::Applying migration
           with migration_name="02_report_schema_session_data"
             at schema-engine/core/src/commands/apply_migrations.rs:91
   2: schema_core::state::ApplyMigrations
             at schema-engine/core/src/state.rs:197
```

**Comment by franciscao633** [comment]
Will fix this now. Wrong syntax for renaming a MySQL column

**Comment by franciscao633** [comment]
@appotry It looks like you have failed migrations from the past. Are you able to query your _prisma_migrations and post your results?

**Comment by orilights** [comment]
@franciscao633 Thanks, I will try to switch to MySQL 8.0 version.

**Comment by orilights** [comment]
> @appotry It looks like you have failed migrations from the past. Are you able to query your _prisma_migrations and post your results?

I think he has encountered the same problem as me, MariaDB support rename a column using the `RENAME COLUMN` syntax starting from 10.5.2.

**Comment by appotry** [comment]
> @appotry It looks like you have failed migrations from the past. Are you able to query your _prisma_migrations and post your results?

the docker was upgraded from 2.20 to 2.30

Docker is currently failing to start。 now how to query _prisma_migrations

**Comment by appotry** [comment]
@orilights @franciscao633 
MySQL 8.0 requires a minimum of 4GB of RAM and officially recommends using a server with 8GB of RAM. Which version of the database is more suitable for a server with 2GB of RAM?

**Comment by orilights** [comment]
@appotry  Just upgrade your MariaDB to 10.5 or above. I am using MariaDB 10.11, which takes about 220MB of RAM and umami works fine.

**Comment by bartosjiri** [comment]
Same issue on Planetscale. Seems that the platform does not support direct renames at all, as per [docs](https://planetscale.com/docs/reference/mysql-compatibility).

Any chance you'll still be supporting it with their recommended [workaround approach](https://planetscale.com/docs/learn/handling-table-and-column-renames)?

**Comment by FHU-yezi** [comment]
> @orilights @franciscao633 
> MySQL 8.0 requires a minimum of 4GB of RAM and officially recommends using a server with 8GB of RAM. Which version of the database is more suitable for a server with 2GB of RAM?

Try Postgres which is officially supported by Umami, it just need a few MBs memory.

**Comment by franciscao633** [comment]
@bartosjiri Definitely need to keep this in mind when prisma creates MySQL migrations. We will follow the workaround approach for any future migrations. For this one you will have to alter the existing migration like the directions above. 

1. Update the migration.sql file in 02_report_schema_session_data. Replace the rename columns code to 
```
-- RenameColumns
ALTER TABLE `event_data` ADD COLUMN data_type INTEGER UNSIGNED AFTER event_data_type;
ALTER TABLE `event_data` ADD COLUMN date_value TIMESTAMP(0) AFTER event_date_value;
ALTER TABLE `event_data` ADD COLUMN event_data_id VARCHAR(36) AFTER event_id;
ALTER TABLE `event_data` ADD COLUMN number_value DECIMAL(19, 4) AFTER event_numeric_value;
ALTER TABLE `event_data` ADD COLUMN string_value VARCHAR(500) AFTER event_string_value;

UPDATE event_data
SET data_type = event_data_type,
    date_value = event_date_value,
    event_data_id = event_id,
    number_value = event_numeric_value,
    string_value = event_string_value;

ALTER TABLE `event_data` MODIFY data_type INTEGER UNSIGNED NOT NULL;
ALTER TABLE `event_data` MODIFY event_data_id VARCHAR(36) NOT NULL;

ALTER TABLE `event_data` DROP COLUMN event_data_type;
ALTER TABLE `event_data` DROP COLUMN event_date_value;
ALTER TABLE `event_data` DROP COLUMN event_id;
ALTER TABLE `event_data` DROP COLUMN event_numeric_value;
ALTER TABLE `event_data` DROP COLUMN event_string_value;

ALTER TABLE `event_data` ADD PRIMARY KEY(event_data_id);

```
3. Run `npx prisma migrate resolve --rolled-back "02_report_schema_session_data"` to bypass the failed migration.
4. Redeploy
