### ISSUE TITLE
Update check even with DISABLE_UPDATES

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#2124]
### Describe the Bug

An update check can sometimes be made even if `DISABLE_UPDATES` is set.

In [components/layout/AppLayout.js](https://github.com/umami-software/umami/blob/master/components/layout/AppLayout.js), when `allowUpdate` is computed, config may not yet be loaded,
And with config being an empty object `{}`, this sets `allowUpdate` to true:
`const allowUpdate = user?.isAdmin && !config?.updatesDisabled && !pathname.includes('/share/');`

### Database

MySQL

**Comment by zhangxingguang1** [comment]
{formatMessage(messages.newVersionAvailable, { version: `v${latest}` })}
because messages.newVersionAvailable doesn't exist
