### ISSUE TITLE
An `id` must be provided to format a message ，why and how to slove it

### ISSUE THREAD

**Issue by ly0511** [umami-software/umami#2131]
### Describe the Bug

[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue

I use docker-compose to start, the content is as follows：
![image](https://github.com/umami-software/umami/assets/23255488/20716e75-4ad4-48a5-851b-167f256eaf2e)

### Database

MySQL

**Comment by franciscao633** [comment]
Please see #2113 . Might need to include some type of notification to update your version.
