### ISSUE TITLE
Authentication failure on Linode managed MySQL instance

### ISSUE THREAD

**Issue by gottafixthat** [umami-software/umami#2135]
### Describe the Bug

When attempting to run a custom docker image on a Linode Kubernetes cluster against a Linode managed MySQL 8 database it fails when trying to login. All migrations succeed, but the actual prisma connection fails with an Authentication failure.

I needed to build a custom image to include the database certificate file.  The DATABASE_URL is set as follows:
`mysql://linroot:<PASSWORD>@lin-xxxxx-xxxx-mysql-primary-private.servers.linodedb.net:3306/umami?sslcert=../database.crt`

The "database.crt" file is in the main /app directory of the custom image. This is the only customization made to the stock Dockerfile.

Logs redacted a bit so as not to expose server addresses.

### Database

MySQL

### Relevant log output

```shell
$ kubectl logs -f umami-85cb494664-2wwl9 
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "umami" at "lin-xxxxx-xxxx-mysql-primary-private.servers.linodedb.net:3306"

2 migrations found in prisma/migrations

Applying migration `01_init`
Applying migration `02_report_schema_session_data`

The following migrations have been applied:

migrations/
  └─ 01_init/
    └─ migration.sql
  └─ 02_report_schema_session_data/
    └─ migration.sql
      
All migrations have been successfully applied.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
info  - Loaded env from /app/.env
Listening on port 3000 url: http://umami-85cb494664-2wwl9:3000
PrismaClientInitializationError: 
Invalid `prisma.user.findFirst()` invocation:


Authentication failed against database server at `lin-xxxxx-xxxx-mysql-primary-private.servers.linodedb.net`, the provided database credentials for `linroot` are not valid.

Please make sure to provide valid database credentials for the database server at `lin-xxxxx-xxxx-mysql-primary-private.servers.linodedb.net`.
    at An.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:174:7205)
    at An.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:174:6358)
    at /app/node_modules/@prisma/client/runtime/library.js:177:2908
    at async /app/node_modules/@prisma/client/runtime/library.js:177:3123
    at async t._executeRequest (/app/node_modules/@prisma/client/runtime/library.js:177:10621)
    at async __WEBPACK_DEFAULT_EXPORT__ (/app/.next/server/pages/api/auth/login.js:117:22) {
  clientVersion: '4.15.0',
  errorCode: undefined
}
```

### Which browser are you using? (if relevant)

Firefox and Chrome

### How are you deploying your application? (if relevant)

Kubernetes on Linode

**Comment by franciscao633** [comment]
Are you able to connect to the db and verify the tables are there? I'm curious if the same `DATABASE_URL` was able to connect to your db and run migrations, but fails through prisma.

**Comment by gottafixthat** [comment]
Yes. I'm able to see all of the tables, 11 in total.

I've also verified that the user and _prisma_migrations tables are both populated with their initial data.

**Comment by gottafixthat** [comment]
So, it turns out it was the special character. I had to replace the "$" with a URL encoded %24 and now it works. Not sure why it worked for the migrations but not for the app itself.

**Comment by Savinvadim1312** [comment]
Thanks. Encountered the same issue. I had a dot and some other characters in the password, that I had to url encode
