### ISSUE TITLE
Umami does not include the BasePath in the shared website URL when it is set.

### ISSUE THREAD

**Issue by nailuoGG** [umami-software/umami#2139]
### Describe the Bug

 It would be more convenient if the BASE_PATH [doc](https://umami.is/docs/environment-variables) is included in the URL when hosting Umami under a subdirectory and enabling the share URL feature.

https://github.com/umami-software/umami/blob/7bfbe264852558a148c7741f8637ff2b266d48cd/components/pages/settings/websites/ShareUrl.js#L25-L30

**Comment by mikecao** [comment]
Fixed in v2.4.0.
