### ISSUE TITLE
relation "account" does not exist at character 15

### ISSUE THREAD

**Issue by tasiotas** [umami-software/umami#2145]
### Describe the Bug

Hi,

I did a fresh build of v2.3.1 and a fresh postgres 15 DB.

Getting those errors in postgres every minute, they are coming from umami.

```
ERROR:  relation "account" does not exist at character 15
STATEMENT:  select * from account limit 1
```

### Database

PostgreSQL

**Comment by franciscao633** [comment]
There is a prisma query that checks for `account` in the check-db step, but this should only run during the build. Once Umami is started, it should not reoccur. Is the error occuring after the build step?

**Comment by tasiotas** [comment]
nope, no errors during or after building.

**Comment by ShermanQ** [comment]
I encountered the same problem, which caused UMAMI to not work properly
`umami-db-1  | 2023-07-27 10:35:41.193 UTC [13216] ERROR:  relation "account" does not exist at character 15
umami-db-1  | 2023-07-27 10:35:41.193 UTC [13216] STATEMENT:  select * from account limit 1
umami-db-1  | 2023-07-27 10:40:44.300 UTC [13650] LOG:  could not receive data from client: Connection reset by peer
umami-db-1  | 2023-07-27 10:40:46.037 UTC [13662] ERROR:  relation "account" does not exist at character 15
umami-db-1  | 2023-07-27 10:40:46.037 UTC [13662] STATEMENT:  select * from account limit 1
umami-db-1  | 2023-07-27 10:42:50.344 UTC [13696] LOG:  could not receive data from client: Connection reset by peer
umami-db-1  | 2023-07-27 10:42:50.344 UTC [13748] LOG:  could not receive data from client: Connection reset by peer
umami-db-1  | 2023-07-27 10:42:50.344 UTC [13695] LOG:  could not receive data from client: Connection reset by peer
umami-db-1  | 2023-07-27 10:42:52.060 UTC [13853] ERROR:  relation "account" does not exist at character 15
umami-db-1  | 2023-07-27 10:42:52.060 UTC [13853] STATEMENT:  select * from account limit 1
`

**Comment by franciscao633** [comment]
@ShermanQ Looks like a networking issue. The account check should not be stopping your postgres conatiner.

**Comment by busybox11** [comment]
Getting this on ARM. Looks like it is related to https://github.com/umami-software/umami/issues/1865#issuecomment-1497593656 / https://github.com/umami-software/umami/issues/2072.

I'm using the provided `docker-compose.yml` without any critical modifications.

**Comment by pxlfrk** [comment]
also having this issue..

**Comment by wSzki** [comment]
same here but only  with traefik

**Comment by Christian-Schou** [comment]
Got the same issue. Reverting to the previous docker image made my Umami container start and run again. Any fix for this? Would like to upgrade and use the new features 🥳

**Comment by stewones** [comment]
I was facing this with a arm64 machine, switched to x86 and everything went back to normal.

**Comment by anoxi** [comment]
Can confirm this on v2.6.2 and postgres 15, traefik and amd64 host. Containers started but it the umami app failed to load.
When i switched back to the image `umami:postgresql-v2.5.0`, the app loaded fine for me. 
Interestingly, the same messages continued to appear in the log, so this may not be related to the app not loading.
```
2023-09-20 20:38:01.613 UTC [1] LOG:  database system is ready to accept connections
2023-09-20 20:38:19.323 UTC [52] ERROR:  relation "account" does not exist at character 15
2023-09-20 20:38:19.323 UTC [52] STATEMENT:  select * from account limit 1
2023-09-20 20:38:26.184 UTC [60] LOG:  could not receive data from client: Connection reset by peer
```

**Comment by Mubelotix** [comment]
Not stale. People ditch Umami for this
