### ISSUE TITLE
[@formatjs/intl] An `id` must be provided to format a message

### ISSUE THREAD

**Issue by jkjoy** [umami-software/umami#2153]
### Describe the Bug

[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue

### Database

PostgreSQL

**Comment by moeyy01** [comment]
same

**Comment by djyde** [comment]
same

**Comment by mikecao** [comment]
Please upgrade to the latest version.

**Comment by LWJerri** [comment]
On the latest version, I have the same problem. Hosted on Vercel.

**Comment by diegofcornejo** [comment]
> Anyone still having this issue, you can use this workaround. Open your browser local storage and enter the key `umami.version-check` with this the value `{"version":"2.3.1","time":1690494329049}`. This will be fixed in the next version.

Thanks, works great, waiting the next version :)

**Comment by LWJerri** [comment]
> Anyone still having this issue, you can use this workaround. Open your browser local storage and enter the key `umami.version-check` with this the value `{"version":"2.3.1","time":1690494329049}`. This will be fixed in the next version.

I wrote yesterday about clearing local storage, but if you don't upgrade to v2.3.1 you still get this error and I deleted the message.

**Comment by mikecao** [comment]
Fixed in v2.4.0.
