### ISSUE TITLE
For this issue An id must be provided to format a message.

### ISSUE THREAD

**Issue by biliblihuorong** [umami-software/umami#2162]
### Describe the feature or enhancement

May I ask why every time a new version is released, the old version will report an error and must be upgraded to the new version? The update frequency introduced is so frequent, hoping to solve the problem of this old version still being usable.

**Comment by oscarhermoso** [comment]
Fixed in 2.4.0

https://github.com/umami-software/umami/issues/2113#issuecomment-1657770707

**Comment by mikecao** [comment]
Because there is a bug in the old version. It is fixed in v2.4.0. If you stay on the old version you will see this every time a new version is released.
