### ISSUE TITLE
console log when blocked by client

### ISSUE THREAD

**Issue by iameru** [umami-software/umami#2164]
### Describe the Bug

It is not clearly a bug but didn't match other categories.

I was doing a google lighthouse test and it complained about	umami logging to console. It is this string:

`Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`

not particular important to me but wanted to let you know.

### Database

MySQL

### Relevant log output

```shell
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
```

### Which browser are you using? (if relevant)

Chrome

**Comment by franciscao633** [comment]
I went through and removed some leftover console.logs that were accidentally left in the app. Thanks for reporting!
