### ISSUE TITLE
Show umami version

### ISSUE THREAD

**Issue by markwoon** [umami-software/umami#2165]
### Describe the feature or enhancement

It would be nice to see Umami's version listed somewhere on the website.

Perhaps in a footer?

**Comment by franciscao633** [comment]
We do have a footer component that displays the version, but it's currently only visible when using a share URL. You can see it at the bottom of the [Live Demo](https://analytics.umami.is/share/LGazGOecbDtaIwDr/umami.is). Need to check why it was decided to be restricted to just share links.

**Comment by markwoon** [comment]
If for some reason it needs to be restricted, can we at least make it a compile time option?

**Comment by uPesy** [comment]
> Need to check why it was decided to be restricted to just share links.

I think it was displayed in former umami version. Should be great having it at least in the admin area to compare version number with new release.
