### ISSUE TITLE
Command failed: prisma migrate deploy Error: P3018

### ISSUE THREAD

**Issue by InvoLve1** [umami-software/umami#2174]
### Describe the Bug

![image](https://github.com/umami-software/umami/assets/93432245/669bba22-7d63-48a2-83b6-23b047787f12)
![image](https://github.com/umami-software/umami/assets/93432245/d325644e-3d53-4929-adff-758a13993f52)

Use MySQL 5.7.42 to connect to the database but execute: yarn start gives an error

### Database

MySQL

### Relevant log output

```shell
✗ Command failed: prisma migrate deploy
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 02_report_schema_session_data

Database error code: 1064

Database error:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COLUMN `event_data_type` TO `data_type`;
ALTER TABLE `event_data` RENAME COLUMN ' at line 2

Please check the query number 1 from the migration file.
```

### Which browser are you using? (if relevant)

Chrome

**Comment by franciscao633** [comment]
Looks related to column renaming syntax using older MySQL version #2118, but you figured it out.
