### ISSUE TITLE
Please update the Dokcer-compose image

### ISSUE THREAD

**Issue by M1nTT** [umami-software/umami#2181]
### Describe the Bug

The last update to [Docker Hub](https://hub.docker.com/r/umamisoftware/umami/tags) image was a year ago, and this version has fatal bugs that haven't been fixed.

Bug：
![Xnip2023-08-03_23-24-07](https://github.com/umami-software/umami/assets/33660603/2a60e8ca-263e-40f6-9c0a-d235b80c4c56)

### Database

PostgreSQL

### Relevant log output

```shell
-
```

### Which browser are you using? (if relevant)

Safari, Chrome

**Comment by franciscao633** [comment]
We don't regularly maintain our docker hub, so just pull the latest image using `docker pull ghcr.io/umami-software/umami:postgresql-latest` and the compose file in the repo should work.  On the same note, yes we should update our docker hub to the latest version and will get to it.
