### ISSUE TITLE
`An error occurred` in many places

### ISSUE THREAD

**Issue by Big-Cake-jpg** [umami-software/umami#2184]
### Describe the Bug

After updating to the latest commit of the `dev` branch, Umami does not appear to be working.

`Reports` page, `Region`, `Referrer`, `OS` and `Device` cannot be displayed and only "Something went wrong" message was shown.

![image](https://github.com/umami-software/umami/assets/76810494/2c76a30a-1af1-45e1-b79f-5d00f81e7499)
![image](https://github.com/umami-software/umami/assets/76810494/6ecbf0a4-98b3-4332-979c-9ea94114cd55)
![image](https://github.com/umami-software/umami/assets/76810494/96eb8761-abfa-4485-ab12-fa7fd9e27c95)

### Database

MySQL

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

Vercel, PlanetScale

**Comment by mikecao** [comment]
The `dev` branch is for active development and is unstable by nature. You don't need to raise issues against it.

**Comment by Big-Cake-jpg** [comment]
> The `dev` branch is for active development and is unstable by nature. You don't need to raise issues against it.

Emmm, if I said that I tried to rollback to the latest commit of `main` branch and still got these messages?

![image](https://github.com/umami-software/umami/assets/76810494/c51fee69-15a0-4243-8c22-5c5e22a3ada6)
![image](https://github.com/umami-software/umami/assets/76810494/063eefa8-f14c-47d9-ba9f-aaeab24db0be)

**Comment by knowsex** [comment]
I've had this problem with filters. After upgrading to the latest version and rebuilding it the problem was solved.

I think you can try to build it again with `main` branch.

**Comment by mikecao** [comment]
Our production branch is `master` not `main`.
