### ISSUE TITLE
After upgrade from v1.4.0 to v2.4.1 ,website detail show unexpected data

### ISSUE THREAD

**Issue by luckykeeper** [umami-software/umami#2185]
### Describe the Bug

env: docker | `ghcr.io/umami-software/umami:mysql-v2.4.1`
I had upgraded umami from v1.4.0 to v2.4.1, according [https://umami.is/docs/migrate-v1-v2](https://umami.is/docs/migrate-v1-v2) , I did this

docker exec
```shell
npx @umami/migrate-v1-v2@latest
```
 and got same result like doc: https://umami.is/images/v2/migrate-v1-v2.png

after update , I found webui data come wrong:
![image](https://github.com/umami-software/umami/assets/34579433/6205ce5c-2259-4deb-a1c7-76dd0e3a48a5)

(also found old tracecode link can't collect data,and I update with new tracecode then found new tracecode can collect data)

I expect data link cyan one, not like red one(I can't know which link is visited) , show page links but not tag, the origin link like this:

`https://blog.luckykeeper.site:24680/article/64/` <- link
`https://blog.luckykeeper.site:24680/article/64/#%E5%89%8D%E8%A8%80` -> link to specific part | `#%E5%89%8D%E8%A8%80` -> part(tag)

I want data like `/article/64/` not `#%E5%89%8D%E8%A8%80` ,  it's normal with v1.4.0, but not with v2.4.1

Referrers has same problem with pages like the picture above

### Database

MySQL

### Relevant log output

```shell
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "databaseName" at "serverip:3306"

2 migrations found in prisma/migrations

Applying migration `02_report_schema_session_data`

The following migration have been applied:

migrations/
  └─ 02_report_schema_session_data/
    └─ migration.sql
      
All migrations have been successfully applied.

✓ Database is up to date.
$ node scripts/update-tracker.js
$ node server.js
Listening on port 3000 url: http://b9c81e166e8f:3000
```

### Which browser are you using? (if relevant)

all

### How are you deploying your application? (if relevant)

Docker / Local

**Comment by franciscao633** [comment]
In v2 there is no longer a combined/raw filter. I believe the combined filter removed the anchor tags and grouped the results. Wonder if we need to add this as an option.

**Comment by luckykeeper** [comment]
> In v2 there is no longer a combined/raw filter. I believe the combined filter removed the anchor tags and grouped the results. Wonder if we need to add this as an option.

I hope this feature can be add as an option, so that when anchor tags not be removed , or the other situation like this, we can change the filter to get data we want, maybe sometime we need data with the anchor tag, maybe sometime we needn't.

An option to allow people choose is great. if we can have a self-define filter, it will be more better.
