### ISSUE TITLE
data-umami-event attribute non-functional

### ISSUE THREAD

**Issue by RonenEizen** [umami-software/umami#2186]
### Describe the Bug

I've had data-umami-event attributes set across my site, but the data was not being collected. Once I switched to umami.track method, I started getting reports on event being collected.

### Database

PostgreSQL

### Relevant log output

```shell
None
```

### Which browser are you using? (if relevant)

Chomre

### How are you deploying your application? (if relevant)

Vercel

**Comment by uncenter** [comment]
Can you show us how you were using the attribute?

**Comment by RonenEizen** [comment]
```          
<button 
  onClick={() => {
     setPersistentStore('isVerticallyFlipped', !persistentStore.isVerticallyFlipped)
  }}
  title="Flip Vertical"
  class="w-full xl:w-auto"
  data-umami-event="Control: Flip Vertically"
>Flip</button>
```

This is an example of my code written in React

**Comment by mikecao** [comment]
@ovidiulixandru Do you see any error in your console logs?
