### ISSUE TITLE
Add support for cities/regions when using Cloudflare

### ISSUE THREAD

**Issue by MrPropre** [umami-software/umami#2188]
### Describe the feature or enhancement

Hello,

There is a managed transform that can be enable in Cloudflare Settings to add visitor location headers including city, country, continent, longitude, and latitude. It would be cool to support those headers to add cities/regions when using Cloudflare.

![image](https://github.com/umami-software/umami/assets/36234981/256ffb57-0611-47b0-97f7-7a923563033c)

Thank you in advance

**Comment by mikecao** [comment]
We are already checking for `cf-ipcountry` but it looks like we're missing region and city. We'll add those for the next release.

**Comment by aldo-roman** [comment]
For anyone wondering in the future, you need to enable this in Cloudflare dashboard.

The docs:
https://developers.cloudflare.com/rules/transform/managed-transforms/configure/

**Comment by diegoatwa** [comment]
@aldo-roman Thanks for the tip, it helped me. I'll add it here to **help beginners**.

Please note the publication date, as this may become outdated over time.

1. Go to your Cloudflare dashboard and choose the site you want to access.
2. In the left column (desktop view) click on "Rules" > "Transform Rules"
3. Click on "Managed Transforms"
4. Turn on "Add visitor location headers"

![image](https://github.com/user-attachments/assets/f9c10286-d84b-4801-b8e1-9eb7a9c625ce)

## Result

Notice that the last rows of the table do not have a city, as soon as I activated "Add visitor location headers" in Cloudflare, city location data started arriving in the first rows of the table.

![image](https://github.com/user-attachments/assets/dce7a273-67c4-4ecd-a090-02080f8549f1)

**Comment by zenminimalist** [comment]
@mikecao 
I'm not seeing any cities on my Pikapods self-hosted version (v2.15.1). Before I was on the Umami cloud and it showed cities.

I've checked the CF option to "on" on both the website with the script and the domain that is providing the tracking script. Anything I can try/check to see what the issue is?

**Comment by Outsmart2383** [comment]
> @aldo-roman Thanks for the tip, it helped me. I'll add details it here to **help beginners**.
> 
> Please note the publication date, as this may become outdated over time.
> 
>     1. Go to your Cloudflare dashboard and choose the site you want to access.
> 
>     2. In the left column (desktop view) click on "Rules" > "Transform Rules"
> 
>     3. Click on "Managed Transforms"
> 
>     4. Turn on "Add visitor location headers"
> 
> 
> ![image](https://private-user-images.githubusercontent.com/26748277/369035594-f9c10286-d84b-4801-b8e1-9eb7a9c625ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3ODUyMzYsIm5iZiI6MTczNjc4NDkzNiwicGF0aCI6Ii8yNjc0ODI3Ny8zNjkwMzU1OTQtZjljMTAyODYtZDg0Yi00ODAxLWI4ZTEtOWViN2E5YzYyNWNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDE2MTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxNzY5ZTUyNWFhNjEzODhmYTNlZmNjY2ViNGQ3MGEzYjJlNGU4YTVhNjIwOTM2YzQxMmRiMDMwODlmOWU0MzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._mv8xSAi0bHHgrmXfnv7v3ZG2fjabQK3SkBA7IpbzQw)
> ## Result
> 
> Notice that the last rows of the table do not have a city, as soon as I activated "Add visitor location headers" in Cloudflare, city location data started arriving in the first rows of the table.
> 
> ![image](https://private-user-images.githubusercontent.com/26748277/369033937-dce7a273-67c4-4ecd-a090-02080f8549f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3ODUyMzYsIm5iZiI6MTczNjc4NDkzNiwicGF0aCI6Ii8yNjc0ODI3Ny8zNjkwMzM5MzctZGNlN2EyNzMtNjdjNC00ZWNkLWEwOTAtMDIwODBmODU0OWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDE2MTUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjNWI0YTE0NzgzMGU0YjM3N2E2MjM2MTEzODZjYjI1ODJmNzFkZTdiMDI4ZWFhODg0ZmM2NmJjODljYjcxYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3eMGSG9gXrsyoskHU69UHeU2HUKanlNmDPMkiXGRjIU)

Trying to get this working for my deployment, but I don't have the option for "Transform rules" in my Cloudflare. Any guidance?
![image](https://github.com/user-attachments/assets/bd440e97-69c6-492f-90c2-3da895df93ff)

**Comment by diegoatwa** [comment]
@Outsmart2383 It looks like the interface has been updated and this option is no longer in the same place.

I tried looking but couldn't find where it was moved.

If anyone has any updates, please share them with us ❤️

**Comment by GlowServices** [comment]
@Outsmart2383 or for those who need to find the new location

You need to go to Rules -> Overview, and you should see “Request Header Transform Rules”, then click on "Create rule" -> Managed Transforms and you can check "Add visitor location headers"

![Image](https://github.com/user-attachments/assets/3109d76d-be9e-4075-a1ac-98ed415d2485)

![Image](https://github.com/user-attachments/assets/10b9e8cf-00cf-4839-b90f-e2fd7f7f1400)

![Image](https://github.com/user-attachments/assets/2ad4838d-f380-4553-852e-6e981198cc64)

**Comment by Outsmart2383** [comment]
@GlowServices your Rules page looks signficantly different to mine. This is what I can see:

![Image](https://github.com/user-attachments/assets/066f902f-bfc4-434b-98dd-2f0f4d5d7dff)

**Comment by GlowServices** [comment]
@Outsmart2383 You have this interface because you have no existing rules, here are the steps:

![Image](https://github.com/user-attachments/assets/74e78713-1fb6-4502-9c1e-a194a3ab069c)

![Image](https://github.com/user-attachments/assets/5fbed7c9-a2c3-4bc2-aafe-022338133c9d)

![Image](https://github.com/user-attachments/assets/ea6e7d3b-6799-4032-9d78-96a812115aaa)

OR:

Replace the path of your url on cloudflare page with something like this, you'll be redirected to the right page:

https://dash.cloudflare.com/XXXXXXXXX/example.test/rules/transform-rules/rewrite-url/new

**Comment by mocherfaoui** [comment]
if you can't find the **Managed Transforms** page because Cloudflare update the UI(again)
[https://dash.cloudflare.com/?to=/:account/:zone/rules/transform-rules/managed-transforms](https://dash.cloudflare.com/?to=/:account/:zone/rules/transform-rules/managed-transforms)

**Comment by designorant** [comment]
☝ PR with the location change so others don't have do crawl through GitHub to find this. 😁

**Comment by kwickramasekara** [comment]
Hey @diegoatwa sorry for bringing this old thread back up, but how do you have custom avatars for session profiles?

> **EDIT: The solution in this comment is outdated, [check this comment](https://github.com/umami-software/umami/issues/2188#issuecomment-2609177100) from [@GlowServices](https://github.com/GlowServices) with an updated solution** ;)
> 
> ~ [@aldo-roman](https://github.com/aldo-roman) Thanks for the tip, it helped me. I'll add details it here to **help beginners**. Please note the publication date, as this may become outdated over time. 1. Go to your Cloudflare dashboard and choose the site you want to access. 2. In the left column (desktop view) click on "Rules" > "Transform Rules" 3. Click on "Managed Transforms" 4. Turn on "Add visitor location headers" ![image](https://github.com/user-attachments/assets/f9c10286-d84b-4801-b8e1-9eb7a9c625ce) ## Result Notice that the last rows of the table do not have a city, as soon as I activated "Add visitor location headers" in Cloudflare, city location data started arriving in the first rows of the table. ![image](https://github.com/user-attachments/assets/dce7a273-67c4-4ecd-a090-02080f8549f1) ~
