### ISSUE TITLE
The version number in the homepage can not be updated.

### ISSUE THREAD

**Issue by knifesoft** [umami-software/umami#2198]
### Describe the Bug

After synchronizing the code on GitHub, the version number in the lower right corner of the homepage has always been V1.37.0.

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by LWJerri** [comment]
Does Vercel show the latest commit as a production build?

![image](https://github.com/umami-software/umami/assets/50290430/8b0de79a-241e-4617-bba9-565cb1199aea)

**Comment by LWJerri** [comment]
@mikecao, can we close this issue?
