### ISSUE TITLE
[Docker] Upgrade from 2.4.1 to 2.5.0 fail

### ISSUE THREAD

**Issue by RikoDEV** [umami-software/umami#2206]
### Describe the Bug

I updated the docker image to the latest version and got a `prisma migrate deploy` command error after container boot.

### Database

MySQL

### Relevant log output

```shell
umami-umami-1  | yarn run v1.22.19
umami-umami-1  | $ npm-run-all check-db update-tracker start-server
umami-umami-1  | $ node scripts/check-db.js
umami-umami-1  | ✓ DATABASE_URL is defined.
umami-umami-1  | ✓ Database connection successful.
umami-umami-1  | ✓ Database version check successful.
umami-umami-1  | Error: P3009
umami-umami-1  | 
umami-umami-1  | 
umami-umami-1  | migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
umami-umami-1  | The `03_metric_performance_index` migration started at 2023-08-18 06:55:19.444 UTC failed
umami-umami-1  | 
umami-umami-1  | 
umami-umami-1  | 
umami-umami-1  | 
umami-umami-1  | 
umami-umami-1  | 
umami-umami-1  | error Command failed with exit code 1.
umami-umami-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami-umami-1  | ERROR: "check-db" exited with 1.
umami-umami-1  | error Command failed with exit code 1.
```

### How are you deploying your application? (if relevant)

Docker

### Temp fix:
```sql
UPDATE _prisma_migrations SET `finished_at` = CURRENT_TIMESTAMP WHERE `migration_name` = '03_metric_performance_index';
```

**Comment by magicgg91** [comment]
Same issue for me.

**Comment by iYoungblood** [comment]
FWIW, this did work:

docker compose pull
docker compose down
docker compose up -d

**Comment by briancao** [comment]
@RikoDEV Can you pull the error message from the _prisma_migration table and post it?

**Comment by RikoDEV** [comment]
Sure:
```A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
Migration name: 03_metric_performance_index
Database error code: 1061
Database error:
Duplicate key name 'event_data_website_id_created_at_idx'
Please check the query number 1 from the migration file.
   0: sql_schema_connector::apply_migration::apply_script
           with migration_name="03_metric_performance_index"
             at schema-engine/connectors/sql-schema-connector/src/apply_migration.rs:106
   1: schema_core::commands::apply_migrations::Applying migration
           with migration_name="03_metric_performance_index"
             at schema-engine/core/src/commands/apply_migrations.rs:91
   2: schema_core::state::ApplyMigrations
             at schema-engine/core/src/state.rs:201```

**Comment by diarpu** [comment]
Same here with MySQL on Vercel

```shell
[13:18:21.775] $ node scripts/check-db.js
[13:18:21.882] ✓ DATABASE_URL is defined.
[13:18:22.361] ✓ Database connection successful.
[13:18:22.736] ✓ Database version check successful.
[13:18:25.046] Error: P3009
[13:18:25.047] 
[13:18:25.047] migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
[13:18:25.047] The `03_metric_performance_index` migration started at 2023-08-19 01:03:29.294 UTC failed
[13:18:25.047] 
[13:18:25.047] 
[13:18:25.047] ✗ Command failed: prisma migrate deploy
[13:18:25.047] Error: P3009
[13:18:25.047] 
[13:18:25.047] migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
[13:18:25.047] The `03_metric_performance_index` migration started at 2023-08-19 01:03:29.294 UTC failed
[13:18:25.047] 
[13:18:25.047] 
[13:18:25.047] 
[13:18:25.062] error Command failed with exit code 1.
[13:18:25.063] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[13:18:25.078] ERROR: "check-db" exited with 1.
[13:18:25.093] error Command failed with exit code 1.
[13:18:25.093] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[13:18:25.117] Error: Command "yarn run build" exited with 1
```

**Comment by briancao** [comment]
@RikoDEV Did you upgrade your Umami from v1 -> v2?  If so, I assume the old schema/tables need to be dropped as the key `event_data_website_id_created_at_idx` currently does not exists in any v2 migrations, but the one trying to be applied.

**Comment by RikoDEV** [comment]
> @RikoDEV Did you (or any of the reporters in this thread) upgrade your Umami from v1 -> v2? If so, I assume the old schema/tables need to be dropped as the key `event_data_website_id_created_at_idx` currently does not exists in any v2 migrations, but the one trying to be applied.

Yes, I updated the umami from v1 to v2.

**Comment by 4ortytwo** [comment]
> @RikoDEV Did you (or any of the reporters in this thread) upgrade your Umami from v1 -> v2? If so, I assume the old schema/tables need to be dropped as the key `event_data_website_id_created_at_idx` currently does not exists in any v2 migrations, but the one trying to be applied.

I have, but it was a long time ago, I've been on probably every updated version after that. Getting this error as well:
![image](https://github.com/umami-software/umami/assets/44406493/772157f5-7e94-4d1b-82ff-d642e6c96d05)

**Comment by franciscao633** [comment]
Can you try manually dropping the index `event_data_website_id_created_at_idx` and rerunning the migrations? I can't track down  that index in both the v1/v2 branch, so I'm not exactly sure how it got there. Maybe it was present before we started prisma migrations?

1. ``DROP INDEX `event_data_website_id_created_at_idx` ON `event_data`;``  (this is mysql syntax, postgresql will be different)
2. `npx prisma migrate resolve --rolled-back "03_metric_performance_index"`
3. `yarn build`

Let me know if you still have issues.

**Comment by cirrusflyer** [comment]
I'm having the same issue and running on fly.io.  What's the best way to handle this here?

**Comment by 4ortytwo** [comment]
Any solution to this, @franciscao633? Can't use umami since the 2.5.0 update and can't seem to find a way to execute this query using dokku.

**Comment by franciscao633** [comment]
@4ortytwo are you able to pull the logs from the failed 03_ migration? Should be in the `logs` column from the `_prisma_migrations` table. From there I can probably help you out more.

**Comment by FuzzyMistborn** [comment]
> Can you try manually dropping the index `event_data_website_id_created_at_idx` and rerunning the migrations? I can't track down that index in both the v1/v2 branch, so I'm not exactly sure how it got there. Maybe it was present before we started prisma migrations?
> 
>     1. `` DROP INDEX `event_data_website_id_created_at_idx` ON `event_data`; ``  (this is mysql syntax, postgresql will be different)
> 
>     2. `npx prisma migrate resolve --rolled-back "03_metric_performance_index"`
> 
>     3. `yarn build`
> 
> 
> Let me know if you still have issues.

I had to roll back to 2.4.1 and load in a backup.  When I tried to run these commands I got the following:

Running ``DROP INDEX `event_data_website_id_created_at_idx` ON `event_data`;`` got me: ``ERROR 1091 (42000): Can't DROP INDEX `event_data_website_id_created_at_idx`; check that it exists``

Then when I tried to run `npx prisma migrate resolve --rolled-back "03_metric_performance_index"` I got:

```
Prisma schema loaded from prisma/schema.prisma
Datasource "db": MySQL database "umami" at "umami-db:3306"
Error: P3011

Migration `03_metric_performance_index` cannot be rolled back because it was never applied to the database. Hint: did you pass in the whole migration name? (example: "20201207184859_initial_migration")
```

**Comment by dennishendricks** [comment]
@franciscao633 Unfortunately, we get the same error. During the update to 2.5, the Prisma migration process fails with the following error:

```
Error: P3009

migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `03_metric_performance_index` migration started at 2023-08-29 07:23:29.907336 UTC failed
```

I tried a rollback, unfortunately without success. Strangely, the logs column is completely empty:
![Bildschirmfoto 2023-08-29 um 09 30 37](https://github.com/umami-software/umami/assets/20031606/35181e71-c1f2-4811-b2e8-ac8ffde4a688)

By the way, an index on `event_data_website_id_created_at_idx` is not created in our case, here is the structure of the event_data table:
![Bildschirmfoto 2023-08-29 um 09 32 09](https://github.com/umami-software/umami/assets/20031606/39e8e341-7e6e-4245-9b89-0c37106cf812)

I will try an update from 2.4.1 to 2.6.1 today or tomorrow and report back.

**Comment by franciscao633** [comment]
@FuzzyMistborn Since you rolled back from a backup those steps aren't needed anymore. What happens when you try to upgrade now? If it errors out can you provide the logs?

**Comment by FuzzyMistborn** [comment]
Nope, same issue.

```
yarn run v1.22.19
$ npm-run-all check-db update-tracker start-server
$ node scripts/check-db.js
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `03_metric_performance_index` migration started at 2023-08-31 18:07:35.757 UTC failed
✗ Command failed: prisma migrate deploy
Error: P3009
migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve
The `03_metric_performance_index` migration started at 2023-08-31 18:07:35.757 UTC failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "check-db" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by franciscao633** [comment]
Feels like the migration is running from an earlier process and that is where the error is to help troubleshoot. What you are seeing the the 2nd attempted try. Your scenario seems very similar to [this](https://github.com/prisma/prisma/issues/12856#issuecomment-1113999288).

**Comment by FuzzyMistborn** [comment]
Just a thought, I'm running Mariadb 11.x.  I know they made some changes, could that be the source of the problem?

**Comment by FuzzyMistborn** [comment]
Still an issue.

**Comment by HermesDE** [comment]
> Still an issue.

It is. I deleted my database and set up a fresh install. It works now.

**Comment by FuzzyMistborn** [comment]
Still an issue.

**Comment by FuzzyMistborn** [comment]
I've given up.  I just nuked my existing install/data and recreated a new Umami instance.  Not happy, but doesn't seem like there will be a fix and didn't want to keep using old software in case there are security issues.

**Comment by MatthK** [comment]
I have the same issue...

**Comment by MatthK** [comment]
Ok, so I did get past it and now I'm back at the latest version (V2.12.1).

I did it with a little trick. 

1. I took a backup of my database by dumping the SQL
2. I then removed the structure data
3. I fired up another container with V2.4.1. into a new database
4. After deleting the admin user, I imported the data only from my real container
5. I removed the container, fired up V2.5.0 and let it do the migration on the new database
6. After the upgrade, I took another SQL dump of the new database
7. I deleted my real database, created a blank new one with the same name and imported the dump which had V2.5.0
8. I fired up the container with V2.5.0 and I passed the migration
9. I then updated the container from 2.5.0 to 2.12.0 in one go and it succeeded again.
10. Last step was to update to V.2.12.1

Where is the version number displayed now in the site? It disappeared from the footer?

**Comment by getanwar** [comment]
I have been facing the same issue since yesterday while trying to upgrade from 2.2.0 to 2.17.0 (guilty of procrastinating :'( ). I came across this post while looking for solution. There was no log produced to `log` column in `_prisma_migrations` table. So I didn't have any idea how to solve it, then I found a comment in this post that says some index couldn't be created. Immediately it hit my mind that my database size is huge and it is failing to create indexes within the timeout set by my docker container. So here is the catch, if you have a very large database and the umami service is running in a docker container, it is possible that the service timeout is reached before the initial migration is completed. Based on the type of your migration, it may take quite a while. 

So, once I have identified the underlying issue, solution was very easy. I manually ran the migration (for 2.4.1 to 2.5.0 it's `03_metric_performance_index`) directly in the database using pgAdmin. Then I created a row in `_prisma_migrations` for `03_metric_performance_index` to suppress migration next time when I would run the application. You can duplicate previous row `02_....` and update the necessary column values. Or you can run the application with `v2.5.0` once without updating `_prisma_migrations` table, certainly it will fail, but it will create a row for `03_...`, then modify the column values, especially `applied_steps_count=1`. Run the application with `v2.5.0` again after saving the row. 

I could upgrade to `v2.10.2` by doing this. But I am stuck again since there are more migrations to run before I could upgrade to `v2.17.0`. Migration `05_add_visit_id` is taking way longer than I expected since it includes query for updating a large table `website_event` (16M rows for my case).
