### ISSUE TITLE
✨Feature Request: Webhook for Periodic Data Reporting

### ISSUE THREAD

**Issue by saaiful** [umami-software/umami#2218]
I'd like to propose a new feature that would greatly enhance the capabilities of umami for many users, especially those who want to integrate umami analytics with other platforms or tools.

### Overview:
The idea is to have a webhook functionality that can send data to another site using an HTTP request. Users should be able to set a specific time interval (e.g., 10 minutes, 20 minutes, etc.) and at the end of that interval, the webhook will make a callback to a specified server with a summary of analytics data.

### Detailed Requirements:

1. Configurable Time Interval: Users should be able to set a time interval for the webhook to trigger. This could be in the form of a dropdown or input field where users can specify the number of minutes (e.g., 10, 20, 30 minutes).
2. Data to be Sent: At the end of the specified interval, the webhook should send:
a. A list of all visited URLs during the previous `x` period.
b. Total views for each URL during the previous `x` period.
3. Webhook Configuration: Users should be able to:
a. Specify the endpoint URL where the HTTP request will be sent.
b. Choose the HTTP method (e.g., `POST`, `PUT`, `GET``).
c. Add custom headers if needed (e.g., for authentication purposes).
4. Error Handling: In case the webhook fails to send data (e.g., server not reachable, authentication failure), there should be a mechanism to retry sending the data or log the error for the user to review.

### Use Case:
This feature would be particularly useful for users who want to integrate umami analytics with other platforms or tools in real-time or near-real-time. For instance, a user might want to send analytics data to a CRM platform every 10 minutes to track and analyze user behavior on their website.

### Data Example
```json
[
    {
        "path": "/",
        "total": 330
    },
    {
        "path": "/docs/getting-started",
        "total": 278
    },
    {
        "path": "/docs/install",
        "total": 98
    }
]
```

### Conclusion:
I believe this feature would be a valuable addition to umami and would open up many integration possibilities for users. I'd love to hear feedback from the community and maintainers on this proposal.

Thank you for considering this feature request!

**Comment by mikecao** [comment]
In general, webhooks are used to inform you when a random event happens, like a user signs up or logs into your website. Then the webhook is called to inform you. They usually don't work on a fixed schedule. I think what you want is a cronjob. You can set up a cronjob on another server to pull from the API whatever data you need.

**Comment by smr0x** [comment]
+1
