### ISSUE TITLE
Event Filter eventName & Event Data not working

### ISSUE THREAD

**Issue by saaiful** [umami-software/umami#2222]
### Describe the Bug

~~When post event data like this  `umami.track('signup-button', { name: 'newsletter', id: 123 });` umami returns 500 error~~
```
code removed
```

In event API `eventName` filter is not working, it returns all events in given time.  

### Database

MySQL

**Comment by saaiful** [comment]
After reviewing the source code and database found that if I use `event_name` it works.

**Comment by mikecao** [comment]
What version are you using? I can't replicate this.

**Comment by uncenter** [comment]
> What version are you using? I can't replicate this.

It looks like they are on a super old version:

<img width="926" alt="image" src="https://github.com/umami-software/umami/assets/47499684/b98b729f-ac1c-457e-a4e9-5a2ba3a4cdf3">

@saaiful Could you try updating to the latest version of Umami?

**Comment by saaiful** [comment]
I'm using version 2.5.0, maybe this pull request has code from my old pull request.

**Comment by saaiful** [comment]
> What version are you using? I can't replicate this.

I'm using 2.5.0, basic event works without issue, but if I try to send any data, I get 500 error. 

`http://localhost:3000/api/websites/****/event?timezone=Asia/Dhaka&eventName=pr0m0-imp-25` this API endpint returns all event, it's eventName does not work, so logged what query is being used and found eventName is not allowed or listed in `lib/constants.ts`'s `FILTER_COLUMNS ` object.

**Comment by saaiful** [comment]
This is the error I'm getting in local and production server while sending data with event. 
```
Invalid `prisma.eventData.createMany()` invocation:

Unique constraint failed on the constraint: `PRIMARY`
    at zr.handleRequestError (D:\wamp64\www\umami2\node_modules\@prisma\client\runtime\library.js:122:8308)
    at zr.handleAndLogRequestError (D:\wamp64\www\umami2\node_modules\@prisma\client\runtime\library.js:122:7697)
    at zr.request (D:\wamp64\www\umami2\node_modules\@prisma\client\runtime\library.js:122:7307)
    at async relationalQuery (webpack-internal:///(api)/./queries/analytics/events/saveEvent.ts:45:9)
    at async __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(api)/./pages/api/send.ts:65:9) {
  digest: undefined
}
```

**Comment by saaiful** [comment]
> This is the error I'm getting in local and production server while sending data with event. I'm using MySQL database.
> 
> ```
> Invalid `prisma.eventData.createMany()` invocation:
> 
> Unique constraint failed on the constraint: `PRIMARY`
>     at zr.handleRequestError (D:\wamp64\www\umami2\node_modules\@prisma\client\runtime\library.js:122:8308)
>     at zr.handleAndLogRequestError (D:\wamp64\www\umami2\node_modules\@prisma\client\runtime\library.js:122:7697)
>     at zr.request (D:\wamp64\www\umami2\node_modules\@prisma\client\runtime\library.js:122:7307)
>     at async relationalQuery (webpack-internal:///(api)/./queries/analytics/events/saveEvent.ts:45:9)
>     at async __WEBPACK_DEFAULT_EXPORT__ (webpack-internal:///(api)/./pages/api/send.ts:65:9) {
>   digest: undefined
> }
> ```

My database had some column missing, set database default engine to InnoDB, Now event with data is working. But the filter is not working. 

![image](https://github.com/umami-software/umami/assets/4525049/a9356a0b-965b-448e-a1a5-790c19a19f4a)
