### ISSUE TITLE
How to save settings

### ISSUE THREAD

**Issue by 404gods** [umami-software/umami#2224]
### Describe the feature or enhancement

How to save the set default time period, language, order of websites on the dashboard, style of switching icons?
Each time these items are set and re-login, they will return to the newly built style.

**Comment by franciscao633** [comment]
For self-hosted there should be a `Profile` button in the `Settings` section. For both self-hosted/cloud there is a button in the top right corner to select profile. These settings persist even after logging out, but let me know if it's still an issue.
