### ISSUE TITLE
Error in calculating the bounce rate

### ISSUE THREAD

**Issue by wokalek** [umami-software/umami#2228]
### Describe the Bug

![image](https://github.com/umami-software/umami/assets/23037847/9b24b6c1-62cd-48f9-9ee2-7408485033e9)

1 person visited my site, but apparently due to the fact that the last hit of the user fell on a new hour period, Umami considered this a bounce, which is an incorrect calculation.

100% must be 0%.

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by Maxime-J** [comment]
I was surprised by that too #1829.
Right now bounces are actually bounces per hour in the self hosted version, and bounces per day in the cloud one.
I think they should be counted for the entire time window selected.
I might submit a PR in that direction.

**Comment by danielunited** [comment]
I'm also experiencing this
