### ISSUE TITLE
After upgrade to v2.5.0, Dashboard shows only 10 websites out of 36

### ISSUE THREAD

**Issue by kornelj** [umami-software/umami#2231]
### Describe the Bug

After upgrade to v2.5.0, Dashboard shows only 10 websites out of total 36. It has been showing all prior upgrade for months.
User: admin

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Running in docker container, hosted on AWS ECS

**Comment by franciscao633** [comment]
Hello are you able to paginate your websites at the bottom? We also provided a search feature so you can filter your websites.
![image](https://github.com/umami-software/umami/assets/31608805/2c7ac79b-0df5-402d-b13d-a42a17e52319)

**Comment by kornelj** [comment]
Hi, unfortunatrly, no pager or anything appears below:
![image](https://github.com/umami-software/umami/assets/128705153/2b8ca004-b453-4782-9783-81d80450e5a0)
however Edit shows all the sites but not the dashboard:
![image](https://github.com/umami-software/umami/assets/128705153/61721716-582e-4771-a6ba-77dda3ae221c)

**Comment by kornelj** [comment]
I tried Reset function also but no luck

**Comment by franciscao633** [comment]
Oh you're correct, the pager is missing on the dashboard and only displaying top 10 websites. I'm labelling this as a bug, we will get it fixed.

**Comment by mikecao** [comment]
Fixed in v2.6.1.

**Comment by kornelj** [comment]
Thank you!
