### ISSUE TITLE
After updating to 2.6.0 getting 400 error on /api/send endpoint

### ISSUE THREAD

**Issue by RonenEizen** [umami-software/umami#2249]
### Describe the Bug

After updating to 2.6.0 the script on my site is getting 400 error on /api/send endpoint

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Any

### How are you deploying your application? (if relevant)

Vercel

**Comment by franciscao633** [comment]
we have a hotfix for this coming out today. Looks like same issues as #2247.

**Comment by mikecao** [comment]
Fixed in v2.6.1.
