### ISSUE TITLE
Support analyse Windows 11 

### ISSUE THREAD

**Issue by vndroid** [umami-software/umami#2253]
### Describe the feature or enhancement

https://learn.microsoft.com/en-us/microsoft-edge/web-platform/how-to-detect-win11

Chrome Series browser supports this function, but Firefox does not.

**Comment by yumusb** [comment]
https://github.com/umami-software/umami/pull/2191

https://developer.chrome.com/en/articles/user-agent-client-hints/#hint-scope-and-cross-origin-requests


As of now the only way to detect win11 is to detect it via JS and then tell the server directly.
