### ISSUE TITLE
Password clear text transmission

### ISSUE THREAD

**Issue by dsyscms** [umami-software/umami#2257]
### Describe the feature or enhancement

The login background management password is not encrypted and transmitted

**Comment by mikecao** [comment]
This is not the responsibility of the app. If you want encryption, you need to use a server like Nginx with SSL.

**Comment by dsyscms** [comment]
> This is not the responsibility of the app. If you want encryption, you need to use a server like Nginx with SSL.

Passwords are sensitive data. During the transmission process, if https is cracked by a man-in-the-middle attack, the password will be leaked. Most app project passwords are front-end md5 encrypted and transmitted to the server, so that even if https is cracked, the password will not be leaked.
