### ISSUE TITLE
Settings - Profile - move English (US) and English (UK) to the top

### ISSUE THREAD

**Issue by mxdpeep** [umami-software/umami#2259]
### Describe the feature or enhancement

I think it would make sense to move the two mostly used languages to the top of the listbox.

**Comment by asantesylvesterkwame** [comment]
please provide an image and Assign me to this task.

**Comment by mxdpeep** [comment]
![Screenshot_20231022-083350-082](https://github.com/umami-software/umami/assets/75358/de3c4541-7997-4c40-aad2-eb51d6005720)

**Comment by asantesylvesterkwame** [comment]
Thank you I am working on it right now

**Comment by asantesylvesterkwame** [comment]
Please I have fixed it and made a pull request
