### ISSUE TITLE
The GeoLite2-City.mmdb file needs to be re-downloaded every time the project is built.

### ISSUE THREAD

**Issue by loongtex** [umami-software/umami#2265]
### Describe the Bug

Every time, I run this command: `yarn build`
Then

The GeoLite2-City.mmdb file needs to be re-downloaded .

I think it's not necessary.

I am a Chinese developer with poor network conditions. This large file has to be re-downloaded every time, which is very frustrating.

I look forward to waiting for a reply, thank you, thank you very much, this project is very awesome~

### Database

PostgreSQL

### Relevant log output

```shell
No pending migrations to apply.

✓ Database is up to date.
$ rollup -c rollup.tracker.config.mjs

src/tracker/index.js → public/script.js...
created public/script.js in 358ms
$ node scripts/build-geo.js

Saved geo database: /opt/umami/geo/GeoLite2-City.mmdb
......(You have to wait about 30 minutes every time)
```

**Comment by mikecao** [comment]
Just remove `build-geo` from the build command.

**Comment by loongtex** [comment]
Thank you very much, I will try it now
