### ISSUE TITLE
Filter values for Country and Region

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#2271]
### Describe the feature or enhancement

Here are two things which I think could be great for useability:

-When choosing a country filter, countries in dropdown are ordered by country code in alphabetical order,
but because these codes are expanded to the full names, the resulting order isn't very user friendly:

![country-order](https://github.com/umami-software/umami/assets/12450219/88cb0d63-d726-4a91-9ef5-1e3128ddfc6b)

\
-When choosing a region filter, regions are displayed with their codes, not expanded.
It might be great to display the pretty full names, but it also raises the previous 'issue' about the resulting order.

![region-names](https://github.com/umami-software/umami/assets/12450219/33a92bfd-a484-4d1f-a509-606bb290a5f7)

\
(and btw, region expansion part is the reason why I didn't finalize translation support for filter tags, in order to first raise the question here)

**Comment by franciscao633** [comment]
Both good points. Dropdown should be alphabetical and displayed by their names and not codes. Thanks for reporting.

**Comment by mikecao** [comment]
Fixed in v2.9.0.
