### ISSUE TITLE
Allow Realtime page to show all websites (it used to but now only shows an individual website at a time)

### ISSUE THREAD

**Issue by kublermdk** [umami-software/umami#2277]
### Describe the feature or enhancement

I think in v2.3.0 you change the way the realtime page works so it's per website.

I've just done a painful migration from an early version 1 of the app to the latest v2.6.2 and found that the main reason I love Umami so much, **the fact that we can see all the activity over all the websites on the Realtime page has disappeared**.

This feature was one of the things I felt really set Umami apart from other options like Google Analytics.

I'm now trying to DOWNGRADE to v2.2.0 in order to get what I think is the latest version which supports this.

Is there a way to allow realtime per website like the latest version does, but also bring back a Realtime functionality for all websites or maybe a list of the websites?

I saw in the latest NodeJS code it uses a specific Website ID, but I haven't checked to see if in the API you could allow an array of website IDs or not provide any and get all the sites again?

Maybe someone can point me to where I'd need to change in order for me to work on this? (Noting that I'm not that good at ReactJS, better at the backend side of things)

**Comment by franciscao633** [comment]
I believe Realtime was changed in v2. You would need to go back to v1 to see how it was implemented. Not exactly sure what the future plans for Realtime are, but I can check with the team to see if this can be re-implemented.

**Comment by kublermdk** [comment]
@franciscao633 It would be great if you could at least see if this can be re-implemented.

It really is a great selling point (at least for me and the team) compared to the other analytics systems I've used.

I'm guessing you'd need:

- An API endpoint that can return results of all domains. This is probably very similar to the existing endpoint just a less restricted SQL query? It could even be an existing endpoint just a specific (e.g empty) request for the domain.
- A Realtime Nav bar entry in the top (or in somewhere like Reports)
-  The Realtime page having the session info with the domain. So you can see which domain the requests are being processed from.


[Example screenshot](https://www.dropbox.com/scl/fi/xk0p8i1b1jh6fpl1zft1m/Realtime-Umami-showing-different-domains.png?rlkey=9x0837khujfgir76z5htzrk4l&dl=0)

![Screenshot of the old Umami v1](https://www.kublermdk.com/wp-content/uploads/2023/09/Realtime-Umami-showing-different-domains.png)
