### ISSUE TITLE
Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [umami-software/umami#2281]
### Describe the Bug

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

Steps To Reproduce
Scroll to footer section and see twitter old logo

Expected behavior
Twitter logo should be changed to X

Screenshot
<img width="960" alt="Screenshot 2023-09-10 082740" src="https://github.com/umami-software/umami/assets/91591901/d6ad2902-31b0-4fb2-ab16-1851bb76226d">

@screendriver 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Database

PostgreSQL

### Which browser are you using? (if relevant)

chrome

**Comment by franciscao633** [comment]
Your screenshot points to hasura, but I think this is more website related. There is already a PR in  the [website repo](https://github.com/umami-software/website/pull/132)) for something similar.
