### ISSUE TITLE
365 Days PageViews API

### ISSUE THREAD

**Issue by YiHui-Liu** [umami-software/umami#2294]
### Describe the feature or enhancement

The pageview API in the V1 version can get the number of daily visits within 1 year, but in the latest version of the API, if the duration exceeds 90 days, it will automatically merge into monthly data.

**Comment by franciscao633** [comment]
Im labeling this as a bug. You should be able to override the unit parameter to display by day.

**Comment by YiHui-Liu** [comment]
The same problem occurs when trying to get the number of monthly visits for more than 3 years

**Comment by franciscao633** [comment]
There is a limit on the Unit Parameter documented [here](https://umami.is/docs/website-stats).

```
Unit Parameter

The unit parameter buckets the data returned. The unit is automatically converted to the next largest applicable time unit if the maximum is exceeded.

minute: Up to 60 minutes.
hour: Up to 48 hours.
day: Up to 12 months.
month: Up to 2 years.
year: No limit.
```

**Comment by franciscao633** [comment]
Actually we will probably remove the limit for `month` as well. Will let you know once updated.

**Comment by mikecao** [comment]
Fixed in v2.9.0.

**Comment by YiHui-Liu** [comment]
it seems that the limit for `day` is less than 300 days with `v2.13.2`.

PS: i fix mariadb with:
```
npx prisma migrate resolve --applied "05_add_visit_id"
```

I don't know weather it will have an impact.

**Comment by YiHui-Liu** [comment]
i have updated `umami` to 3.0.0, but if the number of days exceeds 180 days like `/pageviews?startAt=1746028800000&endAt=1763044095644&unit=day`, it will return monthly data.

<img width="2877" height="276" alt="Image" src="https://github.com/user-attachments/assets/4e7b8a80-f31a-4e72-a7be-7edc434f38fe" />
