### ISSUE TITLE
Sign up: Email Verification Link not received in Email

### ISSUE THREAD

**Issue by marktoh** [umami-software/umami#2298]
### Problem
I am looking to try out Umami Cloud and tried to register as a new user. After entering the relevant information and clicking on Sign up, I waited for the email verification link in my email but did not receive it after `1 hour`. I have checked my `Spam` mail to be sure.

### Reproduction Steps
1. Visit https://umami.is/
2. In the header, click `Sign up`
3. Once navigated to https://cloud.umami.is/signup?ref=header, enter `name`, `email`, `password` and `how did you hear about us?`
4. Click `Sign up`
5. Wait for email verification link

### Database

Umami Cloud

### Which browser are you using? (if relevant)

Chrome

**Comment by apps4research** [comment]
samer here ...

**Comment by franciscao633** [comment]
We had an issue with our email service yesterday to this morning. It should be resolved. If you need us to manually confirm your account please send us an email. Also if you still have issues with receiving emails let me know and we will take another look.

**Comment by marktoh** [comment]
I was able to login and request an email verification link. However, I was not able to receive the verification link in my email. Which email address should I contact?


| Description | Screenshot |
| ------------- | ------------- |
| Confirmation of verification email request  | <img width="408" alt="Screenshot 2023-09-22 at 9 51 48 AM" src="https://github.com/umami-software/umami/assets/25725495/d18463e5-d7b0-43bd-8a7a-dafba7c0dd2c">  |

**Comment by apps4research** [comment]
yes, I have the same. I logged in and resent the verification email, but no luck - nothing arrived.

**Comment by franciscao633** [comment]
Sorry again. Our new email service was continuing to have issues yesterday. Can you please try one more time or email us at support@umami.is. Thank you.

**Comment by apps4research** [comment]
Thank you, it worked now :)

**Comment by marktoh** [comment]
I am able to log in now. Thank you!

**Comment by zenminimalist** [comment]
I'm having the same issue.

**Comment by briancao** [comment]
@zenminimalist We've since changed our verification process.  Please email us at support@umami.is and we'll be happy to troubleshoot.

**Comment by raf202** [comment]
Same issue

**Comment by prerakpatel** [comment]
Is anyone seeing this same issue, still as of July 2026? I am not receiving any verification codes even after three tries.

**Comment by Majekdor** [comment]
Also seeing this issue. Tried 3 times and checked spam.
