### ISSUE TITLE
Api Internal Server Error

### ISSUE THREAD

**Issue by vinumweb** [umami-software/umami#2301]
### Describe the Bug

When calling any of the api modules it just returns Internal Server Error.
I don't know what im doing wrong.
This is my postman script: "https://{{analytics_url}}/api/auth/login?username={{analytics_username}}&password={{analytics_password}}"

Thanks, Peter.

### Database

MySQL

### Relevant log output

```shell
I don't know what logs to check
```

### How are you deploying your application? (if relevant)

Hostinger VPS, OpenLiteSpeed, CyberPanel

**Comment by briancao** [comment]
You need to send the username and password in the request body, and use a POST.

Our API documentation details on what calls are available to you.  https://umami.is/docs/authentication
