### ISSUE TITLE
Disable auto redirect to '/login' if not logged-in

### ISSUE THREAD

**Issue by SmartPhoneLover** [umami-software/umami#2304]
### Describe the feature or enhancement

I talked about this, but in a different context in the Discord server. I will explain it in a different and easier way to see what you think about it.

By default, if the user is not currently signed in, Umami redirects it to its login page when the user enters the main domain where Umami is available, if the **DISABLE_LOGIN** variable is not enabled. This is ok, and I like it. But...

When we configure Umami in a CDN (ie.: Cloudflare), setup access rules for the /login page, and of course we don't want to loose the access to the admin panel because of it being exposed, it just doesn't work, because:

- The automatic redirection to /login allows the user to easily bypass the block rules.
- If applying the block rules to the main domain you will loose API communication, so no metrics are collected anymore.

I suggest to change how the /login page is configured, to force the user to access manually, for example:

- Show a static (or customized) page when accessing the base Umami domain (ie.: `https://web-metrics.<my-domain>.ext`) with a button or an option to click on, and it will redirect us to the /login page.
- Just show a static page when accessing the base Umami domain, and require the user to type /.../login manually to get access to the admin panel.

I think, this will allow us to customize blocking rules easily.

**Comment by franciscao633** [comment]
I feel the redirect is beneficial and straight-forward in most scenarios. However, if you need to disable the redirect you can just alter the catch in `useRequireLogin.ts` and redirect to a simple static page of your liking. Could just be a single button like your said.

**Comment by SmartPhoneLover** [comment]
Good suggestion @franciscao633 
Thank you!

So, I think I will close the issue, as it solves it with a good alternative.

**Comment by SmartPhoneLover** [comment]
Sorry, but I didn't apply the suggested solution until today.

I couldn't find the _useRequireLogin.ts_ file in the docker image.

Where is it located?
