### ISSUE TITLE
npm run start-env extra argument array is missing

### ISSUE THREAD

**Issue by mho22** [umami-software/umami#2308]
### Describe the Bug

The Next CLI `next-start.js` script called by the `start-env.js` script in the `scripts` folder from Umami highlighted an issue on line 38 : 

```
const dir = (0, _getprojectdir.getProjectDir)(args._[0]);
```

Because what was inserted in the parameters of the function `cli.nextStart(['-p', process.env.PORT || 3000, '-H', process.env.HOSTNAME || '0.0.0.0'])` didn't have the `args._` array defined.

I resolved the problem, changing the initial code of `start-env.js` : 

```
require('dotenv').config();
const cli = require('next/dist/cli/next-start');

cli.nextStart(['-p', process.env.PORT || 3000, '-H', process.env.HOSTNAME || '0.0.0.0']);
```

as : 

```
require('dotenv').config();
const cli = require('next/dist/cli/next-start');

let args = ['-p', process.env.PORT || 3000, '-H', process.env.HOSTNAME || '0.0.0.0'];

args._ = [];

cli.nextStart( args );
```

I know it is probably not the most efficient way to bypass the problem, that is why I created an issue instead of a PR. But if you like to let me create a PR, I will, based on your insights. 

### Database

MySQL

### How are you deploying your application? (if relevant)

Laravel Forge on a different port

**Comment by franciscao633** [comment]
I think you can just pass in an object like below. For some reason the shorthand `-p` and `-H` didn't translate, not sure how it worked before. Feel free to test and put in a PR.
```
require('dotenv').config();
const cli = require('next/dist/cli/next-start');

cli.nextStart({
  '--port': process.env.PORT || 3000,
  '--hostname': process.env.HOSTNAME || '0.0.0.0',
  _: [],
});
```

**Comment by Itemshopp** [comment]
Tested and added Pull Request #2314 related to this issue
