### ISSUE TITLE
No more monthly salt in uuid

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#2311]
### Describe the Bug

A monthly salt was previously used in uuid generation here:
https://github.com/umami-software/umami/blob/master/src/lib/crypto.js

This made a session with same details to have a different session_id over months.
It's not used anymore and it doesn't look like a deliberate choice.

### Database

PostgreSQL

**Comment by mikecao** [comment]
This is a bug. It should be part for the uuid function.

**Comment by mikecao** [comment]
Fixed in v2.9.0.
