### ISSUE TITLE
CSS hides part of a button on mobile

### ISSUE THREAD

**Issue by timonson** [umami-software/umami#2315]
### Describe the Bug

On the **shared URLs** the button "Filter" is not completely inside the frame. Please take a look at the screenshot.  The button is almost completely gone on 360px width.

![Screenshot from 2023-10-02 00-21-21](https://github.com/umami-software/umami/assets/54777088/a03e4623-f459-47b4-91dc-b5384993aa2c)

**Comment by 0amirk** [comment]
can you please give me the steps to reproduce this issue again. I found similar thing happening on the page that loads when I click view demo. I might be able to fix it.

**Comment by FHU-yezi** [comment]
> can you please give me the steps to reproduce this issue again. I found similar thing happening on the page that loads when I click view demo. I might be able to fix it. 
> 

Just use DevTools and simulate a device likes a phone.

**Comment by 0amirk** [comment]
> > can you please give me the steps to reproduce this issue again. I found similar thing happening on the page that loads when I click view demo. I might be able to fix it.
> 
> Just use DevTools and simulate a device likes a phone.

I did that. 👍 I'll try to solve it asap.
