### ISSUE TITLE
"Invalid share ID" after editing&saving Domain

### ISSUE THREAD

**Issue by kornelj** [umami-software/umami#2317]
### Describe the Bug

Hey There,
After successfull migration to v2.7.0, Im getting "Invalid share ID" after editing&saving Domain on Website Settings page, Details tab, eventhough I dont touch any other filed but Domain. Apart from this, all feature works fine!

It goes away once I regenerate the share id but I dont want to re-generate 100s of urls and disturb users replcing it.
I assume this share ID check has been changed and older IDs are not conforming
Thank you.

### Database

PostgreSQL

### Relevant log output

```shell
"Invalid share ID."
```

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
Do you know what version you upgraded from? I believe we changed some share ID logic back in August a couple releases ago. Wondering if it's from that. Either way we need to look into this if its causing old share ID's to become invalid.

**Comment by kornelj** [comment]
from v.1.40

**Comment by franciscao633** [comment]
Sorry for the late reply. We updated our validations to allow old generated share ID's to pass as well. This will be included in the next release in the next day or so.

**Comment by kornelj** [comment]
Thanks a lot!

**Comment by mikecao** [comment]
Fixed in v2.8.0.
