### ISSUE TITLE
Specify db schema other than public

### ISSUE THREAD

**Issue by Nikola-Milovic** [umami-software/umami#2323]
### Describe the feature or enhancement

I cannot seem to find an environment variable or an option to specify a custom schema other than public. It would be nice to have this level of configuration

**Comment by franciscao633** [comment]
Sorry for the late reply. I'm guessing you are using postgreSQL? You can add the schema to your DATABASE_URL like below to target a specific schema.

```
DATABASE_URL=postgresql://username:mypassword@localhost:5432/mydb?schema=myschema
```
