### ISSUE TITLE
Uami is not working under Matomo Tag Manager.

### ISSUE THREAD

**Issue by dotmcdh** [umami-software/umami#2324]
### Describe the Bug

I want to add a tracking code using Matomo Tag Manager, but in this way, uami is not tracking traffic. When I add this same code directly in the head, it is working.

P.S.
Other scripts are working with Matomo Tag Manager, and also with plausible and other competitors' uami. Is this normal?

### Database

PostgreSQL

**Comment by mxdpeep** [comment]
try this JS code (replace ***):

`(function() {
  var el = document.createElement('script');
  el.setAttribute('src', '***/script.js');
  el.setAttribute('data-website-id', '***');
  document.body.appendChild(el);
})();
`
