### ISSUE TITLE
Missing Window Mobile icon image

### ISSUE THREAD

**Issue by matt-clegg** [umami-software/umami#2326]
### Describe the Bug

I've noticed the Windows Mobile os listing is missing it's icon image.

![image](https://github.com/umami-software/umami/assets/34515355/d64a9da4-980b-4270-96f2-7840789064cd)

![image](https://github.com/umami-software/umami/assets/34515355/c3ec8979-67bc-4025-86af-55f924d80fe4)

### Database

PostgreSQL

**Comment by franciscao633** [comment]
Thanks for reporting. A png file for windows-mobiled will be added

**Comment by mikecao** [comment]
Fixed in v2.8.0.
