### ISSUE TITLE
Dashboard and buttons are not aligned on mobile view

### ISSUE THREAD

**Issue by GamerKingFaiz** [umami-software/umami#2332]
### Describe the Bug

On the `/dashboard` page, the Dashboard title and the actions button at the top are misaligned when viewed on mobile.
![image](https://github.com/umami-software/umami/assets/9065136/29e68bef-5b9a-49f5-a73a-744ec4eb6b82)

Removing the following two CSS properties seems to resolve the issue.
![image](https://github.com/umami-software/umami/assets/9065136/e3e9e591-ac4e-4dd8-8326-faa6c07fe857)

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

**Comment by franciscao633** [comment]
We have a current task to improve our mobile app / UI. Will attach this to the ticket. Thanks.

**Comment by devarshishimpi** [comment]
Hey! I would love to contribute to this issue along with @gambhirsharma
We both would work on this in a team and provide you with the fix PR while keeping the Contributing Guidelines in mind.
Requesting the team to kindly assign the issue to both of us! Thanks!

**Comment by gambhirsharma** [comment]
Yes please assign us this issue.

**Comment by mikecao** [comment]
Fixed in v2.9.0.
