### ISSUE TITLE
Incorrect referrer parameter in /api/send

### ISSUE THREAD

**Issue by googlecosplay** [umami-software/umami#2339]
### Describe the Bug

version: 2.7
deploy: docker

When redirecting from Google to a website, it was detected that the document. referrer was correct, but the referrer carried in the request sent by/API/send was incorrect, resulting in the source domain name being none in the monitoring data

![image](https://github.com/umami-software/umami/assets/147607002/4f0b3180-46d3-4031-adce-ce23cb87d01d)

### Database

MySQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by mklabcn** [comment]
Yes, many requests do not have referers
