### ISSUE TITLE
Use keep-alive in fetch()

### ISSUE THREAD

**Issue by Nikola-Milovic** [umami-software/umami#2340]
### Describe the feature or enhancement

It can be a nice improvement to use [keep-alive](https://developer.mozilla.org/en-US/docs/Web/API/fetch#keepalive) option for fetch. Since Umami is not using [`navigator.sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon), the events are not guaranteed to be delivered, especially if we want to track outgoing links (when the user leaves the page). Keep-alive is the simple alternative to the problem, it will allow the request to outlive the page

**Comment by mikecao** [comment]
We've tested this and neither keep-alive or sendBeacon works with Firefox.

**Comment by uiii** [comment]
@mikecao Looks like the situation has changed 
![image](https://github.com/user-attachments/assets/e6613744-58c3-4a8e-b9f5-dd7d996177f8)
