### ISSUE TITLE
Different docker images in README and docs

### ISSUE THREAD

**Issue by orgarten** [umami-software/umami#2342]
### Describe the Bug

The readme and the docs recommend different docker images:

In the [docs](https://umami.is/docs/install): ghcr.io/umami-software/umami:postgresql-latest

In the [README](https://github.com/umami-software/umami/blob/master/README.md#installing-with-docker): docker.umami.dev/umami-software/umami:postgresql-latest

The one from docker.umami.dev actually does not have the problem described by PR #2182 .

### Database

PostgreSQL

**Comment by joemaller** [comment]
It's the same image, `4cf0f05a398c`

```
docker pull ghcr.io/umami-software/umami:postgresql-latest
docker pull docker.umami.dev/umami-software/umami:postgresql-latest
```
Results from `docker image list`: 
```
REPOSITORY                              TAG                   IMAGE ID       CREATED         SIZE
ghcr.io/umami-software/umami            postgresql-latest     4cf0f05a398c   2 weeks ago     454MB
docker.umami.dev/umami-software/umami   postgresql-latest     4cf0f05a398c   2 weeks ago     454MB
```
it would be good to pick a single address for consistency and to reduce confusion and potential errors. 

The image is also on DockerHub, but that one _is_ different:
```
umamisoftware/umami                     postgresql-latest     a13b634a1503   2 weeks ago     461MB
```

**Comment by orgarten** [comment]
Interesting, because the docker image from `docker.umami.dev` actually works on my ARM64 server and the one from `ghcr.io` doesnt due to the issue mentioned in #2182 .
