### ISSUE TITLE
Be able to filter the activity log by event property

### ISSUE THREAD

**Issue by onze** [umami-software/umami#2343]
### Describe the feature or enhancement

I'm looking at the activity log and it's a great overview of what's happening in the site :+1: 
Now I'd like to be able to focus on one single user and see their activity and custom events they trigger while using my site. In order to do that, I'd like the activity log to include a filter where I select what event prop and value to display. Or maybe there's another way to achieve this?

edit:
I'm talking about this view:
![image](https://github.com/umami-software/umami/assets/297607/ecc0f0cd-efb8-4ab6-8968-30194116d1f6)

**Comment by mikecao** [comment]
This will go out in the next release.

**Comment by mikecao** [comment]
Fixed in v2.9.0.
