### ISSUE TITLE
2.4 to 2.x Migration error

### ISSUE THREAD

**Issue by diarpu** [umami-software/umami#2344]
### Describe the Bug

Since the 2.5 update it has been impossible for me to apply the new updates.
The error I have **Cpanel** and I would like to take advantage that I have this to store the database there. any ideas?

I have tried Planetscale and it does not present any problem.

### Database

MySQL

### Relevant log output

```shell
✓ DATABASE_URL is defined.
✓ Database connection successful.
✓ Database version check successful.
Error: P3018

A migration failed to apply. New migrations cannot be applied before the error is recovered from. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

Migration name: 03_metric_performance_index

Database error code: 1071

Database error:
Specified key was too long; max key length is 1000 bytes

Please check the query number 2 from the migration file.
```

### How are you deploying your application? (if relevant)

Vercel

**Comment by mikecao** [comment]
What version of MySQL are you using?

**Comment by diarpu** [comment]
Hi, sorry, it seems that in the end it is MariaDB: 10.5.22-MariaDB-cll-lve.
Until version 2.4 it was going perfect, I don't know if it can be fixed, for now I will have to stay on that version
