### ISSUE TITLE
Websites in the report dropdown are cut off

### ISSUE THREAD

**Issue by thueske** [umami-software/umami#2346]
### Describe the Bug

I have an Umami installation with 18 websites. Unfortunately, when selecting websites in the report creation process, only the pages of the first page (pagination) are displayed. I cannot create reports for 8 websites because they simply do not appear in the dropdown.

<img width="1756" alt="image" src="https://github.com/umami-software/umami/assets/436986/a76db0ff-8416-41ca-a740-ba4d832704eb">

### Database

PostgreSQL

**Comment by briancao** [comment]
Hi Tobias,

We have this resolved in the next release.  The results will be scrollable in the next release (coming the next few days).  In the future, we plan to replace this w/ a search-centric combobox.

**Comment by briancao** [comment]
Addressed in release 2.8.

**Comment by mikecao** [comment]
Fixed in v2.8.0.
