### ISSUE TITLE
[Bug?] Missing URL links in page view, titles are displayed correctly however

### ISSUE THREAD

**Issue by zenminimalist** [umami-software/umami#2353]
### Describe the Bug

I'm not 100% this is a bug, but I think it is.

When looking at the pages section, I only see on entry that seems to aggregate all page views under `/`and not the actual URL, like so:

![CleanShot 2023-10-18 at 01 10 33@2x](https://github.com/umami-software/umami/assets/7798503/4ac21ff4-9eea-4a8e-b486-6f7c2c463d90)

If I switch to titles, the titles are display and the views are separated by percentage, like so:

![CleanShot 2023-10-18 at 01 10 40@2x](https://github.com/umami-software/umami/assets/7798503/4ab56054-085d-4014-9a01-023052f79e37)

I did enable the `REMOVE_TRAILING_SLASH = 1` variable during docker deployment. Not sure if that plays a rule, but that is supposed to just remove the trailing slash, right? Not the whole link... 

Overall, it's a very strange behavior. Let me know what I need or can provide in order to narrow in if this is a bug. 

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Vivaldi (Chrome based)

### How are you deploying your application? (if relevant)

selfhosted

**Comment by mikecao** [comment]
Can you send us a CSV export of your website_events table?

**Comment by zenminimalist** [comment]
That is empty. Or am I looking in the wrong place?

![CleanShot 2023-10-18 at 10 51 29@2x](https://github.com/umami-software/umami/assets/7798503/6c5bdfe3-f362-49d8-bdff-ded7c1f18b0e)

I quickly checked the logs of the two containers, no errros.

**Comment by zenminimalist** [comment]
Maybe just to add, I checked my CF account (the website that is **using** the Umami tracker is behind CF proxy). However, the server (different from the website using umami) that is serving the tracker is not behind the CF proxy.

In just 24 hours, I'm seeing more visitors. I don't know how many bots that includes. 
 
![CleanShot 2023-10-18 at 11 28 37@2x](https://github.com/umami-software/umami/assets/7798503/af8c7921-c2da-415e-a1c2-863f0aead9fa)

**Comment by zenminimalist** [comment]
@blyamur Interesting.  

So it seems that it is not just related to my setup. Maybe there are some commonalities in terms of setup. That might rule out some things, I don't know. What are you using? 

I'm using WP, Cyberpanel and Openlitespeed and CF to proxy traffic.

**Comment by QingShan-Xu** [comment]
Maybe it's the spa app?
It's a little short on details, but it works:
```typescript
import { useEffect, useRef } from 'react'
import { useLocation } from 'react-router-dom'

export const useUmami = () => {
  const location = useLocation()
  const preLocation = useRef('')

  useEffect(() => {
    if (preLocation.current === location.pathname) {
      return
    }

    preLocation.current = location.pathname

    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    umami.track((props) => ({ ...props, url: preLocation.current }))
  }, [location])
}

```
