### ISSUE TITLE
Arrows "prev" and "next" inverted when "Yesterday" range selected

### ISSUE THREAD

**Issue by Gouttfi** [umami-software/umami#2358]
### Describe the Bug

When I select "Yesterday" in time range, the arrows seems to be inverted.
Clicking in next arrow goes to precedent day (-1)
Clicking in prev arrow goes to next day (+1)

![image](https://github.com/umami-software/umami/assets/56838707/7629906d-bc59-433e-9cde-9bcdbcc221e3)

I click in right arrow [ > ] : 
![image](https://github.com/umami-software/umami/assets/56838707/d18117d8-65b0-417e-aca0-c169aeae71f6)

I click in right arrow [ > ] : 
![image](https://github.com/umami-software/umami/assets/56838707/ce04397d-6a1a-4c6d-92b0-6d125de06a60)

I click in right arrow [ > ] : 
![image](https://github.com/umami-software/umami/assets/56838707/c866b781-2c7e-4f3e-9bb1-048e99a17ba4)

I click in left arrow [ < ] : 
![image](https://github.com/umami-software/umami/assets/56838707/7445df68-35ac-49a8-954b-fade14ce5b94)

All other ranges seems not to have this issue.
Tested in Firefox and Edge, same problem.

### Database

Umami Cloud

### Which browser are you using? (if relevant)

Firefox, Edge

**Comment by asantesylvesterkwame** [comment]
please assign me to this task.

**Comment by franciscao633** [comment]
feel free to put in a PR and we will approve. Thanks.

**Comment by abrar78** [comment]
IS this issue still open @franciscao633

**Comment by Gouttfi** [comment]
Here is the PR : https://github.com/umami-software/umami/pull/2375

**Comment by mikecao** [comment]
Fixed in v2.9.0.
