### ISSUE TITLE
v2.8.0 docker won't start

### ISSUE THREAD

**Issue by baubie** [umami-software/umami#2360]
### Describe the Bug

Upon starting up v2.8.0 via docker you get a Node.js error on the semver package.  Downgrading back down to v2.7.0 starts fine.

### Database

PostgreSQL

### Relevant log output

```shell
yarn run v1.22.19
umami_1  | $ npm-run-all check-db update-tracker start-server
umami_1  | node:internal/modules/cjs/loader:446
umami_1  |       throw err;
umami_1  |       ^
umami_1  |
umami_1  | Error: Cannot find module '/app/node_modules/semver/index.js'. Please verify that the package.json has a valid "main" entry
umami_1  |     at tryPackage (node:internal/modules/cjs/loader:438:19)
umami_1  |     at Module._findPath (node:internal/modules/cjs/loader:680:18)
umami_1  |     at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
umami_1  |     at Module._load (node:internal/modules/cjs/loader:922:27)
umami_1  |     at Module.require (node:internal/modules/cjs/loader:1143:19)
umami_1  |     at require (node:internal/modules/cjs/helpers:119:18)
umami_1  |     at Object.<anonymous> (/app/node_modules/cross-spawn/lib/parse.js:8:16)
umami_1  |     at Module._compile (node:internal/modules/cjs/loader:1256:14)
umami_1  |     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
umami_1  |     at Module.load (node:internal/modules/cjs/loader:1119:32) {
umami_1  |   code: 'MODULE_NOT_FOUND',
umami_1  |   path: '/app/node_modules/semver/package.json',
umami_1  |   requestPath: 'semver'
umami_1  | }
umami_1  |
umami_1  | Node.js v18.18.2
umami_1  | error Command failed with exit code 1.
umami_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```


### Which browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

Docker

**Comment by hibobmaster** [comment]
Same here.

**Comment by anseltaft** [comment]
I get "404 page not found" in the browser.

In the docker log I noticed that the Node.js version reverted to 18.x despite the node version being set in my docker-compose.yml file from a legacy fix:

    environment:
      NODE_VERSION: 20.0.0

**Comment by mikecao** [comment]
Looking into it. For some reason the docker build pulled a broken version of `semver`. Have no idea how that can happen.

**Comment by KevinYouu** [comment]
Same issues.
<img width="1313" alt="截屏2023-10-20 10 07 58" src="https://github.com/umami-software/umami/assets/46970005/2c4aa2cb-43bb-48d7-a104-86f5fba81d3e">

**Comment by yumusb** [comment]
I think I'm taking a gamble every time umami releases a new version.

**Comment by mikecao** [comment]
Just pushed out new images. Please redownload and try.

**Comment by hibobmaster** [comment]
It works! Thank you for your great project!

**Comment by buyfakett** [comment]
> Just pushed out new images. Please redownload and try.
Error reported during editing:
Loading chunk 5767 failed. (error: https://umami.nmg.buyfakett.top/_next/static/chunks/app/(main)/settings/websites/%5Bid%5D/page-ab17dd36bef17a12.js)
ChunkLoadError: Loading chunk 5767 failed.
(error: https://umami.nmg.buyfakett.top/_next/static/chunks/app/(main)/settings/websites/%5Bid%5D/page-ab17dd36bef17a12.js)
    at l.f.j (https://umami.nmg.buyfakett.top/_next/static/chunks/webpack-d29b485d209acb6d.js:1:3768)
    at https://umami.nmg.buyfakett.top/_next/static/chunks/webpack-d29b485d209acb6d.js:1:1409
    at Array.reduce (<anonymous>)
    at l.e (https://umami.nmg.buyfakett.top/_next/static/chunks/webpack-d29b485d209acb6d.js:1:1375)
    at self.__next_chunk_load__ (https://umami.nmg.buyfakett.top/_next/static/chunks/7864-ed02d4d09d2fae55.js:1:5937)
    at https://umami.nmg.buyfakett.top/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:5751
    at https://umami.nmg.buyfakett.top/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:5974
    at t (https://umami.nmg.buyfakett.top/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:6177)

**Comment by mxdpeep** [comment]
> I think I'm taking a gamble every time umami releases a new version.

as a senior dev I always wait 1-2 months before updating the production :)

**Comment by anseltaft** [comment]
The update fixed me up but @mikecao I wonder if we still need two items in the environment declarations:

    environment:
      HOSTNAME: 0.0.0.0
      NODE_VERSION: 20.0.0

I had to add the HOSTNAME declaration to fix a bug in the last release and added NODE_VERSION: 20.0.0 to fix some other bug maybe three or four versions ago. Are either still needed?

**Comment by Cybermb** [comment]
@mikecao This is still an issue when pulling a tag release branch.

**Comment by mxdpeep** [comment]
weird - my Docker install works from scratch - see https://github.com/GSCloud/umami
