### ISSUE TITLE
Error reported during editing in V2.8.0

### ISSUE THREAD

**Issue by buyfakett** [umami-software/umami#2361]
### Describe the Bug

Error reported during editing:
Loading chunk 5767 failed. (error: https://test/_next/static/chunks/app/(main)/settings/websites/%5Bid%5D/page-ab17dd36bef17a12.js)
ChunkLoadError: Loading chunk 5767 failed.
(error: https://test/_next/static/chunks/app/(main)/settings/websites/%5Bid%5D/page-ab17dd36bef17a12.js)
at l.f.j (https://test/_next/static/chunks/webpack-d29b485d209acb6d.js:1:3768)
at https://test/_next/static/chunks/webpack-d29b485d209acb6d.js:1:1409
at Array.reduce ()
at l.e (https://test/_next/static/chunks/webpack-d29b485d209acb6d.js:1:1375)
at self.next_chunk_load (https://test/_next/static/chunks/7864-ed02d4d09d2fae55.js:1:5937)
at https://test/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:5751
at https://test/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:5974
at t (https://test/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:6177)

### Database

PostgreSQL

**Comment by mikecao** [comment]
What does during editing mean? How are you deploying the app?

**Comment by buyfakett** [comment]
version: "3"
services:
  umami:
    image: buyfakett/umami:postgresql-v2.8.0
    container_name: umami
    ports:
      - "3010:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
    depends_on:
      db:
        condition: service_healthy
    restart: always
  db:
    image: postgres:12-alpine
    container_name: umami_db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


After adding the website, clicking the edit or view button will result in these errors

**Comment by mikecao** [comment]
Why is your image `image: buyfakett/umami:postgresql-v2.8.0` different from the default?

**Comment by buyfakett** [comment]
Sorry, I am using this image:ghcr.io/umami-software/umami:mysql-v2.8.0
I uploaded this image to the Docker Hub because my server cannot access GitHub

**Comment by mikecao** [comment]
This is fixed in the latest version of Next.js. You can try updating and rebuilding your image.

**Comment by buyfakett** [comment]
I tried to build the `analytics` branch, and this bug has been resolved

**Comment by BenJamesAndo** [comment]
I also had this issue. Running `npm install next@latest --force` fixed it for me. Is that the best way to do it? I'm using MySQL and Node 18 LTS.

**Comment by DroidBV8** [comment]
Not for me :(

I have the same error but with nginx proxy only. 
In HTTP Direct access with 3000 port I haven't got the error.

ubuntu 20.01
v18.17.1
yarn run v1.22.19
Next.js 13.5.3

Very strange.

**Comment by franciscao633** [comment]
Combining with #2310.
