### ISSUE TITLE
Country not captured in realtime, but does in overview

### ISSUE THREAD

**Issue by erikpena** [umami-software/umami#2369]
### Describe the Bug

Hello!
I've set up Umami using Docker Compose inside of a private network and am using Cloudflare Tunnels to expose it publicly.

Here's how I've added the script tag to my application (`src` and `data-website-id` is actually populated)—

```html
<script
  src=""
  data-website-id=""
  data-auto-track="false"
></script>
```

I'm tracking page views manually using the following snippet of code—

```js
const viewProperties:ViewProperties = {
  hostname: window.location.hostname,
  language: window.navigator.language,
  referrer: window.document.referrer,
  screen: `${window.screen.width}x${window.screen.height}`,
  title: window.document.title,
  url: window.location.pathname,
  website: websiteId
};

umami.track(viewProperties);
```

I've noticed that when these views are being captured by Umami, in the Realtime page, the Country isn't getting information whereas everything else in the realtime view is getting details.  Here is an example image—

<img width="1322" alt="Screenshot 2023-10-28 at 09 57 37" src="https://github.com/umami-software/umami/assets/2187347/50a67a75-43ca-47c9-b4cc-a6963e5827aa">

However, if I wait for the view to cycle out of the realtime and fall into the Overview page, the Country is now being displayed as I would expect—

<img width="1312" alt="Screenshot 2023-10-28 at 09 56 38" src="https://github.com/umami-software/umami/assets/2187347/ace7c520-2ebf-4340-ab36-53333da077ef">

Is there anything I need to do in order to get Country to show up in Realtime?

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker Compose using Coolify v4

**Comment by mikecao** [comment]
Realtime and the overview page are pulling the same data, so they should be the same. Might be a bug, will investigate.

**Comment by erikpena** [comment]
Thank you!  This was on v2.8.0 if that helps.
