### ISSUE TITLE
Error reporting when editing website and view detail website with reverse proxy

### ISSUE THREAD

**Issue by DroidBV8** [umami-software/umami#2371]
### Describe the Bug

Hello, 

I have installed umami on Ubuntu server last LTS with postgresql and configured a reverse proxy with nginx. All access is good and install is OK without error

--> I have this error when i want to edit a website :

![image](https://github.com/umami-software/umami/assets/71468154/b377ff18-afde-4a6f-bb03-c15f62673e57)
![image](https://github.com/umami-software/umami/assets/71468154/948dbc71-82a9-473a-8c23-7d746eefc7a8)

--> and this error when I want to wiew details stats :

![image](https://github.com/umami-software/umami/assets/71468154/e3f30840-c436-473c-b208-50cc63f52a1f)
![image](https://github.com/umami-software/umami/assets/71468154/8e459c5f-1152-43b6-a3bb-195c1ef839b7)

**I have these error with** **nginx reverse proxy only**.  In HTTP Direct access with 3000 port I haven't got the error.

- ubuntu last LTS
- Postgresql
- NodeJS v18.17.1
- yarn run v1.22.19
- Next.js 13.5.3

-- My nginx proxy conf :

```
	location / {
		proxy_pass http://127.0.0.1:3000/;
		proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection Upgrade;

		proxy_set_header X-Real-IP $remote_addr;
    	        proxy_set_header Host $host;
    	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
```

```npm install next@latest --force``` broke umami installation

### Database

PostgreSQL

### Relevant log output

```shell
Something went wrong.
Loading chunk 5767 failed. (error: https://umami.XXX.fr/_next/static/chunks/app/(main)/settings/websites/%5Bid%5D/page-22acaee2a17d71fd.js)
ChunkLoadError: Loading chunk 5767 failed.
(error: https://umami.XXX.fr/_next/static/chunks/app/(main)/settings/websites/%5Bid%5D/page-22acaee2a17d71fd.js)
    at l.f.j (https://umami.XXX.fr/_next/static/chunks/webpack-d29b485d209acb6d.js:1:3768)
    at https://umami.XXX.fr/_next/static/chunks/webpack-d29b485d209acb6d.js:1:1409
    at Array.reduce (<anonymous>)
    at l.e (https://umami.XXX.fr/_next/static/chunks/webpack-d29b485d209acb6d.js:1:1375)
    at self.__next_chunk_load__ (https://umami.XXX.fr/_next/static/chunks/7864-ed02d4d09d2fae55.js:1:5937)
    at https://umami.XXX.fr/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:5751
    at https://umami.XXX.fr/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:5974
    at t (https://umami.XXX.fr/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:6177)


---

Something went wrong.
Loading chunk 5126 failed. (error: https://umami.XXX.fr/_next/static/chunks/app/(main)/websites/%5Bid%5D/page-29478cead3ccd45c.js)
ChunkLoadError: Loading chunk 5126 failed.
(error: https://umami.XXX.fr/_next/static/chunks/app/(main)/websites/%5Bid%5D/page-29478cead3ccd45c.js)
    at l.f.j (https://umami.XXX.fr/_next/static/chunks/webpack-d29b485d209acb6d.js:1:3768)
    at https://umami.XXX.fr/_next/static/chunks/webpack-d29b485d209acb6d.js:1:1409
    at Array.reduce (<anonymous>)
    at l.e (https://umami.XXX.fr/_next/static/chunks/webpack-d29b485d209acb6d.js:1:1375)
    at self.__next_chunk_load__ (https://umami.XXX.fr/_next/static/chunks/7864-ed02d4d09d2fae55.js:1:5937)
    at https://umami.XXX.fr/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:5751
    at https://umami.XXX.fr/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:5974
    at t (https://umami.XXX.fr/_next/static/chunks/7864-ed02d4d09d2fae55.js:9:6177)
```

### How are you deploying your application? (if relevant)

github source, post gre

**Comment by corentin35000** [comment]
I have the exact same problem via NGINX with basic docker-compose.yaml from the Umami repository v 2.8.0

**Comment by corentin35000** [comment]
You must use Umami version <= 2.5.0

I haven't talked about it with someone on another issue, you have to downgrade the version to version: 2.5.0, you have to change in docker-compose: 

```
version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-2.5.0
```

**Comment by corentin35000** [comment]
I used this for a long time, when it works it's incredibly simple and very good! :)

**Comment by DroidBV8** [comment]
I will try manually since I don't use Docker.

The problem is that I don't really want to test an old version.

If the problem is not resolved, I would turn to another tool I think

**Comment by corentin35000** [comment]
Yes I understand there are quite a few features and fixing bugs.. so we don't take advantage of it unfortunately, I also hate doing that but it's in the meantime..

**Comment by DroidBV8** [comment]
yep no worries

It is also possible that given the problem, there is a problem in my configuration. I'll take a closer look.

The software seems to be worth it :)

**Comment by corentin35000** [comment]
I don't think it's on your side, a lot of issues were open for this problem

**Comment by mikecao** [comment]
The chunk load failed error is a Next.js problem. There are many different issues reported with different solutions.
https://github.com/vercel/next.js/issues/38507
https://github.com/vercel/next.js/issues/56484
https://github.com/vercel/next.js/issues/54008

Keep in mind that we run all of our own versions in production for Umami Cloud, so we would definitely run into any errors. However, we host through Vercel and not behind Nginx or Docker, so it's hard to troubleshoot every possible scenario.

In case this helps, here are the Next versions for each Umami release:
2.5: 13.3.1
2.6: 13.4.19
2.7: 13.5.2
2.8: 13.5.3
master branch: 13.5.6

What you can try is to build your own Docker image from master or simply run the code from master to see if it helps. It has the latest Next.js version.

**Comment by jpgnz** [comment]
What do you need @mikecao to help diagnose this? Docker nginx reverse proxy is a pretty common configuration for a bunch of people I'd imagine. I have the same issue running 2.6+

**Comment by yukikaze1234** [comment]
同样的问题，当我使用ip加端口访问时候没问题。 反向代理，点击查看就会报这样的错误

**Comment by ajaxbits** [comment]
FWIW, I fixed my instance of this bug by disabling ublock origin for my Umami web console url.

**Comment by jpgnz** [comment]
Upgrading to [2.9.0](https://github.com/umami-software/umami/releases/tag/v2.9.0), I don't have this issue anymore.

@mikecao mentioned above that this error looked like a Next problem, and Next has been upgraded to v14.0.4 in this release.
