### ISSUE TITLE
Region format with maxmind

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#2383]
### Describe the Bug

Region stored in subdivision1 is expected to be an ISO 3166-2 code, it's otherwise not displayed with its full name in filters.
That is already ensured with Cloudflare and Vercel headers, but not when maxmind db is used.

`result.subdivisions?.[0]?.iso_code` returns only the region portion.

It seems like country portion was somehow appended in previous Umami versions.
So now, two same regions can be considered different and listed twice in region stats listing (viewing old and new data),both with the full name,
and listed twice in filter values, one with its full name, the other with the region portion code.

Should be a quick fix using `getRegionCode`.
I'll do some tests and digging before submitting a PR.

### Database

PostgreSQL

**Comment by franciscao633** [comment]
I thought Maxmind automatically appended the country and region in their DB, but looks like I was wrong. Thanks, will get this added to next release.

**Comment by mikecao** [comment]
Fixed in v2.9.0.
