### ISSUE TITLE
Pages Url / Query parameters empty

### ISSUE THREAD

**Issue by profhase** [umami-software/umami#2385]
### Describe the Bug

In overview and view=url (`/websites/<id>?view=url`)

the  url shows "No data available" , same with Query parameters.

Everything else works fine (for example `view=title`)

**version=postgresql-v2.8.0**

### Database

PostgreSQL

### Which browser are you using? (if relevant)

any browser

### How are you deploying your application? (if relevant)

docker, image == postgresql-v2.8.0

**Comment by franciscao633** [comment]
Can you verify the data in your psql database in the website_event table? There should be data in the url_path / url_query columns for those views to be populated. Only way I see this happening is if the app is recording a pageview with an empty path.


\

**Comment by profhase** [comment]
Thanks, I can verify that the mentioned columns are always empty, same as referrer path, query, domain

Though:

- page_title is filled correctly
-  event_type is always 1 except if there is an event_name (then it is 2)

So the database is being written

**Comment by profhase** [comment]
@franciscao633 any ideas?
