### ISSUE TITLE
Reset website doesn't work

### ISSUE THREAD

**Issue by michaelmannucci** [umami-software/umami#2386]
### Describe the Bug

I go to settings > edit > data > reset website, enter RESET, submit, it says saved... data is not reset.

I tried clearing Chrome cache.

### Database

Umami Cloud

### Which browser are you using? (if relevant)

Chrome

**Comment by franciscao633** [comment]
Sorry for the late response. Thanks for reporting, we have a fix for this that will go out next cloud release.

**Comment by mikecao** [comment]
Fixed in v2.9.0.
