### ISSUE TITLE
There is a incompactility between umami and node 20 LTS.

### ISSUE THREAD

**Issue by LeenHawk** [umami-software/umami#2389]
### Describe the Bug

There is a installation bug for a long time like [this](https://github.com/umami-software/umami/issues/2293):
```
error /home/limmy/umami/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node install/can-compile && node-gyp rebuild && node install/dll-copy)
Arguments:
```
In node 18 LTS, we can use `yarn install --verbose` to get installation successful. But in node 20 LTS, it still failed.

### Database

PostgreSQL

### How are you deploying your application? (if relevant)

Hosting

**Comment by franciscao633** [comment]
I believe this is an issue with installing sharp. Can you try `yarn install --unsafe-perm`? You can find the official sharp installation docs [here](https://sharp.pixelplumbing.com/install). That command is from the common problems section.

**Comment by LeenHawk** [comment]
> I believe this is an issue with installing sharp. Can you try `yarn install --unsafe-perm`? You can find the official sharp installation docs [here](https://sharp.pixelplumbing.com/install). That command is from the common problems section.

If i have installed umami,I can use node20,but in a fresh machine, it failed...

**Comment by LeenHawk** [comment]
> > I believe this is an issue with installing sharp. Can you try `yarn install --unsafe-perm`? You can find the official sharp installation docs [here](https://sharp.pixelplumbing.com/install). That command is from the common problems section.
> 
> If i have installed umami,I can use node20,but in a fresh machine, it failed...

Test again, success with fresh machine. There must be something I miss...

**Comment by zhujunyong** [comment]
I encounter the same issue when I using yarn 1.22.21 (previous installed for another project)
And it disappear when I switch to yarn 4.1.0
```
$ yarn --version
1.22.21
$ corepack enable
$ yarn set version stable
$ yarn --version
4.1.0
```
