### ISSUE TITLE
Cockroach db support

### ISSUE THREAD

**Issue by simonboisset** [umami-software/umami#2393]
### Describe the feature or enhancement

Hi !
Since you already support PostgreSQL with Prisma, it would be awesome (and easy I think) to add CockroachDB as a supported database.

**Comment by abrar78** [comment]
@franciscao633, I want to work on it. For this I think we need to create another env variable for "database_type" because cockroach db has the same connection url as postgresql .

**Comment by abrar78** [comment]
I'm working on it, and adding all database support which is currently supported by prisma.

**Comment by Sammy-T** [comment]
Hi, I created a PR (#1579) for this a while back but there wasn't enough interest. 
However, I've been using and maintaining my own branch which supports Cockroach db. Feel free to check it out. https://github.com/Sammy-T/umami/tree/cockroach-db
