### ISSUE TITLE
Add more advanced filtering options to website overview

### ISSUE THREAD

**Issue by andrwcnln** [umami-software/umami#2394]
### Describe the feature or enhancement

Currently, you can only add filters for a single URL, referrer etc. in the overview.

There are already more advanced filtering options for reports, and it would be nice to have the same flexibility in the overview.

For instance, there is currently no way to filter out referrals from a specific site in the overview, but this is possible in reports:

![image](https://github.com/umami-software/umami/assets/20906402/952382c5-d418-43e6-ac68-113eb45b6675)

Thanks!

**Comment by franciscao633** [comment]
Agreed, Advanced filtering and other filtering enhancements #2322 are in our plans.

**Comment by franciscao633** [comment]
Added in [v2.11.0](https://github.com/umami-software/umami/releases/tag/v2.11.0)
