### ISSUE TITLE
User creation: modal won't close

### ISSUE THREAD

**Issue by esdete2** [umami-software/umami#2400]
### Describe the Bug

When attempting to create a new user and clicking the 'save' button, the loading indicator on the button continues spinning indefinitely, and the modal window remains open. After a reload the user is displayed in the list.

### Database

PostgreSQL

### Relevant log output

```shell
Uncaught (in promise) TypeError: onSave is not a function – UserAddButton.js
```

**Comment by mikecao** [comment]
Fixed in v2.9.0.
