### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by IO-igiannako** [umami-software/umami#2403]
### Describe the Bug

I get this error when I click "Settings" next to "Dashboard Realtime" link. This doesn't happen though when I get to this page from the account button on the right side of the page via the "Account" page.

<img width="1431" alt="image" src="https://github.com/umami-software/umami/assets/81645704/f904d56f-830d-483b-bb08-7a57792ce58e">

### Database

MySQL

### Relevant log output

```shell
[@formatjs/intl] An `id` must be provided to format a message. You can either: 1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin) or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR 2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id) to autofix this issue
```

### Which browser are you using? (if relevant)

Safari

**Comment by franciscao633** [comment]
What version of Umami are you currently on? It looks like your self-hosting using MySQL, but I believe `Accounts` is a cloud page. Can you please verify if you are self-hosting or using cloud.

**Comment by IO-igiannako** [comment]
I'm self hosting

node -v v16.20.0
umami [v2.2.0]

<img width="1792" alt="image" src="https://github.com/umami-software/umami/assets/81645704/994c53e0-f2d3-4954-867b-4f6e9526a577">
<img width="1792" alt="image" src="https://github.com/umami-software/umami/assets/81645704/b8d9e914-d76b-4d37-a8c0-9a60fbbb3f10">

**Comment by mikecao** [comment]
This has already been fixed in later versions. You will need to upgrade.

**Comment by Innei** [comment]
Why can't we add an ErrorBoundary to prevent the entire page from crashing every time this issue occurs?
