### ISSUE TITLE
I can't sign up

### ISSUE THREAD

**Issue by Ali-Hussein-dev** [umami-software/umami#2404]
### Describe the Bug

![Umami-Cloud](https://github.com/umami-software/umami/assets/42802922/b7eacefb-c4f3-40ae-ae2e-582ef3d38526)

### Database

Umami Cloud

### Which browser are you using? (if relevant)

sidekick

**Comment by Ali-Hussein-dev** [comment]
I tried on a private window and it doesn't work as weel

**Comment by franciscao633** [comment]
I'm unable to reproduce the issue on chrome. Can you check the network tab and see what error code is being returned?

**Comment by Ali-Hussein-dev** [comment]
checking...

**Comment by Ali-Hussein-dev** [comment]
@franciscao633 Accounts: post request status: 500

**Comment by Ali-Hussein-dev** [comment]
Any update?

**Comment by franciscao633** [comment]
Sorry one last check. Are you using cloud.umami.is to sign-up? That is our production cloud app.

**Comment by Ali-Hussein-dev** [comment]
Yes

**Comment by mikecao** [comment]
This should be resolved.

**Comment by Ali-Hussein-dev** [comment]
@mikecao not yet!
the request has 500 status code!
![Umami-Cloud](https://github.com/umami-software/umami/assets/42802922/7ebf04a0-e527-44be-bd03-741e721365ab)

**Comment by mikecao** [comment]
I don't know what is going on with your situation. We get lots of signups every single day without issue. Have you tried a different email address?
