### ISSUE TITLE
`/settings` page not loading on Netlify

### ISSUE THREAD

**Issue by GamerKingFaiz** [umami-software/umami#2411]
### Pre-requisite
Have Umami v2.8.0 deployed on Netlify

### Steps

1. Click the Settings link from the navbar
![image](https://github.com/umami-software/umami/assets/9065136/c504c675-c861-40bd-96fa-031802241fa7)
1. Page navigates to `/settings`, which loads a **404**
![image](https://github.com/umami-software/umami/assets/9065136/f3a2d1d8-6c48-4e87-a26a-378a6c5d2656)

## Additional Details

1. If I test these steps **locally** or deployed on **Railway** it works fine.
   a. Clicking `/settings` redirects to `/settings/websites` and the page loads just fine
   b. Page loads are snappy when navigating locally or when deployed to Railway
1. Umami deployed on **Netlify** doesn't seem to behave like an SPA.
   a. Clicking through the links feels like the page is reloading the whole site each time (slow)
   b. _**I'm wondering if maybe I deployed it incorrectly**_
   c. Here are my deploy settings on Netlify
![image](https://github.com/umami-software/umami/assets/9065136/9f139737-3278-420e-9df6-183f5a779b11)

### Database

PostgreSQL

### Relevant log output

This is the logging I see in Netlify's Function logging section. Specifically for the Next.js SSR handler.
```shell
Nov 27, 04:40:38 PM: 41d91c91 INFO   [GET] /settings (SSR)
Nov 27, 04:40:38 PM: 41d91c91 Duration: 26.15 ms	Memory Usage: 337 MB
```

### How are you deploying your application? (if relevant)

Netlify

**Comment by ccbikai** [comment]
Related to this issue https://github.com/netlify/next-runtime/issues/2359

**Comment by mikecao** [comment]
Latest version uses updated package for netlify.

**Comment by LushawnDev** [comment]
I'm still getting this issue. I can spin up the site fine, using everything as default from the cloned repo (+ my .env environment with my database url to Supabase).

When I navigate to the settings page from the app once it's hosted on Netlify I get "Page not found" too.

I'm using the latest version of Umami. Any idea why this could be happening?

Thank you!

**Comment by azat-io** [comment]
The same problem on v2.11.2

**Comment by ccbikai** [comment]
> The same problem on v2.11.2

This method is effective.

https://github.com/umami-software/umami/pull/2687

**Comment by gsambrotta** [comment]
> > The same problem on v2.11.2
> 
> This method is effective.
> 
> [#2687](https://github.com/umami-software/umami/pull/2687)

Not for me :(

I can see all the pages but the graphics works just for the last week data, not all the data. So sad
