### ISSUE TITLE
Docs: HASH_SALT in fly.io example is not documented in list of environment variables

### ISSUE THREAD

**Issue by gridsystem** [umami-software/umami#2414]
### Describe the Bug

[The fly.io example in the documentation](https://umami.is/docs/running-on-fly-io) instructs the user to set an environment variable, `HASH_SALT`. 

> fly secrets set HASH_SALT="<any-string-minus-angle-brackets>", using whatever string you want to salt the hash.

This environment variable isn't in [the documentation's list of environment variables](https://umami.is/docs/environment-variables). There is a similar variable in that list, `APP_SECRET`.

> APP_SECRET = <random string>
> A random string used to generate unique values.

Is the fly.io example using a deprecated variable which needs changing to `APP_SECRET`? Does `HASH_SALT` need to be added to the list of environment variables?

### Database

PostgreSQL

**Comment by SmartPhoneLover** [comment]
+1

**Comment by mikecao** [comment]
HASH_SALT was used in v1. You should be using APP_SECRET now.

**Comment by paulrudy** [comment]
@mikecao I created the documentation page for running on fly. I wasn't aware that with v2, we should be using `APP_SECRET`. For already running instances of Umami v2, can `APP_SECRET` be safely added and `HASH_SALT` removed, without disrupting anything?

**Comment by mikecao** [comment]
@paulrudy Yes

**Comment by paulrudy** [comment]
Ok, I created a [PR](https://github.com/umami-software/website/pull/153 to reflect) to reflect the change, along with a couple of other PRs for that doc—a typo, and removing `HOSTNAME` env variable as it's no longer needed since Umami version 2.7.0.

**Comment by mikecao** [comment]
PR merged.
