### ISSUE TITLE
No information showed in Dashboard

### ISSUE THREAD

**Issue by WShaoLab** [umami-software/umami#2415]
### Describe the Bug

Hi

Thanks for your work in Umami. In my linux (ubuntu) server, Node.js v18.17.1 and MySQL 8.0.35-0ubuntu0.20.04.1 (Ubuntu) have been installed and configured. And then I followed the instractions to apply Umami v2.8.0 by 'yarn'. I logged in umami successfully by http://localhost:3000 and paste the tracking code in my website. But, I got no information in dashboard.
I am writing to ask for help, thanks very much!

best regards
xiaoxiang

the start log is as follows:

xx@dell:/data/umami$ yarn start
yarn run v1.22.21
$ next start
 ⚠ Invalid next.config.js options detected: 
 ⚠     Expected string, received boolean at "env.cloudMode"
 ⚠     "env.cloudUrl" is missing, expected string
 ⚠     "env.defaultLocale" is missing, expected string
 ⚠     "env.disableLogin" is missing, expected string
 ⚠     "env.disableUI" is missing, expected string
 ⚠     Expected string, received boolean at "env.isProduction"
 ⚠ See more info here: https://nextjs.org/docs/messages/invalid-next-config
 ⚠ "next start" does not work with "output: standalone" configuration. Use "node .next/standalone/server.js" instead.
  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000

 ✓ Ready in 509ms

Here is the dashboard:

![Screenshot from 2023-11-30 12-11-04](https://github.com/umami-software/umami/assets/146646190/50e9f8b6-a7de-4bb8-8f85-62a371bae7a1)

### Database

MySQL

### Which browser are you using? (if relevant)

Chrome, Firefox

**Comment by franciscao633** [comment]
Can you verify there is data in your website_event table? Another way to verify if the tracking script is working is checking the network tab in your website for /api/send or whatever endpoint you named it.
