### ISSUE TITLE
Not loading graph data

### ISSUE THREAD

**Issue by qlaffont** [umami-software/umami#2417]
### Describe the Bug

Impossible to load graph data 

### Database

PostgreSQL

### Relevant log output

```shell
Version : 2.8.0

https://analytics.qlaffont.com/api/websites/73c3f86f-04e6-44f7-80a3-0441dcddfb42/pageviews?startAt=1698966000000&endAt=1701557999999&unit=day&timezone=Europe/Paris

Response : 400

Cannot read property 'zone' of undefined
```

### Which browser are you using? (if relevant)

FIREFOX

### How are you deploying your application? (if relevant)

SSH Local

**Comment by qlaffont** [comment]
maybe related to : https://github.com/umami-software/umami/issues/2415

**Comment by franciscao633** [comment]
This [PR](https://github.com/umami-software/umami/pull/2395) might be related. I can't reproduce the issue myself, but it's certainly causing issues for some users. This will get out next release.
