### ISSUE TITLE
Activity log and graph times don't match

### ISSUE THREAD

**Issue by ranghaus** [umami-software/umami#2423]
### Describe the Bug

On the Realtime tab, the times on the graph and on the activity log are 1 hour apart. I am on CET, the time on the graph is the correct one.

![firefox_WE0NIlvLGc](https://github.com/umami-software/umami/assets/96725927/308b06ab-c233-42b5-9a0c-44d319580f9f)

### Database

Umami Cloud

**Comment by mikecao** [comment]
Fixed in v2.9.0.
