### ISSUE TITLE
Building site hangs and Killed the process in Ubuntu 20.04 and Node v18.19.0

### ISSUE THREAD

**Issue by mskian** [umami-software/umami#2434]
### Describe the Bug

Try to update Umami's latest version `2.9.0` but it's not building the optimized site
it hangs and stops in the middle of the page build

ubuntu: 20.04
Node: v18.19.0
MYSQL: 8.0.35

as per Next `v14.0.4` it require node v18 or v20 using v18 no issue on package issue etc... but build was killed in the middle of the task

command:  `yarn build`

### Database

MySQL

### Relevant log output

```sh
   Creating an optimized production build  ..Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build-app" exited with 137.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### How are you deploying your application? (if relevant)

Ubuntu server 20.04 LTS

**Comment by mskian** [comment]
# Update

Tested `2.8.0` same issue as `2.9.0`

Tested `2.7.0` no issues work well

**next v13.5.2**
**prisma v5.3.1**
**node v18.19.0**

**Comment by mxctx-jake** [comment]
137 means operating system killed process because the system ran out of memory (see [OOM manager](https://www.kernel.org/doc/gorman/html/understand/understand016.html)). Can you allocate more RAM to your server or allocate more swap?
