### ISSUE TITLE
Horizontal scroll bar present on mobile after 2.9.0

### ISSUE THREAD

**Issue by GamerKingFaiz** [umami-software/umami#2435]
### Describe the Bug

After upgrading to 2.9.0, the Dashboard page on mobile has a tiny horizontal scroll bar as well as a white square in the corner.

![image](https://github.com/umami-software/umami/assets/9065136/ddde8f38-c0f0-4215-9ded-f17b9b9612dc)

It seems like the `+1m 18s` on the Average visit time is what's causing the scroll bar.
I don't remember this happening on 2.8.0.

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by uzzii-21** [comment]
@franciscao633 can u assign me this task

**Comment by mikecao** [comment]
This should be resolved now.
