### ISSUE TITLE
Public/Shared url: also share events data

### ISSUE THREAD

**Issue by alcalyn** [umami-software/umami#2441]
### Describe the feature or enhancement

We can send custom data with an event like this:

``` html
<a
    data-umami-event="Create thing"
    data-umami-event-thing-category="category_X"
    href="..."
>...</a>
```

These details are visible in UI, on the top left button, "Event data"

![image](https://github.com/umami-software/umami/assets/1588144/59311cc7-fe4a-40d3-afe6-9996975cb2f0)

But I did not found this page when using a public/shared URL, I can see only events names, not details.

**Comment by mikecao** [comment]
Share pages are limited to just the basic details. If you want to share more data you will need to create a team.

**Comment by alcalyn** [comment]
Ok, for now I don't have much events though, and just one key in data, so I'd go for events named like `Create thing | category_X`.
Thanks !
