### ISSUE TITLE
404: Tracking code from initial onboarding does not include eu subdomain

### ISSUE THREAD

**Issue by mbanerjeepalmer** [umami-software/umami#2448]
### Describe the Bug

1. Start onboarding, choose EU
2. Copy/paste script tag from onboarding journey (e.g. <script async src="https://cloud.umami.is/script.js" data-website-id="UUID-goes-here"></script>
3. Deploy and see 404 response
4. Get tracking code from settings page
5. Now the URL includes the EU subdomain: <script async src="https://eu.umami.is/script.js" data-website-id="UUID-goes-here"></script>

### Database

Umami Cloud

**Comment by franciscao633** [comment]
Confirmed. We will try to hotfix this today. Thanks for reporting.

**Comment by franciscao633** [comment]
We just released a fixed. Closing out.

**Comment by mbanerjeepalmer** [comment]
Wow that was fast
