### ISSUE TITLE
Website stat bounce rate color is wrong

### ISSUE THREAD

**Issue by KaiPereira** [umami-software/umami#2457]
### Describe the Bug

Inside of the website stats dashboard, you can see that sometimes the color on the bounce rate change is green instead of red when it's negative. Just a small issue but thought I'd report it!
![image](https://github.com/umami-software/umami/assets/88850028/f77cbdaa-d770-4686-9c82-8840b721765a)

### Database

PostgreSQL

**Comment by FHU-yezi** [comment]
Low bounce rate is good because it shows less people leave our site, so it should be a right behavior.

**Comment by KaiPereira** [comment]
Mb
