### ISSUE TITLE
Difference in Page Views between Umami and Vercel Analytics

### ISSUE THREAD

**Issue by jparismorgan** [umami-software/umami#2461]
### Describe the Bug

I have both [Vercel Analytics](https://vercel.com/analytics) and Umami set up on my site, but they report very different Page Views numbers (and slightly different Visitors numbers). I am inclined to trust the Vercel numbers because Umami seems unrealistic. So it makes me think that perhaps Umami counts page views incorrectly sometimes. 

The issue mainly happens on `/path2`, which is a page that fetches data from the server with [useSWR](https://swr.vercel.app/) and which will often use `router.replace(href, {scroll: false})` to update the query params based on the user clicking around.

**Umami**
<img width="1073" alt="Screenshot 2024-01-05 at 3 37 23 PM" src="https://github.com/umami-software/umami/assets/1396242/2cc8c3cc-bb54-420a-ae53-415d44404837">

**Vercel Analytics**
<img width="989" alt="Screenshot 2024-01-05 at 3 37 13 PM" src="https://github.com/umami-software/umami/assets/1396242/30dcbe94-e978-4e7e-b276-5689594f6439">

My specific questions:
* Has anyone seen something like this? 
* Does anyone have suggestions on potential causes?

Thank you for any help!

### Database

PostgreSQL

**Comment by jparismorgan** [comment]
Update - I've done some investigation and see what looks like the root cause. 

When we first load the page we are at `www.mywebsite.com`. Then a user clicks a button and we call:
```
import {useRouter} from 'next/navigation' // we are on "next": "13.4.19"
...
const router = useRouter()
...
router.replace('/?foo=bar', {scroll: false})
```
And we end up at `www.mywebsite.com/?foo=bar`. When that happens we send an event which will look like:
```
{
  "type": "event",
  "payload": {
    "website": "1234",
    "hostname": "localhost",
    "screen": "1920x1080",
    "language": "en-US",
    "url": "/?foo=bar",
    "referrer": "/?foo=bar"
  }
}
```
I then click a button which will get rid of the query param and we send:
```
{
  "type": "event",
  "payload": {
    "website": "1234",
    "hostname": "localhost",
    "screen": "1920x1080",
    "language": "en-US",
    "url": "/",
    "referrer": "/"
  }
}
```
So my question is now - how can I prevent an event from firing here? I would like to only fire events which will count towards page views when the page changes, not when the query parameters change. Thank you for any help!

**Comment by mikecao** [comment]
Umami considers changes to the query string to be a new page view. If you don't want that behavior, you would have to disable the auto-tracking and send the events yourself. See https://umami.is/docs/tracker-functions

**Comment by jparismorgan** [comment]
Thanks, I see. 

It would be a nice to be able to disable that via a setting as I imagine other people may also run into this when migrating from other analytics providers.
