### ISSUE TITLE
Umami Cloud empty dashboard despite 200 /send network request

### ISSUE THREAD

**Issue by rnkdev** [umami-software/umami#2463]
### Describe the Bug

Using Umami Cloud and loading script from `https://analytics.umami.is/script.js` in Next.JS, I got empty dashboard including events tab. This is despite having /send network request sending successfully and data got 

For privacy purpose I'm not sure if I should give you the website ID in public but I can send you one example of /send response which seems to be constant through requests. 

Also: 
- verified not using ad b locker while opening cloud dashboard
- verified there's traffic through Vercel analytics

### Database

Umami Cloud

### Relevant log output

```shell
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjcyYmY0ZTRlLWM3ZjMtNTY1OC05OTQ2LTE5Y2JiNmQyODIzOSIsIndlYnNpdGVJZCI6ImUzYjkwMjJhLTM1MDctNDAwOC1iMzVkLTExZTJkYzM1ZTc0NyIsImhvc3RuYW1lIjoid3d3Lm91cm93bmNhcnMuY29tLmF1IiwiYnJvd3NlciI6ImNocm9tZSIsIm9zIjoiV2luZG93cyAxMCIsImRldmljZSI6ImRlc2t0b3AiLCJzY3JlZW4iOiIzNDQweDE0NDAiLCJsYW5ndWFnZSI6ImVuLVVTIiwiY291bnRyeSI6IkFVIiwic3ViZGl2aXNpb24xIjoiQVUtVklDIiwiY2l0eSI6Ik1lbGJvdXJuZSIsIm93bmVySWQiOiIxNmJlNzk4NC1jNWY5LTRmOWYtODcwOS1lNzFmZDIwMWQ1OTEiLCJpYXQiOjE3MDQ2MzQ4NDF9.ZeAsdnc8OC6I-PwZMXFa0vMjcLaABHn6rn-iLXASXzA
```

### Which browser are you using? (if relevant)

Chrome 120.0.6099.109 

### How are you deploying your application? (if relevant)

Vercel

**Comment by mikecao** [comment]
Please send an email to support@umami.is for any Umami Cloud related issues. Include you account id and website it.

**Comment by learntheropes** [comment]
I can confirm. The crazy thing is that for me it shows empty data on the logged-in dashboard, but it shows data on the sharing link. Writing to support as well.
