### ISSUE TITLE
I can't go to event data page on european Umami Cloud 

### ISSUE THREAD

**Issue by d22ier** [umami-software/umami#2467]
### Describe the Bug

Hello everyone,

The issue is when i try to go to event data page on european umami cloud I got this error : 

![image](https://github.com/umami-software/umami/assets/23150157/1340e140-63c4-4ef8-a905-35a60c6d3672)

Thanks for this tool ! 

### Database

Umami Cloud

### Which browser are you using? (if relevant)

Chrome

**Comment by briancao** [comment]
Please check your ad-block.  

Similar issue in this thread:
https://github.com/umami-software/umami/issues/2169

**Comment by d22ier** [comment]
Thank you Brian, it seems to work ! Maybe it would be nice to have a warning or something like that because it's a bit confusing !
