### ISSUE TITLE
Funnel with query parameters

### ISSUE THREAD

**Issue by d22ier** [umami-software/umami#2468]
### Describe the feature or enhancement

Hello everyone,

I can't find a way to track a funnel with page with query parameters. 
![image](https://github.com/umami-software/umami/assets/23150157/da54bbb7-e94e-4e48-b35a-02cb7d97b26e)

Another problem is once i created a step/url i can't edit it.

Unfortunately, the funnel feature is a bit to simple for the moment compared to another tracking tool, i hope umami will improve it soon ! 

Thank you

**Comment by franciscao633** [comment]
Currently you can only track base URLs. Thanks for your suggestions! Definitely room for improvements in both the UX and functionality.

**Comment by franciscao633** [comment]
In the last release [v2.11.0](https://github.com/umami-software/umami/releases/tag/v2.11.0) we added editable steps, wildcard URLs, event steps, as well as better visuals. Still no query params, but gradually making improvements.
