### ISSUE TITLE
If a click event is bubbled from its children, it will not be tracked

### ISSUE THREAD

**Issue by CNSeniorious000** [umami-software/umami#2471]
### Describe the feature or enhancement

If my DOM is like this:

```html
<button data-umami-event="btn">
  <div>some icon</div>
<button>
```

If I clicked on the div (which is often), this event will not be raised. I think this is a common case.

Of course I can trigger an `window?.umami.track` manually in `onclick` function, but I think this enhancement is beneficial in most cases.

**Comment by mikecao** [comment]
Confirmed, we'll get this fixed.
