### ISSUE TITLE
Error in initial Build & Deploy configuration on Netlify

### ISSUE THREAD

**Issue by leftieFriele** [umami-software/umami#2476]
### Describe the Bug

When running Umami on Netlify following the instructions in [Running on Netlify](https://umami.is/docs/running-on-netlify), the **Build & Deploy**section has an invalid **Build command**. It uses `yarn run build-app`, which does not run database migrations and such.
This lead me to be unable to get things setup, changing the build command to `yarn run build` made everything work as expected.
When trying to login for the first time, the application fails with a generic `500 Server Error` with no additional information.

I am not sure _where_ this is done in Umami, otherwise I would have sent a PR instead of an issues.
The [running on Netlify](https://umami.is/docs/running-on-netlify) page does not mention anything about the need to have the database migrations run.

### Database

Any

### Relevant log output

The Next.js SSR handler outputs this:
```
Jan 20, 11:36:36 AM: 4480336f ERROR   ⨯ Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.Jan 20,
11:36:36 AM: 4480336f ERROR  In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
```

### How are you deploying your application? (if relevant)

Netlify

**Comment by franciscao633** [comment]
So I updated our [Netlify docs](https://umami.is/docs/running-on-netlify) to include updating the build command to `yarn run build`. I did a quick run in deploying Umami and everything went smooth from there. The `prisma generate` command is run from `yarn build` so I'm not sure how its not getting generated. Can you try redeploying the app?

![image](https://github.com/umami-software/umami/assets/31608805/0cb88e12-58e1-416e-9058-6f2411a63385)

**Comment by leftieFriele** [comment]
> I'm not sure how it's not getting generated. Can you try redeploying the app?
> 

my app works with 'yarn build'. I just field the ticket to have the docs fixed for anyone else struggling with the same thing. thanks for fixing it 👍
