### ISSUE TITLE
If there are too many websites, the team is unable to add any one

### ISSUE THREAD

**Issue by maou-shonen** [umami-software/umami#2481]
### Describe the Bug

![bug01](https://github.com/umami-software/umami/assets/22576780/97b44a1a-67f7-49e2-b4b2-6aee9cb39048)
![bug02](https://github.com/umami-software/umami/assets/22576780/fa1b984e-3e96-4d6c-87a9-211dd4d83870)

### Database

PostgreSQL

### Which browser are you using? (if relevant)

chrome

**Comment by franciscao633** [comment]
Teams has been reworked in v2.10 and this add website component is no longer used.
