### ISSUE TITLE
Funnel with events

### ISSUE THREAD

**Issue by 3kezoh** [umami-software/umami#2487]
### Describe the feature or enhancement

It would be amazing if we could include events in the funnels, so we could know how many people perform a certain action on a page. I'm thinking in particular of outbound links.

**Comment by mikecao** [comment]
This is definitely on the roadmap.

**Comment by franciscao633** [comment]
Feature added in [v2.11.0](https://github.com/umami-software/umami/releases/tag/v2.11.0)
