### ISSUE TITLE
self-host API get could not working

### ISSUE THREAD

**Issue by mobeicanyue** [umami-software/umami#2488]
### Describe the Bug

the documentation mention
![image](https://github.com/umami-software/umami/assets/81098819/b878aa92-9022-4e54-92a3-95c29bfa4637)

and I try to get it
![image](https://github.com/umami-software/umami/assets/81098819/ab0230de-4f89-4805-9a31-74babc06a593)

I do not know why and I could not find any `api-key` in my admin page, except tracking code.
And I make this site's umami statistics public.
Hope someone could help me

### Database

MySQL

**Comment by pstadler** [comment]
See https://umami.is/docs/authentication

**Comment by mobeicanyue** [comment]
> See https://umami.is/docs/authentication

Thank you for the response. Does this imply that every request requires a token? I find this inconvenient. Here's my perspective:

I maintain a public GitHub repository for my blog, where I aim to display the reading and visitor counts for each article. While the Umami site page can provide detailed statistics at https://umami.ovvv.top/share/BH4jm8X6bYFS2b7X/test, I couldn't locate any method to access the data via API.

In my view, public Umami statistics should offer an alternative, more convenient way to access data, without the need for a token.

**Comment by emouawad** [comment]
@mobeicanyue I almost have the same use case - how was this solved?

**Comment by mobeicanyue** [comment]
> [@mobeicanyue](https://github.com/mobeicanyue) I almost have the same use case - how was this solved?

Set a public readonly user, get its token and set it in the front end. So that you could read the site data

**Comment by emouawad** [comment]
> > [@mobeicanyue](https://github.com/mobeicanyue) I almost have the same use case - how was this solved?
> 
> Set a public readonly user, get its token and set it in the front end. So that you could read the site data

I created a view only user BUT there doesn't seem to be a way to generate a token (at least from the UI) - Can you point me to where can i generate this token? (I am using the self-hosted option)

Tried for a view only user and admin user.

**Comment by mobeicanyue** [comment]
> I created a view only user BUT there doesn't seem to be a way to generate a token (at least from the UI) - Can you point me to where can i generate this token? (I am using the self-hosted option)
> 
> Tried for a view only user and admin user.
Creating a Team and invite the viewonly user, add the website you want. Find the tracking code.

**Comment by mobeicanyue** [comment]
> I created a view only user BUT there doesn't seem to be a way to generate a token (at least from the UI) - Can you point me to where can i generate this token? (I am using the self-hosted option)
> 
> Tried for a view only user and admin user.

https://github.com/umami-software/umami/issues/2489
This might help you.
