### ISSUE TITLE
Get public umamic statistics more convenient

### ISSUE THREAD

**Issue by mobeicanyue** [umami-software/umami#2489]
### Describe the feature or enhancement

Thank you for your hard work. Umami is very good tool, I love it.

I maintain a public GitHub repository for my blog, where I aim to display the reading and visitor counts for each article. 
While the Umami site page can provide detailed statistics at https://umami.ovvv.top/share/BH4jm8X6bYFS2b7X/test 

In my view, public Umami statistics should offer an alternative, more convenient way to access data(like get public data without need of token). Hope you could consider this.

**Comment by brunoamaral** [comment]
I have actually done that using cloudflare workers to fetch the data I need and display on a page. Take a look here: https://github.com/Lisbon-Collective/umami-transparency

Hope it helps.

**Comment by brunoamaral** [comment]
Technically, it already does and the implementation is up to us. I used CloudFlare workers because it allowed me to keep the login credentials away from prying eyes.

I never really looked at the roadmap for umami, but I like the way the project has been delivering a good alternative in Web Analytics.

**Comment by brunoamaral** [comment]
@mobeicanyue I missed that there was a view-only option for users. Thank you for taking the time to write out the blog post.

**Comment by boehs** [comment]
My [Umami fork](https://github.com/boehs/miami) enables this feature, as well as some other quality of life changes. Specifically relevant is:

- API requests do not require a date to be set (https://github.com/boehs/miami/commit/1ad06bafae0b5a2fd7216326d09acab35bc76a2a)
- There is no cors on the share API (https://github.com/boehs/miami/commit/cb13a6b46aa69bb6d201ef160cdde0c261c6a257)
- Share IDs *are* the tokens, so an additional request is not needed (https://github.com/boehs/miami/commit/59cdff8564ac89e62e46d17cd4f9bec973b94e33)

This means that it can be queried like this: https://github.com/boehs/site/blob/73083b1ab6e5430b635fa0e967685ba68aa45c9e/src/scripts/infoot.ts#L6-L31

You can see it in usage by visiting any page on my blog (https://boehs.org/in/blog), and you can see it deployed [here](https://espy.boehs.org/share/JGBYO4bVg3kZVQUb) or [here](https://analytik.uncenter.dev/share/Atf7LPtQCPGa0643/uncenter)
