### ISSUE TITLE
Huge sudden drop in number of visitors (sessions) after upgrading to v2.9.0

### ISSUE THREAD

**Issue by zavan** [umami-software/umami#2492]
### Describe the Bug

We upgraded from 2.7.0 to v2.9.0 on December 19th. This caused a huge drop in the visitors (sessions) count for all all websites as can be seen below:

![image](https://github.com/umami-software/umami/assets/1722965/8f5cacce-75d5-4fb8-97f8-7af36bd46a1f)

This continues into January.

Since the views (pageview events) has not changed much, this can only mean views are now more concentrated across less visitors (sessions). We went from ~2 views/visitor/day on average, to ~10 views/visitor/day on average.

Running this query:

```sql
SELECT s.session_id, top_sessions.count AS pageviews, s.hostname, s.browser, s.os, s.device, s.screen FROM session s JOIN (SELECT e.session_id, count(e.session_id) FROM website_event e WHERE e.event_type = 1 AND e.website_id = '70e5b858-157f-4976-ad11-2ce4382d88b1' AND e.created_at BETWEEN '2023-12-07' AND '2023-12-18' GROUP BY e.session_id ORDER BY count(e.session_id) DESC LIMIT 10) AS top_sessions ON s.session_id = top_sessions.session_id;
```

We can get the get the Top 10 session_ids by pageview count in the 12 days from December 7th to December 18th, before the upgrade:

```
              session_id              | pageviews |    hostname     | browser |     os     | device  |  screen
--------------------------------------+-----------+-----------------+---------+------------+---------+-----------
 e85067d6-6569-5afb-9d38-84c8c96467cb |        41 | www.elpinto.com | ios     | iOS        | mobile  | 393x852
 e24894c3-76d1-582a-a1ff-7becec3c8c3d |        31 | www.elpinto.com | chrome  | Windows 10 | desktop | 1920x1080
 5509fd77-5a93-5372-b0ec-223d33ccbf76 |        31 | www.elpinto.com | safari  | Mac OS     | desktop | 2048x1152
 e3c476f7-221f-5e24-9f18-f09e269d0ca8 |        27 | www.elpinto.com | ios     | iOS        | mobile  | 393x852
 c90eab1e-ef35-5f90-9c00-3e019a5605c1 |        21 | www.elpinto.com | firefox | Linux      | laptop  | 1366x768
 459a7bb0-e9ed-5cc2-a285-4d1eca9a7fb9 |        20 | www.elpinto.com | ios     | iOS        | mobile  | 393x852
 9d8cb764-4f6c-50cc-9a0e-96face7eee83 |        18 | www.elpinto.com | ios     | iOS        | mobile  | 414x896
 33e410ad-8f53-53df-a743-4799785d44f3 |        18 | www.elpinto.com | ios     | iOS        | mobile  | 390x844
 bc070bf5-d5da-5147-8222-1e520817f284 |        17 | www.elpinto.com | chrome  | Windows 10 | desktop | 1920x1080
 ffd00f48-e680-5b56-84eb-f3f3eafd4979 |        16 | www.elpinto.com | chrome  | Windows 10 | desktop | 1920x1080
```

And from December 20th and December 31st, after the upgrade:

```
              session_id              | pageviews |    hostname     |    browser    |     os     | device  |  screen
--------------------------------------+-----------+-----------------+---------------+------------+---------+-----------
 7d66612e-3661-5fc7-aad4-f2b7e8e28bd5 |      2702 | www.elpinto.com | ios           | iOS        | mobile  | 430x932
 9a3ae813-616d-5ea0-a782-35d76892bf8d |      1112 | www.elpinto.com | chrome        | Android OS | mobile  | 412x1006
 300147ec-b51e-5934-9a97-5da8c054edc6 |       615 | www.elpinto.com | chrome        | Windows 10 | laptop  | 1280x720
 30a62591-9d5d-514b-92eb-d2aee1b057d9 |       427 | www.elpinto.com | ios           | iOS        | mobile  | 430x932
 78748dc1-88d8-59d2-8262-329895cc000c |       404 | www.elpinto.com | ios           | iOS        | mobile  | 375x812
 4b5980de-84da-59ce-ae5a-2a561b8a9f0a |       334 | www.elpinto.com | crios         | iOS        | mobile  | 375x812
 0262e952-38e5-574a-bf6c-1f16f6eb5786 |       252 | www.elpinto.com | safari        | Mac OS     | laptop  | 834x1194
 199020fc-5857-5d15-afa2-984d3e4c5148 |       208 | www.elpinto.com | ios-webview   | iOS        | mobile  | 393x852
 1cd4f507-d10f-5449-be64-8c324d5a87a1 |       205 | www.elpinto.com | edge-chromium | Windows 10 | desktop | 1920x1080
 4b980cf4-fdeb-56ab-bba1-221f4c703cd3 |       198 | elpinto.com     | ios           | iOS        | mobile  | 390x844
```

It's clear that views are accumulating across less sessions.

This means less distinct sessions are being created, which means something is making session ids be the same across different arguments.

The arguments used to generate the session UUID are `websiteId, hostname, ip, userAgent` and haven't changed:

https://github.com/umami-software/umami/blob/784237bfab6da8c960efac7fd1073b8e0f67dfd9/src/lib/session.ts#L66-L69

I checked how they're collected and it also hasn't changed (location data has changed, but they're not used in the UUID):

https://github.com/umami-software/umami/blob/784237bfab6da8c960efac7fd1073b8e0f67dfd9/src/lib/detect.ts#L124-L137

The only thing that changed related to this that I found was that a monthly `salt()` was added as an argument to the hash that gets encoded into the UUID:

https://github.com/umami-software/umami/blob/784237bfab6da8c960efac7fd1073b8e0f67dfd9/src/lib/crypto.ts#L9-L19

This happened in [this commit](https://github.com/umami-software/umami/commit/f175534f5120bcbf807d2421b5232d48e102f261) trying to fix [this issue](https://github.com/umami-software/umami/issues/2311) and was released with v2.9.0.

I don't know how this could cause the problem, but it's the only related change that I found. Any other ideas?

### Database

PostgreSQL

**Comment by zavan** [comment]
I found the issue, it's not Umami.

My service is behind Nginx and my request headers look like:

```
'x-real-ip': '100.28.50.121',
'user-agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
'x-forwarded-for': '::ffff:127.0.0.1'
```

So the real IP is in `x-real-ip`, but the `request-ip` library gives `x-forwarded-for` priority over `x-real-ip`:

https://github.com/pbojinov/request-ip/blob/e1d0f4b89edf26c77cf62b5ef662ba1a0bd1c9fd/lib/index.js#L45-L65

![image](https://github.com/umami-software/umami/assets/1722965/c9cc04d3-2a47-49b9-a3eb-ef59a29afd71)

This makes visitors using the same `userAgent` get the same session id.

`request-ip` hasn't changed in 2 years, so it was probably myself that changed some Nginx config or something like that.

**Comment by zavan** [comment]
I fixed the problem by adding `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;` to my Nginx configuration.

**Comment by mikecao** [comment]
Glad you were able to solve it! FYI, there's also an environment variable to tell Umami which header to check, `CLIENT_IP_HEADER`. See https://umami.is/docs/environment-variables

**Comment by zavan** [comment]
Thanks @mikecao!

To fix the incorrect data I created a tool to parse the NGINX logs and force the correct session data in the DB. It worked for my case and [can be found here](https://github.com/zavan/umami-nginx-session-rebuilder) if anyone has the same problem.

**Comment by firu11** [comment]
Regarding this issue, I might need a little help from you guys. I run Umami behind Caddy, and both inside a virtual Podman network. From what I can see, even Caddy itself does not get the original ip, only the NATed one. What are my options?

_edit:_
After a few hours of trying to get it working. The issue is that the combination of rootless podman and a virtual network does NAT before traffic even reaches the first container.

I managed do it with this setup:
- rootless podman
- quadlet files in `~/.config/containers/systemd/`
- a virtual network `~/.config/containers/systemd/shared.network`
  - all containers use this shared network `Network=shared.network`
  - only caddy is on the host network `Network=host`
- other containers expose ports 80XX `PublishPort=80XX:<WHATEVER_THE_APP_LISTENS_ON>`
  - umami has `PublishPort=8001:3000`
- caddy proxies to localhost `reverse_proxy localhost:8001` (instead of `umami:8001` if caddy were on the same virtual network as umami)

I hope this helps someone.
