### ISSUE TITLE
Upgrading from v2.4.1 to v2.9.0 encountered an error.

### ISSUE THREAD

**Issue by mobeicanyue** [umami-software/umami#2494]
### Describe the Bug

![image](https://github.com/umami-software/umami/assets/81098819/c4942284-9977-40da-b73a-105e787e558a)
![image](https://github.com/umami-software/umami/assets/81098819/53a20df6-3999-4fd6-ae30-06d9cae53357)
How can I preserve my data and restore

### Database

MySQL

### How are you deploying your application? (if relevant)

Docker compose

**Comment by FHU-yezi** [comment]
Seems like you have no problem with your umami backend & db (No pending migrations to apply) but the frontend crashed because some js file failed to load.

Try to clear your browser cache?

**Comment by mobeicanyue** [comment]
> Seems like you have no problem with your umami backend & db (No pending migrations to apply) but the frontend crashed because some js file failed to load.
> 
> Try to clear your browser cache?

No work.
And the browser console print
![image](https://github.com/umami-software/umami/assets/81098819/4b592442-ad23-44d9-83e6-3080384ae965)

**Comment by FHU-yezi** [comment]
Try to remove the entire image and rebuild it.

Make sure you are using docker volume to store the data or you will lose it.

Run this command to remove the image:

```
docker compose down --remove
```

and start it again:

```
docker compose up -d
```

**Comment by mobeicanyue** [comment]
Thanks for reply,
Remove and rebuild, still encounter error, seems like upgrade version not compatible?

**Comment by mobeicanyue** [comment]
It seems I can only to install a new version of umami rather than upgrade, one question, how many things do I need to backup? The database looks like this
![image](https://github.com/umami-software/umami/assets/81098819/b8a778af-853b-4b24-8f13-6e2a5890deaf)
