### ISSUE TITLE
Automatically filled passwords are not accepted

### ISSUE THREAD

**Issue by Koen1999** [umami-software/umami#2495]
### Describe the Bug

When logging in using Firefox (on Windows and Fedora) on Umami with autofilled passwords, Umami does not allow submission of the form (front-end) because it thinks fields are not filled. After changing some characters in the fields, submission is allowed and login proceeds as expected.

For both Umami and Firefox, I am using the most recent versions.

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Docker (behind nginx https proxy)

**Comment by hankolsen** [comment]
Duplicate of #2449 ?

**Comment by Koen1999** [comment]
> Duplicate of #2449 ?

Thank you for pointing this out. I indeed consider this a duplicate. I will close this issue in favor of the older issue, and follow that one.
