### ISSUE TITLE
Tracking script returns 403

### ISSUE THREAD

**Issue by cocowalla** [umami-software/umami#2500]
### Describe the Bug

I've got Umami v2.9.0 setup and working just fine for a website that programmatically sends events from the backend. Now I've added a new website and want to use the JavaScript tracking code for it. So, I add this to the web site (this is from the Umami web app, with Umami running at `umami.example.com`):

```html
<script async src="https://umami.example.com/script.js" data-website-id="<MY_WEBSITE_ID_HERE>"></script>
```

But no pages are tracked, and if I check the browser console I see that Umami is returning a 403 (forbidden) error. There are no logs at all from the Umami instance, so I've no idea what's going on.

Any help would be much appreciated 🙏 

### Database

PostgreSQL

**Comment by cocowalla** [comment]
So, if I add `data-do-not-track="true"` or `data-do-not-track="false"` to the script element, the 403s dissapear in Firefox - but no XHR request is made. Meanwhile over in Chrome and Edge, the 403s persist.

**Comment by Bagpuss** [comment]
In case it helps anyone else: I just was struggling today with the same problem, and I came across this post: https://github.com/umami-software/umami/issues/1461#issuecomment-1237625977

Basically if you are visiting from an IP listed in IGNORE_IPs, then it will return a 403. I hadn't noticed this before and thought that something had broken when updating.
