### ISSUE TITLE
Date switching doesn't work

### ISSUE THREAD

**Issue by wokalek** [umami-software/umami#2540]
### Describe the Bug

Previously, switching worked for 1 day, switching one day if you selected “today” in the switch. Now he behaves in the wrong way:

![Анимация](https://github.com/umami-software/umami/assets/23037847/566d8aaf-a917-4dfc-8611-117da050018e)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.10.0

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
Confirmed, we will get this fixed.

**Comment by mikecao** [comment]
Fixed in v2.10.1.
