### ISSUE TITLE
After Update to 2.10.0 teams got no websites and cant assign new ones

### ISSUE THREAD

**Issue by KaiSoellch** [umami-software/umami#2543]
### Describe the Bug

After Update to 2.10.0 teams got no websites and cant assign new ones
![image](https://github.com/umami-software/umami/assets/1941783/b15651b6-6dd1-4ac2-9d71-78a7fa262499)
cant assign websites to team
![image](https://github.com/umami-software/umami/assets/1941783/88ef4c04-43fc-4f40-b68a-cb5d363a49fa)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.10.0

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by KaiSoellch** [comment]
its also not possible to assign users to websites
![image](https://github.com/umami-software/umami/assets/1941783/7feb2aad-ed97-4c30-b6af-211eb3d44100)

**Comment by KaiSoellch** [comment]
there are several sites configured and active tracking
![image](https://github.com/umami-software/umami/assets/1941783/821babbc-0741-404c-9d83-2613d73f5dc3)

**Comment by franciscao633** [comment]
We completely redid teams in 2.10. You can see details [here](https://umami.is/blog/improved-teams-collaboration).

**Comment by KaiSoellch** [comment]
hi @franciscao633 thanks for the link but like in your screenshot
![image](https://github.com/umami-software/umami/assets/1941783/055438a0-9a3c-4d24-89a4-d5e940e31eff)
i cant migrate a website to a team
![image](https://github.com/umami-software/umami/assets/1941783/082ac82d-c086-41f6-a7ac-2daee204a900)
the option transfer is missing

**Comment by franciscao633** [comment]
That's not correct. Putting in a hotfix soon.
