### ISSUE TITLE
Support for wildcard values for funnels

### ISSUE THREAD

**Issue by AkashRajpurohit** [umami-software/umami#2545]
### Describe the feature or enhancement

It would be great to have a wildcard support for values while preparing a funnel.
For example, user goes to blogs page and click on any blog `/blog` -> `/blog/*`.

**Comment by franciscao633** [comment]
Yea there's a bucket list for the funnel report that we need to get to. The parameters UX needs to redone with drag/drop + editability, need to add custom events as a step, and wildcards like your suggesting. Adding a label so the issue doesn't become stale. Thanks for your suggestions.

**Comment by AkashRajpurohit** [comment]
Btw, I was able to get the wildcards to work on my forked version, but couldn't test for Clickhouse since I could not find any doc for umami + Clickhouse setup.

Can discuss on discord, can send an initial PR for the SQL one as a starting point if needed.

**Comment by franciscao633** [comment]
Sure create a PR and ill test it out and take a look. Thanks!

**Comment by franciscao633** [comment]
Feature added in [v2.11.0](https://github.com/umami-software/umami/releases/tag/v2.11.0)
