### ISSUE TITLE
Umami failed to send request, server responded with status 400

### ISSUE THREAD

**Issue by itsOdell** [umami-software/umami#2546]
### Describe the Bug

Im using Umami cloud for website analytics purposes, I have umami setup in this way:

```
import Script from 'next/script'

<Script
        src={`https://analytics.us.umami.is/script.js`}
        data-website-id={`"${UMAMI_ID}"`}
        strategy="afterInteractive"
      />
```

and this is whats getting logged to the browser:
![image](https://github.com/umami-software/umami/assets/75822755/f98242f8-3b7e-45c6-83f6-a5a11e5e7997)
![image](https://github.com/umami-software/umami/assets/75822755/d929cd83-82a8-4d7b-8354-19ba94082b34)

but in the networks tab, the intial request is successful: 
![image](https://github.com/umami-software/umami/assets/75822755/c47e6e13-f1e7-49d9-964b-d011498b24b9)

i also am not getting any data collected in the umami cloud interface

### Database

Umami Cloud

### Which Umami version are you using? (if relevant)

Umami Cloud

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

localhost

**Comment by franciscao633** [comment]
You can try something like this. Let me know if it works.
```
<script
  src="https://analytics.us.umami.is/script.js"
  data-website-id={UMAMI_ID}
  strategy="afterInteractive"
/>
```
