### ISSUE TITLE
MySQL broken search

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#2557]
### Describe the Bug

DB sided search (websites, users, ...) is broken on my side with current version (2.10.1) and Prisma.
An error message is shown front-end, and Prisma throws an error (log is pasted below for a website search).

It looks like I shouldn't be the only one affected, and most likely a bug in Prisma.

### Database

MySQL

### Relevant log output

```shell
PrismaClientValidationError:
Invalid `prisma.website.findMany()` invocation:

{
  where: {
    userId: "41e2b680-648e-4b09-bcd7-3e2b10c06264",
    AND: {
      OR: [
        {
          name: {
            contains: "a",
            mode: "default"
          }
        },
        {
          domain: {
            contains: "a",
            mode: "default"
          }
        }
      ]
    },
    deletedAt: null
  },
  include: {
    user: {
      select: {
        username: true,
        id: true
      }
    }
  },
  take: 10,
  skip: 0,
  orderBy: [
    {
      name: "asc"
    }
  ]
}

Unknown argument `mode`. Did you mean `lte`?
```

**Comment by Maxime-J** [comment]
Ok, it's not a bug in Prisma.
`mode` property was only included with PostgreSQL in previous Umami versions.

It is now also included with a default value with MySQL (see `getQueryMode` and `getSearchParameters` in `lib/prisma.ts`)
but it's not available in generated Prisma Client API when `mode` isn't needed.

Docs:
https://www.prisma.io/docs/orm/prisma-client/queries/filtering-and-sorting#case-insensitive-filtering
https://www.prisma.io/docs/orm/prisma-client/queries/case-sensitivity

**Comment by franciscao633** [comment]
Good catch. will approve thanks.
