### ISSUE TITLE
Date picker styling issue

### ISSUE THREAD

**Issue by Maxime-J** [umami-software/umami#2559]
### Describe the Bug

When choosing a custom range, date picker modal can have overflow issues with some languages.
I don't think it happened before, but can't say from which version it's like that.

This seems to happen when day name is more than 3 characters, for example in French:
![calendar](https://github.com/umami-software/umami/assets/12450219/2bdffa6a-7023-4470-88e7-fddb190b1dcb)

But it could be way worse: (Português do Brasil)
![calendar-2](https://github.com/umami-software/umami/assets/12450219/0e42bb93-ac06-4abc-a51e-439cb0ce4520)

### Database

PostgreSQL

**Comment by franciscao633** [comment]
Just one clarification. Can you point out the issue with the French screenshot? Also thanks again for all the help with the community.

**Comment by Maxime-J** [comment]
Would you accept contributions to your react-basics repo?
Here is a way to fix these styling issues https://github.com/Maxime-J/react-basics/commit/b882ca94722304d7de4873d3a5ba4607c9ed0051

Note that English locale is also affected by these issues, the calendars cells not having the length in some cases:
![calendar_cells](https://github.com/umami-software/umami/assets/12450219/5e59c143-ad64-42fe-aefc-a2e932d202da)

**Comment by franciscao633** [comment]
@Maxime-J Yes we are welcome to PRs and contributions on all our public repositories.
