### ISSUE TITLE
Tracker script always using /api/send rather than the endpoint defined by environment variable

### ISSUE THREAD

**Issue by shiruken** [umami-software/umami#2562]
### Describe the Bug

The tracker script always references `/api/send` rather than the endpoint defined by the `COLLECT_API_ENDPOINT` environment variable.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.10.1

### How are you deploying your application? (if relevant)

Railway Template

**Comment by franciscao633** [comment]
Confirmed. Do you know what version you were on previously before upgrading?

**Comment by shiruken** [comment]
Judging by when analytics stopped being reported, it looks like the v2.10.0 release caused the issue

**Comment by jonaskuske** [comment]
The replacer in the script is looking for `"/api/send"`, but the script contains <code>\`${someExpression}/api/send\`</code>

**Comment by franciscao633** [comment]
Thanks, this is fixed. The regex expression in update-tracker was incorrect as @jonaskuske noted.

**Comment by jonaskuske** [comment]
Thanks for the quick update!

But the regex is now adding superfluous quotes into the script, as the double quotes were only removed from the regex, not from the replacement string ⚠️

@franciscao633

**Comment by franciscao633** [comment]
That was not smart... fixed again!
