### ISSUE TITLE
cannot filter report by visit time

### ISSUE THREAD

**Issue by LightInn** [umami-software/umami#2575]
### Describe the feature or enhancement

I would like to create rapport to see only user witch didnt bounce, and stay a bit on the page.

**Comment by franciscao633** [comment]
This specific report is not in our plans, but are working on user specific reports like user journeys, etc.

**Comment by daeh** [comment]
I would also really like to be able to use "Visit duration" as a filter. 

I'm surprised that this (or at least the ability to filter bounces) isn't already a feature. Really hope that this makes it into the development plans!
