### ISSUE TITLE
Can umami add website UV and PV statistics feature?

### ISSUE THREAD

**Issue by appotry** [umami-software/umami#2580]
### Describe the feature or enhancement

I use Hexo static blog for personal purposes and need PV and UV statistics functionality. 

The service I'm currently using is not very stable. It would be great if Umami could add UV and PV statistics feature.

**Comment by mikecao** [comment]
Do you mean unique visitors and page views? That's already included.

**Comment by appotry** [comment]
yes. I saw that it supports unique visitors and pages, but I didn't see an explanation of how to obtain these two parameters and set them on the webpage.

**Comment by appotry** [comment]
include page uv pv, and site uv pv
how to obtain these parameters and set them on the webpage

**Comment by mikecao** [comment]
Just follow the setup instructions, Umami will collect the data automatically.

**Comment by appotry** [comment]
@mikecao I want to get page UV, PV, and site UV, PV from Umami, and then set them on the webpage.

After carefully checking the documentation, I couldn't find the method to set them. Did I miss something?

**Comment by appotry** [comment]
@mobeicanyue Good job，已经用上了
