### ISSUE TITLE
Realtime is re-animating on every event

### ISSUE THREAD

**Issue by mikeckennedy** [umami-software/umami#2583]
### Describe the Bug

Watch this animated gif, notice the redrawing and the animations without refreshing the page:

![redraw-every-update](https://github.com/umami-software/umami/assets/2035561/34c66dc1-f6f3-4938-9e53-6e67d4e14bac)

That is the view (at least on Safari) for the real time dashboard for one of my web apps. Every time anything changes, it reanimates the whole graph. I like that animation on load, but it seems out of place for a fixed "show me the realtime view" of the site.

I would love to see it not flashing constantly and animating every, unchanged part of the UI when only the last bar changed or even when it shifts in time, it's weird that it animates the bars up rather than just shifting them.

Feel free to close as won't fix if you don't find this relevant.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.10.2

**Comment by mikecao** [comment]
It shouldn't do that. We'll get it fixed.

**Comment by mikeckennedy** [comment]
Thank you @mikecao !

**Comment by mikeckennedy** [comment]
Thank you @mikecao

**Comment by franciscao633** [comment]
Fixed in v2.11.0

**Comment by mikeckennedy** [comment]
I just tested this @franciscao633 and it's perfect. Thank you!
