### ISSUE TITLE
Menu MY ACCOUNT & TEAM lost when responsive mobile size

### ISSUE THREAD

**Issue by chris-lily** [umami-software/umami#2585]
### Describe the Bug

the MY ACCOUNT & TEAM Menu
disappears when switching to a mobile size screen

Mobile Size  mode menu MY ACCOUNT & TEAM is KO
![Screenshot from 2024-03-08 18-54-23](https://github.com/umami-software/umami/assets/50880840/7a5c664b-edeb-4c81-aea7-58db3cedaa06)

Desktop mode menu MY ACCOUNT & TEAM is OK
![Screenshot from 2024-03-08 18-51-24-blur](https://github.com/umami-software/umami/assets/50880840/0f03f128-c6cc-4649-8d19-0fed96716fb8)

### Database

MySQL

### Which Umami version are you using? (if relevant)

umami v2.10.2

### Which browser are you using? (if relevant)

Google Chrome Version 122.0.6261.69 (Official Build) (64-bit)

### How are you deploying your application? (if relevant)

umami v2.10.2   avec docker pull ghcr.io/umami-software/umami:mysql-latest

**Comment by chris-lily** [comment]
Thank's <3

**Comment by franciscao633** [comment]
Fixed in v2.11.0
