### ISSUE TITLE
Add a note in the docs on the behaviour of event tracking data attributes

### ISSUE THREAD

**Issue by paradite** [umami-software/umami#2586]
### Describe the feature or enhancement

I found out today (the hard way) that using data attributes for event tracking has a consequence that other event listeners are not triggered: https://umami.is/docs/cloud/track-events

I think it is better to make it clear in the docs to avoid accidentally disabling other event listeners on click.

For more context, I am using GA4 to track clicks in addition to umami because I needed it for Google Ads conversion tracking, and GA4 events stopped firing once I added `data-umami-event` to my elements.

**Comment by franciscao633** [comment]
We should definitely call that out. I added a note to the [track-event](https://umami.is/docs/track-events)  section. Hopefully it won't happen to others.

**Comment by ahmednabik** [comment]
Is there a work around to add data attributes and also make the event listeners fire on click?
