### ISSUE TITLE
Enhancement: Dark/Light Theme based on System Preference

### ISSUE THREAD

**Issue by arcastro** [umami-software/umami#2587]
### Describe the feature or enhancement

Hello,

Looks like Umami supports both light/dark themes with a toggle on the top-right.
However, it always defaults to light theme.

Would be great if the default would be based on system preference.

Best regards,

**Comment by franciscao633** [comment]
Probably wont be a priority for us since the toggle is visible upon login and users just have to set it once. However, it is a cool default feature and we are always welcome to PRs.

**Comment by Maxime-J** [comment]
Hi @franciscao633,
I can probably give it a shot in a fair amount of time.
Here's how I see it, more or less like Github:
![theme_system](https://github.com/umami-software/umami/assets/12450219/b5b6a186-b542-43b4-9b7b-53d546a64721)

As soon as a theme is manually set, that sync toggle will be off
and like the other settings, user would have to go through its settings to get back to the default sync enabled.

That way, the simplicity of theme toggling is kept.

Would it be ok for you ?

**Comment by franciscao633** [comment]
Looks like the system theme check was already there, but the default theme logic was incorrect. This has been fixed in this [commit](https://github.com/umami-software/umami/commit/902d4c83bab934fe93a47eef56ac56c9b79504f4) by Mike.  Going to close this out, but thanks for helping identify the bug.
