### ISSUE TITLE
data-umami-event attribute non-functional (Reopening #2186)

### ISSUE THREAD

**Issue by plokkingmachine** [umami-software/umami#2590]
### Describe the Bug

I utilized the `data-umami-event` attribute in some of my links and the data gets collected. For some elements it does not work.
Both of them are `<a>` elements.
Page views are registered without issues.

### Database

PostgreSQL

### Relevant log output

```shell
No, there is none in the console output.
Some events get recorded, some don't.
```

### Which Umami version are you using? (if relevant)

v2.10.2

### How are you deploying your application? (if relevant)

Docker

**Comment by briancao** [comment]
I'm having trouble reproducing this issue.  Are you using any particular UI framework, link component, or does this apply to a straight `<a>` element in html?

And when you say 'some elements it does not work', are you saying it disables the <a> tag from working, or that Umami is not sending data?

**Comment by ThomasCloarec** [comment]
Would it be possible to up the limit a bit please? 

For some precise events, it is useful to be able to describe them in more details than 50 characters.
