### ISSUE TITLE
REMOVE_TRAILING_SLASH behaves "unexpected"

### ISSUE THREAD

**Issue by profhase** [umami-software/umami#2592]
### Describe the Bug

The code 
```
      if (process.env.REMOVE_TRAILING_SLASH) {
        urlPath = urlPath.replace(/.+\/$/, '');
      }
```
from https://github.com/umami-software/umami/blob/a2245efa2defba71990fac3ece78e048e79729a0/src/pages/api/send.ts#L113 leads to issue: #2385  : It does not only remove the trailing slash but also everything before it. (Also see

https://umami.is/docs/environment-variables

)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

newest

### Which browser are you using? (if relevant)

any

**Comment by franciscao633** [comment]
Fixed in v2.11.0
