### ISSUE TITLE
User flow report

### ISSUE THREAD

**Issue by sumitridhal** [umami-software/umami#2598]
### Describe the feature or enhancement

Support to extract data, based on user flow.
[Example ](https://mixpanel.com/blog/user-flow-analysis/)

**Comment by franciscao633** [comment]
This is currently in the works. Aiming to have it out in the next 1-2 releases.

**Comment by sumitridhal** [comment]
@franciscao633 That's great. Thanks for the update.
Is there a feature list that is in WIP?

**Comment by krstivoja** [comment]
any update on this one?

**Comment by mikecao** [comment]
This is the covered by the user journey report.
