### ISSUE TITLE
API team user endpoint fails with 405

### ISSUE THREAD

**Issue by theriftlab** [umami-software/umami#2599]
### Describe the Bug

When calling the following endpoint as per the docs:

> GET /api/teams/{teamId}/users/{userId}
> 
> Get a user belonging to a team.

the server returns 405. Both Postman & the official API client also fail with this call.

### Database

MySQL

### Which Umami version are you using? (if relevant)

2.10.2

### How are you deploying your application? (if relevant)

Both local npm install & remote AWS

**Comment by franciscao633** [comment]
Odd it is working for me. Are you able to hit the previous endpoint `/api/teams/{teamId}/users`? I just tried it on a test db.

![image](https://github.com/umami-software/umami/assets/31608805/7fc5455a-02c7-44b0-957c-79c0c286d725)

Then adding userId

![image](https://github.com/umami-software/umami/assets/31608805/5fa88b08-66c1-4c17-a94d-457ec37e1d05)

**Comment by theriftlab** [comment]
@franciscao633 apologies, my pm2 had multiple `umami`s - clearing them and restarting seems to have ensured the latest version is running & the issue is fixed. I need a stiff drink lol.
