### ISSUE TITLE
Add the possibility to share a website analytics on a personal account, to a team

### ISSUE THREAD

**Issue by pclavelloux** [umami-software/umami#2604]
### Describe the feature or enhancement

All my websites are set on my user's profile.
I would like to create a team to invite persons and share within that team some of the website set on my profile.

I don't think it's possible right now, I can either:
- create again the website with anoter code (it reset all my stats)
- transfer the ownership but then on my personal profile I can't see this website

**Comment by franciscao633** [comment]
If your interested in just sharing just the website details you can supply that team [share URLs](https://umami.is/docs/enable-share-url)  for each website you want to share. Alternatively if you really want team functionality where you can create reports, access realtime, and event data you would need to transfer ownership of the websites to that team.
