### ISSUE TITLE
Clicking on team website from dashboard changes team

### ISSUE THREAD

**Issue by Wulfheart** [umami-software/umami#2607]
### Describe the Bug

Given I have a website which belongs to a team, when clicking on the website it changes the "team" back to the user. 

https://github.com/umami-software/umami/assets/25671390/887210d2-771e-4aa3-a371-6f6e4e08fd8b

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
Confirmed. We will get this fixed.
