### ISSUE TITLE
admin user shows role as unknown

### ISSUE THREAD

**Issue by brunoamaral** [umami-software/umami#2609]
### Describe the Bug

<img width="757" alt="image" src="https://github.com/umami-software/umami/assets/543344/c1f8ab27-c28a-420d-b02b-02352a045e04">

### Database

PostgreSQL

**Comment by franciscao633** [comment]
Weird. The admin label was missing from `messages.ts`. This is fixed in dev and will go out next release.

**Comment by franciscao633** [comment]
Fixed in release v2.11.0
