### ISSUE TITLE
No query parameters captured

### ISSUE THREAD

**Issue by oliverzgy** [umami-software/umami#2615]
### Describe the Bug

All the paths are captured, but query parameters lost. This page is embeded with tracking code [https://front.dev.openstone.cn/?channel=2023-0001](https://front.dev.openstone.cn/?channel=2023-0001). When the page is loaded, 4 requests of umami statistics sent, but no query parameters captured. 

![image](https://github.com/umami-software/umami/assets/3712729/5b86070f-5c7a-4e42-a22d-0e76a6b5f863)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.10.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
upon visiting i see a single send with the query params captured in the URL. Did you update something since?
![image](https://github.com/umami-software/umami/assets/31608805/c8b8c0ba-489e-44e4-97c8-736eb175ef7e)

**Comment by oliverzgy** [comment]
Follow the step below , this could be reproduced:

1. Open a browser like chrome, open the check console, and then copy and paste the link above 

![image](https://github.com/umami-software/umami/assets/3712729/df2779bd-0fa3-4b9d-b208-5d6c536d8024)

![image](https://github.com/umami-software/umami/assets/3712729/1cb3c88e-d834-4045-9174-b34211d41220)

![image](https://github.com/umami-software/umami/assets/3712729/da1a18eb-1340-4bed-8646-364835e27c53)

![image](https://github.com/umami-software/umami/assets/3712729/7dacfb21-1d7c-4b11-9b22-c8c631f06f77)
