### ISSUE TITLE
api for real-time online counts & api for the current page

### ISSUE THREAD

**Issue by HowieHz** [umami-software/umami#2616]
### Describe the feature or enhancement

Sorry, my English proficiency is not very good, so I used a translator
`GET /api/websites/{websiteId}/active`
Currently, the delay of this API is significant, almost 2 minutes. I previously set the API on my site to refresh every 5 seconds, but when visitors on my site access this API, it still shows that 0 people are visiting.
After two minutes, the API updated, and my visitors had finished browsing the webpage.If displayed directly according to the API, my visitors will not be able to see the online count as 1. So, I had to set it up to display 1 if the API returns 0.

Also, can you provide an API to fetch the current number of online users on a certain webpage?
For example, retrieve the online user count on the /links page.

![image](https://github.com/umami-software/umami/assets/94725606/ec8287b7-5169-4a92-9b89-eb071f1f4698)
The online user count displayed on this page is always accurate. If this could be provided as an API, it would fulfill the first point I mentioned above. Thank you for checking my issue.

**Comment by franciscao633** [comment]
It looks like the refetchinterval is set to 60 seconds. If you want to set it lower in `ActiveUsers.tsx` you are welcome to. The count should update after the endpoint is called, so need for any custom logic.

**Comment by HowieHz** [comment]
> h

Can we add an environment variables to control this variable? I'm using Umami in Docker.

**Comment by HowieHz** [comment]
> It looks like the refetchinterval is set to 60 seconds. If you want to set it lower in `ActiveUsers.tsx` you are welcome to. The count should update after the endpoint is called, so need for any custom logic.

Can we add an environment variables to control this variable? I'm using Umami in Docker.
