### ISSUE TITLE
Add `splitted_url_query` and `splitted_referrer_query` for better UTM/Query Params filtering

### ISSUE THREAD

**Issue by mathix420** [umami-software/umami#2619]
### Describe the feature or enhancement

Many issues and discussions already asking the same thing, this feature request is meant to group them and therefore show the significant interest in this feature.

**Exemple:**
Being able to filter stats/metrics/events by campaign source.

URIs:
```
https://mysite.com/blog-1?utm_source=twitter&utm_medium=social&utm_campaign=feature-1
https://mysite.com/blog-1?utm_source=facebook&utm_medium=social&utm_campaign=feature-1
https://mysite.com/blog-1?utm_source=twitter&utm_medium=social&utm_campaign=feature-2
https://mysite.com/blog-1?utm_source=twitter&utm_medium=social&utm_campaign=feature-3
```

Right now we can only filter by **all** query params at the same time, and not by specific `utm_campaign` or `utm_source`.

**Mentions of this feature:**
- https://github.com/umami-software/umami/issues/2086
- https://github.com/umami-software/umami/issues/1850#issuecomment-1536359290
- https://github.com/umami-software/umami/discussions/619#discussioncomment-6091104
- https://github.com/umami-software/umami/issues/273#issuecomment-821990623
- https://github.com/umami-software/umami/issues/845

**Comment by franciscao633** [comment]
We currently have a UTM report that will go out next release. It isn't exactly what your requesting since it won't filter from the dashboard, but it will give a general summary on UTM param vs views across a date range.

![image](https://github.com/umami-software/umami/assets/31608805/d9f23785-2ec2-43d8-b1d7-cc06a6704d8a)

**Comment by mathix420** [comment]
It's looking pretty neat, will give it a try!
It seems to fulfill the goal of tracking campaigns performances, so it might not be needed to implement my suggestion.
