### ISSUE TITLE
completely redundant large dependency

### ISSUE THREAD

**Issue by boehs** [umami-software/umami#2623]
### Describe the Bug

The timezone picker requires downloading 30kb of gzipped json the browser already has from another library. Fixing this is a 2 line change: 

![image](https://github.com/umami-software/umami/assets/51836263/304c3906-1e31-4ecb-a2e7-16804aab74df)

![image](https://github.com/umami-software/umami/assets/51836263/87ea67db-9bc9-447b-8170-f72dd1aab13b)

https://github.com/boehs/miami/commit/f07058efcbbaa8e4b90c6b758f6f86997321a939

**Comment by boehs** [comment]
<img width="1427" alt="image" src="https://github.com/umami-software/umami/assets/51836263/34b1d5d4-48b7-4602-bbd9-e1a4cbf24324">

I also got rid of moment-timezones on the frontend

**Comment by boehs** [comment]
https://github.com/umami-software/umami/assets/51836263/d7f6b5e2-bfa0-4683-b807-f4c61e07ee91

also it seems like the timezone picker doesn't even do anything

**Comment by boehs** [comment]
before vs after
![image](https://github.com/umami-software/umami/assets/51836263/a27c0ba5-33cc-4475-938a-cc4af0dd8dbe)
![image](https://github.com/umami-software/umami/assets/51836263/8a1fcc3c-6a19-4844-875c-ee736d5eb361)
it's still not good but it's less not bad

**Comment by mikecao** [comment]
Would welcome a PR for this.

**Comment by franciscao633** [comment]
Fixed in release v2.11.0
