### ISSUE TITLE
No region and cities are showing

### ISSUE THREAD

**Issue by dhwaj1902** [umami-software/umami#2624]
### Describe the Bug

No region and cities are showing in Umami dashboard, while countries are showing.
Countries:
<img width="586" alt="image" src="https://github.com/umami-software/umami/assets/57860123/10cc931a-db15-4743-a8d3-f41e5013c1b8">
Region:
<img width="1393" alt="image" src="https://github.com/umami-software/umami/assets/57860123/8ceb984c-9f92-4279-a962-c780e473c1c8">
Cities:
<img width="1445" alt="image" src="https://github.com/umami-software/umami/assets/57860123/9632a05d-d696-4296-ab00-1eaeb1d4d869">

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.10.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
Are you behind Cloudflare? If you are you need to enable geolocation data.

**Comment by dhwaj1902** [comment]
@mikecao Got it done, thanks for the help!

**Comment by YONN2222** [comment]
For anyone looking for the Cloudflare setting:

Go to your domain -> Rules -> Settings -> Managed Transforms, then enable **Add visitor location headers**.
