### ISSUE TITLE
world map

### ISSUE THREAD

**Issue by xCss** [umami-software/umami#2627]
### Describe the Bug

Singapore is not visible on the world map. 

[![](https://github.com/umami-software/umami/assets/10877162/ffda6b0a-8b2f-42d2-89ab-69a83be9b889)](https://github.com/umami-software/umami/assets/10877162/ffda6b0a-8b2f-42d2-89ab-69a83be9b889)

### Database

PostgreSQL

**Comment by franciscao633** [comment]
We use [react-simple-maps](https://github.com/zcreativelabs/react-simple-maps). Feel free to open an issue there is there is an issue with the generated map.
