### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by AkashRajpurohit** [umami-software/umami#2628]
### Describe the Bug

The search for individual stats like Pages, referrers etc is broken and returns the whole dataset.

Seems to work fine on Cloud but broken on self-hosted version, is there any bug fix that is tracking this issue that will be fixed in new release?

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.10.2

**Comment by franciscao633** [comment]
Trying to figure out what version this broke, but will get fixed next release. #2605 is similar, but not exactly related to your issue.

**Comment by franciscao633** [comment]
Fixed in release v2.11.0
