### ISSUE TITLE
This issue still exists in v2.10.2. url encode special characters

### ISSUE THREAD

**Issue by zonewancheng** [umami-software/umami#2631]
This issue still exists in v2.10.2.

redirect to the page with special characters 

```
url: "/blog/2023/09/11/VLDB%E8%AE%BA%E6%96%87%E6%8E%A8%E8%8D%90"
```

refresh the page with special characters

```
url: "/blog/2023/09/11/VLDB%25E8%25AE%25BA%25E6%2596%2587%25E6%258E%25A8%25E8%258D%2590"
```

_Originally posted by @zonewancheng in https://github.com/umami-software/umami/issues/2470#issuecomment-1991346190_

**Comment by franciscao633** [comment]
There was a fix for this in the latest version. When you have time, can you confirm if it's fixed for your site as well?
