### ISSUE TITLE
translations: regression with `tracking code`

### ISSUE THREAD

**Issue by kiprasmel** [umami-software/umami#2633]
There's been a regression with the "tracking code" translation -- it used to translate to just "tracking code", but now the english text contains (1) "tracking code", and (2) the instructions to setup the tracking code.

Old translations do not include these instructions (2), only the "tracking code" text.

While we're at it, the translation could additionally add a link to the tracker configuration docs: [umami.is/docs/tracker-configuration](https://umami.is/docs/tracker-configuration)

**Comment by mikecao** [comment]
Can you show me an example? I can't seem to find what you're referring to.

**Comment by kiprasmel** [comment]
en US (full info)

![en US](https://github.com/umami-software/umami/assets/29430509/8bb7b355-e154-428e-9cbe-95a706864afd)

en UK (missing info):
![en UK](https://github.com/umami-software/umami/assets/29430509/86ecf836-dd1c-4946-94a8-30488e0d1325)

lt LT (missing info):

![lt LT](https://github.com/umami-software/umami/assets/29430509/0d5630ce-8bbd-451a-beca-bd22749fd5bf)

**Comment by kiprasmel** [comment]
no it isn't...
