### ISSUE TITLE
Environment variable "CLIENT_IP_HEADER" support Case insensitive

### ISSUE THREAD

**Issue by acmookey** [umami-software/umami#2634]
### Describe the feature or enhancement

When the CLIENT_IP_HEADER is set to "X-Real-IP" (in upper case), the setting does not take effect (the effect at this time will still use the request-ip package to obtain the ip from the code point of view). However, when the CLIENT_IP_HEADER is set to "x-real-ip" (all lowercase), the value can be correctly obtained from the HTTP Header X-Real-IP. The document does not mention whether the CLIENT_IP_HEADER value is case sensitive.

The above confusion exists when setting the environment variable "CLIENT_IP_HEADER". Therefore,i'm asking whether the setting value of the environment variable CLIENT_IP_HEADER can be supported to be case-insensitive, or explain in the [document description](https://umami.is/docs/environment-variables) that only all lowercase header values are supported. 

ps: The above content is translated from Chinese, please forgive me for any inaccuracies. ☺

**Comment by mikecao** [comment]
You are right. We should convert the header to lowercase before doing the comparison.
