### ISSUE TITLE
t.toLowerCase(...).replaceAll is not a function

### ISSUE THREAD

**Issue by SmmnaBeta** [umami-software/umami#2635]
### Describe the Bug

mobile phone explorer

t.toLowerCase(...).replaceAll is not a function TypeError: t.toLowerCase(...).replaceAll is not a function at renderLabel (https://example.com/_next/static/chunks/2977-6408ac201d2165cd.js:1:5023) at f (https://example.com/_next/static/chunks/2977-6408ac201d2165cd.js:1:15563) at https://example.com/_next/static/chunks/2977-6408ac201d2165cd.js:1:16158 at Array.map (<anonymous>) at t.Z (https://example.com/_next/static/chunks/2977-6408ac201d2165cd.js:1:16151) at rk (https://example.com/_next/static/chunks/fd9d1056-91813fe3cbd705a6.js:1:40371) at iB (https://example.com/_next/static/chunks/fd9d1056-91813fe3cbd705a6.js:1:116380) at o4 (https://example.com/_next/static/chunks/fd9d1056-91813fe3cbd705a6.js:1:94633) at https://example.com/_next/static/chunks/fd9d1056-91813fe3cbd705a6.js:1:94455 at o3 (https://example.com/_next/static/chunks/fd9d1056-91813fe3cbd705a6.js:1:94462)

![PixPin_2024-03-28_11-22-04](https://github.com/umami-software/umami/assets/58733268/d984f894-5cd0-42bb-88e3-320e0be5b5fc)

### Database

MySQL

### Which browser are you using? (if relevant)

android mobile explorer

**Comment by SmmnaBeta** [comment]
V2.10.2

**Comment by franciscao633** [comment]
Fixed in release v2.11.0
