### ISSUE TITLE
When creating a report, not all auto-completion options are displayed when creating a filter by city

### ISSUE THREAD

**Issue by wokalek** [umami-software/umami#2646]
### Describe the Bug

I can insert only `Krasnodar` city and only it, which was present in visits to the site today, but not all the options for cities that were previously in visits.

Same with region, referrer fields, etc.

![image](https://github.com/umami-software/umami/assets/23037847/32fbd0d7-44a2-41eb-a31a-69b609da667b)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.11.0

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
I can't reproduce the bug 100% of the time, but I was able to get it. When it happens, just close filter and redo the step. If you have steps to reproduce the bug every time please lets me know. Thanks for reporting.

![image](https://github.com/umami-software/umami/assets/31608805/d1acaaab-428b-40d4-a18b-62bb1e4e201a)

**Comment by franciscao633** [comment]
Found the issue. The report date parameters are not getting correctly passed o the filter search. Its only looking for possible cities in the last day and not 90 days. Will get this fixed.
