### ISSUE TITLE
Error when changing report's date range after "run query"

### ISSUE THREAD

**Issue by uiii** [umami-software/umami#2649]
### Describe the Bug

When I create report, select website, date range and run query and then change the date range I get this error:
```
Something went wrong.
Cannot set properties of undefined (setting 'text')
```

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.0

**Comment by franciscao633** [comment]
I can't seem to reproduce the error. Do you have a specific report I can target? (Funnel, Retention, etc). I'm testing on a self-hosted psql instance.
