### ISSUE TITLE
Integration with Expo Router

### ISSUE THREAD

**Issue by AprilNEA** [umami-software/umami#2654]
### Describe the feature or enhancement

As a developer involved in building applications with Expo, I've been leveraging Expo Router to enhance the routing capabilities in my projects. Expo Router provides a framework that allows for URL-like routing within React Native applications, offering a seamless experience similar to web navigation.

[Expo Router - Screen Tracking](https://docs.expo.dev/router/reference/screen-tracking/)

I kindly request the consideration of adding support or integration with the Expo Router. This feature would not only expand your user base by accommodating the needs of React Native developers but also enrich the analytics insights by capturing more detailed user interactions through advanced routing capabilities.

Umami has proven to be an excellent tool for web analytics; however, it currently focuses solely on the web platform, leaving a gap in the mobile application domain where no equally impressive open-source software exists.

Given the current landscape, I believe starting support from Expo Router could be an excellent entry point for extending Umami's capabilities into mobile app analytics. The lack of direct support or integration between Umami and the latest version of Expo Router is a missed opportunity. This integration would be incredibly beneficial for developers like myself who are looking for robust analytics solutions while utilizing the advanced routing features provided by Expo Route.

**Comment by AkashRajpurohit** [comment]
I think similar to their [node sdk](https://github.com/umami-software/node), if they release sdks for other platforms then it can be leveraged.
Just out of curiosity, if you have an expo project up and running, can you give it a try and see if this package works for React Native as well?

**Comment by AprilNEA** [comment]
> I think similar to their [node SDK](https://github.com/umami-software/node), if they release SDKs for other platforms then it can be leveraged. Just out of curiosity, if you have an expo project up and running, can you give it a try and see if this package works for React Native as well because I don't see any node specific APIs being used in this SDK that should be problematic for React Native

It's really a nice library. I tried it but ran into a problem, umami doesn't receive the data sent in the expo client because the User-Agent isn't set correctly (no node version found).

**Comment by jaime-rivas** [comment]
Please can this issue be reopened? Umami is wonderful and it would be great to easily track analytics in react native apps / expo. Finger crossed!

**Comment by YaserKhangoli** [comment]
I’ve recently published a React Native library for integrating Umami Analytics.
It’s designed to be lightweight and easy to use.
Feedback is very welcome.
💥 https://www.npmjs.com/package/react-native-umami-sdk
https://github.com/YaserKhangoli/react-native-umami

**Comment by geomlattice** [comment]
I am trying to test out the Expo Umami Analytics. 

I am confused on what the hostname should be for the expo react native app. The app is not a website deployed with a domain name, so what should be put there? Is the value for that arbitrary?

I am going to put something arbitrary for now in order to website id, but feedback on this would be highly appreciated! 

EDIT: seems to just work. Thanks @YaserKhangoli
