### ISSUE TITLE
TypeError: e.datasets[n] is undefined

### ISSUE THREAD

**Issue by AkashRajpurohit** [umami-software/umami#2656]
### Describe the Bug

Occasionally I am noticing lot more failures with this error in the console: `TypeError: e.datasets[n] is undefined`

It works when I do a hard refresh on the page, mostly this failure occurs when performing some actions like going to website details page from the overview, or like changing the dates.

I don't have any specific way to repro this consistently, but this is happening a lot more frequently since v2.11.0 upgrade.

Attaching a screenshot if its helps in debugging.

![image](https://github.com/umami-software/umami/assets/30044630/71390fe2-639e-4a2b-a44f-3c40f493b6dc)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.0

### Which browser are you using? (if relevant)

Firefox

### How are you deploying your application? (if relevant)

Docker

**Comment by gramakri** [comment]
Was debugging this same issue with the Cloudron package. This turns out to be ublock origin issue. It seems ublock blocks some URLs.

![image](https://github.com/umami-software/umami/assets/82041/270ff815-2a7f-4cba-a79c-de79075e10cc)

It loads fine when ublock origin is disabled .
