### ISSUE TITLE
Groups of websites

### ISSUE THREAD

**Issue by chreniuc** [umami-software/umami#2663]
### Describe the feature or enhancement

Having a few websites, might work ok with no groups, but after 10-15, things get a little messy.

I was wondering if others are interested in having a group feature. This way you can group websites on dashboard, and also expand all websites from a group or hide.

I think it would be more organized like this.

**Comment by franciscao633** [comment]
Not exactly the feature you are explaining, but you can achieve this with teams. You would create a team for each group, then assign your grouped websites to each team. Once your in a team context, you will only see websites belonging to your team or group.
