### ISSUE TITLE
Mobile navigation doesn't show the context switcher for user / team

### ISSUE THREAD

**Issue by brunoamaral** [umami-software/umami#2667]
### Describe the Bug

The desktop view shows a dropdown to switch context to a Team or user, but it doesn't show up on mobile.
<img width="1470" alt="image" src="https://github.com/umami-software/umami/assets/543344/ca58a9f8-efa6-41f9-a604-244e8e20efb1">

<img width="488" alt="image" src="https://github.com/umami-software/umami/assets/543344/6b2160b1-6cf9-43b9-8e31-80cc6eaabde3">

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.1

### Which browser are you using? (if relevant)

Chrome

**Comment by franciscao633** [comment]
Do you know what mobile device you are on? I can't seem to reproduce the issue. You should be able to see an icon to switch team context on mobile devices.

https://github.com/umami-software/umami/assets/31608805/55ed5b75-9334-4a8a-b84b-8ababa243fcb

**Comment by brunoamaral** [comment]
Sorry should have added that. I'm on an iphone 12 with google chrome.

![IMG_302D4ECEB9C8-1](https://github.com/umami-software/umami/assets/543344/25f9d593-c499-4924-8ed7-29645e6c806a)

**Comment by franciscao633** [comment]
Can you verify you are running the latest version? Websites should now have the `visits` metrics which is missing from your screenshot. 

![image](https://github.com/umami-software/umami/assets/31608805/67eb4f61-14fa-4d26-b883-72155cfb2d86)

**Comment by brunoamaral** [comment]
You're right, @franciscao633. I tried pulling the docker image again and this time it is showing the context button. Thank you for helping out. 🙂
