### ISSUE TITLE
Perhaps China should be added before Taiwan

### ISSUE THREAD

**Issue by Raven777777** [umami-software/umami#2668]
### Describe the Bug

On the map of the web page, the map of Taiwan and China is not one, which confuses Chinese users because when I share this web page, I will face censorship, and ambiguous maps will cause me a lot of trouble. So please add the China prefix to Taiwan on the web map, just like “Taiwan, China”.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

 Edg

### Which browser are you using? (if relevant)

 Edg

**Comment by franciscao633** [comment]
We use a 3rd party package [react-simple-maps](https://github.com/zcreativelabs/react-simple-maps).

**Comment by Raven777777** [comment]
> We use a 3rd party package [react-simple-maps](https://github.com/zcreativelabs/react-simple-maps). 

Thanks, I will try to edit the web file by myself.

**Comment by xingpingcn** [comment]
sc+100000
