### ISSUE TITLE
Countries: (Unknown) 100%

### ISSUE THREAD

**Issue by essovius** [umami-software/umami#2670]
Is there something I should do before collecting this data?

Database: MySQL
Version: v2.11.1

**Comment by franciscao633** [comment]
Are you testing via a local ip address or are all visitors of your websites showing unknown? The location wont work if you are testing locally. After the build step you should have a `geo` folder with a `GeoLite2-City.mmdb` db. This is used to lookup country, region, city, etc. Can you verify its there?

**Comment by essovius** [comment]
I do have `geo` folder and `GeoLite2-City.mmdb` file (around 52mb of size). Umami is currently installed on my Alpine Linux server, I'm using Nginx Unit to serve it via proxy from `localhost:4000`  I have a domain name to access to dashboard. I'm tracking stats for website using tracking code with custom `TRACKER_SCRIPT_NAME`

**Comment by zavan** [comment]
@essovius It could be that Umami is not receiving the correct visitor IP address from nginx, take a look at https://github.com/umami-software/umami/issues/2492#issuecomment-1925577415

**Comment by kiritoxjf** [comment]
> @essovius It could be that Umami is not receiving the correct visitor IP address from nginx, take a look at [#2492 (comment)](https://github.com/umami-software/umami/issues/2492#issuecomment-1925577415)

Thanks about that. I got the same problem in my umami. And I fixed it by adding the `proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;` in `nginx.conf`.
