### ISSUE TITLE
Inconsistent Data Presented Over Time

### ISSUE THREAD

**Issue by petetisa** [umami-software/umami#2672]
### Describe the Bug

Statistical results are not consistent when choosing the filter over time drop-down on Dashboard and property detail views. I recently installed/started tracking data on four web properties using Umami mid-week/mid-month. 2-3 days worth of data collection should report consistent total views/visits, etc. Attached screenshots illustrate the erroneous results.
![01-stats-1-week](https://github.com/umami-software/umami/assets/734864/3fea0fd6-4b23-4529-be4f-82aa908dedf8)
![02-stats-7-days](https://github.com/umami-software/umami/assets/734864/054bfa2f-6af7-4c7f-b2c3-62865db6503c)
![03-stats-30-days](https://github.com/umami-software/umami/assets/734864/c8bcd696-d45f-4ff6-985a-88a4856cf7cf)
![04-stats-this-month](https://github.com/umami-software/umami/assets/734864/c7684688-b5c6-4a65-86c0-68da35e01d0e)
![05-stats-6-months](https://github.com/umami-software/umami/assets/734864/2cb7fa1f-9f98-4b06-85f7-2de1dca56665)

### Database

MySQL

### Which Umami version are you using? (if relevant)

2.11.1

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Self Hosted

**Comment by mikecao** [comment]
Hey Pete, how are you? Long time no see. 😄 

So I think this might just be a terminology issue. When you select This week, it counts the days from Sunday to Saturday. When you select last 7 days, it counts the past 7 days, excluding today. So if you had a lot of traffic today, those numbers would be different. Same idea for last 30 days versus this month. And when you select last 6 months, it includes the previous 6 months, excluding the current month. If you look at the graph bars, I think it will be more clear.

If that's not the case, then we can dive deeper into your data to troubleshoot.

**Comment by mikecao** [comment]
But it could also mean we have it wrong and maybe we should include the current day by default.

**Comment by petetisa** [comment]
Thx for the ACK Mike and I'm a big fan of your projects. Back to business:

I processed your explanation and it now makes sense why I get the results I see. My only input would be that it is not intuitive. Maybe consider adjusting the query parameters based on the Filter selected. E.g. The 6 month filter should return the full result set right?

As an aside, I'm also using your Flight Framework in a number of projects and excited to see that get some traction.

**Comment by mikecao** [comment]
Alright, we'll change it so it always includes the current time period.. I think that makes more sense.

**Comment by petetisa** [comment]
@mikecao Thank you for considering my concerns/suggestions. I'm by no means an expert regarding web analytics. Like many I've been using GA for years and just excited to see more competitive products that align with end-user privacy and data ownership. You and the other contributors to this project are doing great work. My colleagues who consume the data love the clean interface and I like the API feature.

I don't believe there is a roadmap published, but for what it's worth, the "user segmentation" feature I noticed in Discussion, for lack a better descriptor, is exciting.

Thanks for all your hard work, and I hope to contribute in some way in the future. We'll have to catch-up personally some time soon.
