### ISSUE TITLE
Incorrect page view tracking since 2.11

### ISSUE THREAD

**Issue by melchiorb** [umami-software/umami#2677]
### Describe the Bug

After upgrading to 2.11, I noticed an issue with the default tracking:

On a single-page application (using history.pushState), the **full url (including domain) is tracked**, not just the path.

Reverting back to 2.10.2 solved the issue immediately.

Any ideas what could cause this? I saw several changes to the tracker script between those releases, but could not easily see what my cause this.

Note: it's a Vue app with Vue Router and Umami running on Docker.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.2

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
Thanks for the PR, well take a look

**Comment by mikecao** [comment]
Should be fixed by this PR, https://github.com/umami-software/umami/pull/2679. We will release a hotfix.

**Comment by mikecao** [comment]
Fixed in v2.11.2.
