### ISSUE TITLE
When trying to click on a jump, the clicked link is rendered twice.

### ISSUE THREAD

**Issue by efuo** [umami-software/umami#2681]
### Describe the Bug

When trying to click on a jump, the clicked link is rendered twice.

ex: https://www.efu.me click: https://www.efu.mehttps//www.efu.me/
<img width="1337" alt="image" src="https://github.com/umami-software/umami/assets/74389842/7c09e092-de7f-45f2-85fc-dab9f6947a34">

### Database

MySQL

### Which Umami version are you using? (if relevant)

chrome

### Which browser are you using? (if relevant)

chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
This is probably related to #2677. It looks like its capturing the entire domain name and not just the path. I will close this as a duplicate.
