### ISSUE TITLE
Cities and regions are not being recorded

### ISSUE THREAD

**Issue by franyerverjel** [umami-software/umami#2682]
### Describe the Bug

After installing the latest version v2.11.1, the recording of cities and regions stopped, but countries are still being recorded.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.1

### How are you deploying your application? (if relevant)

Docker

**Comment by franyerverjel** [comment]
I was reviewing and it turns out that this issue arose because I started using Cloudflare. You need to enable the headers in Cloudflare for Umami to register them. This is done in **Rules** > **Transform Rules** > **Managed Transforms** and you enable "Add visitor location headers".

**Comment by dontic** [comment]
> **Rules** > **Transform Rules** > **Managed Transforms** 

As this is the first result on Google search in 2025, just wanted to update the location of the setting:

**Rules** > _**Settings**_ > **Managed Transforms** > **Add visitor location headers**
