### ISSUE TITLE
UTM reports returns "405 Method Not Allowed"

### ISSUE THREAD

**Issue by mathix420** [umami-software/umami#2690]
### Describe the Bug

When trying to create a new UTM report for my team from the web app `/teams/_TEAM_ID_/reports/utm`.
On vercel logs I get a 405.
![image](https://github.com/umami-software/umami/assets/37625778/3439f636-febf-439c-afb3-c81517c3f75a)
No more context, and it result in a blank page on the web app.
![image](https://github.com/umami-software/umami/assets/37625778/36465af2-bf5c-492a-888a-48c5388a55d1)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.2 (but never worked before)

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by mikecao** [comment]
Confirmed the issue. Will fix.

**Comment by gerardnll** [comment]
Insights reports also report a 400 code for me.

**Comment by mikecao** [comment]
Fixed in v2.11.3.
