### ISSUE TITLE
Events not visible on the Event data tab

### ISSUE THREAD

**Issue by pawelpbm** [umami-software/umami#2692]
### Describe the Bug

Recently I migrated from Umami 1.x  to 2.11.0. I had some issues with DB migrations, but I believe at the end that was resolved.

Now I'm trying to add event tracking for my website (external links clicks).

I'm seeing the data being send to Umami endpoint and then I see the events on the "Realtime" tab, but when going into "Event data" it's empty.

Not sure how to debug it - I looked into the DB - `event_data` table is empty, but also not sure if that is even the correct table as there is quite a few of them with `event` in the name.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.0

**Comment by mikecao** [comment]
There should be records in `event_data` if you sent data along with events. How are you sending the event data?

**Comment by pawelpbm** [comment]
I messed up. I named the params as `data-umami-NAME` instead of `data-umami-event-NAME`.
