### ISSUE TITLE
Event is not fully rendered

### ISSUE THREAD

**Issue by acisky** [umami-software/umami#2694]
### Describe the Bug

![image](https://github.com/umami-software/umami/assets/6076379/a19b6242-e62d-4a7e-b90e-03997c7ff357)

The default time period is the last 24 hours. When I change it to the current day and then change it to the last 24 hours, the event will only display the events of the current day.

### Database

Umami Cloud

**Comment by franciscao633** [comment]
I think your screenshot is showing 12PM-12PM which includes the last 24 hours. For example our demo.

![image](https://github.com/umami-software/umami/assets/31608805/c20ff8d7-6367-414d-9c40-9b9666205cb4)
