### ISSUE TITLE
Event graph not using filters

### ISSUE THREAD

**Issue by mathix420** [umami-software/umami#2701]
### Describe the Bug

As you can see on the pictures I have defined a filter, and event list is returned correctly, but the graph just shows all the events present in the given time range without filtering out those not matching the filter.

![image](https://github.com/umami-software/umami/assets/37625778/d95604de-8e50-4f44-b138-39948554b288)

![image](https://github.com/umami-software/umami/assets/37625778/c441aebe-b99e-4af1-a678-d188fd08cf76)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by mikecao** [comment]
Fixed in v2.11.3.
