### ISSUE TITLE
Sankey Diagrams for funnel reports

### ISSUE THREAD

**Issue by mathix420** [umami-software/umami#2702]
### Describe the feature or enhancement

Actual funnel report doesn't really allow comparison between different user journeys.

For example my use case is the following:
- Users can create an account and then either follow a quick demo of the platform or skip the demo. I want to compare which of these user flow is more likely to finally buy a subscription to my platform.
- Right now I have to create two different reports and compare them, by opening two chrome windows side by side.
- And for this example I have only two possible events, but I have some flows where users can take 8 path to achieve same result, I want to be able to compare those path and identify quickly which one is the most performing one.
- I can also have multiple source events converging to the same final event. For example `affiliate-signup` `paywall-signup` `home-signup` `end-cta-signup` will all ultimately converge to `pay-modale` or `pay-page` and then `abort-payment` or `pay-btn`

![image](https://github.com/umami-software/umami/assets/37625778/e4044f28-46eb-410b-af33-b632a08e7452)

This one is not a sankey diagram, but could also be helpful (https://github.com/greghub/funnel-graph-js):
![image](https://github.com/umami-software/umami/assets/37625778/18d44ae2-6c30-4288-b95b-01a44bc6560d)
Here we can clearly and quickly see that direct traffic is the best performing one.

**Comment by franciscao633** [comment]
We have a separate Sankey Report in our plan that will be able compare different user journeys. Will label enhancement so it doesn't get stale.

**Comment by mikecao** [comment]
Covered by the User Journey report.
