### ISSUE TITLE
Team website - can't generate report

### ISSUE THREAD

**Issue by vbalazs913** [umami-software/umami#2704]
### Describe the Bug

As a member of a team I can't generate reports for a website that is available under that same team. When clicking on the website selector drop-down, I don't see the website and can't even search for it.
<img width="576" alt="Screenshot 2024-04-22 at 2 12 40 PM" src="https://github.com/umami-software/umami/assets/28981285/694f8d79-ec54-4e23-823f-92e3c7f034d1">

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.10.2

### Which browser are you using? (if relevant)

Safari, Edge, Chrome, Firefox

### How are you deploying your application? (if relevant)

Docker Compose

**Comment by franciscao633** [comment]
Looks like there is an bug with the website specific navigation bar (red) changing the context from your team to your personal account. However if your in the team context, and use the global reports button you should be able to see the teams websites when creating a reprot. We will resolve this. Thanks for reporting.

![image](https://github.com/umami-software/umami/assets/31608805/827f879b-699f-47e1-a71f-178ca681b45b)

**Comment by mikecao** [comment]
Fixed in v2.11.3.
