### ISSUE TITLE
PagesTable generated an incorrect externalUrl

### ISSUE THREAD

**Issue by shuaixr** [umami-software/umami#2707]
### Describe the Bug

PagesTable generated an incorrect externalUrl. When FilterButtons switches to title, PagesTable concatenates domain and title as externalUrl.[PagesTable.tsx#L41](https://github.com/umami-software/umami/blob/a38baa50afa7eae54ffdbafece83d10745bb808d/src/components/metrics/PagesTable.tsx#L41)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

a38baa50afa7eae54ffdbafece83d10745bb808d

**Comment by franciscao633** [comment]
Confirmed. Feel free to submit a PR. If not we will get it fixed next release.

**Comment by mikecao** [comment]
Fixed in v2.11.3.
