### ISSUE TITLE
Filters by hostname. Why not?

### ISSUE THREAD

**Issue by klawdyo** [umami-software/umami#2710]
### Describe the feature or enhancement

Hello,

First and foremost, I want to commend you on the incredible work you’ve done with the Umami project. The simplicity and efficiency of the tool are truly noteworthy.

However, I noticed that it’s currently not possible to search for statistics based on the hostname. This feature is crucial for me because I manage a system that spans multiple subdomains, and I’d like to centralize these statistics.

Could you please explain why this functionality isn’t available? It would be great if we could filter data by hostname.

Thank you in advance for your attention!

**Comment by franciscao633** [comment]
We already store hostname in the session table so it wouldn't be too hard to implement. Were you looking for hostname as its own metric card and filter? Users that don't use subdomain would just see a single record like `umami.is` which would be pretty useless. I guess we can make it configurable where the default would be to disable it.

**Comment by klawdyo** [comment]
You can implement this filter only in API. It would be an advanced option.

**Comment by giuseongit** [comment]
I actually already implemented this feature in https://github.com/umami-software/umami/pull/2689, I just need someone to review my code

**Comment by giuseongit** [comment]
The only thing that is missing is the ability to make it configurable, but for that I'd like some help since I've never worked with next.js

**Comment by klawdyo** [comment]
One more thing.
In this example: one website managing multiple subdomains.

The "open in new tab" button link displayed in this list is wrong
![image](https://github.com/umami-software/umami/assets/100168/c9cfd7c9-ad56-42c3-a48e-777ab7a25974)


- I think the hostname used in this list should be the one in the session, not the one in the website registration.
- I also think the page icon could be displayed in this list. In cases where they are the same "hostname", nothing would change, but it would look better with the pages' favicon. But in the case of multiple sub-domains, it would help a lot.

**Comment by franciscao633** [comment]
@giuseongit Thanks well take a look. I think were leaning towards just an API change, but if adding a configurable host card makes sense we'll implement. 

@klawdyo adding a bug tag. page links should work with subdomains. Thanks for reporting.

**Comment by klawdyo** [comment]
> @giuseongit Thanks well take a look. I think were leaning towards just an API change, but if adding a configurable host card makes sense we'll implement. 

I think if have many hostnames, make sense show them. Maybe this checking can be better than a config.

> @klawdyo adding a bug tag. page links should work with subdomains. Thanks for reporting.

Just remember group pages by hostnames on SQL, because some pages are common between them.
Example:

**Comment by snaildos** [comment]
bump - wish this feature was added and integrated just like refers.

**Comment by rishabhAjay** [comment]
I second this. A card that shows the hostnames and a hostname filter while reporting would be really useful for applications using a lot of subdomains.

**Comment by mikecao** [comment]
Filtering is now available in v2.12.0. The issue with links and configuration will have to be address in the future.
