### ISSUE TITLE
[Feature] detect users from PWA

### ISSUE THREAD

**Issue by vatheara** [umami-software/umami#2712]
### Describe the feature or enhancement

I try to encourage my users to adopt PWA feature for better UX but I didn't know how many user had been done install and using PWA. I think it would be helpful if umami have this feature

**Comment by StevenSlaa** [comment]
Here's a handy workaround: set the start_url parameter in your manifest.json file to a URL that includes a query parameter, such as \?source=pwa. Umami can track these query parameters, allowing you to keep track of various sources like QR codes, NFC tags, and more. 😉
