### ISSUE TITLE
Consolidate time range dropdowns into one

### ISSUE THREAD

**Issue by devxan** [umami-software/umami#2714]
### Describe the feature or enhancement

Replace multiple drop-downs that require the same action for a result with a single dropdown.

![Umami dashboard](https://github.com/umami-software/umami/assets/57809064/9e872b06-145f-4998-b4c5-966bbf8a1df2)

This makes no sense. There should only be one dropdown for the main dashboard, because these buttons all do the same thing. It could be made sticky and stay at the top of the page, or anything else.

**Comment by franciscao633** [comment]
Depends how users use the dashboard, but I can see users wanting to have a single date filter apply to every website for this screen. Alternatively users may want to quickly check stats on a single website without waiting for up to 9 other websites to load their stats.

**Comment by devxan** [comment]
> Depends how users use the dashboard, but I can see users wanting to have a single date filter apply to every website for this screen. 

Awesome! So this might be added? 

> Alternatively users may want to quickly check stats on a single website without waiting for up to 9 other websites to load their stats.

Then wouldn't they click the View Details button?

**Comment by devxan** [comment]
😔 This would be a wonderful feature for an end user

**Comment by devxan** [comment]
I switched over to an alternative, Plausible! It's more feature complete. 😐
