### ISSUE TITLE
Docker is missing some JavaScript files after deploying umami

### ISSUE THREAD

**Issue by roywangdev** [umami-software/umami#2716]
### Describe the Bug

After deploying umami through Docker, some JS files were lost when accessing web services, resulting in only white pages being displayed.

What we are currently seeing is:

_next/static/chunks/fd9d1056-cd5fe364d4094f8b.js
_next/static/chunks/4938-821da5639b429cc1.js

The above two files display 404 when referenced, and when I entered the container to view them, there were no such files.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

docker

**Comment by mikecao** [comment]
Are you building your own docker or using the pre-built images?

**Comment by roywangdev** [comment]
Pre built images.

**Comment by mikecao** [comment]
Is there a specific page you were trying to access?

**Comment by roywangdev** [comment]
All the pages are like this, but I reinstalled Docker today and it returned to normal.
