### ISSUE TITLE
Issue with Incorrect Encoding of City Names from Cloudflare Headers

### ISSUE THREAD

**Issue by franyerverjel** [umami-software/umami#2720]
### Describe the Bug

I am currently using Umami (self-hosted) behind Traefik as my reverse proxy, and I have Cloudflare set up above that. However, I've encountered an issue where the city names from Cloudflare headers, specifically 'cf-ipcity', are showing up with incorrect character encoding in Umami's analytics. The city names are displayed with garbled accents, like "ChÃ­a" instead of "Chía".

This is the header received from Cloudflare:

![image](https://github.com/umami-software/umami/assets/8519731/80ab81a0-39d1-40ff-a2ce-793b91d11723)

I've verified that both Traefik and Umami are set to handle UTF-8 encoding, but the issue persists. The headers are possibly being misinterpreted somewhere between Cloudflare, Traefik, and Umami.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.11.2

### How are you deploying your application? (if relevant)

Docker

**Comment by farzadsoltani** [comment]
@franyerverjel Could this help?

https://developers.cloudflare.com/rules/transform/managed-transforms/reference/#encoding-of-non-ascii-header-values
