### ISSUE TITLE
Show number of events in dashboard overview

### ISSUE THREAD

**Issue by CodeAlDente** [umami-software/umami#2731]
### Describe the feature or enhancement

It would be nice to see how many events have been triggered on the websites at the dashboard overview. I have plenty of websites and it is a pain to open each of them to see if and what events have been triggered.

Maybe we can even link to the events page (view=event)?

**Comment by franciscao633** [comment]
I suppose we can bring it in with the other website stats, but it would just be a count. The dashboard is really for a quick view of high level metrics. Ill label as enhancement and review with the team.
