### ISSUE TITLE
Event data not filtering or displaying properly

### ISSUE THREAD

**Issue by halphalp** [umami-software/umami#2737]
### Describe the Bug

Event data across my installation seems to be broken. When viewing trying to filter events using the search box, it does not work. the /event-data endpoint also does not load and continues spinning.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.11.3

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

Docker via docker-compose on Debian

**Comment by franciscao633** [comment]
I'm guessing it was working before `v2.11.3`? There was a small migration that made some changes to the `event_data` table. I wonder if your app is somehow not in sync with the the new prisma schema. Are there any errors returning from the event-data endpoint?

**Comment by supermar1010** [comment]
I have the same problem. When typing in the search bar, no requests are being sent, so if this is a backend functionaility I think the frontend is broken.

**Comment by franciscao633** [comment]
For event_type 1 this is correct. Those are pageviews which are collected by default via the tracker. If you want to setup custom events see [here](https://umami.is/docs/track-events).

**Comment by mikecao** [comment]
Fixed in v2.12.0.
