### ISSUE TITLE
How to write a Workflow for automatic synchronization of forks?

### ISSUE THREAD

**Issue by huhexian** [umami-software/umami#2745]
### Describe the feature or enhancement

As the title suggests, I use Vercel to deploy umami, and every time umami is updated, I need to manually sync the fork to update. Is there a Workflow that provides automatic updates for the fork?

**Comment by franciscao633** [comment]
I believe Github Actions is the only way to truly automate it. Outside of that Github makes it really easy to fetch and merge the upstream changes, but yes its manual.
