### ISSUE TITLE
[Feature] "Average visit time" and "Bounce rate" on API stats

### ISSUE THREAD

**Issue by berkayunal** [umami-software/umami#2750]
### Describe the feature or enhancement

Would love to have "Average visit time" and "Bounce rate" added to the API endpoint /api/websites/:websiteId/stats like we have on the dashboard.

**Comment by franciscao633** [comment]
Looks like you can calculate it yourself with the data already provided, but I get having it pre-calculated as well.

![image](https://github.com/umami-software/umami/assets/31608805/bec6063b-152f-45d8-bca6-1abe55c0db34)
