### ISSUE TITLE
Enhancing README.md for Better Usability and Accessibility

### ISSUE THREAD

**Issue by shubhusion** [umami-software/umami#2755]
### Describe the feature or enhancement

# Enhancing README.md for Better Usability and Accessibility

To improve the usability, accessibility, and overall experience of the README.md for new users and contributors, we propose the following enhancements. These changes aim to provide clearer instructions, better navigation, and a more visually appealing presentation.

### Add a Logo
- Incorporate the Umami logo at the top of the README to enhance brand identity and visual appeal.

### Table of Contents
- Add a Table of Contents to allow users to quickly navigate to different sections of the README.

### Enhanced Configuration Instructions
- Provide detailed instructions and examples for creating and configuring the `.env` file.

### Code Block Consistency
- Ensure all commands and code snippets are enclosed in code blocks for readability.

### Step-by-Step Guide
- Break down the installation and configuration process into clear, numbered steps.

### Links to Documentation
- Include direct links to relevant documentation pages for more in-depth guidance.

### Contact Information and Support
- Add a section with contact information or links to support channels for users needing help.

### Contribution Guidelines
- Add a section that outlines how to contribute to the project, including code style guidelines, branch naming conventions, and how to submit a pull request.

### Badges
- Add Shields.io badges for build status, license, version, and other relevant metrics to provide at-a-glance information about the project.

## Rationale
These enhancements will make the README more user-friendly and informative, helping new users get started quickly and enabling contributors to understand how to engage with the project effectively. Clearer instructions and better organization will reduce confusion and support issues, improving the overall user experience.

## Tasks
1. Add the Umami logo at the top of the README.
2. Create a Table of Contents section.
3. Update the configuration instructions with detailed examples.
4. Enclose all commands and URLs in code blocks.
5. Break down the installation steps into a clear, step-by-step guide.
6. Add links to the official documentation where relevant.
7. Create a new section for contact and support information.
8. Add a contribution guidelines section.
9. Integrate Shields.io badges for build status, license, version, and more.

**Comment by franciscao633** [comment]
Thanks for all the suggestions. I feel some of these tasks are better suited for our website/official docs and we want to keep the readme as straight-forward as possible. On the other hand I agree, the readme can always be improved. We will integrate what we can, but also welcome PRs.

**Comment by shubhusion** [comment]
Please let me know which tasks you think are suitable, and I will make changes accordingly. I aim to keep the readme straightforward yet visually appealing.

**Comment by shubhusion** [comment]
@franciscao633 i have made a Pull Request related to it. I have just Enhanced the Readme.md Visually.
