### ISSUE TITLE
load via js directly instead of script tag

### ISSUE THREAD

**Issue by psifertex** [umami-software/umami#2766]
### Describe the feature or enhancement

Is there a recommended way to load umami via js directly instead of using a script tag? I don't see that as a currently supported feature but hopefully I'm missing it. 

My use-case is I would like to include umami stat tracking in some generated HTML documentation that is both available in a website but also in local builds that are potentially offline. I explicitly do not want to collect data from the local copy of the same files and my first thought was to simply check the hostname before loading umami. 

A solution like #2328 would also suffice. (Related, I don't see what malicious actors being able to spoof has to do with the original request -- it would still prevent you from accidentally adding stats from non-production deployments which is basically what I'm asking for here as well).

**Comment by franciscao633** [comment]
If nothing in the tracker configuration [docs ](https://umami.is/docs/tracker-configuration) helps you, are you able to pass environment variables do identify a production setting?

In our website repo we do something like below
```
{process.env.NODE_ENV === 'production' && (
          <script
            defer
            data-website-id="my website UUID"
            data-domains="umami.is"
            src="/a/script.js"
          />
        )}
```

**Comment by psifertex** [comment]
Nope -- the content is purely static HTML. The website is updated directly with the same copy that is built into the offline code. I could certainly do some post-processing shenanigans to change the code when I upload it, but it would be far cleaner to have something like this feature.

**Comment by mikecao** [comment]
You can use `data-domains` to limit it to certain domains only. See https://umami.is/docs/tracker-configuration
