### ISSUE TITLE
contains filter not work for pages metric

### ISSUE THREAD

**Issue by mydearxym** [umami-software/umami#2769]
### Describe the Bug

hi team ~

just try umami's demo page, the contains filter seems not works on page section, other metric works as expect

https://eu.umami.is/share/LGazGOecbDtaIwDr/umami.is?url=~%2Fblog 
![image](https://github.com/umami-software/umami/assets/6184465/91032ce9-39a6-4ff4-b9f9-90423fdd6e71)

### Database

Umami Cloud

### Which Umami version are you using? (if relevant)

latest

### Which browser are you using? (if relevant)

chrome

### Expect

https://plausible.io/plausible.io?filters=((contains,page,(blog))) 

![image](https://github.com/umami-software/umami/assets/6184465/aa0d1de5-c384-4120-8b56-4a8acc9cd9b5)

**Comment by franciscao633** [comment]
The query on the backend is actually reflecting the correct numbers, but the UI is not reflecting the filter results. Adding a label so it doesnt become stale.

**Comment by mydearxym** [comment]
hi @franciscao633 , any progress on this?
