### ISSUE TITLE
Provide a type definition for `tracker-functions`

### ISSUE THREAD

**Issue by Zxilly** [umami-software/umami#2772]
### Describe the feature or enhancement

Is that possible to provide a TypeScript `d.ts` file for `https://umami.is/docs/tracker-functions`?

**Comment by Lehoczky** [comment]
I think you are looking for this: https://github.com/umami-software/umami/blob/master/src/tracker/index.d.ts

**Comment by Zxilly** [comment]
@Lehoczky thank you
