### ISSUE TITLE
Publish the tracker as an npm package

### ISSUE THREAD

**Issue by Lehoczky** [umami-software/umami#2776]
### Describe the feature or enhancement

Hi there 👋 

Integrating umami with JS projects that use a bundler would be more convenient with a published library. Especially when using TypeScript, since the type declarations are lost from https://github.com/umami-software/umami/blob/master/src/tracker/index.d.ts when someone wants to use the tracker now.

Solution:

Publish the https://github.com/umami-software/umami/blob/master/src/tracker as an npm package called something like `@umami/tracker` with a small modification: have an init function that accepts a configuration object instead of using `data-*` attributes for configuration:

```ts
import {umami} from "@umami/tracker"

umami.init({
  website: "b59e9c65-ae32-47f1-8400-119fcf4861c4"
})

umami.track("event")
```

**Comment by mikecao** [comment]
This already exists, https://github.com/umami-software/node

**Comment by Lehoczky** [comment]
Thank you! The name of the package is a bit misleading though, I would assume it only works in node, which is the server environment for JavaScript. For example [nodemailer](https://nodemailer.com/) is using `node` in its name for this reason.

A better alternative would be `@umami/js` to know it works in browsers as well.

**Comment by Lehoczky** [comment]
Upon some investigation, it look like https://github.com/umami-software/node is not identical to the tracker in this repository. I has different function signatures and does not support auto-inferring of the screen size, referer, etc.

**Comment by mikecao** [comment]
Because those things only exist on the client side. You would just use the tracker that comes with your installation in that case, since the functionality would be bound to whatever version you are running. It wouldn't make sense as a package.

**Comment by Lehoczky** [comment]
A client side npm package would be great to have TypeScript support in our IDE, and to be able to initilaize the tracker without adding a `<script>` element to the HTML.

As an example Aptabase has a client side sdk as well: https://github.com/aptabase/aptabase-js/tree/main/packages/web

**Comment by nandi95** [comment]
there is a @types/umami package for that which is close to what really it is: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70372#discussioncomment-10436673

**Comment by Lehoczky** [comment]
This issue was the second most upvoted in the repository, would it be possible to re-open it? Or is it really not planned? @mikecao

**Comment by mikecao** [comment]
@Lehoczky The issue is the tracker supports whatever features are in your current install, so a separate package doesn't make sense. You can still use the node package on the front end, it doesn't use and node specific functions.
