### ISSUE TITLE
How I can export my data on opensource to migrate or study data

### ISSUE THREAD

**Issue by miguelgargallo** [umami-software/umami#2778]
### Describe the Bug

Guide is not the same for free opensource full version, maybe incomplete, critical feature: export to import later data How I can export my data on opensource to migrate or study data

### Database

PostgreSQL

**Comment by mikecao** [comment]
There is no guide because all the data is in your database. You would just use the database tools. See https://www.prisma.io/dataguide/postgresql/inserting-and-modifying-data/importing-and-exporting-data-in-postgresql
