### ISSUE TITLE
Unable to reorder more than 10 websites

### ISSUE THREAD

**Issue by shiruken** [umami-software/umami#2783]
### Describe the Bug

On deployments with more than 10 websites, it is impossible to reorder them all since only the first 10 are shown on the dashboard edit page. This means that any websites beyond the first 10 are unavailable to reorder.

### Database

PostgreSQL

### Relevant log output

```shell
N/A
```

### Which Umami version are you using? (if relevant)

v2.11.3

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Railway

**Comment by franciscao633** [comment]
Sorry for late response, but agreed. The whole sorting functionality on the dashboard need to be redone. Labeling so it doesn't become stale

**Comment by mikecao** [comment]
Fixed in v2.14.0
