### ISSUE TITLE
Umami site keeps refreshing and going back to previous page every few seconds

### ISSUE THREAD

**Issue by ryanovas** [umami-software/umami#2790]
### Describe the Bug

We have been running umami for about a month with no issues until today. I clicked into a page on our site to see some page specific insights and whenever I tried to clear the filter, after about 3 seconds the page would refresh and the filters would be applied again. It applies everywhere though. Any time I navigate to a new page, after 3 seconds it refreshes and returns me to the previous page. This is even the case when I try to log in, it brings me back to the login form though the sign-in succeeded. 

Other details:
- We are on kubernetes and I am running the latest image. I even tried redeploying the pods and pulling the latest image fresh but the issue persists.
- If I log in incognito the issue is gone
- If I quickly refresh the page after I navigate before it refreshes itself I will stay on the page.

### Database

PostgreSQL

### Relevant log output

```shell
server logs just show a successful boot. Javascript console shows nothing.
```

### Which Umami version are you using? (if relevant)

ghcr.io/umami-software/umami:postgresql-latest

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Kubernetes

**Comment by mikecao** [comment]
I've never heard of anything like this. Have you tried a completely new browser? Sounds like a browser extension doing some weird stuff.

**Comment by ryanovas** [comment]
Well, it goes away in incognito so I'm thinking it's cookie/local storage related. If it was a browser extension I would expect the behaviour in other tabs than just umami. There is another similar ticket titled something like "umami refreshes every 3 seconds" though the resolution appears to be the platform the reporter deployed to? But me experiencing it now on kubernetes makes me think it isn't isolated. It does seem very tricky to replicate though. I can't get it to happen in my incognito browser but I can't get it to go away in my main browser.
