### ISSUE TITLE
View Detail Page Throws An Error

### ISSUE THREAD

**Issue by darrylmorley** [umami-software/umami#2797]
### Describe the Bug

When clicking through to "View Details" from the dashboard page an Error is thrown. "Something went wrong.
Cannot read properties of undefined (reading 'length')"

v2.11.3 works without issue

### Database

PostgreSQL

### Relevant log output

```shell
TypeError: Cannot read properties of undefined (reading 'length')
   
```

### Which Umami version are you using? (if relevant)

v2.12.0

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker/Caprover

**Comment by sebiweise** [comment]
Just wanted to post that issue. Same error on my side.

**Comment by mikecao** [comment]
Some things to try:
- Disable your adblock
- Clear your local storage

**Comment by sebiweise** [comment]
Crazy, disabling AD-Blocker did the job, but its strange that our STAGE environment does got this behavior, its just the PROD deployment.

**Comment by darrylmorley** [comment]
> Some things to try:
> 
> * Disable your adblock
> * Clear your local storage

Yes, that works when turning off adblock

**Comment by jonisapp** [comment]
same here.

**Comment by Silvenga** [comment]
The event data issue is likely the same as this one: #2798.

I can also confirm that EasyPrivacy pushed a generic block for the URL "://analytics.*/event" that breaks Umami incorrectly. It should be ignoring origin requests...
