### ISSUE TITLE
Events Data cannot be displayed at all, tons of errors

### ISSUE THREAD

**Issue by MFYDev** [umami-software/umami#2798]
### Describe the Bug

Click the Events Data for the website

### Database

PostgreSQL

### Relevant log output

```shell
Something went wrong.
Cannot read properties of null (reading 'toString')
TypeError: Cannot read properties of null (reading 'toString')
    at t.Z (https://mydomain/_next/static/chunks/4994-a5f59a12a07941bf.js:1:8033)
    at rE (https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:40344)
    at iZ (https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:117029)
    at ia (https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:95165)
    at https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:94987
    at il (https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:94994)
    at oJ (https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:92350)
    at nb (https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:26836)
    at nw (https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:27574)
    at https://mydomain/_next/static/chunks/fd9d1056-32e91c42f6a1484e.js:1:28608
```

### Which Umami version are you using? (if relevant)

ghcr.io/umami-software/umami:postgresql-latest (v2.12.0)

### Which browser are you using? (if relevant)

Edge

### How are you deploying your application? (if relevant)

docker compose

**Comment by mikecao** [comment]
This is fixed in the `dev` branch if need it before we issue a hotfix.

**Comment by MFYDev** [comment]
@mikecao Thanks a lot for the response, do you have any timeline for the next release? I really do not wanna do the source install just to fix this tho

**Comment by bertusdebruin** [comment]
> @mikecao Thanks a lot for the response, do you have any timeline for the next release? I really do not wanna do the source install just to fix this tho

It is time for for an LTS release. 
This is yet another "bug" that causes essential functions to stop working, after an update. 2 options; either test a release better. Or stop pushing new features that kill the complete system.

> This is fixed in the `dev` branch if need it before we issue a hotfix.

> @mikecao Thanks a lot for the response, do you have any timeline for the next release? I really do not wanna do the source install just to fix this tho

It is time for for an LTS release. 
This is yet another "bug" that causes essential functions to stop working, after an update. 2 options; either test a release better. Or stop pushing new features that kill the complete system.

**Comment by MFYDev** [comment]
> > @mikecao Thanks a lot for the response, do you have any timeline for the next release? I really do not wanna do the source install just to fix this tho
> 
> 
> 
> It is time for for an LTS release. 
> 
> This is yet another "bug" that causes essential functions to stop working, after an update. 2 options; either test a release better. Or stop pushing new features that kill the complete system.

Cannot agree more, I stopped using Umami long time ago because a function has broken for long time without releasing. Then the moment when I wanna use it again to test, this issue happens. Fortunately I backed up my plausible

**Comment by mikecao** [comment]
Fixed in v2.12.1.

**Comment by bertusdebruin** [comment]
@MFYDev Let's reopen this issue, it has nothing to do with this fix. But the given fact that, Umami nowadays is released very fast, there is no LTS version, and with almost every release there are bugs present, so the software just does not function as it should.

**Comment by devarshishimpi** [comment]
@bertusdebruin @MFYDev I might be wrong, but as long as you are running Umami from `master` branch, everything works fine. Atleast, I haven't encountered an issue yet. Unless and until you want to use the latest features from the `dev` branch!

**Comment by MFYDev** [comment]
Dude of course you won't have issues as this is already fixed

**Comment by devarshishimpi** [comment]
> Dude of course you won't have issues as this is already fixed

I meant particularly towards your comment on creating a LTS version.
