### ISSUE TITLE
Settings page for 'Teams' is 404

### ISSUE THREAD

**Issue by heybobjones** [umami-software/umami#2799]
### Describe the Bug

I updated today via docker image and seem to have issues with the 'Setting' page not being found when switching view to 'Team'.

I can see all the tracking data for the sites that are part of the Team section, but I can't access the settings page. (e.g /teams/651fcf58-90d9-483a-b2f8-66ee7021ccdd/settings/team)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.12.0

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by Foohx** [comment]
Same here

**Comment by mikecao** [comment]
Will have a hotfix for this soon.

**Comment by chrisdeeming** [comment]
Is it possible to downgrade?

**Comment by tamerhayek** [comment]
> Is it possible to downgrade?

I just changed the image tag in my `docker-compose.yml` from `ghcr.io/umami-software/umami:postgresql-latest` to `ghcr.io/umami-software/umami:postgresql-v2.11.3` and it works perfectly

**Comment by mikecao** [comment]
Fixed in v2.12.1.
