### ISSUE TITLE
[User Journey] Text overflow on long route names

### ISSUE THREAD

**Issue by reaganmcf** [umami-software/umami#2802]
### Describe the Bug

Absolutely love the new User Journey feature! Thanks so much for adding it.

I noticed a visual bug where pages that have very long names (aka, /mypage/some-really-really-really-long-path-param) it overflows the boxes that break down each path a user took in each step.

I can provide an example when I get the chance - should be very simple to reproduce though

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.12.0

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
Fixed in v2.12.1.
