### ISSUE TITLE
Refreshing on website page results in content width changing to full width

### ISSUE THREAD

**Issue by tudor-cel-stan** [umami-software/umami#2806]
### Describe the Bug

When I first access any website analytics page it is being loaded just fine, but whenever I hit refresh the layout breaks and it turns into a full width layout just like in the screenshots below.

<img width="1680" alt="Screenshot 2024-06-21 at 17 43 42" src="https://github.com/umami-software/umami/assets/87135984/a894c0f0-8431-4497-8461-a7b733c6abf7">

### Database

MySQL

### Which Umami version are you using? (if relevant)

Latest (2.12.0)

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker, Node (On CloudPanel server)

**Comment by franciscao633** [comment]
I'm having a hard time reproducing this. When you start the container on a non-CloudPanel server are you experiencing these issues. I don't know too much about CloudPanel, but if it's just server hosting, I don't see why it would cause issues.

**Comment by tudor-cel-stan** [comment]
Thank you for answering, after installing the latest patch the issue seems to have gone away. Sorry for not coming back with an update for that, and thank you for the amazing work at Umami!
