### ISSUE TITLE
Delete website Data for a Specified Period and Implement Import/Export Functionality 

### ISSUE THREAD

**Issue by LahlouMohamed** [umami-software/umami#2810]
### Describe the feature or enhancement

**Objective**
Add the ability to delete data for a specified period for Umami users.

**Context**
    This feature aims to improve performance management by allowing the deletion of data within specific date ranges. This helps to maintain a lighter and more performant database. Additionally, an import/export feature will be ideal for archiving complete periods before deletion.

**Implementation Details**

**Database**
    Addition of cascading delete functionality to ensure that all data related to a specific period is correctly removed.
    Update of database schemas and necessary migration scripts.

**API**
    Create a new API endpoint that takes two parameters: startDate and endDate.
    Implement the logic for deleting data (event_data) within this date range.

**Frontend**
    Add a user interface to select a date range and initiate the deletion of the corresponding data.
    Display appropriate confirmations and alerts to prevent accidental deletions.

**Import/Export**
    Set up API endpoints for exporting and importing data for a specified period.
    Create user interfaces to facilitate data export and import before deletion.

**Screenshot**

![image](https://github.com/umami-software/umami/assets/40507691/72ce4fe1-8d82-403a-a350-74e467772ea6)
![image](https://github.com/umami-software/umami/assets/40507691/463526ac-3699-4990-a7fc-979539d0bc6c)

**Comment by franciscao633** [comment]
Import / Export date ranges definitely needs to be done. I think if the main purpose to delete data is performance, I would rather focus on pure performance changes.

**Comment by Q-Quan** [comment]
It seems to me that this would've been a useful feature to have. I can imagine, for example, a site's analytics being contaminated e.g. by developer tests with tracking enabled, or by traffic anomalies one does not want to disrupt later overall statistics.
