### ISSUE TITLE
/event-data page broken in 2.12.0

### ISSUE THREAD

**Issue by huijing** [umami-software/umami#2811]
### Describe the Bug

Clicking on the Event Data link (/websites/THE_LONG_WEBSITE_ID_STRING/event-data) in the website details page triggers a `Cannot read properties of null (reading 'toString')` error.
![Screenshot 2024-06-25 at 07-45-15 Event Data Umami](https://github.com/umami-software/umami/assets/1461498/68db14d2-38bb-4f63-93cd-6f11e3474d8d)

This issue occurs on both local machine and the version deployed on Heroku. The page was working fine in 2.11.3

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.12.0

### Which browser are you using? (if relevant)

Chrome, Firefox

### How are you deploying your application? (if relevant)

Heroku

**Comment by Silvenga** [comment]
Looks like the same as #2798.

**Comment by mikecao** [comment]
Fixed in v2.12.1.
