### ISSUE TITLE
Umami always responding with 307 Temporary Redirect after v2.12.0

### ISSUE THREAD

**Issue by SenseiMarv** [umami-software/umami#2820]
### Current behaviour

After upgrading to version >2.12.0, Umami will always respond to a request to the root URL with a 307 Temporary Redirect HTTP response. Requests to other pages like /dashboard, /websites, ... will return 200 OK instead.

### Expected behaviour

Umami should respond with 200 OK to a request for the root URL. I noticed this issue because I have Uptime Kuma checking my service and after the upgrade, it failed the check since I'm only counting 2XX responses as healthy responses.

### Steps to reproduce

1. Spin up Umami with a version >2.12.0.
2. Open the DevTools in the browser and open the Network tab.
3. Navigate to the root URL of the Umami instance. Local HTTP or Remote HTTPS will return the same result.
4. Examine the first response in the DevTools which returns the initial HTML. It will have the status code 307.

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.12.1

### Which browser are you using? (if relevant)

Chrome, also tested in Postman

### How are you deploying your application? (if relevant)

Docker through Reverse Proxy and Cloudflare

**Comment by franciscao633** [comment]
confirmed. We will take a look. Thanks for reporting.

**Comment by mikecao** [comment]
Redirect is the correct code. When you go to the root, it either redirects you to `/dashboard` or `/login` depending on your logged in status. There is no page at the root. If you want to simply want to check uptime, send a request to `/api/heartbeat`

**Comment by boerge30** [comment]
Thanks! It now works with calling `/api/heartbeat`. But the 307 error described above only appeared here with the current version. (Uptime Kuma / updown.io)

**Comment by SenseiMarv** [comment]
Makes sense with that explanation. Using the heartbeat route works for me. If this is the intended behaviour, this issue can be closed.
