### ISSUE TITLE
Installation Documentation does not state risk on using "pm2 start umami" or how to make usage safe

### ISSUE THREAD

**Issue by bbx-github** [umami-software/umami#2822]
### Describe the Bug

In section [Start the application](https://umami.is/docs/install#start-the-application) installation documentation first states
> By default this will launch the application on http://localhost:3000. You will need to either [proxy](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) requests from your web server or change the [port](https://nextjs.org/docs/api-reference/cli#production) to serve the application directly.

But in section [Running Umami](https://umami.is/docs/install#running-umami) it is not stated that running umami as described lets it listen on `http://*:3000`.

The documentation should show how to make umami  listen on `http://127.0.0.1:3000` only using pm2 or at least warn that it does listen everywhere if it is setup as described.

### Database

PostgreSQL

**Comment by mikecao** [comment]
We should probably move that PM2 content to a separate section.
