### ISSUE TITLE
Track Google Discovery traffic.

### ISSUE THREAD

**Issue by SvetZitrka** [umami-software/umami#2828]
### Describe the feature or enhancement

Is it possible to track incoming traffic from Google Discovery in Umami? Like in this tutorial ?https://www.cueforgood.com/blog/how-to-optimize-track-google-discover-in-google-analytics/

**Comment by mikecao** [comment]
Umami always collects the raw referrer so you don't need to do anything.

**Comment by SvetZitrka** [comment]
I'm new to Umami and although I tried very hard to find this referrer in the traffic source "google.android.googlequicksearchbox" unfortunately I couldn't. Can someone please advise?

**Comment by lynt-smitka** [comment]
Unfortunately, this data cannot be accessed in the Umami interface. The raw referrer in this case is for example "android-app://com.google.android.googlequicksearchbox/", which umami interprets as "None" and so it is mixed with direct visits.

![image](https://github.com/umami-software/umami/assets/3875093/f66acaf1-670f-469e-aadf-69eadbec256d)
![image](https://github.com/umami-software/umami/assets/3875093/27b89fe3-97c4-4cfd-82a1-0c19e5040dfe)

**Comment by SvetZitrka** [comment]
Can anyone here reply to this thread, even though @mikecao closed it prematurely?

Or should I start a new thread on the same topic?

**Comment by SvetZitrka** [comment]
Can anyone here reply to this thread, even though @mikecao closed it prematurely?

Or should I start a new thread on the same topic?
