### ISSUE TITLE
Similar to electron framework application API response {"beep": "boop"}

### ISSUE THREAD

**Issue by QYG2297248353** [umami-software/umami#2833]
### Describe the Bug

Reporting data using the API approach

![image](https://github.com/umami-software/umami/assets/56836951/7d142084-691c-4fa5-8911-c61b344d1860)

![image](https://github.com/umami-software/umami/assets/56836951/11a794d8-a9de-4d4f-8d59-9fc90110780d)

The response obtained is
![image](https://github.com/umami-software/umami/assets/56836951/9edd1830-e917-43e8-b99e-2d088324d5c7)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

Chrome

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by q2316367743** [comment]
我也是相同的问题，electron应用，请求发送成功，但是没有统计数据

**Comment by q2316367743** [comment]
已经解决了，umami把你当成机器人了，docker启动的时候可以加入`DISABLE_BOT_CHECK=1 `禁止机器人检查就可以

**Comment by mikecao** [comment]
That response means it thinks you're a bot. You need to pass a legitimate user-agent or disable the bot detection like @q2316367743 mentioned
