### ISSUE TITLE
Allow to start week on a Monday

### ISSUE THREAD

**Issue by mulder999** [umami-software/umami#2838]
### Describe the feature or enhancement

Currently, the calendar week starts on Sunday. This feature request proposes adding the flexibility for users to choose Monday as the start of the week instead.

# Details

- **User Flexibility:** Provide users with the option to set Monday as the first day of the week in calendar views.
- **Consistency:** Aligns with international standards where Monday is traditionally considered the first day of the week in many cultures and calendars.
- **User Experience:** Enhances user experience by allowing them to personalize their calendar to match their preference and workflow.
- **Implementation:** Implement as a user-selectable option in calendar settings or preferences, ensuring ease of access and usability.

# Benefits

- **Global Relevance:** Appeals to users worldwide accustomed to Monday-first week layouts.
- **Customization:** Enhances user satisfaction by catering to diverse scheduling preferences.
- **Clarity:** Improves clarity and usability of calendar interfaces for users expecting Monday as the start of their week.

**Comment by mikecao** [comment]
It depends on which locale your select. The dates will adjust according to the locale. For example, this is French, where the week starts on a Monday.

![image](https://github.com/umami-software/umami/assets/477975/bdc711bb-d0b7-4ce1-ace9-dd44689b519d)

**Comment by mulder999** [comment]
Thanks for the tip! I switched to the UK setting and now enjoy having the week start on Mondays. (I'm a native French speaker, but I prefer reading in English online.)
