### ISSUE TITLE
traffic indicator is missing on the dashboard

### ISSUE THREAD

**Issue by Demoxing** [umami-software/umami#2840]
### Describe the Bug

There is a minor visual glitch I am facing that appeared in the latest version (v2.12.0) and remains the same in v2.12.1. When opening the dashboard, there is no green and red indicator showing how much traffic I gained and lost. The indicators are present when I go inside a particular site, but not on the dashboard anymore. I am not using any adblocker and have tried multiple web browsers, but the issue is still there.

![bug](https://github.com/umami-software/umami/assets/53024273/02d1b8c9-cc69-4b12-af9f-1badf1e53f74)

### Database

MySQL

### Which Umami version are you using? (if relevant)

v2.12.1

### Which browser are you using? (if relevant)

Firefox, Edge

### How are you deploying your application? (if relevant)

Source

**Comment by mikecao** [comment]
Yes, that's a bug.
