### ISSUE TITLE
"Event Data" page empty but events definitely coming in

### ISSUE THREAD

**Issue by psifertex** [umami-software/umami#2858]
### Describe the Bug

The "Event Data" page is completely blank despite all other portions of the UI showing plenty of events. In the activity log, in the overview, and even in reports.

Note the timestamp I took the photo in was only a few minutes after the event shown. The event summay from the overview was also from the last 24hrs, same period as the event data page.

<img width="455" alt="Screenshot 2024-07-24 at 18 37 31" src="https://github.com/user-attachments/assets/9ebf313a-e5fa-45bd-8301-c44f994272c6">
<img width="848" alt="Screenshot 2024-07-24 at 18 36 49" src="https://github.com/user-attachments/assets/c1d8babf-fb17-4316-8adc-1c6dc5798c3f">
<img width="1609" alt="Screenshot 2024-07-24 at 18 36 22" src="https://github.com/user-attachments/assets/b2e69416-59d6-4d60-a973-656d9b1c7bad">

### Database

PostgreSQL

### Relevant log output

```shell
Not sure what log output would be relevant here. Happy to provide any.
```

### Which Umami version are you using? (if relevant)

Umami 2.12.1

### Which browser are you using? (if relevant)

Brave, Safari, Chrome, same results

### How are you deploying your application? (if relevant)

Cloudron (preconfigured docker)

**Comment by franciscao633** [comment]
Those screen are only used if you are sending dynamic data along with your events like [here](https://umami.is/docs/tracker-functions#event-data). If you are sending dynamic data and it's not showing, please let us know. Wondering what terminology we can use to alleviate the confusion, since your not the first.

**Comment by psifertex** [comment]
Ahh, that makes more sense then. Hmm, good question.

Maybe something as simple as if the page is blank including a note: "This page only shows custom dynamic data included with events."

Closing this for now unless you want to re-open it to track that particular change. 

Thanks!
