### ISSUE TITLE
Allow filtering by User / Session and improve Realtime tab usability

### ISSUE THREAD

**Issue by bigbasti** [umami-software/umami#2863]
### Describe the feature or enhancement

I love the Realtime view, seeing what the users are doing on the site - awesome!

You mentioned on twitter that a new Sessions feature is coming where user activity is grouped into sessions. I am REALLY looking forward to this.

It would be really nice, if you could click on the colorful dots (which represent a user) and directly open the whole session for this user seeing all of his views and events.

Also, it would be very nice if you would show the events in the graph above the realtime flow (not only views and visits). Many of my user's interactions are through events (since its an SPA) and it would be nice to reflect this activity in the graph.

Thanks again for the awesome Product!

Really looking forward to v3!

**Comment by franciscao633** [comment]
We have new event / session screens available in Umami Cloud. These should be available to self-hosted the next release. This is the 1st iteration. We will add more features and make it more robust as we go. If you have any feedback or must have features please let us know!

![image](https://github.com/user-attachments/assets/d09f7a1c-94d1-4fef-80a3-915a8226d0a4)

**Comment by AlejandroRM-DEV** [comment]
+1

**Comment by ahaapple** [comment]
Hi, could we add the referrer value in the sessions page, I would like to know through which channels the paying users enter my website, thanks.
