### ISSUE TITLE
website: The search box on the report page disappeared unexpectedly

### ISSUE THREAD

**Issue by Stapxs** [umami-software/umami#2879]
### Describe the Bug

When searching on the report page, if the retrieval result is empty, the search box component will also disappear.

https://github.com/user-attachments/assets/8d803ff0-48ea-4955-b9fa-7c3271f9d7b3

### Database

MySQL

### Which Umami version are you using? (if relevant)

v2.12.0

### Which browser are you using? (if relevant)

safari/chrome(They can all trigger it.)

### How are you deploying your application? (if relevant)

docker

**Comment by franciscao633** [comment]
Confirmed. Thanks for reporting. We'll get this fixed.
