### ISSUE TITLE
Docs: Umami API documentation is very poor

### ISSUE THREAD

**Issue by sonysn** [umami-software/umami#2884]
I have to guess to know what queries are required for each endpoint. Some endpoints throw 500 errors too.
For example

`https://api.umami.is/v1/websites/<id>/pageviews` - request
Invalid unit - response
or
`https://api.umami.is/v1/websites/<id>/events` - request
500: Internal Server error - response

_Originally posted by @sonysn in https://github.com/umami-software/umami/discussions/2883_

**Comment by mikecao** [comment]
API documentation is here, https://umami.is/docs/api/website-stats
