### ISSUE TITLE
Allow public sharing of real time dashboard

### ISSUE THREAD

**Issue by ccrvlh** [umami-software/umami#2887]
### Describe the feature or enhancement

Currently it is possible to create a public shareable link through the settings, however, it does not allow for real time view. I'd suggestion to have an extra toggle on the share section "Allow Realtime", which would allow users to see not only the website's dashboard, but also the real time dashboard. Happy to contribute to this.

**Comment by d19dotca** [comment]
Honestly it probably doesn’t even need a toggle, IMO. Curious what the use-case is to not have them see realtime data. I would just assume there’s no downside and that they should allow realtime data by default to everyone with a share URL.

**Comment by mzohrab** [comment]
Just upvoting this, would be great to have that feature!

**Comment by zhengqunkoo** [comment]
I would love to see my site analytics from anywhere, without having to log in.
