### ISSUE TITLE
load via js directly instead of script tag

### ISSUE THREAD

**Issue by psifertex** [umami-software/umami#2889]
### Describe the feature or enhancement

Is there a recommended way to load umami via js directly instead of using a script tag? I don't see that as a currently supported feature but hopefully I'm missing it.

My use-case is I would like to include umami stat tracking in some generated HTML documentation that is both available in a website but also in local builds that are potentially offline. I explicitly do not want to collect data from the local copy of the same files and my first thought was to simply check the hostname before loading umami.

A solution like https://github.com/umami-software/umami/issues/2328 would also suffice. (Related, I don't see what malicious actors being able to spoof has to do with the original request -- it would still prevent you from accidentally adding stats from non-production deployments which is basically what I'm asking for here as well).

Note, this is a duplicate of #2766 as the feature is still valuable

**Comment by Lehoczky** [comment]
Would https://github.com/umami-software/umami/issues/2776 work for you?

**Comment by psifertex** [comment]
Not necessarily. This doesn't have anything to do with how the distributed files are packaged -- they're packaged the same way in both of my use cases. One is in a bundle downloaded with a local piece of software. The other is the same bundle hosted on a static website. By having code in the page check whether it's being loaded from a file URL or a remote one first I can only load the tracking on the remote site. As I understand it anyway, I don't see how anything in #2776 helps.

**Comment by Lehoczky** [comment]
It would allow you to conditionally initialize the tracker:

```ts
import {umami} from "@umami/tracker"

if(SHOULD_INIT_ANALYTICS) {
  umami.init({
    website: "b59e9c65-ae32-47f1-8400-119fcf4861c4"
  })
}
```

And I mentioned that this would allow loading the tracker from JavaScript instead of a script tag, just like you wish in this ticket:

> A client side npm package would be great ... to be able to initilaize the tracker without adding a <script> element to the HTML.

**Comment by psifertex** [comment]
But it also requires me to integrate NPM into something that doesn't already use it? I'm afraid I don't have familiarity with using it for client-side javascript.

**Comment by mikecao** [comment]
You can use `data-domains` to limit it to certain domains only. See https://umami.is/docs/tracker-configuration

**Comment by psifertex** [comment]
That's helpful and helps with half the problem. Unfortunately it can still cause issues when the documentation is being rendered offline or partially offline and I want to limit even requesting the .js from the network in the first place. For example, when on a slow network like a plane flight the page I have in question is entirely offline and I'd like to detect in the JS before I even load the umami.js and avoid even trying to load it.

**Comment by mikecao** [comment]
Have you tried something like this?
```
function loadUmami() {
  var el = document.createElement('script');
  el.setAttribute('src', 'http://mywebsite.com/umami.js');
  el.setAttribute('data-website-id', '94db1cb1-74f4-4a40-ad6c-962362670409');
  document.body.appendChild(el);
}
```
Which you could conditionally call.

**Comment by psifertex** [comment]
I thought I tried that and it failed to load, but let me double check again and report back.
