### ISSUE TITLE
Session history not sorted correctly

### ISSUE THREAD

**Issue by wokalek** [umami-software/umami#2898]
### Describe the Bug

August 22nd in the middle?... 

![image](https://github.com/user-attachments/assets/8e6f9597-5bce-4b81-ab8c-c9a72c708c2e)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.13.0

### How are you deploying your application? (if relevant)

docker

**Comment by eroc1990** [comment]
#2897

**Comment by franciscao633** [comment]
Will use #2897 going forward
