### ISSUE TITLE
event_data table empty and dashboard events page (Postgres) while front-end fires /api/send requests for the events

### ISSUE THREAD

**Issue by immunity20** [umami-software/umami#2899]
### Describe the Bug

i can see in network tab that umami js sends the api request for storing events but postgres is empty and  so umami dashboard
![image](https://github.com/user-attachments/assets/75f006ed-e8b2-46ac-959f-dac0244fa915)

I have also pulled the latest version but still doesn't work.

Any help  from where to start looking?

### Database

PostgreSQL

### How are you deploying your application? (if relevant)

Ubuntu server, Docker

**Comment by tbkblues** [comment]
This is happening in SQL server as well. As soon as I upgraded to 2.13.0 all data stopped being logged.

**Comment by mikecao** [comment]
The `event_data` table is for data (properties) attached to events. Custom events go into the `website_events` table.

**Comment by immunity20** [comment]
> The `event_data` table is for data (properties) attached to events. Custom events go into the `website_events` table.

I have `website-event` table not `website-events` and I can see the table has rows (events logged) but dashboard event data page is empty

![image](https://github.com/user-attachments/assets/8e59f44c-0541-4519-9e28-4ef469de0acb)
![image](https://github.com/user-attachments/assets/513b5d41-3c49-4800-8f4f-52c2b7489c05)

**Comment by immunity20** [comment]
> The `event_data` table is for data (properties) attached to events. Custom events go into the `website_events` table.

Oh I just saw the events are displayed on front-page I thought they would be on events data page 

Sorry about this, All's good (although website_event and event_data is a bit confusing (in dashboard)
![Uploading image.png…]()
