### ISSUE TITLE
Proposal for Multi-Group Feature Within a Single Unnami Site

### ISSUE THREAD

**Issue by sunlho** [umami-software/umami#2920]
### Describe the feature or enhancement

I am requesting a new feature for unami that would enable the creation of groups within a single website, eliminating the need to establish multiple websites.

My website is a complex network of sites that utilizes parameters like site-id to serve distinct content and user data. The current necessity to replicate entire websites for monitoring purposes is both inefficient and unsustainable, given the potentially infinite scale of my site information. All these sites are under a unified domain, making real-time maintenance a significant challenge.

I propose a grouping mechanism that would allow for differentiation within a single website based on transmitted parameters. This would streamline management and monitoring, significantly reducing the workload.

A big thank you to the maintainers for this awesome project!

**Comment by franciscao633** [comment]
Are you able to leverage to use of multiple hostnames under a single domain for your network of sites? You would then be able to use a single tracking script and just filter by hosts on the dashboard. I'm not sure about your exact setup, so this may not be possible for you.

**Comment by sunlho** [comment]
> Are you able to leverage to use of multiple hostnames under a single domain for your network of sites? You would then be able to use a single tracking script and just filter by hosts on the dashboard. I'm not sure about your exact setup, so this may not be possible for you.

I apologize for not being able to use multiple hostnames.

My website is more like a GitHub project management system.  When a project is created, I want to see specific project traffic and visiting users, rather than GitHub's overall traffic data.

I see that the current filtering is only available on the Overview page.  Is there a plan to add filtering to Sessions, Events, or other pages, or to add a global filter for the website?

Can the filtering fields be customized?  For example, if I add a setId field to the track event, can I use it as a filtering target?

Thank you very much for your prompt reply.

**Comment by mikecao** [comment]
We have something like that planned. Basically you would set an id to group all your events under, Then you would be able to filter by that specific id. You would pass the id through a data attribute on the tracker script tag.

**Comment by sunlho** [comment]
> We have something like that planned. Basically you would set an id to group all your events under, Then you would be able to filter by that specific id. You would pass the id through a data attribute on the tracker script tag.

Thank you very much for your prompt reply! I fully understand what you're saying. The ability to group events by a custom ID will greatly enhance our ability to analyze project data. I look forward to seeing this feature implemented soon.
