### ISSUE TITLE
[Feat] Add docker tags for major/minor/patch versions

### ISSUE THREAD

**Issue by Quadrubo** [umami-software/umami#2930]
### Description

As of the point of writing this, `v2.13.2` is the latest Umami version.
As I'm manually updating my images and not using something like "latest", I have to change the image tag every new release. It would be nice if I wouldn't have to do that for patch releases (minor releases too).

Currently these tags are provided:
- `v2.13.2` - Version 2.13.2
- `v2.13.1` - Version 2.13.1
- `latest` - Version 2.13.2

### Desired Behavior

I would propose a tag system like this:
- `v2.13.2` - Version 2.13.2
- `v2.13.1` - Version 2.13.1
- `v2.13`    - Version 2.13.2
- `v2`       - Version 2.13.2
- `latest` - Version 2.13.2

This would allow pinning to specific version and allows the user to choose which semver types they are okay with auto updating.
I for example would have pinned to `v2` and would have automatically gotten the update up to `2.13.2`.
However I won't get the update to a new major version like "v2.x" which would be desired for me.

**Comment by mikecao** [comment]
This is all done in the GitHub workflow files. Would welcome a PR.

**Comment by mikecao** [comment]
Fixed in v2.14.0.
