### ISSUE TITLE
Can't export self-hosted data: "column we.visit_id does not exist"

### ISSUE THREAD

**Issue by sonicbaume** [umami-software/umami#2931]
### Describe the Bug

I'm trying to export the website events from my self-hosted instance so I can import them into Umami Cloud. I'm following [these instructions](https://umami.is/docs/cloud/import-data#postgresql) to export a .csv file using psql, but the table `website_event` seems to be missing the column `visit_id`. Is there a upgrade/migration I need to do first?

I tried excluding that column from the export. Umami Cloud 'completes' the import but nothing appears. I also tried changing the website ID to match the ID on Umami Cloud, but still no data appears.

### Database

PostgreSQL

### Relevant log output

```shell
CREATE VIEW website_event_import AS
SELECT we.website_id,
    we.session_id,
    we.visit_id,
    we.event_id,
    s.hostname,
    s.browser,
    s.os,
    s.device,
    s.screen,
    s.language,
    s.country,
    s.subdivision1,
    s.subdivision2,
    s.city,
    we.url_path,
    we.url_query,
    we.referrer_path,
    we.referrer_query,
    we.referrer_domain,
    we.page_title,
    we.event_type,
    we.event_name,
    TO_CHAR(we.created_at, 'YYYY-MM-DD HH24:MI:SS') created_at
 FROM website_event we
 JOIN session s
 ON s.session_id = we.session_id;
ERROR:  column we.visit_id does not exist
LINE 4:     we.visit_id,
```

### Which Umami version are you using? (if relevant)

2.9.0

**Comment by mikecao** [comment]
Umami Cloud is currently running 2.13.2. You will need to upgrade to the same version first.

**Comment by sonicbaume** [comment]
Thanks. After upgrading I was able to export okay, but importing into Umami Cloud does not add any data. I tried swapping the old website ID for the new one in the .csv, but still nothing. I'll email support.
