### ISSUE TITLE
User preference of default date range doesn’t save to user

### ISSUE THREAD

**Issue by d19dotca** [umami-software/umami#2932]
### Describe the Bug

I’ve noticed that the user preference for the default date range doesn’t save to the user account. It seems like it’s more browser session oriented. If for example I sign in from a new device, it resets to 24 hours again even though I had saved it as 7 days. I find that I often have to reset the default time range so often that it’s almost pointless to set it now because it often goes back to 24 hours, and I have to change it anytime I view client analytics now. 

PS - I’m not sure if this is intentional behaviour or not so am reporting as a bug for now. It may be a feature request though if intentional. 

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.13.2

### Which browser are you using? (if relevant)

Safari and Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
That's right, user preferences are stored in local storage on the browser. This allows us to add features without having to change the db schema. This will likely change in the next major version as we will have more advanced use cases.
