### ISSUE TITLE
Track articles by author (od tag, kategory)

### ISSUE THREAD

**Issue by SvetZitrka** [umami-software/umami#2933]
### Describe the feature or enhancement

We use WordPress and have several authors writing articles. Umami is a great insight into analytics if we talk about individual URLs.

However, I haven't currently found a way to see traffic (analytics data) relative to multiple articles by a single author. Is this possible? Is this planned?

Similarly, one could look at articles in terms of tags or article categories. This would be extremely beneficial for us and we have used this functionality frequently in Google Analytic.

**Comment by mikecao** [comment]
You can send custom event properties along with your events. So if someone was reading a particular article you could send a property with the author's name. See https://umami.is/docs/track-events

**Comment by SvetZitrka** [comment]
However, the author is not an event, but rather a URL parameter. Event does not allow to display all the data they need.

**Comment by lynt-smitka** [comment]
I think it could be related to this PR https://github.com/umami-software/umami/pull/2436

**Comment by SvetZitrka** [comment]
Are there plans to include this functionality in production?
