### ISSUE TITLE
Argument `website` is missing. AND duplicate key value violates unique constraint "session_pkey"

### ISSUE THREAD

**Issue by xuserz** [umami-software/umami#2950]
### Describe the Bug

db-1     | 2024-09-05 10:39:30.165 UTC [605] ERROR:  duplicate key value violates unique constraint "session_pkey"
db-1     | 2024-09-05 10:39:30.165 UTC [605] DETAIL:  Key (session_id)=(bf6344cf-a7be-518b-bb18-7caf072561df) already exists.
db-1     | 2024-09-05 10:39:30.165 UTC [605] STATEMENT:  INSERT INTO "public"."session" ("session_id","website_id","hostname","browser","os","device","screen","language","country","subdivision1","subdivision2","city","created_at") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING "public"."session"."session_id", "public"."session"."website_id", "public"."session"."hostname", "public"."session"."browser", "public"."session"."os", "public"."session"."device", "public"."session"."screen", "public"."session"."language", "public"."session"."country", "public"."session"."subdivision1", "public"."session"."subdivision2", "public"."session"."city", "public"."session"."created_at"
umami-1  | PrismaClientValidationError: 
umami-1  | Invalid `prisma.websiteEvent.create()` invocation:
umami-1  | 
umami-1  | {
umami-1  |   data: {
umami-1  |     id: "3acfc1b1-eb8f-4797-b961-b0460aede29c",
umami-1  |     sessionId: undefined,
umami-1  |     visitId: "c39267b2-41d3-5aca-8ba9-3464a38414a2",
umami-1  |     urlPath: "/static/app/rating",
umami-1  |     urlQuery: "ref=b008336b6b7011ef97d90242ac1b000225d671",
umami-1  |     referrerPath: undefined,
umami-1  |     referrerQuery: undefined,
umami-1  |     referrerDomain: "",
umami-1  |     pageTitle: "title",
umami-1  |     eventType: 1,
umami-1  |     eventName: null,
umami-1  | +   websiteId: String
umami-1  |   }
umami-1  | }
umami-1  | 
umami-1  | Argument `websiteId` is missing.
umami-1  |     at An (/app/node_modules/@prisma/client/runtime/library.js:114:7526)
umami-1  |     at _n.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7392)
umami-1  |     at _n.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:121:7057)
umami-1  |     at _n.request (/app/node_modules/@prisma/client/runtime/library.js:121:6741)
umami-1  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:130:9355)
umami-1  |     at async x (/app/.next/server/pages/api/send.js:1:2791)
umami-1  |     at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
umami-1  |     at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
umami-1  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
umami-1  |     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37) {
umami-1  |   clientVersion: '5.17.0'
umami-1  | }
umami-1  | PrismaClientValidationError: 
umami-1  | Invalid `prisma.websiteEvent.create()` invocation:
umami-1  | 
umami-1  | {
umami-1  |   data: {
umami-1  |     id: "b229e74b-f254-47a0-88d0-a02cfd176f49",
umami-1  |     sessionId: undefined,
umami-1  |     visitId: "a392e2f8-fdd5-5120-a29f-37a417acf06a",
umami-1  |     urlPath: "/static/",
umami-1  |     urlQuery: undefined,
umami-1  |     referrerPath: undefined,
umami-1  |     referrerQuery: undefined,
umami-1  |     referrerDomain: "",
umami-1  |     pageTitle: "title",
umami-1  |     eventType: 1,
umami-1  |     eventName: null,
umami-1  | +   websiteId: String
umami-1  |   }
umami-1  | }

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

2.13.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by jjjhill** [comment]
Check my comment here: https://github.com/umami-software/umami/issues/2614

I made a PR to address it, another possible workaround is to just manually put an entry in your website_event table with the correct website_id and session_id
