### ISSUE TITLE
Northern Cyprus shows up as undefined on map

### ISSUE THREAD

**Issue by thomasgassmann** [umami-software/umami#2953]
### Describe the Bug

Hovering on the island of Cyprus, what would be Northern Cyprus shows up as `undefined` (see attached image). I suggest removing it, in line with #525.

![image](https://github.com/user-attachments/assets/991f18ef-4600-4faa-8ade-3b1d179cf946)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.13.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by franciscao633** [comment]
This should be fixed in cloud. It will be fixed in self-hosted instance the next release.

![image](https://github.com/user-attachments/assets/2c2d0c72-9b38-4c4e-84f4-a712abbf20d9)
