### ISSUE TITLE
[Feature Request] Support for Hash-Based Routing Analytics

### ISSUE THREAD

**Issue by DDDDD12138** [umami-software/umami#2954]
#### Description:
I am working on a project that uses Vue 2 and Vue Router 3 with hash-based routing. While integrating `Umami` for analytics, I noticed that all collected page paths are recorded as `/`. This issue prevents accurate tracking of user navigation within the application.

#### Minimal Example
[demo](https://stackblitz.com/edit/vitejs-vite-6ldkxk?file=src%2FApp.vue)

#### Expected Behavior
Umami should correctly record the full hash-based paths (e.g., `#/home`, `#/about`) instead of just `/`.

#### Actual Behavior
All recorded paths are shown as `/`, regardless of the actual route.

#### Possible Solution
I noticed that in the `parseURL` function within the Umami script, it only retrieves `URL.pathname`. This results in the path always being recorded as `/` when using hash routing. Perhaps `URL.hash` could be used to capture the full path when using hash routing?

**Comment by mikecao** [comment]
We'll definitely get this added.

**Comment by DDDDD12138** [comment]
Hello @mikecao ,

This PR #2960 should resolve the issue. Could you review it when you get a chance? Thanks!

**Comment by mikecao** [comment]
Fixed in v2.14.0.
