### ISSUE TITLE
Loading chunk error after navigating to project event dashboard

### ISSUE THREAD

**Issue by AlaminPu1007** [umami-software/umami#2962]
### Describe the Bug

![image](https://github.com/user-attachments/assets/7e4189a3-8f5b-4783-9d93-3e1bccb9351e)

- Log in to the Umami dashboard.
- Navigate to the dashboard for a specific project.
- Attempt to navigate to the "Event" section within the project dashboard.
- Observe the error.

**Note :** - After reload sometimes this issue resolved by itself.

### Database

PostgreSQL

### Relevant log output

```shell
ChunkLoadError
at d.f.j (https://umami-rho-henna.vercel.app/_next/static/chunks/webpack-5896310cd3d11e56.js:1:3362)
at https://umami-rho-henna.vercel.app/_next/static/chunks/webpack-5896310cd3d11e56.js:1:1427
at Array.reduce (<anonymous>)
at d.e (https://umami-rho-henna.vercel.app/_next/static/chunks/webpack-5896310cd3d11e56.js:1:1393)
at https://umami-rho-henna.vercel.app/_next/static/chunks/7023-55af897905404a48.js:2:18878
at https://umami-rho-henna.vercel.app/_next/static/chunks/7023-55af897905404a48.js:2:19080
at t (https://umami-rho-henna.vercel.app/_next/static/chunks/7023-55af897905404a48.js:2:19283)
```

### Which Umami version are you using? (if relevant)

v2.13.2

### Which browser are you using? (if relevant)

chrome

**Comment by Bullrich** [comment]
I'm also facing this same issue.

I tried to re deploy the app and reload the page but I'm still facing this error.

**Comment by franciscao633** [comment]
usually get chunk errors with adblock on `event` specific pages for some reason. If you turn off adblock for that page do the errors still occur?

**Comment by StephenGunn** [comment]
> usually get chunk errors with adblock on `event` specific pages for some reason. If you turn off adblock for that page do the errors still occur?

I had the same problem and I was very worried I had set it up incorrectly but it was just adblockers.  Thank you!
