### ISSUE TITLE
Questions about web statistics

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [umami-software/umami#2966]
All the web pages on my website are XXX.php?+related parameters, but the website statistics will not count the content after "?". Is it possible to add an option to select the content after "?"?

For example：
xxx.php?ss=1&v=262656
xxx.php?ss=2&v=566565

Statistics are xxx.php

----From Google Translate

**Comment by franciscao633** [comment]
We currently strip the query params from the page URL, and there is no current option to leave it in the URL. We use to have the raw URLs in v1, but we no longer expose those.
