### ISSUE TITLE
cloud: Overview does not show data generated after Reset website

### ISSUE THREAD

**Issue by myesn** [umami-software/umami#2970]
### Describe the Bug

 https://cloud.umami.is/ Overview does not show data generated after Reset website.
![image](https://github.com/user-attachments/assets/49a67c36-3c9c-4d66-a603-6f20c59b13e7)
![image](https://github.com/user-attachments/assets/e0f25a65-5f6d-4c0a-a92e-a7780d053c46)
![image](https://github.com/user-attachments/assets/192470eb-f83f-4830-bc3f-da5e0b2bf3b3)

### Database

Umami Cloud

**Comment by franciscao633** [comment]
This is confirmed. There is an issue with querying date ranges for reset websites and our database views that are truncated to the hour. There should be data showing after an hour, but let me know if its still blank. We we get this fixed anyways.
