### ISSUE TITLE
Add the ability to delete websites from the dashboard

### ISSUE THREAD

**Issue by Mel-Roth-AI** [umami-software/umami#2983]
### Describe the feature or enhancement

We have some websites that are staging sites that we track statistics for that are appearing on the dashboard. We would like to hide them from the dashboard so we only see public facing websites. Please add the ability to delete or disable websites from appearing on the dashboard.

**Comment by franciscao633** [comment]
This makes sense. Thanks for the rec.

**Comment by mikecao** [comment]
v2.14.0 now lets you do this.
