### ISSUE TITLE
Can't collect data. `/send` request get `404 - Website not found` and tracking events not working.

### ISSUE THREAD

**Issue by hta218** [umami-software/umami#2987]
### Describe the Bug

The **Umami** script is loaded successfully but I see the request to `https://api-gateway.umami.dev/api/send` always return `404 - Website not found`. Some events tracker works (I see a `/send` request, but still 404), some doesn't (I don't see any `/send` request)

![image](https://github.com/user-attachments/assets/f82fe55e-dbf5-482f-981b-831683a93f3f)

I'm using **NextJS** (`v14.2.8`), here's how I load the **Umami** script:

```typescript
import Script from 'next/script.js'

export function UmamiAnalytics({
  umamiWebsiteId,
  src = 'https://analytics.umami.is/script.js',
}: {
  umamiWebsiteId: string
  src?: string
}) {
  return <Script async defer data-website-id={umamiWebsiteId} src={src} />
}
```

This is the script tag rendered on the website:
![image](https://github.com/user-attachments/assets/643aceda-99c2-43e7-8aba-0a6118632958)

You can inspect the **Network tab** to check on my website: https://leohuynh.dev
It's a public repo: https://github.com/hta218/leohuynh.dev/

This is website config in my **Umami** dashboard:
![image](https://github.com/user-attachments/assets/a649ba07-6164-4092-a13e-a42c0100c80a)

The analytics source is also a public repo as well: https://github.com/hta218/blog-analytics
This is the share URL: https://analytics.leohuynh.dev/share/c9ErglxqzY5CQJ8g/leohuynh.dev

Could you take look on this? It's been working for more than a year, and now it's not.

### Database

PostgreSQL

### Relevant log output

Response received when the script send a POST to `https://api-gateway.umami.dev/api/send`:
```js
{"error":{"message":"Website not found"}}
```

Some tracking events works, some doesn't.

### Which Umami version are you using? (if relevant)

v2.13.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Vercel

**Comment by mikecao** [comment]
If you are self hosting, then you need to load the script from your own website, not from Umami Cloud.

**Comment by hta218** [comment]
Are you mean that I should follow the **"Proxy Umami Analytics via Vercel"** section in this docs article: https://umami.is/docs/guides/running-on-vercel ? 

If so I have already done that here: [https://github.com/hta218/leohuynh.dev/commit/425d79abad6b9bb1d4f14cf9bb0674b2bd294a22](https://github.com/hta218/leohuynh.dev/commit/425d79abad6b9bb1d4f14cf9bb0674b2bd294a22).
Demo link: [leohuynh-qtuw6g4g8-leo-huynhs-projects.vercel.app](https://leohuynh-qtuw6g4g8-leo-huynhs-projects.vercel.app/)

Or should I put the Umami script inside my project and load it fron my own website like this: https://github.com/hta218/leohuynh.dev/commit/9186f755a1587bcd90aea9e8a7cc0592db79c691
Demo link: [leohuynh-n2eyk7x7z-leo-huynhs-projects.vercel.app](https://leohuynh-n2eyk7x7z-leo-huynhs-projects.vercel.app/)

Both results are still the same: 
![image](https://github.com/user-attachments/assets/44924f44-03bc-492c-9398-8d0504c688d8)

What could be the reason @mikecao ?
