### ISSUE TITLE
Timed out trying to acquire a postgres advisory lock

### ISSUE THREAD

**Issue by bayerlse** [umami-software/umami#2999]
### Describe the Bug

I updated from `2.4.1` to `2.13.2` and now my app is not starting anymore. It logs following errors

### Database

PostgreSQL

### Relevant log output

```shell
✗ Command failed: prisma migrate deploy
Error: P1002
The database server at `xx.xx.xx:5432` was reached but timed out.
Please try again.
Please make sure your database server is running at `xx.xx.xx:5432`.
Context: Timed out trying to acquire a postgres advisory lock (SELECT pg_advisory_lock(72707369)). Elapsed: 10000ms. See https://pris.ly/d/migrate-advisory-locking for details.
error Command failed with exit code 1.
```

### Which Umami version are you using? (if relevant)

2.13.2

### Which browser are you using? (if relevant)

/

### How are you deploying your application? (if relevant)

Docker

**Comment by bayerlse** [comment]
My PSQL Version is: `15.1`

It seams that its related to the size of the db. We have two environments (dev and live) and on dev with less data, the same migration made no problems. 

Maybe set the timeout to a higher value?

**Comment by franciscao633** [comment]
This is an open prisma [issue](https://github.com/prisma/prisma/issues/12999). If you run the code below on your locked db, migrations should be resolved

```
SELECT pg_terminate_backend(PSA.pid)
FROM pg_locks AS PL
    INNER JOIN pg_stat_activity AS PSA ON PSA.pid = PL.pid
WHERE PSA.state LIKE 'idle'
    AND PL.objid IN (72707369);
