### ISSUE TITLE
Feature Request: IP blocking

### ISSUE THREAD

**Issue by techcow2** [umami-software/umami#3003]
### Describe the feature or enhancement

Could we please have the option to block our own IP addresses? This would help us get more accurate statistics.

**Comment by franciscao633** [comment]
If you are self-hosting you can use the env var `IGNORE_IP`. If you are using cloud you can try a browser specific option [here](https://umami.is/docs/guides/exclude-my-own-visits).

**Comment by techcow2** [comment]
Thank you!
________________________________

**Comment by techcow2** [comment]
@franciscao633 solution worked perfectly.
