### ISSUE TITLE
Non-English Characters Support

### ISSUE THREAD

**Issue by jcubic** [umami-software/umami#3008]
### Describe the Bug

It looks like Umami don't support Unicode/UTF8.

it display "Å¼" instead of "ż" (it's Polish diactrict character)

![Przechwycenie obrazu ekranu_2024-10-17_10-42-04](https://github.com/user-attachments/assets/14647245-d56b-4041-8234-a0f1b75ded76)

I'm using Cloud version.

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Brave

**Comment by mikecao** [comment]
Not really sure what's going on here. Would appreciate some help debugging.

**Comment by jcubic** [comment]
How the city is retrieved? Do you use some kind of external API? Maybe the API use different encoding and it's not properly decoded.

**Comment by mikecao** [comment]
The location data comes from Cloudflare.

**Comment by jcubic** [comment]
Is this an API, can you share the link. When I worked with different encoding in PHP, I first detected encoding and use iconv to convert to utf8 before using.

**Comment by mikecao** [comment]
Headers are sent with every request from Cloudflare, https://developers.cloudflare.com/rules/transform/managed-transforms/reference/#add-visitor-location-headers

**Comment by jcubic** [comment]
Not sure how to test it, maybe this should be reported to Cloudflare, maybe they have encoding issue.

**Comment by mikecao** [comment]
Should be resolved in v2.15.0

**Comment by jcubic** [comment]
What was the issue?
