### ISSUE TITLE
Event not being tracked?

### ISSUE THREAD

**Issue by Gabriel-p** [umami-software/umami#3018]
### Describe the Bug

I added several events to my [site](https://ucc.ar) but only a few are showing in the Events tab:

![Captura de pantalla de 2024-10-22 14 43 33](https://github.com/user-attachments/assets/b1dfe30f-2c0c-4069-a203-140e2422a67c)

Why are some events (e.g: `Viewed page /_clusters/ngc6531/`) shown listed below but not aggregated in the top view like `faq` etc?

This is how those events are added:

![Captura de pantalla de 2024-10-22 14 41 34](https://github.com/user-attachments/assets/6c054b8a-d680-41a0-9be2-b86d7d0fcb9f)

### Database

Umami Cloud

**Comment by mikecao** [comment]
Do you have some other script running that could be capturing events on the page and not passing them on?

**Comment by Gabriel-p** [comment]
It's working now @mikecao  although I'm not sure I'm using it as intended having so many events tracked? Could you take a look maybe? https://cloud.umami.is/share/hc3DSKDJ19kK1Uql/ucc.ar

**Comment by Gabriel-p** [comment]
Nevermind, I understand now that these are two different events
