### ISSUE TITLE
CORS with custom API endpoint 

### ISSUE THREAD

**Issue by romangg** [umami-software/umami#3022]
### Describe the Bug

I'm running latest Umami Docker container behind Traefik. Website to track runs Nuxt with [Umami module](https://nuxt.com/modules/umami). When using a custom API endpoint like `/api/getdata` instead of `/api/send` I'm getting CORS violations.

Making exceptions for CORS via Traefik similar to [here](https://doc.traefik.io/traefik/middlewares/http/headers/#cors-headers), removes the error. But then I get 405 - Method not allowed.

Only the default endpoint `/api/send` works for me without issues.

### Database

PostgreSQL

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
Are you able to run it without Traefik?

**Comment by IgnisDa** [comment]
Hey @romangg how did you solve this?

**Comment by romangg** [comment]
Opted to use the default endpoint.
