### ISSUE TITLE
umami.is is down

### ISSUE THREAD

**Issue by decentropy** [umami-software/umami#3023]
### Describe the Bug

cannot load site for docker or docs, etc

### Database

PostgreSQL

### Relevant log output

```shell
pinging ... it shows 127.0.0.1
```

**Comment by mikecao** [comment]
The website is up. Not sure why you're getting 127.0.0.1 since that is a localhost address.

**Comment by decentropy** [comment]
I determined this was my adblocker (adguard)... for some reason it miscategoried umami.is as adware
