### ISSUE TITLE
Feature Request - Option to pin websites

### ISSUE THREAD

**Issue by zcraber** [umami-software/umami#3029]
### Describe the feature or enhancement

It'd be nice to have an option to pin a website in the dashboard.

**Comment by mikecao** [comment]
We will be completely reworking the dashboard soon so that you will pick exactly what websites to show.

**Comment by zcraber** [comment]
@mikecao, I updated Umami to the latest version, where you've added the option to show/hide websites. But the feature I was looking for is still missing. I meant an option to pin a website or multiple websites to the top.
