### ISSUE TITLE
Property select has wrong z-index on mobile view

### ISSUE THREAD

**Issue by martinmaricak** [umami-software/umami#3039]
### Describe the Bug

![IMG_8590](https://github.com/user-attachments/assets/8f0d2648-7791-450a-8dbb-0fcfcecde373)

### Database

Umami Cloud

### Which browser are you using? (if relevant)

Safari

### How are you deploying your application? (if relevant)

Scene

**Comment by mikecao** [comment]
Fixed in v2.14.0.
