### ISSUE TITLE
default dashboard (either personal / team)

### ISSUE THREAD

**Issue by phken91** [umami-software/umami#3044]
### Describe the feature or enhancement

Currently, after logging in, users are automatically shown their personal dashboard. If the user only has access to the team dashboard, they have to manually switch to it after logging in.

Could we add a new setting that allows the team dashboard to be displayed directly upon login?

**Comment by chelsey-g** [comment]
#3043 fixes this issue

**Comment by mikecao** [comment]
Fixed in dev, will go out in next release.

**Comment by mikecao** [comment]
Fixed in v2.14.0.
