### ISSUE TITLE
Did the data-do-not-track Tracker Configuration get removed in 2.0?

### ISSUE THREAD

**Issue by amxmln** [umami-software/umami#3047]
### Describe the Bug

In versions below 2.0, there used to be a `data-do-not-track` option for the tracker configuration that would honour the user’s "Do not track" setting. This seems to no longer be the case in post `v2.0` – or is the option simply missing from the docs?

### Database

MySQL

**Comment by mikecao** [comment]
It was removed because it is not a standard and not supported in all browsers. You can trivially add it to your own code, but we didn't want to bloat the tracker code with something not commonly supported.

**Comment by amxmln** [comment]
Thanks for letting me know, perhaps this should be added to the document about how to migrate to v2.

**Comment by 0x1618** [comment]
> It was removed because it is not a standard and not supported in all browsers. You can trivially add it to your own code, but we didn't want to bloat the tracker code with something not commonly supported.

[You should add a note about it being deprecated.](https://umami.is/docs/tracker-configuration)
