### ISSUE TITLE
See metrics without visually incrementing numbers

### ISSUE THREAD

**Issue by vitobotta** [umami-software/umami#305]
Hola, metrics are shown with a number that is incremented until it reaches the actual value, instead of showing the actual value right away. Why is that? Is it just a visual thing that can be disabled? Thanks!

**Comment by mikecao** [comment]
It's a design decision. I think it looks neat. But I can provide an option to disable animations.

**Comment by vitobotta** [comment]
An option would be awesome :)

**Comment by mikecao** [comment]
Closing for now. Will reconsider for future.
