### ISSUE TITLE
Improve handling of `undefined` visitor data for Somaliland region

### ISSUE THREAD

**Issue by eremannisto** [umami-software/umami#3054]
### Describe the Bug

**Description:**
When viewing the visitor map, hovering over the Somaliland region displays "undefined: X visitors" which appears to be a raw JavaScript `undefined` value being rendered. While Somaliland's status as an unrecognized state may explain the lack of data, the current display looks like a technical error rather than an intentional handling of this edge case.

**Suggested Solution:**
Replace the "undefined" text with a more user-friendly message such as:
- "Unknown region: X visitors"
- "Unrecognized region: X visitors"
- "No data available: X visitors"

This would make it clearer that the lack of data is handled intentionally rather than showing what appears to be a JavaScript error to end users.

<img width="367" alt="map" src="https://github.com/user-attachments/assets/0bf097f2-faf6-41ba-adfe-79f5838eaa1c">

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.13.2

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
That makes sense. A PR would be welcome.

**Comment by eremannisto** [comment]
We should handle this with `i18n` in mind. We could either add new translations for all languages, or simply reuse the existing `label.unknown` from the locale JSON. With `label.unknown` it would be simpler since we wouldn't need to create new translations.

Example image:

<img width="402" alt="image" src="https://github.com/user-attachments/assets/81f036b1-449b-4731-ae5a-c18e2b41b5f5">

**Comment by eremannisto** [comment]
PR made [3060](https://github.com/umami-software/umami/pull/3060)

**Comment by mikecao** [comment]
Fixed in v2.14.0.
