### ISSUE TITLE
Revenue report currency selection not possible

### ISSUE THREAD

**Issue by ceviixx** [umami-software/umami#3064]
### Describe the Bug

If I want to create an revenue report it’s not possible to select an revenue. 

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v2.14.0

### Which browser are you using? (if relevant)

Safari

### How are you deploying your application? (if relevant)

Docker with postgresql

**Comment by franciscao633** [comment]
The revenue report requires some configuration to start tracking. Please see the docs [here](https://umami.is/docs/reports/report-revenue). If you already configured tracking and still can't use it please let us know.

**Comment by ceviixx** [comment]
Oh I missed it, you can close this.
