### ISSUE TITLE
400 Bad Request - type is a required field

### ISSUE THREAD

**Issue by zbycz** [umami-software/umami#3066]
### Describe the Bug

Hi,

i wonder what might be the reason for this error message.
```
$ [Error]: 400 Bad Request at https://cloud.umami.is/api/send
    at d (/var/task/.next/server/chunks/2595.js:71:2253)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m (/var/task/.next/server/chunks/2595.js:71:2337) {
  code: '400',
  data: 'type is a required field'
}
```

I am sending the following headers and payload. When I compare it with other successful requests, the only difference is missing brackets in the user-agent header. Could it be the issue? The message "type is required" doesn't indicate this..

My failing request:
```
const data= {
    "type": "event",
    "payload": {
      "name": "next-server",
      "website": "5e4d4917-9031-42f1-a26a-e71d7ab8e3fe",
      "url": "/",
      "hostname": "osmapp-r3cgr65bz-osm-app-team.vercel.app",
      "language": "en"
    }
}

const headers = {
    "X-Client-IP": "128.199.0.145",
    "User-Agent": "vercel-screenshot/1.0"
}

fetch('https://cloud.umami.is/api/send', {
    method: 'POST',
    headers,
    body: JSON.stringify(data),
  })
```

### Database

Umami Cloud

**Comment by mikecao** [comment]
Is that the actual request you're sending? It should juse be:
```json
{
  "type": "event",
  "payload": { }
}
```

**Comment by zbycz** [comment]
No, it was only for debugging. I updated the description of the issue. I am still getting the 400 with strange description "type is required" even though i send the field correctly.

I am executing the code with this call in node.js
```
fetch('https://cloud.umami.is/api/send', {
    method: 'POST',
    headers,
    body: JSON.stringify(data),
  })
  ```

**Comment by zbycz** [comment]
I've got it! I was missing the content-type header. So the description was only a bit misleading.. I suggest changing the error to `content-type si required`.
