### ISSUE TITLE
Country (T1) has no associated `<a>` tag

### ISSUE THREAD

**Issue by znxftw** [umami-software/umami#3067]
### Describe the Bug

If you get traffic from a Tor route the country comes as `(T1)` with no flag, which is fine - however, I am unable to filter out these results by clicking on the country name - there is no `<a>` tag that gets associated to the (T1) country unlike all other countries.

If I manually append `?view=country&country=T1` the output is as expected - correctly filtering out these values.

T1 : 
<img width="352" alt="image" src="https://github.com/user-attachments/assets/92cf9309-676f-430d-919e-03ef19781845">

United States : 
![image](https://github.com/user-attachments/assets/14aae7ad-423c-4b79-9ea3-5c1b3c478ab5)

### Database

Umami Cloud

### Which Umami version are you using? (if relevant)

Chrome

### Which browser are you using? (if relevant)

Chrome

**Comment by franciscao633** [comment]
Thanks for reporting. This is fixed in the dev and will go out the next cloud deployment.
