### ISSUE TITLE
Hash changes are reported on the wrong URL

### ISSUE THREAD

**Issue by Kilian** [umami-software/umami#3083]
### Describe the Bug

If you have a page that updates the URL's hash value, those URL changes are reported on the top level / rather than the page itself.

For example, https://polypane.app/css-specificity-calculator/ will append e.g. `#selector=header%20h1%23sitetitle%20%3E%20.logo` depending on the value added to the input field on that page.

All of these show up as top level links:
![Selection_2886](https://github.com/user-attachments/assets/694ec282-7d5c-4f69-9d3e-1504ac7deb97)

### Database

PostgreSQL

### Relevant log output

```shell
n/a
```

### Which browser are you using? (if relevant)

all

### How are you deploying your application? (if relevant)

node on vps

**Comment by mikecao** [comment]
I think I know what's going on. We hook into the `history.pushState` method which passes the changed url. However it looks like it doesn't pass the entire url but just the fragment.

You can try this, edit the `tracker/index.js` file and change

```javascript
  const handlePush = (state, title, url) => {
    if (!url) return;

    currentRef = currentUrl;
    // currentUrl = parseURL(url.toString());
    // change to this
    currentUrl = parseURL(location.href);

    if (currentUrl !== currentRef) {
      setTimeout(track, delayDuration);
    }
  };
```

Then run `yarn build-tracker`. Let me know if this works for you.

**Comment by Kilian** [comment]
Right, so what you'll want to do is this:

```
currentUrl = new URL(url, location.href).href;
```

This will use the built-in URL API to resolve a potentially relative URL against the current document and then `.href` will return the combined full url.

I also looked at the parseURL implementation and using origin is wrong, because links can be one of three types, The following links all resolve to the same page:
- fully specified: `https://example.com/foo/bar`
- relative to the root: `/foo/bar`
- relative to the current page: `../bar` when you're on  `https://example.com/foo/baz`

Using `origin` will fail the last case.

**Comment by Kilian** [comment]
Fixed with the above PR
