### ISSUE TITLE
Remember last selected timeframe

### ISSUE THREAD

**Issue by Kilian** [umami-software/umami#3084]
### Describe the feature or enhancement

Every time you refresh the overview page, the timeframe is reset to the last 24 hours. 

It would be nice if the chosen timeframe was stored (in the dB or in a cookie/localstorage) on a per-website level so that it's remembered on subsequent pageviews.

**Comment by franciscao633** [comment]
In the top right there should be a profile button where you can set the default date range, which uses local storage. However, It is global for the application and not at the website level.

![image](https://github.com/user-attachments/assets/9f43c4fa-f47c-4aea-b2fc-840e480c9059)

**Comment by Kilian** [comment]
It would be nice if this was stored per-site based and updated on changing the dropdown there. That way it will be consistent against page refreshes.

Storing 'profile' settings in local storage is also a little odd, as then your profile isn't consistent against devices. Are there plans to store these in the db?
