### ISSUE TITLE
Updating Umami should not lead to re-iimporting all my accounts

### ISSUE THREAD

**Issue by germanD** [umami-software/umami#3085]
### Describe the Bug

I have been using Umami v2.3.3 on Linux (Ubuntu 24.04.1 LTS, if you can call that Linux). I click the in-app link to update to v2.3.4.

Upon restart, I need to re-import all my accounts for scratch.  

![Screenshot from 2024-12-03 18-13-06](https://github.com/user-attachments/assets/bc264b4d-6e8e-411e-b539-93962b5d3cde)

### Database

PostgreSQL

### Which Umami version are you using? (if relevant)

v.2.3.4 // Linux packages

**Comment by mikecao** [comment]
Wrong project, https://github.com/trilitech/umami-v2

**Comment by germanD** [comment]
LOL! Sorry about that @mikecao
