### ISSUE TITLE
 Internal Server Error (500) when deploying Umami to Netlify

### ISSUE THREAD

**Issue by JamesManalili** [umami-software/umami#3086]
### Describe the Bug

I attempted to deploy Umami (web analytics) to Netlify, but I am encountering a 500: Internal Server Error when trying to log in. This happens after successfully deploying the app.
![image](https://github.com/user-attachments/assets/b59ee178-5654-4d71-83b9-3c9c7fa2d2d4)

### Database

PostgreSQL

### Which browser are you using? (if relevant)

Chrome

### How are you deploying your application? (if relevant)

Netlify

### Error Message

<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>500: Internal Server Error</title><meta name="next-head-count" content="3"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js"></script><script src="/_next/static/chunks/webpack-0546caa49df5d92e.js" defer=""></script><script src="/_next/static/chunks/framework-8e0e0f4a6b83a956.js" defer=""></script><script src="/_next/static/chunks/main-1026f11cc5657f6d.js" defer=""></script><script src="/_next/static/chunks/pages/_app-f870474a17b7f2fd.js" defer=""></script><script src="/_next/static/chunks/pages/_error-c66a4e8afc46f17b.js" defer=""></script><script src="/_next/static/bz5RxoF8iL_suINaUGiW0/_buildManifest.js" defer=""></script><script src="/_next/static/bz5RxoF8iL_suINaUGiW0/_ssgManifest.js" defer=""></script></head><body><div id="__next"><div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="line-height:48px"><style>body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}</style><h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">500</h1><div style="display:inline-block"><h2 style="font-size:14px;font-weight:400;line-height:28px">Internal Server Error.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"bz5RxoF8iL_suINaUGiW0","isFallback":false,"isExperimentalCompile":false,"err":{"name":"Internal Server Error.","message":"500 - Internal Server Error.","statusCode":500},"gip":true,"scriptLoader":[]}</script></body></html>

**Comment by JamesManalili** [comment]
> You'll need to post the actual error message.

I already updated my post. Thank you.

**Comment by JamesManalili** [comment]
> You'll need to post the actual error message.

<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>500: Internal Server Error</title><meta name="next-head-count" content="3"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js"></script><script src="/_next/static/chunks/webpack-0546caa49df5d92e.js" defer=""></script><script src="/_next/static/chunks/framework-8e0e0f4a6b83a956.js" defer=""></script><script src="/_next/static/chunks/main-1026f11cc5657f6d.js" defer=""></script><script src="/_next/static/chunks/pages/_app-f870474a17b7f2fd.js" defer=""></script><script src="/_next/static/chunks/pages/_error-c66a4e8afc46f17b.js" defer=""></script><script src="/_next/static/bz5RxoF8iL_suINaUGiW0/_buildManifest.js" defer=""></script><script src="/_next/static/bz5RxoF8iL_suINaUGiW0/_ssgManifest.js" defer=""></script></head><body><div id="__next"><div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="line-height:48px"><style>body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}</style><h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">500</h1><div style="display:inline-block"><h2 style="font-size:14px;font-weight:400;line-height:28px">Internal Server Error.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"bz5RxoF8iL_suINaUGiW0","isFallback":false,"isExperimentalCompile":false,"err":{"name":"Internal Server Error.","message":"500 - Internal Server Error.","statusCode":500},"gip":true,"scriptLoader":[]}</script></body></html>

**Comment by JamesManalili** [comment]
"<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>500: Internal Server Error</title><meta name="next-head-count" content="3"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js"></script><script src="/_next/static/chunks/webpack-0546caa49df5d92e.js" defer=""></script><script src="/_next/static/chunks/framework-8e0e0f4a6b83a956.js" defer=""></script><script src="/_next/static/chunks/main-1026f11cc5657f6d.js" defer=""></script><script src="/_next/static/chunks/pages/_app-f870474a17b7f2fd.js" defer=""></script><script src="/_next/static/chunks/pages/_error-c66a4e8afc46f17b.js" defer=""></script><script src="/_next/static/bz5RxoF8iL_suINaUGiW0/_buildManifest.js" defer=""></script><script src="/_next/static/bz5RxoF8iL_suINaUGiW0/_ssgManifest.js" defer=""></script></head><body><div id="__next"><div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="line-height:48px"><style>body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}</style><h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">500</h1><div style="display:inline-block"><h2 style="font-size:14px;font-weight:400;line-height:28px">Internal Server Error.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":500}},"page":"/_error","query":{},"buildId":"bz5RxoF8iL_suINaUGiW0","isFallback":false,"isExperimentalCompile":false,"err":{"name":"Internal Server Error.","message":"500 - Internal Server Error.","statusCode":500},"gip":true,"scriptLoader":[]}</script></body></html>"

Here's the error message

**Comment by JamesManalili** [comment]
> You'll need to post the actual error message.

I have pasted the code in a notepad since GitHub removed some parts of the code in my initial post. 
[error message.txt](https://github.com/user-attachments/files/18001483/error.message.txt)

**Comment by JamesManalili** [comment]
> > You'll need to post the actual error message.
> 
> I have pasted the error message in a notepad since GitHub removed some parts of the code in my initial post. [error message.txt](https://github.com/user-attachments/files/18001483/error.message.txt)

**Comment by mikecao** [comment]
This doesn't really say anything other than a 500 error occurred. Does netlify have server logs you can look at?

**Comment by JamesManalili** [comment]
> This doesn't really say anything other than a 500 error occurred. Does netlify have server logs you can look at?

I switched to Vercel, and the deployment was successful. However, when I try to log in, it just keeps loading. I'm using Supabase for database. Could you help me troubleshoot what might be causing this issue?
