### ISSUE TITLE
History charts not showing or loading in v2.15.0

### ISSUE THREAD

**Issue by cedric-kany** [umami-software/umami#3114]
### Describe the Bug

The history chart of views and visitors is not showing in the new version of umami, neither in the dashboard nor in the details page. I have multiple pages connected to umami all having the same issue, there are no errors in the console or the requests and the "non-chart" data is showing fine. There might be an issue in the chart library? 

<img width="1342" alt="image" src="https://github.com/user-attachments/assets/3b72ec2f-bcb4-4eff-81b0-1ac226585787" />

### Database

MySQL

### Which Umami version are you using? (if relevant)

v2.15.0

### Which browser are you using? (if relevant)

Chrome (& Arc), Safari Desktop and mobile

### How are you deploying your application? (if relevant)

selfhosted next.js

**Comment by diarpu** [comment]
Same here. Also nothing is shown in the realtime graphs, compare.

**Comment by tbkblues** [comment]
Same issue here. Seeing this error in log:
`Dec 13 11:15:12 www mariadbd[808]: 2024-12-13 11:15:12 20284 [ERROR] Incorrect definition of table mysql.column_stats: expected column 'histogram' at position 10 to have type longblob, found type varbinary(255).
Dec 13 11:17:01 www CRON[31254]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)`

**Comment by Bertigrad** [comment]
Same issue here. happened after v2.15.0 update

**Comment by Maxime-J** [comment]
Hi !
I didn't try that much, but spotted an issue which can surely be the culprit here:

In lib/prisma.ts, MySQL `convert_tz`  expects a timezone to be in a +00:00 like format, which was correctly done with `moment-timezone` library.
It has changed in the transition to `date-fns-tz` => `tz` is now a 'full' date, and should cause NULL values to be returned because it's an invalid argument.

**Comment by mikecao** [comment]
Should be fixed in v2.15.1.

**Comment by Bertigrad** [comment]
> Should be fixed in v2.15.1.

its fixed for me in 2.15.1
