### ISSUE TITLE
Events - Loading chunk 65 failed

### ISSUE THREAD

**Issue by LunaticZorr** [umami-software/umami#3119]
### Describe the Bug

Running Umami in Docker. I've got one website connected for testing and when clicking on `Events` I get the error message posted in the log output. Sometimes instead of the error, the page just stays blank with the loading circle until I refresh.

### Database

PostgreSQL

### Relevant log output

```shell
Something went wrong.
Loading chunk 65 failed. (missing: https://stats.domain.com/_next/static/chunks/app/(main)/websites/%5BwebsiteId%5D/events/page-d6d04dae0828fa45.js)
ChunkLoadError
    at r.f.j (https://stats.domain.com/_next/static/chunks/webpack-f477b7e97247025d.js:1:3006)
    at https://stats.domain.com/_next/static/chunks/webpack-f477b7e97247025d.js:1:1226
    at Array.reduce (<anonymous>)
    at r.e (https://stats.domain.com/_next/static/chunks/webpack-f477b7e97247025d.js:1:1205)
    at i (https://stats.domain.com/_next/static/chunks/1517-92ffe76c3ec2a0fe.js:2:34085)
    at https://stats.domain.com/_next/static/chunks/1517-92ffe76c3ec2a0fe.js:2:46476
    at https://stats.domain.com/_next/static/chunks/1517-92ffe76c3ec2a0fe.js:2:46680
    at t (https://stats.domain.com/_next/static/chunks/1517-92ffe76c3ec2a0fe.js:2:47924)
```

### Which Umami version are you using? (if relevant)

umami:postgresql-latest

### Which browser are you using? (if relevant)

Brave

### How are you deploying your application? (if relevant)

Docker

**Comment by mikecao** [comment]
Make sure you don't have adblock running

**Comment by LunaticZorr** [comment]
> Make sure you don't have adblock running

Oh wow! Thanks! That's it :D
