### ISSUE TITLE
[Feature Request] Path or regex aggregations & Url parameters

### ISSUE THREAD

**Issue by jweisbaum** [umami-software/umami#421]
I'm really excited to use Umami for a project I'm working on that has a ton of pages. Basically I have a lot of paths like website.com/sourceA/page1. I have about 15 sources and for each source there may be hundreds or thousands of pages. 
I am looking for a way to get analytics aggregated for each source, ie all pages that fit the pattern website.com/sourceA/*. 

I'm also wondering if there's a way to get the analytics by URL parameter? 

I'd be happy to help contribute these if you're on board. Thanks.

**Comment by mikecao** [comment]
You can already get stats by URL, by not by URL fragment. I think it can be done by adjusting the SQL query, but I'm not sure how to surface that in the UI.

**Comment by d19dotca** [comment]
I think this is similar to https://github.com/mikecao/umami/issues/1033 for what it's worth, unless I've misunderstood.

**Comment by mikecao** [comment]
Fixed in v1.37.0.
