### ISSUE TITLE
Script for adding users

### ISSUE THREAD

**Issue by thueske** [umami-software/umami#792]
Hey,

to automatically create the first user (or even more) via environment variables (e.g. Docker), it would be good if there was a corresponding script. Currently, the default user is in the SQL file.

The following parameters would be good:

- username
- Password
- optional: admin

Are there any plans for this?

Tobias

**Comment by mikecao** [comment]
Is there a reason you're not doing it through the UI interface? Otherwise your options are,
1. Use admin UI
2. Manually insert into the database
3. Run a script

For 3 we would have to create a new script. There is already a script for changing passwords so it should be doable.

**Comment by mikecao** [comment]
@rosscdh `node scripts/change-password.js`
