### ISSUE TITLE
No way to go to the actual link

### ISSUE THREAD

**Issue by saiftheboss7** [umami-software/umami#800]
Found out that there's no way to go to the actual link form the Stats. An external link icon to like this to directly open the URL in a new tab would be very helpful

![CleanShot 2021-09-28 at 15 29 03](https://user-images.githubusercontent.com/19363738/135061833-560c5dd6-d1f1-452d-8b38-7ec164c9e549.png)

**Comment by saiftheboss7** [comment]
I see you closed the issue but after trying today, I couldn't find the go to external links

![CleanShot 2022-02-10 at 12 49 50](https://user-images.githubusercontent.com/19363738/153352971-8805c221-ce84-4055-ae52-8a8ac6d61ee8.png)


It only works for referrers section, but I actually suggested for the own website pages.

**Comment by psifertex** [comment]
Please re-open this issue -- as mentioned by @saiftheboss7 , it's not actually resolved as it only exists on referrers, not pages. This is a feature I would like as well. The only work-around currently is to copy the url, paste it on top of an existing url of the site. Very unergonomic.

**Comment by saiftheboss7** [comment]
Agreed with @psifertex

**Comment by psifertex** [comment]
It's still, however, desired. Anything that has to be done to keep it from being auto-closed?

**Comment by mxdpeep** [comment]
I'd also like to add an 🔗 icon to go directly to the link in a new window. ❤️

**Comment by psifertex** [comment]
Just replying to proactively prevent this from going stale. This is still very much a desired feature. To be clear, adding an outgoing link icon that links to the full path for pages, not just referrers.
