### ISSUE TITLE
Publishing on Docker Hub

### ISSUE THREAD

**Issue by benjaminrancourt** [umami-software/umami#819]
Hi,

Thank you for your application, it is a simple and great alternative to Google Analytics. 😀

Is there any reason why you aren't publish images on Docker Hub?

Personnaly, I use the [docker notify](https://docker-notify.com/) service to be notified when a new image is released for the containers I am using and it doesn't support yet GitHub Packages...

If you want to support both, GitHub has created a documentation [here](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages) to publish on both platforms simultaneously. Let me know if I can implement it for you.

Psst. If you want to opt in your repository to the [Hacktoberfest](https://hacktoberfest.digitalocean.com/) event, you can [add the `Hacktoberfest` topic](https://hacktoberfest.digitalocean.com/resources/maintainers) to your repository. 🎃

**Comment by ajfriesen** [comment]
@ranb2002 
You can also use something like https://github.com/containrrr/watchtower to automatically update your containers.

You just need to be careful which tag you use and this will auto update your containers.
