### ISSUE TITLE
Mobile dark/light mode header

### ISSUE THREAD

**Issue by 8times4** [umami-software/umami#869]
Hey @mikecao , 

as detailed in https://github.com/mikecao/umami/pull/847
the dark/light mode mobile header does not work without the two ##'s within the content. 
I literally have no idea why that is, but once I added back both extra #'s to my own deployment, it started working once again. 
Any idea there? 

Also, if that does not break anything on your end, can we add that extra # back so that the feature works in the main deployment too?

Thanks!

**Comment by mikecao** [comment]
I am having the opposite problem. If I use two ##'s, then it doesn't work at all. Tested on Safari in iOS. And neither setting works in Chrome on iOS.
