### ISSUE TITLE
Most of the visitors are showing up as `Unknown` in the countries

### ISSUE THREAD

**Issue by deshetti** [umami-software/umami#984]
I deployed Umami a few hours ago and is using in production for one of the sites. The countries are not populating as expected, most of them are showing up as **Unknown**.

<img width="1109" alt="Screen Shot 2022-02-23 at 2 58 13 PM" src="https://user-images.githubusercontent.com/10763210/155408584-d2f419d1-7821-47e8-8352-86f7cad55529.png">

**Comment by mikecao** [comment]
See #814. You have need to use a custom header value.
